/*
Purpose:    应用集市层-建表脚本，此脚本由生成引擎自动生成。
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd idl_oass_crss_upl_business_contract
CreateDate: 20180515
FileType:   DML
Logs:
    zjj 2018-05-15 新建表本
*/

set timing on

-- 1 alter parallel
alter session force parallel query parallel 4;
alter session force parallel dml parallel 4;
-- alter session force parallel ddl parallel 4;


-- 2.1 drop timeout partition and add partition
-- it is no need to check when this segment SQL was return faied
whenever sqlerror continue none;
alter table ${idl_schema}.oass_crss_upl_business_contract drop partition p_${retain_week};
alter table ${idl_schema}.oass_crss_upl_business_contract drop partition p_${batch_date};


-- 2.2 add today partition
whenever sqlerror exit sql.sqlcode;
alter table ${idl_schema}.oass_crss_upl_business_contract add  partition p_${batch_date} values (to_date('${batch_date}','yyyymmdd'));

-- 2.3 insert data target table
whenever sqlerror exit sql.sqlcode;
insert /*+ append */ into ${idl_schema}.oass_crss_upl_business_contract (
    etl_dt  -- 数据日期
    ,serialno  -- 流水号
    ,relativeserialno  -- 相关批准流水号
    ,artificialno  -- 人工编号
    ,occurdate  -- 发生日期
    ,customerid  -- 客户编号
    ,customername  -- 客户名称
    ,businesstype  -- 业务品种(关联表Business_Type中字段TypeNo)
    ,oldbusinesstype  -- 老业务品种
    ,businesssubtype  -- 业务子类型
    ,occurtype  -- 发生类型(代码：OccurType)
    ,creditdigest  -- 额度是否融通
    ,creditcycle  -- 额度是否循环
    ,credittype  -- 额度品种
    ,currenylist  -- 可融通币种表
    ,currencymode  -- 汇率计算模式
    ,businesstypelist  -- 可混用品种表
    ,calculatemode  -- 额度金额占用计算模式
    ,useorglist  -- 额度可使用机构范围
    ,flowreduceflag  -- 额度是否简化审批流程
    ,contractflag  -- 额度是否需要签署协议(1：是2：否)
    ,subcontractflag  -- 额度下业务是否需要签署合同
    ,selfuseflag  -- 额度自用或他用
    ,creditindex  -- 额度占用系数
    ,creditreducesum  -- 额度扣减金额
    ,limitationterm  -- 额度使用最迟日期
    ,useterm  -- 额度项下业务最迟到期日期
    ,creditaggreement  -- 使用授信协议号(额度合同流水号)
    ,relativeagreement  -- 其他相关协议号
    ,loanflag  -- 是否可以直接申请出帐(1：是 2：否)
    ,totalsum  -- 银行融资总额
    ,ourrole  -- 我行参与角色
    ,reversibility  -- 有无追索权
    ,billnum  -- 票据数量（张）(跑批时候更新)
    ,housetype  -- 房产类型(1：别墅2：商住两住、商用、写字楼3：普通住宅)
    ,lctermtype  -- 信用证期限类型(01：即期02：<90天03：90-180天04：180-360天05：>360天)
    ,riskattribute  -- 低风险类型
    ,suretype  -- 对外担保类型
    ,safeguardtype  -- 保函类型(01：融资性担保02：非融资性担保)
    ,creditbusiness  -- 单项额度指定品种
    ,businesscurrency  -- 币种(代码：Currency)
    ,businesssum  -- 金额
    ,businessprop  -- 贷款成数
    ,termyear  -- 期限年
    ,termmonth  -- 期限月
    ,termday  -- 期限日
    ,lgterm  -- 远期信用证付款期限
    ,baseratetype  -- 基准利率类型
    ,baserate  -- 基准利率
    ,ratefloattype  -- 利率类型(0010：浮动0020：固定)
    ,ratefloat  -- 利率浮动
    ,businessrate  -- 利率
    ,ictype  -- 收费方式(代码：ChargeType)
    ,iccyc  -- 计息周期
    ,pdgratio  -- 手续费比例
    ,pdgsum  -- 手续费金额
    ,pdgpaymethod  -- 手续费支付方式
    ,pdgpayperiod  -- 收费周期
    ,promisesfeeratio  -- 承诺费率
    ,promisesfeesum  -- 承诺费金额
    ,promisesfeeperiod  -- 承诺费计收期
    ,promisesfeebegin  -- 承诺费计收起始日
    ,mfeeratio  -- 管理费比例
    ,mfeesum  -- 管理费金额
    ,mfeepaymethod  -- 管理费支付方式
    ,agentfee  -- 代理费
    ,dealfee  -- 安排费
    ,totalcast  -- 总成本
    ,discountinterest  -- 贴现利息
    ,purchaserinterest  -- 买方应付贴现利息
    ,bargainorinterest  -- 卖方应付贴现利息
    ,discountsum  -- 实付贴现金额
    ,bailratio  -- 保证金比例
    ,bailcurrency  -- 保证金币种(代码：Currency)
    ,bailsum  -- 保证金金额
    ,bailaccount  -- 保证金帐号
    ,fineratetype  -- 罚息利率类型
    ,finerate  -- 罚息利率
    ,drawingtype  -- 提款方式(01：一次提款02：分次提款)
    ,firstdrawingdate  -- 首次提款日期
    ,drawingperiod  -- 提款期限
    ,paytimes  -- 还款期次
    ,paycyc  -- 还本付息方式(1：等额还款法2：等额本金还款3：一次还本付息4：分次付息一次还本)
    ,graceperiod  -- 还款宽限期(月)
    ,overdraftperiod  -- 连续透支期
    ,oldlcno  -- 原信用证编号
    ,oldlctermtype  -- 原信用证期限类型
    ,oldlccurrency  -- 原信用证币种
    ,oldlcsum  -- 原信用证金额
    ,oldlcloadingdate  -- 原信用证装期
    ,oldlcvaliddate  -- 原信用证效期
    ,direction  -- 投向(代码：ndustryType)
    ,purpose  -- 用途
    ,planallocation  -- 用款计划
    ,immediacypaysource  -- 直接还款来源
    ,paysource  -- 还款来源
    ,corpuspaymethod  -- 本金还款方式(代码：CorpusPayMeth)
    ,interestpaymethod  -- 利息支付方式(01：按季支付02：按月支付03：一次付清)
    ,putoutdate  -- 约定发放日
    ,maturity  -- 到期日期
    ,thirdparty1  -- 涉及第三方1
    ,thirdpartyid1  -- 第三方法人代码1
    ,thirdparty2  -- 涉及第三方2
    ,thirdpartyid2  -- 第三方法人代码2
    ,thirdparty3  -- 涉及第三方3
    ,thirdpartyid3  -- 第三方法人代码3
    ,thirdpartyregion  -- 涉及第三方所在地区和国家
    ,thirdpartyaccounts  -- 第三方帐号
    ,cargoinfo  -- 货物名称
    ,projectname  -- 贷款项目名称
    ,operationinfo  -- 业务信息
    ,contextinfo  -- 背景信息
    ,securitiestype  -- 有价证券类型(代码：InvoiceType)
    ,securitiesregion  -- 有价证券发行地
    ,constructionarea  -- 建筑面积
    ,usearea  -- 使用面积
    ,flag1  -- 是否1(1：是2：否)
    ,flag2  -- 是否2(1：是2：否)
    ,flag3  -- 是否3(1：是2：否)
    ,tradecontractno  -- 相关贸易合同号
    ,invoiceno  -- 增值税发票
    ,tradecurrency  -- 贸易合同币种
    ,tradesum  -- 贸易合同金额
    ,lcno  -- 信用证编号（或承兑汇票号码）
    ,paymentdate  -- 最迟对外付汇日期
    ,operationmode  -- 业务模式(代码：OperationMode)
    ,begindate  -- 起始日期
    ,enddate  -- 到期日
    ,vouchclass  -- 担保形式
    ,vouchtype  -- 主要担保方式(代码：VouchType)
    ,vouchtype1  -- 担保方式1
    ,vouchtype2  -- 担保方式2
    ,vouchflag  -- 有无其他担保方式(1：有2：无)
    ,warrantor  -- 主要担保人
    ,warrantorid  -- 主要担保人代码
    ,othercondition  -- 其他条件和要求
    ,guarantyvalue  -- 担保总价值
    ,guarantyrate  -- 担保率
    ,baseevaluateresult  -- 基期信用等级
    ,riskrate  -- 综合风险度
    ,lowrisk  -- 是否低风险业务(1：有2：无)
    ,otherarealoan  -- 是否异地贷款(1：有2：无)
    ,lowriskbailsum  -- 低风险担保金额
    ,applytype  -- 申请方式(代码：ApplyType)
    ,originalputoutdate  -- 首次发放日
    ,extendtimes  -- 展期次数
    ,lngotimes  -- 借新还旧次数
    ,golntimes  -- 还旧借新次数
    ,drtimes  -- 债务重组次数
    ,guarantyno  -- 抵质押编号
    ,putoutsum  -- 已出帐金额
    ,actualputoutsum  -- 已实际出帐金额
    ,balance  -- 当前余额
    ,normalbalance  -- 正常余额
    ,overduebalance  -- 逾期余额
    ,dullbalance  -- 呆滞余额
    ,badbalance  -- 呆帐余额
    ,interestbalance1  -- 表内欠息余额
    ,interestbalance2  -- 表外欠息余额
    ,finebalance1  -- 本金罚息
    ,finebalance2  -- 利息罚息
    ,overduedays  -- 逾期天数
    ,oweinterestdays  -- 欠息天数
    ,tabalance  -- 分期业务欠本金
    ,tainterestbalance  -- 分期业务欠利息
    ,tatimes  -- 累计欠款期数
    ,lcatimes  -- 连续欠款期数
    ,pbinterestsum  -- 本累计收回利息
    ,pbmfeesum  -- 累计收回管理费
    ,pbpdgsum  -- 累计收回手续费
    ,pblegalcostsum  -- 累计收回诉讼费
    ,polegalcostsum  -- 累计付出诉讼费
    ,originalbaddate  -- 首次认定不良日期
    ,baseclassifyresult  -- 基期风险分类结果
    ,classifyresult  -- 五级分类结果
    ,classifytype  -- 最新风险分类方式
    ,classifydate  -- 最新风险分类时间
    ,classifyorgid  -- 最新分类认定机构
    ,reservesum  -- 计提准备金
    ,expectlosssum  -- 预测损失金额
    ,bailrate  -- 保证金比率
    ,finishorg  -- 终批机构级别
    ,finishtype  -- 终结类型
    ,finishdate  -- 终结日期
    ,describe1  -- 描述1
    ,reinforceflag  -- 补登标志
    ,manageorgid  -- 当前管户机构
    ,manageuserid  -- 当前管户人
    ,recoveryorgid  -- 保全管理机构
    ,recoveryuserid  -- 保全管理人
    ,statorgid  -- 当前统计机构
    ,statuserid  -- 当前统计人
    ,operateorgid  -- 经办机构
    ,operateuserid  -- 经办人
    ,operatedate  -- 经办日期
    ,inputorgid  -- 登记机构
    ,inputuserid  -- 登记人
    ,inputdate  -- 登记日期人
    ,updatedate  -- 更新日期
    ,pigeonholedate  -- 归档日期
    ,remark  -- 备注
    ,flag4  -- 是否4
    ,paycurrency  -- 付款币种
    ,paydate  -- 付款时间
    ,flag5  -- 转建行标志
    ,classifysum1  -- 最新分类正常金额
    ,classifysum2  -- 最新分类关注金额
    ,classifysum3  -- 最新分类次级金额
    ,classifysum4  -- 最新分类可疑金额
    ,classifysum5  -- 最新分类损失金额
    ,shifttype  -- 移交类型
    ,operatetype  -- 操作方式
    ,fundsource  -- 资金来源
    ,cycleflag  -- 循环标志
    ,creditfreezeflag  -- 额度是否冻结
    ,shiftbalance  -- 移交保全时余额
    ,classifyfrequency  -- 分类频率
    ,classifylevel  -- 认定级别
    ,vouchnewflag  -- 是否新增担保
    ,actualartificialno  -- 实际合同号
    ,deleteflag  -- 合并标志
    ,accountno  -- 结算帐号
    ,loanaccountno  -- 入账账户
    ,secondpayaccount  -- 第二还款帐号
    ,adjustratetype  -- 利率调整方式
    ,adjustrateterm  -- 利率调整月数
    ,overinttype  -- 逾期计息方式
    ,rateadjustcyc  -- 利率调整周期
    ,pdgaccountno  -- 手续费支出帐号
    ,deductdate  -- 扣款日期
    ,fzanbalance  -- 发展商入帐净额
    ,acceptinttype  -- 收息类型
    ,ratio  -- 比例
    ,thirdpartyadd1  -- 涉及第三方地址1
    ,thirdpartyzip1  -- 第三方法人邮编1
    ,thirdpartyadd2  -- 涉及第三方地址2
    ,thirdpartyzip2  -- 第三方法人邮编2
    ,thirdpartyadd3  -- 涉及第三方地址3
    ,thirdpartyzip3  -- 第三方法人邮编3
    ,effectarea  -- 信用证有效地
    ,termdate1  -- 最晚装运期
    ,termdate2  -- 交单期
    ,termdate3  -- 付款期限
    ,fixcyc  -- 固定周期
    ,describe2  -- 描述2
    ,cancelsum  -- 核销金额
    ,cancelinterest  -- 核销利息
    ,loanterm  -- 期限
    ,putoutorgid  -- 放款机构
    ,tempsaveflag  -- 暂存标志
    ,overduedate  -- 逾期日期
    ,oweinterestdate  -- 欠息日期
    ,freezeflag  -- 冻结标志
    ,cyclemonths  -- 指定月的利率重定价月数
    ,gainamount  -- 等比（等额）<br>递变幅度
    ,gaincyc  -- 等比（等额）<br>递变周期
    ,holdcorpus  -- 保留本金
    ,incomeorgid  -- 入账机构编号
    ,mainrepaymentmethod  -- 还款方式
    ,payaccountname  -- 还款账户名
    ,payaccountno  -- 还款账户
    ,ratemode  -- 利率执行方式
    ,paymentmode  -- 支付方式
    ,transformflag  -- 转授信标志
    ,transformtimes  -- 变更次数
    ,defaultpaydate  -- 统一还款日
    ,batchpaymentflag  -- 是否参与批扣
    ,loankind  -- 期限类型
    ,creditmode  -- 合同类型
    ,effectflag  -- 有效标志位
    ,totalbalance  -- 敞口余额
    ,recoverycognuserid  -- 保全业务经理
    ,recoverycognorgid  -- 保全业务机构
    ,classifyresulteleven  -- 十级分类结果
    ,riskacctno  -- 风险金账户
    ,riskacctname  -- 风险金账户名
    ,risksum  -- 代扣风险金金额
    ,otherfee  -- 其他费用金额
    ,subbusinesstype  -- 助贷业务品种
    ,lastclassifyresult  -- 上次五级分类结果
    ,payaccountname2  -- 第二还款账户名
    ,payaccountno2  -- 第二还款账户
    ,start_dt  -- 
    ,end_dt  -- 
    ,id_mark  -- 
    ,etl_timestamp  -- 数据处理时间
)
select
    to_date('${batch_date}','yyyymmdd') as etl_dt  -- 数据日期
    ,replace(replace(t1.serialno,chr(13),''),chr(10),'')  -- 流水号
    ,replace(replace(t1.relativeserialno,chr(13),''),chr(10),'')  -- 相关批准流水号
    ,replace(replace(t1.artificialno,chr(13),''),chr(10),'')  -- 人工编号
    ,replace(replace(t1.occurdate,chr(13),''),chr(10),'')  -- 发生日期
    ,replace(replace(t1.customerid,chr(13),''),chr(10),'')  -- 客户编号
    ,replace(replace(t1.customername,chr(13),''),chr(10),'')  -- 客户名称
    ,replace(replace(t1.businesstype,chr(13),''),chr(10),'')  -- 业务品种(关联表Business_Type中字段TypeNo)
    ,replace(replace(t1.oldbusinesstype,chr(13),''),chr(10),'')  -- 老业务品种
    ,replace(replace(t1.businesssubtype,chr(13),''),chr(10),'')  -- 业务子类型
    ,replace(replace(t1.occurtype,chr(13),''),chr(10),'')  -- 发生类型(代码：OccurType)
    ,replace(replace(t1.creditdigest,chr(13),''),chr(10),'')  -- 额度是否融通
    ,replace(replace(t1.creditcycle,chr(13),''),chr(10),'')  -- 额度是否循环
    ,replace(replace(t1.credittype,chr(13),''),chr(10),'')  -- 额度品种
    ,replace(replace(t1.currenylist,chr(13),''),chr(10),'')  -- 可融通币种表
    ,replace(replace(t1.currencymode,chr(13),''),chr(10),'')  -- 汇率计算模式
    ,replace(replace(t1.businesstypelist,chr(13),''),chr(10),'')  -- 可混用品种表
    ,replace(replace(t1.calculatemode,chr(13),''),chr(10),'')  -- 额度金额占用计算模式
    ,replace(replace(t1.useorglist,chr(13),''),chr(10),'')  -- 额度可使用机构范围
    ,replace(replace(t1.flowreduceflag,chr(13),''),chr(10),'')  -- 额度是否简化审批流程
    ,replace(replace(t1.contractflag,chr(13),''),chr(10),'')  -- 额度是否需要签署协议(1：是2：否)
    ,replace(replace(t1.subcontractflag,chr(13),''),chr(10),'')  -- 额度下业务是否需要签署合同
    ,replace(replace(t1.selfuseflag,chr(13),''),chr(10),'')  -- 额度自用或他用
    ,t1.creditindex  -- 额度占用系数
    ,t1.creditreducesum  -- 额度扣减金额
    ,replace(replace(t1.limitationterm,chr(13),''),chr(10),'')  -- 额度使用最迟日期
    ,replace(replace(t1.useterm,chr(13),''),chr(10),'')  -- 额度项下业务最迟到期日期
    ,replace(replace(t1.creditaggreement,chr(13),''),chr(10),'')  -- 使用授信协议号(额度合同流水号)
    ,replace(replace(t1.relativeagreement,chr(13),''),chr(10),'')  -- 其他相关协议号
    ,replace(replace(t1.loanflag,chr(13),''),chr(10),'')  -- 是否可以直接申请出帐(1：是 2：否)
    ,t1.totalsum  -- 银行融资总额
    ,replace(replace(t1.ourrole,chr(13),''),chr(10),'')  -- 我行参与角色
    ,replace(replace(t1.reversibility,chr(13),''),chr(10),'')  -- 有无追索权
    ,t1.billnum  -- 票据数量（张）(跑批时候更新)
    ,replace(replace(t1.housetype,chr(13),''),chr(10),'')  -- 房产类型(1：别墅2：商住两住、商用、写字楼3：普通住宅)
    ,replace(replace(t1.lctermtype,chr(13),''),chr(10),'')  -- 信用证期限类型(01：即期02：<90天03：90-180天04：180-360天05：>360天)
    ,replace(replace(t1.riskattribute,chr(13),''),chr(10),'')  -- 低风险类型
    ,replace(replace(t1.suretype,chr(13),''),chr(10),'')  -- 对外担保类型
    ,replace(replace(t1.safeguardtype,chr(13),''),chr(10),'')  -- 保函类型(01：融资性担保02：非融资性担保)
    ,replace(replace(t1.creditbusiness,chr(13),''),chr(10),'')  -- 单项额度指定品种
    ,replace(replace(t1.businesscurrency,chr(13),''),chr(10),'')  -- 币种(代码：Currency)
    ,t1.businesssum  -- 金额
    ,t1.businessprop  -- 贷款成数
    ,t1.termyear  -- 期限年
    ,t1.termmonth  -- 期限月
    ,t1.termday  -- 期限日
    ,t1.lgterm  -- 远期信用证付款期限
    ,replace(replace(t1.baseratetype,chr(13),''),chr(10),'')  -- 基准利率类型
    ,t1.baserate  -- 基准利率
    ,replace(replace(t1.ratefloattype,chr(13),''),chr(10),'')  -- 利率类型(0010：浮动0020：固定)
    ,t1.ratefloat  -- 利率浮动
    ,t1.businessrate  -- 利率
    ,replace(replace(t1.ictype,chr(13),''),chr(10),'')  -- 收费方式(代码：ChargeType)
    ,replace(replace(t1.iccyc,chr(13),''),chr(10),'')  -- 计息周期
    ,t1.pdgratio  -- 手续费比例
    ,t1.pdgsum  -- 手续费金额
    ,replace(replace(t1.pdgpaymethod,chr(13),''),chr(10),'')  -- 手续费支付方式
    ,replace(replace(t1.pdgpayperiod,chr(13),''),chr(10),'')  -- 收费周期
    ,t1.promisesfeeratio  -- 承诺费率
    ,t1.promisesfeesum  -- 承诺费金额
    ,t1.promisesfeeperiod  -- 承诺费计收期
    ,replace(replace(t1.promisesfeebegin,chr(13),''),chr(10),'')  -- 承诺费计收起始日
    ,t1.mfeeratio  -- 管理费比例
    ,t1.mfeesum  -- 管理费金额
    ,replace(replace(t1.mfeepaymethod,chr(13),''),chr(10),'')  -- 管理费支付方式
    ,t1.agentfee  -- 代理费
    ,t1.dealfee  -- 安排费
    ,t1.totalcast  -- 总成本
    ,t1.discountinterest  -- 贴现利息
    ,t1.purchaserinterest  -- 买方应付贴现利息
    ,t1.bargainorinterest  -- 卖方应付贴现利息
    ,t1.discountsum  -- 实付贴现金额
    ,t1.bailratio  -- 保证金比例
    ,replace(replace(t1.bailcurrency,chr(13),''),chr(10),'')  -- 保证金币种(代码：Currency)
    ,t1.bailsum  -- 保证金金额
    ,replace(replace(t1.bailaccount,chr(13),''),chr(10),'')  -- 保证金帐号
    ,replace(replace(t1.fineratetype,chr(13),''),chr(10),'')  -- 罚息利率类型
    ,t1.finerate  -- 罚息利率
    ,replace(replace(t1.drawingtype,chr(13),''),chr(10),'')  -- 提款方式(01：一次提款02：分次提款)
    ,replace(replace(t1.firstdrawingdate,chr(13),''),chr(10),'')  -- 首次提款日期
    ,t1.drawingperiod  -- 提款期限
    ,t1.paytimes  -- 还款期次
    ,replace(replace(t1.paycyc,chr(13),''),chr(10),'')  -- 还本付息方式(1：等额还款法2：等额本金还款3：一次还本付息4：分次付息一次还本)
    ,t1.graceperiod  -- 还款宽限期(月)
    ,t1.overdraftperiod  -- 连续透支期
    ,replace(replace(t1.oldlcno,chr(13),''),chr(10),'')  -- 原信用证编号
    ,replace(replace(t1.oldlctermtype,chr(13),''),chr(10),'')  -- 原信用证期限类型
    ,replace(replace(t1.oldlccurrency,chr(13),''),chr(10),'')  -- 原信用证币种
    ,t1.oldlcsum  -- 原信用证金额
    ,replace(replace(t1.oldlcloadingdate,chr(13),''),chr(10),'')  -- 原信用证装期
    ,replace(replace(t1.oldlcvaliddate,chr(13),''),chr(10),'')  -- 原信用证效期
    ,replace(replace(t1.direction,chr(13),''),chr(10),'')  -- 投向(代码：ndustryType)
    ,replace(replace(t1.purpose,chr(13),''),chr(10),'')  -- 用途
    ,replace(replace(t1.planallocation,chr(13),''),chr(10),'')  -- 用款计划
    ,replace(replace(t1.immediacypaysource,chr(13),''),chr(10),'')  -- 直接还款来源
    ,replace(replace(t1.paysource,chr(13),''),chr(10),'')  -- 还款来源
    ,replace(replace(t1.corpuspaymethod,chr(13),''),chr(10),'')  -- 本金还款方式(代码：CorpusPayMeth)
    ,replace(replace(t1.interestpaymethod,chr(13),''),chr(10),'')  -- 利息支付方式(01：按季支付02：按月支付03：一次付清)
    ,replace(replace(t1.putoutdate,chr(13),''),chr(10),'')  -- 约定发放日
    ,replace(replace(t1.maturity,chr(13),''),chr(10),'')  -- 到期日期
    ,replace(replace(t1.thirdparty1,chr(13),''),chr(10),'')  -- 涉及第三方1
    ,replace(replace(t1.thirdpartyid1,chr(13),''),chr(10),'')  -- 第三方法人代码1
    ,replace(replace(t1.thirdparty2,chr(13),''),chr(10),'')  -- 涉及第三方2
    ,replace(replace(t1.thirdpartyid2,chr(13),''),chr(10),'')  -- 第三方法人代码2
    ,replace(replace(t1.thirdparty3,chr(13),''),chr(10),'')  -- 涉及第三方3
    ,replace(replace(t1.thirdpartyid3,chr(13),''),chr(10),'')  -- 第三方法人代码3
    ,replace(replace(t1.thirdpartyregion,chr(13),''),chr(10),'')  -- 涉及第三方所在地区和国家
    ,replace(replace(t1.thirdpartyaccounts,chr(13),''),chr(10),'')  -- 第三方帐号
    ,replace(replace(t1.cargoinfo,chr(13),''),chr(10),'')  -- 货物名称
    ,replace(replace(t1.projectname,chr(13),''),chr(10),'')  -- 贷款项目名称
    ,replace(replace(t1.operationinfo,chr(13),''),chr(10),'')  -- 业务信息
    ,replace(replace(t1.contextinfo,chr(13),''),chr(10),'')  -- 背景信息
    ,replace(replace(t1.securitiestype,chr(13),''),chr(10),'')  -- 有价证券类型(代码：InvoiceType)
    ,replace(replace(t1.securitiesregion,chr(13),''),chr(10),'')  -- 有价证券发行地
    ,t1.constructionarea  -- 建筑面积
    ,t1.usearea  -- 使用面积
    ,replace(replace(t1.flag1,chr(13),''),chr(10),'')  -- 是否1(1：是2：否)
    ,replace(replace(t1.flag2,chr(13),''),chr(10),'')  -- 是否2(1：是2：否)
    ,replace(replace(t1.flag3,chr(13),''),chr(10),'')  -- 是否3(1：是2：否)
    ,replace(replace(t1.tradecontractno,chr(13),''),chr(10),'')  -- 相关贸易合同号
    ,replace(replace(t1.invoiceno,chr(13),''),chr(10),'')  -- 增值税发票
    ,replace(replace(t1.tradecurrency,chr(13),''),chr(10),'')  -- 贸易合同币种
    ,t1.tradesum  -- 贸易合同金额
    ,replace(replace(t1.lcno,chr(13),''),chr(10),'')  -- 信用证编号（或承兑汇票号码）
    ,replace(replace(t1.paymentdate,chr(13),''),chr(10),'')  -- 最迟对外付汇日期
    ,replace(replace(t1.operationmode,chr(13),''),chr(10),'')  -- 业务模式(代码：OperationMode)
    ,replace(replace(t1.begindate,chr(13),''),chr(10),'')  -- 起始日期
    ,replace(replace(t1.enddate,chr(13),''),chr(10),'')  -- 到期日
    ,replace(replace(t1.vouchclass,chr(13),''),chr(10),'')  -- 担保形式
    ,replace(replace(t1.vouchtype,chr(13),''),chr(10),'')  -- 主要担保方式(代码：VouchType)
    ,replace(replace(t1.vouchtype1,chr(13),''),chr(10),'')  -- 担保方式1
    ,replace(replace(t1.vouchtype2,chr(13),''),chr(10),'')  -- 担保方式2
    ,replace(replace(t1.vouchflag,chr(13),''),chr(10),'')  -- 有无其他担保方式(1：有2：无)
    ,replace(replace(t1.warrantor,chr(13),''),chr(10),'')  -- 主要担保人
    ,replace(replace(t1.warrantorid,chr(13),''),chr(10),'')  -- 主要担保人代码
    ,replace(replace(t1.othercondition,chr(13),''),chr(10),'')  -- 其他条件和要求
    ,t1.guarantyvalue  -- 担保总价值
    ,t1.guarantyrate  -- 担保率
    ,replace(replace(t1.baseevaluateresult,chr(13),''),chr(10),'')  -- 基期信用等级
    ,t1.riskrate  -- 综合风险度
    ,replace(replace(t1.lowrisk,chr(13),''),chr(10),'')  -- 是否低风险业务(1：有2：无)
    ,replace(replace(t1.otherarealoan,chr(13),''),chr(10),'')  -- 是否异地贷款(1：有2：无)
    ,t1.lowriskbailsum  -- 低风险担保金额
    ,replace(replace(t1.applytype,chr(13),''),chr(10),'')  -- 申请方式(代码：ApplyType)
    ,replace(replace(t1.originalputoutdate,chr(13),''),chr(10),'')  -- 首次发放日
    ,t1.extendtimes  -- 展期次数
    ,t1.lngotimes  -- 借新还旧次数
    ,t1.golntimes  -- 还旧借新次数
    ,t1.drtimes  -- 债务重组次数
    ,replace(replace(t1.guarantyno,chr(13),''),chr(10),'')  -- 抵质押编号
    ,t1.putoutsum  -- 已出帐金额
    ,t1.actualputoutsum  -- 已实际出帐金额
    ,t1.balance  -- 当前余额
    ,t1.normalbalance  -- 正常余额
    ,t1.overduebalance  -- 逾期余额
    ,t1.dullbalance  -- 呆滞余额
    ,t1.badbalance  -- 呆帐余额
    ,t1.interestbalance1  -- 表内欠息余额
    ,t1.interestbalance2  -- 表外欠息余额
    ,t1.finebalance1  -- 本金罚息
    ,t1.finebalance2  -- 利息罚息
    ,t1.overduedays  -- 逾期天数
    ,t1.oweinterestdays  -- 欠息天数
    ,t1.tabalance  -- 分期业务欠本金
    ,t1.tainterestbalance  -- 分期业务欠利息
    ,t1.tatimes  -- 累计欠款期数
    ,t1.lcatimes  -- 连续欠款期数
    ,t1.pbinterestsum  -- 本累计收回利息
    ,t1.pbmfeesum  -- 累计收回管理费
    ,t1.pbpdgsum  -- 累计收回手续费
    ,t1.pblegalcostsum  -- 累计收回诉讼费
    ,t1.polegalcostsum  -- 累计付出诉讼费
    ,replace(replace(t1.originalbaddate,chr(13),''),chr(10),'')  -- 首次认定不良日期
    ,replace(replace(t1.baseclassifyresult,chr(13),''),chr(10),'')  -- 基期风险分类结果
    ,replace(replace(t1.classifyresult,chr(13),''),chr(10),'')  -- 五级分类结果
    ,replace(replace(t1.classifytype,chr(13),''),chr(10),'')  -- 最新风险分类方式
    ,replace(replace(t1.classifydate,chr(13),''),chr(10),'')  -- 最新风险分类时间
    ,replace(replace(t1.classifyorgid,chr(13),''),chr(10),'')  -- 最新分类认定机构
    ,t1.reservesum  -- 计提准备金
    ,t1.expectlosssum  -- 预测损失金额
    ,t1.bailrate  -- 保证金比率
    ,replace(replace(t1.finishorg,chr(13),''),chr(10),'')  -- 终批机构级别
    ,replace(replace(t1.finishtype,chr(13),''),chr(10),'')  -- 终结类型
    ,replace(replace(t1.finishdate,chr(13),''),chr(10),'')  -- 终结日期
    ,replace(replace(t1.describe1,chr(13),''),chr(10),'')  -- 描述1
    ,replace(replace(t1.reinforceflag,chr(13),''),chr(10),'')  -- 补登标志
    ,replace(replace(t1.manageorgid,chr(13),''),chr(10),'')  -- 当前管户机构
    ,replace(replace(t1.manageuserid,chr(13),''),chr(10),'')  -- 当前管户人
    ,replace(replace(t1.recoveryorgid,chr(13),''),chr(10),'')  -- 保全管理机构
    ,replace(replace(t1.recoveryuserid,chr(13),''),chr(10),'')  -- 保全管理人
    ,replace(replace(t1.statorgid,chr(13),''),chr(10),'')  -- 当前统计机构
    ,replace(replace(t1.statuserid,chr(13),''),chr(10),'')  -- 当前统计人
    ,replace(replace(t1.operateorgid,chr(13),''),chr(10),'')  -- 经办机构
    ,replace(replace(t1.operateuserid,chr(13),''),chr(10),'')  -- 经办人
    ,replace(replace(t1.operatedate,chr(13),''),chr(10),'')  -- 经办日期
    ,replace(replace(t1.inputorgid,chr(13),''),chr(10),'')  -- 登记机构
    ,replace(replace(t1.inputuserid,chr(13),''),chr(10),'')  -- 登记人
    ,replace(replace(t1.inputdate,chr(13),''),chr(10),'')  -- 登记日期人
    ,replace(replace(t1.updatedate,chr(13),''),chr(10),'')  -- 更新日期
    ,replace(replace(t1.pigeonholedate,chr(13),''),chr(10),'')  -- 归档日期
    ,replace(replace(t1.remark,chr(13),''),chr(10),'')  -- 备注
    ,replace(replace(t1.flag4,chr(13),''),chr(10),'')  -- 是否4
    ,replace(replace(t1.paycurrency,chr(13),''),chr(10),'')  -- 付款币种
    ,replace(replace(t1.paydate,chr(13),''),chr(10),'')  -- 付款时间
    ,replace(replace(t1.flag5,chr(13),''),chr(10),'')  -- 转建行标志
    ,t1.classifysum1  -- 最新分类正常金额
    ,t1.classifysum2  -- 最新分类关注金额
    ,t1.classifysum3  -- 最新分类次级金额
    ,t1.classifysum4  -- 最新分类可疑金额
    ,t1.classifysum5  -- 最新分类损失金额
    ,replace(replace(t1.shifttype,chr(13),''),chr(10),'')  -- 移交类型
    ,replace(replace(t1.operatetype,chr(13),''),chr(10),'')  -- 操作方式
    ,replace(replace(t1.fundsource,chr(13),''),chr(10),'')  -- 资金来源
    ,replace(replace(t1.cycleflag,chr(13),''),chr(10),'')  -- 循环标志
    ,replace(replace(t1.creditfreezeflag,chr(13),''),chr(10),'')  -- 额度是否冻结
    ,t1.shiftbalance  -- 移交保全时余额
    ,t1.classifyfrequency  -- 分类频率
    ,replace(replace(t1.classifylevel,chr(13),''),chr(10),'')  -- 认定级别
    ,replace(replace(t1.vouchnewflag,chr(13),''),chr(10),'')  -- 是否新增担保
    ,replace(replace(t1.actualartificialno,chr(13),''),chr(10),'')  -- 实际合同号
    ,replace(replace(t1.deleteflag,chr(13),''),chr(10),'')  -- 合并标志
    ,replace(replace(t1.accountno,chr(13),''),chr(10),'')  -- 结算帐号
    ,replace(replace(t1.loanaccountno,chr(13),''),chr(10),'')  -- 入账账户
    ,replace(replace(t1.secondpayaccount,chr(13),''),chr(10),'')  -- 第二还款帐号
    ,replace(replace(t1.adjustratetype,chr(13),''),chr(10),'')  -- 利率调整方式
    ,replace(replace(t1.adjustrateterm,chr(13),''),chr(10),'')  -- 利率调整月数
    ,replace(replace(t1.overinttype,chr(13),''),chr(10),'')  -- 逾期计息方式
    ,replace(replace(t1.rateadjustcyc,chr(13),''),chr(10),'')  -- 利率调整周期
    ,replace(replace(t1.pdgaccountno,chr(13),''),chr(10),'')  -- 手续费支出帐号
    ,replace(replace(t1.deductdate,chr(13),''),chr(10),'')  -- 扣款日期
    ,t1.fzanbalance  -- 发展商入帐净额
    ,replace(replace(t1.acceptinttype,chr(13),''),chr(10),'')  -- 收息类型
    ,t1.ratio  -- 比例
    ,replace(replace(t1.thirdpartyadd1,chr(13),''),chr(10),'')  -- 涉及第三方地址1
    ,replace(replace(t1.thirdpartyzip1,chr(13),''),chr(10),'')  -- 第三方法人邮编1
    ,replace(replace(t1.thirdpartyadd2,chr(13),''),chr(10),'')  -- 涉及第三方地址2
    ,replace(replace(t1.thirdpartyzip2,chr(13),''),chr(10),'')  -- 第三方法人邮编2
    ,replace(replace(t1.thirdpartyadd3,chr(13),''),chr(10),'')  -- 涉及第三方地址3
    ,replace(replace(t1.thirdpartyzip3,chr(13),''),chr(10),'')  -- 第三方法人邮编3
    ,replace(replace(t1.effectarea,chr(13),''),chr(10),'')  -- 信用证有效地
    ,replace(replace(t1.termdate1,chr(13),''),chr(10),'')  -- 最晚装运期
    ,replace(replace(t1.termdate2,chr(13),''),chr(10),'')  -- 交单期
    ,replace(replace(t1.termdate3,chr(13),''),chr(10),'')  -- 付款期限
    ,t1.fixcyc  -- 固定周期
    ,replace(replace(t1.describe2,chr(13),''),chr(10),'')  -- 描述2
    ,t1.cancelsum  -- 核销金额
    ,t1.cancelinterest  -- 核销利息
    ,replace(replace(t1.loanterm,chr(13),''),chr(10),'')  -- 期限
    ,replace(replace(t1.putoutorgid,chr(13),''),chr(10),'')  -- 放款机构
    ,replace(replace(t1.tempsaveflag,chr(13),''),chr(10),'')  -- 暂存标志
    ,replace(replace(t1.overduedate,chr(13),''),chr(10),'')  -- 逾期日期
    ,replace(replace(t1.oweinterestdate,chr(13),''),chr(10),'')  -- 欠息日期
    ,replace(replace(t1.freezeflag,chr(13),''),chr(10),'')  -- 冻结标志
    ,t1.cyclemonths  -- 指定月的利率重定价月数
    ,t1.gainamount  -- 等比（等额）<br>递变幅度
    ,t1.gaincyc  -- 等比（等额）<br>递变周期
    ,t1.holdcorpus  -- 保留本金
    ,replace(replace(t1.incomeorgid,chr(13),''),chr(10),'')  -- 入账机构编号
    ,replace(replace(t1.mainrepaymentmethod,chr(13),''),chr(10),'')  -- 还款方式
    ,replace(replace(t1.payaccountname,chr(13),''),chr(10),'')  -- 还款账户名
    ,replace(replace(t1.payaccountno,chr(13),''),chr(10),'')  -- 还款账户
    ,replace(replace(t1.ratemode,chr(13),''),chr(10),'')  -- 利率执行方式
    ,replace(replace(t1.paymentmode,chr(13),''),chr(10),'')  -- 支付方式
    ,replace(replace(t1.transformflag,chr(13),''),chr(10),'')  -- 转授信标志
    ,t1.transformtimes  -- 变更次数
    ,replace(replace(t1.defaultpaydate,chr(13),''),chr(10),'')  -- 统一还款日
    ,replace(replace(t1.batchpaymentflag,chr(13),''),chr(10),'')  -- 是否参与批扣
    ,replace(replace(t1.loankind,chr(13),''),chr(10),'')  -- 期限类型
    ,replace(replace(t1.creditmode,chr(13),''),chr(10),'')  -- 合同类型
    ,replace(replace(t1.effectflag,chr(13),''),chr(10),'')  -- 有效标志位
    ,t1.totalbalance  -- 敞口余额
    ,replace(replace(t1.recoverycognuserid,chr(13),''),chr(10),'')  -- 保全业务经理
    ,replace(replace(t1.recoverycognorgid,chr(13),''),chr(10),'')  -- 保全业务机构
    ,replace(replace(t1.classifyresulteleven,chr(13),''),chr(10),'')  -- 十级分类结果
    ,replace(replace(t1.riskacctno,chr(13),''),chr(10),'')  -- 风险金账户
    ,replace(replace(t1.riskacctname,chr(13),''),chr(10),'')  -- 风险金账户名
    ,t1.risksum  -- 代扣风险金金额
    ,t1.otherfee  -- 其他费用金额
    ,replace(replace(t1.subbusinesstype,chr(13),''),chr(10),'')  -- 助贷业务品种
    ,replace(replace(t1.lastclassifyresult,chr(13),''),chr(10),'')  -- 上次五级分类结果
    ,replace(replace(t1.payaccountname2,chr(13),''),chr(10),'')  -- 第二还款账户名
    ,replace(replace(t1.payaccountno2,chr(13),''),chr(10),'')  -- 第二还款账户
    ,t1.start_dt  -- 
    ,t1.end_dt  -- 
    ,replace(replace(t1.id_mark,chr(13),''),chr(10),'')  -- 
    ,to_timestamp('${batch_timestamp}', 'yyyy-mm-dd hh24:mi:ss.ff6') as etl_timestamp  -- 数据处理时间
from ${iol_schema}.crss_upl_business_contract t1    --微贷业务合同表
where t1.start_dt between to_date('${batch_date}', 'yyyymmdd') - 6 and to_date('${batch_date}', 'yyyymmdd') ;
commit;


-- 4 gater table status
whenever sqlerror exit sql.sqlcode;
exec dbms_stats.gather_table_stats(ownname => '${idl_schema}',tabname => 'oass_crss_upl_business_contract',partname => 'p_${batch_date}', granularity => 'PARTITION', degree => 8, cascade => true);