/*
Purpose:    偏源模型层-增量流水脚本，清空目标表当天分区，把当天数据与目标表进行分区交换。此脚本由生成引擎自动生成。
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iol_pams_pam_aum
CreateDate: 20180515
Logs:
    zjj 2018-05-15 新建脚本
*/

set timing on

-- 1 alter parallel
alter session force parallel query parallel 8;
alter session force parallel dml parallel 8;
-- alter session force parallel ddl parallel 8;

-- 2.1 create table for exchage and add partition
-- it is no need to check when this segment SQL was return faied
whenever sqlerror continue none ;
drop table ${iol_schema}.pams_pam_aum_ex purge;
alter table ${iol_schema}.pams_pam_aum add partition p_${batch_date} values (to_date('${batch_date}','yyyymmdd'));

-- 2.2 truncate target table batch_date partition
whenever sqlerror exit sql.sqlcode;
alter table ${iol_schema}.pams_pam_aum truncate partition p_${batch_date};

-- 2.3 insert data to ex table
create table ${iol_schema}.pams_pam_aum_ex nologging
compress ${option_switch} for query high
as
select * from ${iol_schema}.pams_pam_aum where 0=1;

insert /*+ append */ into ${iol_schema}.pams_pam_aum_ex(
    aum_q_avg_bal -- AUM季均值
    ,aum_cp_q_mavg -- AUM季均值较上季度
    ,aum_cp_q_bal -- AUM较上季度末新增余额
    ,aum_cp_y_bal -- AUM较上年末新增余额
    ,aum_cp_m_bal -- AUM较上月末新增余额
    ,aum_cp_d_bal -- AUM较昨日新增余额
    ,aum_cp_y_yavg -- aum年均比上年
    ,aum_y_avg_bal -- AUM年均值
    ,aum_acct_bal -- AUM余额（保险余额+基金余额+零售存款余额+理财余额+实物贵金属余额+第三方存管保证金余额+资管信托余额）
    ,aum_cp_w_bal -- AUM余额较上周
    ,aum_m_avg_bal -- AUM月均值
    ,aum_cp_y_mavg -- AUM月均值较上年
    ,aum_cp_m_mavg -- AUM月均值较上月
    ,e_fund_q_avg_bal -- E基金季日均
    ,e_fund_y_avg_bal -- E基金年日均
    ,e_fund_acct_bal -- E基金余额
    ,e_fund_m_avg_bal -- E基金月日均
    ,t0_sr_q_avg_bal -- T0非保本理财季日均
    ,t0_sr_y_avg_bal -- T0非保本理财年日均
    ,t0_sr_acct_bal -- T0非保本理财余额
    ,t0_cp_q_bal -- T0非保本理财余额比上季度
    ,t0_cp_y_bal -- T0非保本理财余额比上年
    ,t0_cp_d_bal -- T0非保本理财余额比上日
    ,t0_cp_m_bal -- T0非保本理财余额比上月
    ,t0_cp_q_avg -- T0非保本理财余额季均比上季度
    ,t0_cp_y_avg -- T0非保本理财余额年均比上年
    ,t0_cp_m_avg -- T0非保本理财余额月月均比上月
    ,t0_sr_m_avg_bal -- T0非保本理财月日均
    ,t0_q_avg_bal -- T0理财季日均
    ,t0_acct_cp_q_avg -- T0理财季日均比上季
    ,t0_y_avg_bal -- T0理财年日均
    ,t0_acct_cp_y_avg -- T0理财年日均比上年
    ,t0_acct_bal -- T0理财余额
    ,t0_acct_cp_q_bal -- T0理财余额比上季
    ,t0_acct_cp_y_bal -- T0理财余额比上年
    ,t0_acct_cp_d_bal -- T0理财余额比上日
    ,t0_acct_cp_m_bal -- T0理财余额比上月
    ,t0_m_avg_bal -- T0理财月日均
    ,t0_acct_cp_m_avg -- T0理财月日均比上月
    ,axc_q_avg_bal -- 安兴存季日均
    ,axc_cp_q_avg -- 安兴存季日均比上季
    ,axc_y_avg_bal -- 安兴存年日均
    ,axc_cp_y_avg -- 安兴存年日均比上年
    ,axc_acct_bal -- 安兴存余额
    ,axc_cp_q_bal -- 安兴存余额比上季
    ,axc_cp_y_bal -- 安兴存余额比上年
    ,axc_cp_d_bal -- 安兴存余额比上日
    ,axc_cp_m_bal -- 安兴存余额比上月
    ,axc_m_avg_bal -- 安兴存月日均
    ,axc_cp_m_avg -- 安兴存月日均比上月
    ,loan_mortgage_acct_bal -- 按揭贷余额
    ,nsr_acct_qavg -- 保本理财季日均
    ,nsr_cp_q_avg -- 保本理财季日均季净增
    ,nsr_acct_yavg -- 保本理财年日均
    ,nsr_cp_y_avg -- 保本理财年日均年净增
    ,nsr_acct_bal -- 保本理财余额
    ,nsr_q_cp_bal -- 保本理财余额季净增
    ,nsr_y_cp_bal -- 保本理财余额年净增
    ,nsr_m_cp_bal -- 保本理财余额月净增
    ,nsr_acct_mavg -- 保本理财月日均
    ,nsr_cp_m_avg -- 保本理财月日均月净增
    ,ensure_fee -- 保费金额
    ,insure_acct_bal -- 保险余额（包括理财系统提供的保险和CRM提供保险台账，只有承保的保险台账才计入AUM）
    ,insure_cp_q_bal -- 保险余额比上季度
    ,insure_cp_y_bal -- 保险余额比上年
    ,insure_cp_d_bal -- 保险余额比上日
    ,insure_cp_m_bal -- 保险余额比上月
    ,insure_cp_q_avg -- 保险余额季均比上季度
    ,insure_q_avg_bal -- 保险余额季日均
    ,insure_acct_jz_bal -- 保险余额净增
    ,insure_cp_y_avg -- 保险余额年均比上年
    ,insure_y_avg_bal -- 保险余额年日均
    ,insure_cp_m_avg -- 保险余额月月均比上月
    ,insure_cp_w_bal -- 保险余额周净增
    ,insure_m_avg_bal -- 保险月日均
    ,cds_q_avg_bal -- 大额存单季日均
    ,cds_cp_q_avg -- 大额存单季日均季净增
    ,cds_y_avg_bal -- 大额存单年日均
    ,cds_cp_y_avg -- 大额存单年日均年净增
    ,cds_acct_bal -- 大额存单余额
    ,cds_q_cp_bal -- 大额存单余额季净增
    ,cds_y_cp_bal -- 大额存单余额年净增
    ,cds_m_cp_bal -- 大额存单余额月净增
    ,cds_m_avg_bal -- 大额存单月日均
    ,cds_cp_m_avg -- 大额存单月日均月净增
    ,decd_zr_sum -- 大额存单转让金额
    ,dx_q_avg_bal -- 代销理财季日均
    ,sr_q_dx_q_avg_bal -- 代销理财季日均季净增
    ,dx_y_avg_bal -- 代销理财年日均
    ,sr_y_dx_y_avg_bal -- 代销理财年日均年净增
    ,dx_finc_bal -- 代销理财余额
    ,sr_q_dx_finc_bal -- 代销理财余额季净增
    ,sr_y_dx_finc_bal -- 代销理财余额年净增
    ,sr_d_dx_finc_bal -- 代销理财余额日净增
    ,sr_m_dx_finc_bal -- 代销理财余额月净增
    ,sr_w_dx_finc_bal -- 代销理财余额周净增
    ,dx_m_avg_bal -- 代销理财月日均
    ,sr_m_dx_m_avg_bal -- 代销理财月日均月净增
    ,t_agent_acct_qavg -- 第三方存管季日均
    ,t_agent_acct_yavg -- 第三方存管年日均
    ,t_agent_acct_bal -- 第三方存管余额（第三方存管的保证金总金额）
    ,t_agent_acct_jz_bal -- 第三方存管余额净增
    ,t_agent_acct_mavg -- 第三方存管月日均
    ,third_acct_bal -- 第三方存款保证金余额
    ,third_cp_q_bal -- 第三方存款保证余额比上季度
    ,third_cp_y_bal -- 第三方存款保证余额比上年
    ,third_cp_d_bal -- 第三方存款保证余额比上日
    ,third_cp_m_bal -- 第三方存款保证余额比上月
    ,third_cp_q_avg -- 第三方存款保证余额季均比上季度
    ,third_cp_y_avg -- 第三方存款保证余额年均比上年
    ,third_y_avg_bal -- 第三方存款保证余额年日均
    ,third_m_avg_bal -- 第三方存款保证余额月日均
    ,third_cp_m_avg -- 第三方存款保证余额月月均比上月
    ,dep_cp_q_avg -- 定期存款季日均季净增
    ,dep_cp_y_avg -- 定期存款年日均年净增
    ,dep_acct_bal -- 定期存款余额
    ,dep_q_cp_bal -- 定期存款余额季净增
    ,dep_q_avg_bal -- 定期存款余额季日均
    ,dep_acct_jz_bal -- 定期存款余额净增
    ,dep_y_cp_bal -- 定期存款余额年净增
    ,dep_y_avg_bal -- 定期存款余额年日均
    ,dep_m_avg_bal -- 定期存款余额余月日均
    ,dep_m_cp_bal -- 定期存款余额月净增
    ,dep_cp_m_avg -- 定期存款月日均月净增
    ,nt0_acct_bal -- 非T0理财余额
    ,nt0_cp_q_bal -- 非T0理财余额比上季度
    ,nt0_cp_y_bal -- 非T0理财余额比上年
    ,nt0_cp_d_bal -- 非T0理财余额比上日
    ,nt0_cp_m_bal -- 非T0理财余额比上月
    ,nt0_cp_q_avg -- 非T0理财余额季均比上季度
    ,nt0_q_avg_bal -- 非T0理财余额季日均
    ,nt0_cp_y_avg -- 非T0理财余额年均比上年
    ,nt0_y_avg_bal -- 非T0理财余额年日均
    ,nt0_m_avg_bal -- 非T0理财余额月日均
    ,nt0_cp_m_avg -- 非T0理财余额月月均比上月
    ,sr_acct_qavg -- 非保本理财季日均
    ,sr_cp_q_avg -- 非保本理财季日均季净增
    ,sr_acct_yavg -- 非保本理财年日均
    ,sr_cp_y_avg -- 非保本理财年日均年净增
    ,sr_acct_bal -- 非保本理财余额
    ,sr_q_cp_bal -- 非保本理财余额季净增
    ,sr_acct_jz_bal -- 非保本理财余额净增
    ,sr_y_cp_bal -- 非保本理财余额年净增
    ,sr_m_cp_bal -- 非保本理财余额月净增
    ,sr_acct_mavg -- 非保本理财月日均
    ,sr_cp_m_avg -- 非保本理财月日均月净增
    ,fmone_cp_q_avg -- 非货币基金季日均比上季
    ,fmone_cp_y_avg -- 非货币基金年日均比上年
    ,fmone_acct_bal -- 非货币基金余额
    ,fmone_cp_q_bal -- 非货币基金余额比上季
    ,fmone_cp_y_bal -- 非货币基金余额比上年
    ,fmone_cp_d_bal -- 非货币基金余额比上日
    ,fmone_cp_m_bal -- 非货币基金余额比上月
    ,fmone_q_avg_bal -- 非货币基金余额季日均
    ,fmone_y_avg_bal -- 非货币基金余额年日均
    ,fmone_m_avg_bal -- 非货币基金余额余月日均
    ,fmone_cp_m_avg -- 非货币基金月日均比上月
    ,sr_d_cp_bal -- 个人非保本理财余额日净增
    ,sr_w_cp_bal -- 个人非保本理财余额周净增
    ,fin_cp_w_bal -- 个人理财余额周净增
    ,metals_cp_w_bal -- 贵金属产品余额周净增
    ,rm_q_avg_bal -- 滚动理财季日均
    ,rm_y_avg_bal -- 滚动理财年日均
    ,rm_acct_bal -- 滚动理财余额
    ,rm_m_avg_bal -- 滚动理财月日均
    ,cur_y_cp_bal -- 活期存款较上年新增余额
    ,cur_acct_bal -- 活期存款余额
    ,cur_q_cp_bal -- 活期存款余额季净增
    ,cur_q_avg_bal -- 活期存款余额季日均
    ,cur_acct_jz_bal -- 活期存款余额净增
    ,cur_y_avg_bal -- 活期存款余额年日均
    ,cur_m_cp_bal -- 活期存款余额月净增
    ,cur_m_avg_bal -- 活期存款余额月日均
    ,mone_acct_bal -- 货币基金余额
    ,mone_cp_q_bal -- 货币基金余额比上季度
    ,mone_cp_y_bal -- 货币基金余额比上年
    ,mone_cp_d_bal -- 货币基金余额比上日
    ,mone_cp_m_bal -- 货币基金余额比上月
    ,mone_cp_q_avg -- 货币基金余额季均比上季度
    ,mone_q_avg_bal -- 货币基金余额季日均
    ,mone_cp_y_avg -- 货币基金余额年均比上年
    ,mone_y_avg_bal -- 货币基金余额年日均
    ,mone_cp_m_avg -- 货币基金余额月均比上月
    ,mone_m_avg_bal -- 货币基金余额月日均
    ,fund_acct_qavg -- 基金季日均
    ,fund_acct_yavg -- 基金年日均
    ,fund_cp_w_bal -- 基金市值周净增
    ,fund_acct_bal -- 基金余额（统计认购成功、委托状态、在途的基金余额）
    ,fund_cp_q_bal -- 基金余额比上季度
    ,fund_cp_y_bal -- 基金余额比上年
    ,fund_cp_d_bal -- 基金余额比上日
    ,fund_cp_m_bal -- 基金余额比上月
    ,fund_q_cp_bal -- 基金余额季净增
    ,fund_cp_q_avg -- 基金余额季均比上季度
    ,fund_acct_jz_bal -- 基金余额净增
    ,fund_y_cp_bal -- 基金余额年净增
    ,fund_cp_y_avg -- 基金余额年均比上年
    ,fund_m_cp_bal -- 基金余额月净增
    ,fund_cp_m_avg -- 基金余额月月均比上月
    ,fund_acct_mavg -- 基金月日均
    ,ft_bal -- 家族信托余额
    ,ft_cp_q_bal -- 家族信托余额比上季
    ,ft_cp_y_bal -- 家族信托余额比上年
    ,ft_cp_d_bal -- 家族信托余额比上日
    ,ft_cp_m_bal -- 家族信托余额比上月
    ,ft_cp_q_avg -- 家族信托余额季均比上季度
    ,ft_q_avg -- 家族信托余额季日均
    ,ft_cp_y_avg -- 家族信托余额年均比上年
    ,ft_y_avg -- 家族信托余额年日均
    ,ft_cp_m_avg -- 家族信托余额月均比上月
    ,ft_m_avg -- 家族信托余额月日均
    ,loan_business_acct_bal -- 经营贷余额
    ,cust_id -- 客户ID
    ,asset_level -- 客户风险等级
    ,fin_fdyk -- 客户基金浮动盈亏
    ,fin_profit_ratio -- 客户基金浮动盈亏比率
    ,fin_lj_profit -- 客户基金累计收益
    ,cust_name -- 客户名称
    ,lc_zr_bal -- 理财产品转让金额
    ,fin_acct_qavg -- 理财季日均
    ,fin_acct_yavg -- 理财年日均
    ,fin_acct_bal -- 理财余额（保本理财余额+非保本理财余额，不包含分销理财余额）
    ,fin_cp_q_bal -- 理财余额比上季度
    ,fin_cp_y_bal -- 理财余额比上年
    ,fin_cp_d_bal -- 理财余额比上日
    ,fin_cp_m_bal -- 理财余额比上月
    ,fin_cp_q_avg -- 理财余额季均比上季度
    ,fin_acct_jz_bal -- 理财余额净增
    ,fin_cp_y_avg -- 理财余额年均比上年
    ,fin_cp_m_avg -- 理财余额月月均比上月
    ,fin_acct_mavg -- 理财月日均
    ,depfinc_avgq_bal -- 零售存款季日均
    ,depfinc_avgqcpq_bal -- 零售存款季日均季净增
    ,depfinc_avgy_bal -- 零售存款年日均
    ,depfinc_avgycpy_bal -- 零售存款年日均年净增
    ,depfinc_bal -- 零售存款余额
    ,dept_acct_bal -- 零售存款余额（活期存款余额+定期存款余额）
    ,dept_cp_q_bal -- 零售存款余额比上季度
    ,dept_cp_y_bal -- 零售存款余额比上年
    ,dept_cp_d_bal -- 零售存款余额比上日
    ,dept_cp_m_bal -- 零售存款余额比上月
    ,depfinc_cpq_bal -- 零售存款余额季净增
    ,dept_cp_q_avg -- 零售存款余额季均比上季度
    ,dept_q_avg_bal -- 零售存款余额季日均
    ,depfinc_cpy_bal -- 零售存款余额年净增
    ,dept_cp_y_avg -- 零售存款余额年均比上年
    ,dept_y_avg_bal -- 零售存款余额年日均
    ,depfinc_cpd_bal -- 零售存款余额日净增
    ,depfinc_cpm_bal -- 零售存款余额月净增
    ,dept_cp_m_avg -- 零售存款余额月均比上月
    ,depfinc_cpw_bal -- 零售存款余额周净增
    ,dept_acct_mavg -- 零售存款月日均
    ,depfinc_avgm_bal -- 零售存款月日均
    ,depfinc_avgmcpm_bal -- 零售存款月日均月净增
    ,loan_acct_yavg -- 零售贷款年日均
    ,loan_acct_bal -- 零售贷款余额
    ,loan_cp_q_bal -- 零售贷款余额比上季度
    ,loan_cp_y_bal -- 零售贷款余额比上年
    ,loan_cp_d_bal -- 零售贷款余额比上日
    ,loan_cp_m_bal -- 零售贷款余额比上月
    ,loan_cp_q_avg -- 零售贷款余额季均比上季度
    ,loan_q_avg_bal -- 零售贷款余额季日均
    ,loan_cp_y_avg -- 零售贷款余额年均比上年
    ,loan_cp_m_avg -- 零售贷款余额月月均比上月
    ,loan_acct_mavg -- 零售贷款月日均
    ,loan_other_acct_bal -- 其他贷款余额
    ,metals_acct_bal -- 实物贵金属余额（统计客户名下生效的实物贵金属台账，数据由CRM提供）
    ,metals_cp_q_bal -- 实物贵金属余额比上季度
    ,metals_cp_y_bal -- 实物贵金属余额比上年
    ,metals_cp_d_bal -- 实物贵金属余额比上日
    ,metals_cp_m_bal -- 实物贵金属余额比上月
    ,metals_cp_q_avg -- 实物贵金属余额季均比上季度
    ,metals_q_avg_bal -- 实物贵金属余额季日均
    ,metals_acct_jz_bal -- 实物贵金属余额净增
    ,metals_cp_y_avg -- 实物贵金属余额年均比上年
    ,metals_y_avg_bal -- 实物贵金属余额年日均
    ,metals_m_avg_bal -- 实物贵金属余额月日均
    ,metals_cp_m_avg -- 实物贵金属余额月月均比上月
    ,et_dt -- 数据日期
    ,asset_level1 -- 细分资产等级
    ,loan_consum_acct_bal -- 消费贷余额 贷款业务类型
    ,new_q_avg_bal -- 新兴存季日均
    ,new_cp_q_avg -- 新兴存季日均比上季
    ,new_y_avg_bal -- 新兴存年日均
    ,new_cp_y_avg -- 新兴存年日均比上年
    ,new_acct_bal -- 新兴存余额
    ,new_cp_q_bal -- 新兴存余额比上季
    ,new_cp_y_bal -- 新兴存余额比上年
    ,new_cp_d_bal -- 新兴存余额比上日
    ,new_cp_m_bal -- 新兴存余额比上月
    ,new_m_avg_bal -- 新兴存月日均
    ,new_cp_m_avg -- 新兴存月日均比上月
    ,sdp_q_avg_bal -- 智能存款季日均
    ,sdp_y_avg_bal -- 智能存款年日均
    ,sdp_acct_bal -- 智能存款余额
    ,sdp_m_avg_bal -- 智能存款月日均
    ,trust_acct_qavg -- 资管信托季日均
    ,trust_acct_yavg -- 资管信托年日均
    ,trust_acct_bal -- 资管信托余额（统计认购成功、委托状态、在途的基金余额）
    ,trust_cp_q_bal -- 资管信托余额比上季度
    ,trust_cp_y_bal -- 资管信托余额比上年
    ,trust_cp_d_bal -- 资管信托余额比上日
    ,trust_cp_m_bal -- 资管信托余额比上月
    ,trust_cp_q_avg -- 资管信托余额季均比上季度
    ,trust_acct_jz_bal -- 资管信托余额净增
    ,trust_cp_y_avg -- 资管信托余额年均比上年
    ,trust_cp_m_avg -- 资管信托余额月月均比上月
    ,trust_cp_w_bal -- 资管信托余额周净增
    ,trust_acct_mavg -- 资管信托月日均
    ,zy_q_avg_bal -- 自营理财季日均
    ,sr_q_zy_q_avg_bal -- 自营理财季日均季净增
    ,zy_y_avg_bal -- 自营理财年日均
    ,sr_y_zy_y_avg_bal -- 自营理财年日均年净增
    ,zy_finc_bal -- 自营理财余额
    ,sr_q_zy_finc_bal -- 自营理财余额季净增
    ,sr_y_zy_finc_bal -- 自营理财余额年净增
    ,sr_d_zy_finc_bal -- 自营理财余额日净增
    ,sr_m_zy_finc_bal -- 自营理财余额月净增
    ,sr_w_zy_finc_bal -- 自营理财余额周净增
    ,zy_m_avg_bal -- 自营理财月日均
    ,sr_m_zy_m_avg_bal -- 自营理财月日均月净增
    ,etl_dt -- ETL处理日期
    ,etl_timestamp -- ETL处理时间戳
)
select
    aum_q_avg_bal -- AUM季均值
    ,aum_cp_q_mavg -- AUM季均值较上季度
    ,aum_cp_q_bal -- AUM较上季度末新增余额
    ,aum_cp_y_bal -- AUM较上年末新增余额
    ,aum_cp_m_bal -- AUM较上月末新增余额
    ,aum_cp_d_bal -- AUM较昨日新增余额
    ,aum_cp_y_yavg -- aum年均比上年
    ,aum_y_avg_bal -- AUM年均值
    ,aum_acct_bal -- AUM余额（保险余额+基金余额+零售存款余额+理财余额+实物贵金属余额+第三方存管保证金余额+资管信托余额）
    ,aum_cp_w_bal -- AUM余额较上周
    ,aum_m_avg_bal -- AUM月均值
    ,aum_cp_y_mavg -- AUM月均值较上年
    ,aum_cp_m_mavg -- AUM月均值较上月
    ,e_fund_q_avg_bal -- E基金季日均
    ,e_fund_y_avg_bal -- E基金年日均
    ,e_fund_acct_bal -- E基金余额
    ,e_fund_m_avg_bal -- E基金月日均
    ,t0_sr_q_avg_bal -- T0非保本理财季日均
    ,t0_sr_y_avg_bal -- T0非保本理财年日均
    ,t0_sr_acct_bal -- T0非保本理财余额
    ,t0_cp_q_bal -- T0非保本理财余额比上季度
    ,t0_cp_y_bal -- T0非保本理财余额比上年
    ,t0_cp_d_bal -- T0非保本理财余额比上日
    ,t0_cp_m_bal -- T0非保本理财余额比上月
    ,t0_cp_q_avg -- T0非保本理财余额季均比上季度
    ,t0_cp_y_avg -- T0非保本理财余额年均比上年
    ,t0_cp_m_avg -- T0非保本理财余额月月均比上月
    ,t0_sr_m_avg_bal -- T0非保本理财月日均
    ,t0_q_avg_bal -- T0理财季日均
    ,t0_acct_cp_q_avg -- T0理财季日均比上季
    ,t0_y_avg_bal -- T0理财年日均
    ,t0_acct_cp_y_avg -- T0理财年日均比上年
    ,t0_acct_bal -- T0理财余额
    ,t0_acct_cp_q_bal -- T0理财余额比上季
    ,t0_acct_cp_y_bal -- T0理财余额比上年
    ,t0_acct_cp_d_bal -- T0理财余额比上日
    ,t0_acct_cp_m_bal -- T0理财余额比上月
    ,t0_m_avg_bal -- T0理财月日均
    ,t0_acct_cp_m_avg -- T0理财月日均比上月
    ,axc_q_avg_bal -- 安兴存季日均
    ,axc_cp_q_avg -- 安兴存季日均比上季
    ,axc_y_avg_bal -- 安兴存年日均
    ,axc_cp_y_avg -- 安兴存年日均比上年
    ,axc_acct_bal -- 安兴存余额
    ,axc_cp_q_bal -- 安兴存余额比上季
    ,axc_cp_y_bal -- 安兴存余额比上年
    ,axc_cp_d_bal -- 安兴存余额比上日
    ,axc_cp_m_bal -- 安兴存余额比上月
    ,axc_m_avg_bal -- 安兴存月日均
    ,axc_cp_m_avg -- 安兴存月日均比上月
    ,loan_mortgage_acct_bal -- 按揭贷余额
    ,nsr_acct_qavg -- 保本理财季日均
    ,nsr_cp_q_avg -- 保本理财季日均季净增
    ,nsr_acct_yavg -- 保本理财年日均
    ,nsr_cp_y_avg -- 保本理财年日均年净增
    ,nsr_acct_bal -- 保本理财余额
    ,nsr_q_cp_bal -- 保本理财余额季净增
    ,nsr_y_cp_bal -- 保本理财余额年净增
    ,nsr_m_cp_bal -- 保本理财余额月净增
    ,nsr_acct_mavg -- 保本理财月日均
    ,nsr_cp_m_avg -- 保本理财月日均月净增
    ,ensure_fee -- 保费金额
    ,insure_acct_bal -- 保险余额（包括理财系统提供的保险和CRM提供保险台账，只有承保的保险台账才计入AUM）
    ,insure_cp_q_bal -- 保险余额比上季度
    ,insure_cp_y_bal -- 保险余额比上年
    ,insure_cp_d_bal -- 保险余额比上日
    ,insure_cp_m_bal -- 保险余额比上月
    ,insure_cp_q_avg -- 保险余额季均比上季度
    ,insure_q_avg_bal -- 保险余额季日均
    ,insure_acct_jz_bal -- 保险余额净增
    ,insure_cp_y_avg -- 保险余额年均比上年
    ,insure_y_avg_bal -- 保险余额年日均
    ,insure_cp_m_avg -- 保险余额月月均比上月
    ,insure_cp_w_bal -- 保险余额周净增
    ,insure_m_avg_bal -- 保险月日均
    ,cds_q_avg_bal -- 大额存单季日均
    ,cds_cp_q_avg -- 大额存单季日均季净增
    ,cds_y_avg_bal -- 大额存单年日均
    ,cds_cp_y_avg -- 大额存单年日均年净增
    ,cds_acct_bal -- 大额存单余额
    ,cds_q_cp_bal -- 大额存单余额季净增
    ,cds_y_cp_bal -- 大额存单余额年净增
    ,cds_m_cp_bal -- 大额存单余额月净增
    ,cds_m_avg_bal -- 大额存单月日均
    ,cds_cp_m_avg -- 大额存单月日均月净增
    ,decd_zr_sum -- 大额存单转让金额
    ,dx_q_avg_bal -- 代销理财季日均
    ,sr_q_dx_q_avg_bal -- 代销理财季日均季净增
    ,dx_y_avg_bal -- 代销理财年日均
    ,sr_y_dx_y_avg_bal -- 代销理财年日均年净增
    ,dx_finc_bal -- 代销理财余额
    ,sr_q_dx_finc_bal -- 代销理财余额季净增
    ,sr_y_dx_finc_bal -- 代销理财余额年净增
    ,sr_d_dx_finc_bal -- 代销理财余额日净增
    ,sr_m_dx_finc_bal -- 代销理财余额月净增
    ,sr_w_dx_finc_bal -- 代销理财余额周净增
    ,dx_m_avg_bal -- 代销理财月日均
    ,sr_m_dx_m_avg_bal -- 代销理财月日均月净增
    ,t_agent_acct_qavg -- 第三方存管季日均
    ,t_agent_acct_yavg -- 第三方存管年日均
    ,t_agent_acct_bal -- 第三方存管余额（第三方存管的保证金总金额）
    ,t_agent_acct_jz_bal -- 第三方存管余额净增
    ,t_agent_acct_mavg -- 第三方存管月日均
    ,third_acct_bal -- 第三方存款保证金余额
    ,third_cp_q_bal -- 第三方存款保证余额比上季度
    ,third_cp_y_bal -- 第三方存款保证余额比上年
    ,third_cp_d_bal -- 第三方存款保证余额比上日
    ,third_cp_m_bal -- 第三方存款保证余额比上月
    ,third_cp_q_avg -- 第三方存款保证余额季均比上季度
    ,third_cp_y_avg -- 第三方存款保证余额年均比上年
    ,third_y_avg_bal -- 第三方存款保证余额年日均
    ,third_m_avg_bal -- 第三方存款保证余额月日均
    ,third_cp_m_avg -- 第三方存款保证余额月月均比上月
    ,dep_cp_q_avg -- 定期存款季日均季净增
    ,dep_cp_y_avg -- 定期存款年日均年净增
    ,dep_acct_bal -- 定期存款余额
    ,dep_q_cp_bal -- 定期存款余额季净增
    ,dep_q_avg_bal -- 定期存款余额季日均
    ,dep_acct_jz_bal -- 定期存款余额净增
    ,dep_y_cp_bal -- 定期存款余额年净增
    ,dep_y_avg_bal -- 定期存款余额年日均
    ,dep_m_avg_bal -- 定期存款余额余月日均
    ,dep_m_cp_bal -- 定期存款余额月净增
    ,dep_cp_m_avg -- 定期存款月日均月净增
    ,nt0_acct_bal -- 非T0理财余额
    ,nt0_cp_q_bal -- 非T0理财余额比上季度
    ,nt0_cp_y_bal -- 非T0理财余额比上年
    ,nt0_cp_d_bal -- 非T0理财余额比上日
    ,nt0_cp_m_bal -- 非T0理财余额比上月
    ,nt0_cp_q_avg -- 非T0理财余额季均比上季度
    ,nt0_q_avg_bal -- 非T0理财余额季日均
    ,nt0_cp_y_avg -- 非T0理财余额年均比上年
    ,nt0_y_avg_bal -- 非T0理财余额年日均
    ,nt0_m_avg_bal -- 非T0理财余额月日均
    ,nt0_cp_m_avg -- 非T0理财余额月月均比上月
    ,sr_acct_qavg -- 非保本理财季日均
    ,sr_cp_q_avg -- 非保本理财季日均季净增
    ,sr_acct_yavg -- 非保本理财年日均
    ,sr_cp_y_avg -- 非保本理财年日均年净增
    ,sr_acct_bal -- 非保本理财余额
    ,sr_q_cp_bal -- 非保本理财余额季净增
    ,sr_acct_jz_bal -- 非保本理财余额净增
    ,sr_y_cp_bal -- 非保本理财余额年净增
    ,sr_m_cp_bal -- 非保本理财余额月净增
    ,sr_acct_mavg -- 非保本理财月日均
    ,sr_cp_m_avg -- 非保本理财月日均月净增
    ,fmone_cp_q_avg -- 非货币基金季日均比上季
    ,fmone_cp_y_avg -- 非货币基金年日均比上年
    ,fmone_acct_bal -- 非货币基金余额
    ,fmone_cp_q_bal -- 非货币基金余额比上季
    ,fmone_cp_y_bal -- 非货币基金余额比上年
    ,fmone_cp_d_bal -- 非货币基金余额比上日
    ,fmone_cp_m_bal -- 非货币基金余额比上月
    ,fmone_q_avg_bal -- 非货币基金余额季日均
    ,fmone_y_avg_bal -- 非货币基金余额年日均
    ,fmone_m_avg_bal -- 非货币基金余额余月日均
    ,fmone_cp_m_avg -- 非货币基金月日均比上月
    ,sr_d_cp_bal -- 个人非保本理财余额日净增
    ,sr_w_cp_bal -- 个人非保本理财余额周净增
    ,fin_cp_w_bal -- 个人理财余额周净增
    ,metals_cp_w_bal -- 贵金属产品余额周净增
    ,rm_q_avg_bal -- 滚动理财季日均
    ,rm_y_avg_bal -- 滚动理财年日均
    ,rm_acct_bal -- 滚动理财余额
    ,rm_m_avg_bal -- 滚动理财月日均
    ,cur_y_cp_bal -- 活期存款较上年新增余额
    ,cur_acct_bal -- 活期存款余额
    ,cur_q_cp_bal -- 活期存款余额季净增
    ,cur_q_avg_bal -- 活期存款余额季日均
    ,cur_acct_jz_bal -- 活期存款余额净增
    ,cur_y_avg_bal -- 活期存款余额年日均
    ,cur_m_cp_bal -- 活期存款余额月净增
    ,cur_m_avg_bal -- 活期存款余额月日均
    ,mone_acct_bal -- 货币基金余额
    ,mone_cp_q_bal -- 货币基金余额比上季度
    ,mone_cp_y_bal -- 货币基金余额比上年
    ,mone_cp_d_bal -- 货币基金余额比上日
    ,mone_cp_m_bal -- 货币基金余额比上月
    ,mone_cp_q_avg -- 货币基金余额季均比上季度
    ,mone_q_avg_bal -- 货币基金余额季日均
    ,mone_cp_y_avg -- 货币基金余额年均比上年
    ,mone_y_avg_bal -- 货币基金余额年日均
    ,mone_cp_m_avg -- 货币基金余额月均比上月
    ,mone_m_avg_bal -- 货币基金余额月日均
    ,fund_acct_qavg -- 基金季日均
    ,fund_acct_yavg -- 基金年日均
    ,fund_cp_w_bal -- 基金市值周净增
    ,fund_acct_bal -- 基金余额（统计认购成功、委托状态、在途的基金余额）
    ,fund_cp_q_bal -- 基金余额比上季度
    ,fund_cp_y_bal -- 基金余额比上年
    ,fund_cp_d_bal -- 基金余额比上日
    ,fund_cp_m_bal -- 基金余额比上月
    ,fund_q_cp_bal -- 基金余额季净增
    ,fund_cp_q_avg -- 基金余额季均比上季度
    ,fund_acct_jz_bal -- 基金余额净增
    ,fund_y_cp_bal -- 基金余额年净增
    ,fund_cp_y_avg -- 基金余额年均比上年
    ,fund_m_cp_bal -- 基金余额月净增
    ,fund_cp_m_avg -- 基金余额月月均比上月
    ,fund_acct_mavg -- 基金月日均
    ,ft_bal -- 家族信托余额
    ,ft_cp_q_bal -- 家族信托余额比上季
    ,ft_cp_y_bal -- 家族信托余额比上年
    ,ft_cp_d_bal -- 家族信托余额比上日
    ,ft_cp_m_bal -- 家族信托余额比上月
    ,ft_cp_q_avg -- 家族信托余额季均比上季度
    ,ft_q_avg -- 家族信托余额季日均
    ,ft_cp_y_avg -- 家族信托余额年均比上年
    ,ft_y_avg -- 家族信托余额年日均
    ,ft_cp_m_avg -- 家族信托余额月均比上月
    ,ft_m_avg -- 家族信托余额月日均
    ,loan_business_acct_bal -- 经营贷余额
    ,cust_id -- 客户ID
    ,asset_level -- 客户风险等级
    ,fin_fdyk -- 客户基金浮动盈亏
    ,fin_profit_ratio -- 客户基金浮动盈亏比率
    ,fin_lj_profit -- 客户基金累计收益
    ,cust_name -- 客户名称
    ,lc_zr_bal -- 理财产品转让金额
    ,fin_acct_qavg -- 理财季日均
    ,fin_acct_yavg -- 理财年日均
    ,fin_acct_bal -- 理财余额（保本理财余额+非保本理财余额，不包含分销理财余额）
    ,fin_cp_q_bal -- 理财余额比上季度
    ,fin_cp_y_bal -- 理财余额比上年
    ,fin_cp_d_bal -- 理财余额比上日
    ,fin_cp_m_bal -- 理财余额比上月
    ,fin_cp_q_avg -- 理财余额季均比上季度
    ,fin_acct_jz_bal -- 理财余额净增
    ,fin_cp_y_avg -- 理财余额年均比上年
    ,fin_cp_m_avg -- 理财余额月月均比上月
    ,fin_acct_mavg -- 理财月日均
    ,depfinc_avgq_bal -- 零售存款季日均
    ,depfinc_avgqcpq_bal -- 零售存款季日均季净增
    ,depfinc_avgy_bal -- 零售存款年日均
    ,depfinc_avgycpy_bal -- 零售存款年日均年净增
    ,depfinc_bal -- 零售存款余额
    ,dept_acct_bal -- 零售存款余额（活期存款余额+定期存款余额）
    ,dept_cp_q_bal -- 零售存款余额比上季度
    ,dept_cp_y_bal -- 零售存款余额比上年
    ,dept_cp_d_bal -- 零售存款余额比上日
    ,dept_cp_m_bal -- 零售存款余额比上月
    ,depfinc_cpq_bal -- 零售存款余额季净增
    ,dept_cp_q_avg -- 零售存款余额季均比上季度
    ,dept_q_avg_bal -- 零售存款余额季日均
    ,depfinc_cpy_bal -- 零售存款余额年净增
    ,dept_cp_y_avg -- 零售存款余额年均比上年
    ,dept_y_avg_bal -- 零售存款余额年日均
    ,depfinc_cpd_bal -- 零售存款余额日净增
    ,depfinc_cpm_bal -- 零售存款余额月净增
    ,dept_cp_m_avg -- 零售存款余额月均比上月
    ,depfinc_cpw_bal -- 零售存款余额周净增
    ,dept_acct_mavg -- 零售存款月日均
    ,depfinc_avgm_bal -- 零售存款月日均
    ,depfinc_avgmcpm_bal -- 零售存款月日均月净增
    ,loan_acct_yavg -- 零售贷款年日均
    ,loan_acct_bal -- 零售贷款余额
    ,loan_cp_q_bal -- 零售贷款余额比上季度
    ,loan_cp_y_bal -- 零售贷款余额比上年
    ,loan_cp_d_bal -- 零售贷款余额比上日
    ,loan_cp_m_bal -- 零售贷款余额比上月
    ,loan_cp_q_avg -- 零售贷款余额季均比上季度
    ,loan_q_avg_bal -- 零售贷款余额季日均
    ,loan_cp_y_avg -- 零售贷款余额年均比上年
    ,loan_cp_m_avg -- 零售贷款余额月月均比上月
    ,loan_acct_mavg -- 零售贷款月日均
    ,loan_other_acct_bal -- 其他贷款余额
    ,metals_acct_bal -- 实物贵金属余额（统计客户名下生效的实物贵金属台账，数据由CRM提供）
    ,metals_cp_q_bal -- 实物贵金属余额比上季度
    ,metals_cp_y_bal -- 实物贵金属余额比上年
    ,metals_cp_d_bal -- 实物贵金属余额比上日
    ,metals_cp_m_bal -- 实物贵金属余额比上月
    ,metals_cp_q_avg -- 实物贵金属余额季均比上季度
    ,metals_q_avg_bal -- 实物贵金属余额季日均
    ,metals_acct_jz_bal -- 实物贵金属余额净增
    ,metals_cp_y_avg -- 实物贵金属余额年均比上年
    ,metals_y_avg_bal -- 实物贵金属余额年日均
    ,metals_m_avg_bal -- 实物贵金属余额月日均
    ,metals_cp_m_avg -- 实物贵金属余额月月均比上月
    ,et_dt -- 数据日期
    ,asset_level1 -- 细分资产等级
    ,loan_consum_acct_bal -- 消费贷余额 贷款业务类型
    ,new_q_avg_bal -- 新兴存季日均
    ,new_cp_q_avg -- 新兴存季日均比上季
    ,new_y_avg_bal -- 新兴存年日均
    ,new_cp_y_avg -- 新兴存年日均比上年
    ,new_acct_bal -- 新兴存余额
    ,new_cp_q_bal -- 新兴存余额比上季
    ,new_cp_y_bal -- 新兴存余额比上年
    ,new_cp_d_bal -- 新兴存余额比上日
    ,new_cp_m_bal -- 新兴存余额比上月
    ,new_m_avg_bal -- 新兴存月日均
    ,new_cp_m_avg -- 新兴存月日均比上月
    ,sdp_q_avg_bal -- 智能存款季日均
    ,sdp_y_avg_bal -- 智能存款年日均
    ,sdp_acct_bal -- 智能存款余额
    ,sdp_m_avg_bal -- 智能存款月日均
    ,trust_acct_qavg -- 资管信托季日均
    ,trust_acct_yavg -- 资管信托年日均
    ,trust_acct_bal -- 资管信托余额（统计认购成功、委托状态、在途的基金余额）
    ,trust_cp_q_bal -- 资管信托余额比上季度
    ,trust_cp_y_bal -- 资管信托余额比上年
    ,trust_cp_d_bal -- 资管信托余额比上日
    ,trust_cp_m_bal -- 资管信托余额比上月
    ,trust_cp_q_avg -- 资管信托余额季均比上季度
    ,trust_acct_jz_bal -- 资管信托余额净增
    ,trust_cp_y_avg -- 资管信托余额年均比上年
    ,trust_cp_m_avg -- 资管信托余额月月均比上月
    ,trust_cp_w_bal -- 资管信托余额周净增
    ,trust_acct_mavg -- 资管信托月日均
    ,zy_q_avg_bal -- 自营理财季日均
    ,sr_q_zy_q_avg_bal -- 自营理财季日均季净增
    ,zy_y_avg_bal -- 自营理财年日均
    ,sr_y_zy_y_avg_bal -- 自营理财年日均年净增
    ,zy_finc_bal -- 自营理财余额
    ,sr_q_zy_finc_bal -- 自营理财余额季净增
    ,sr_y_zy_finc_bal -- 自营理财余额年净增
    ,sr_d_zy_finc_bal -- 自营理财余额日净增
    ,sr_m_zy_finc_bal -- 自营理财余额月净增
    ,sr_w_zy_finc_bal -- 自营理财余额周净增
    ,zy_m_avg_bal -- 自营理财月日均
    ,sr_m_zy_m_avg_bal -- 自营理财月日均月净增
    ,to_date('${batch_date}','yyyymmdd') as etl_dt -- ETL处理日期
    ,to_timestamp('${batch_timestamp}', 'yyyy-mm-dd hh24:mi:ss.ff6') as etl_timestamp -- ETL处理时间
from ${itl_schema}.pams_pam_aum
where etl_dt = to_date('${batch_date}', 'yyyymmdd')
;

-- 2.4 exchage ex table and target table
alter table ${iol_schema}.pams_pam_aum exchange partition p_${batch_date} with table ${iol_schema}.pams_pam_aum_ex;

-- 3.1 table grant
whenever sqlerror exit sql.sqlcode;
-- grant select on ${iol_schema}.pams_pam_aum to ${iml_schema};

-- 3.2 drop ex table
drop table ${iol_schema}.pams_pam_aum_ex purge;

-- 4 gater table status
exec dbms_stats.gather_table_stats(ownname => '${iol_schema}',tabname => 'pams_pam_aum',partname => 'p_${batch_date}', granularity => 'PARTITION', degree => 8, cascade => true);