/*
Purpose:    偏源模型层-全量流水脚本，清空目标表，把当天数据与目标表进行分区交换。此脚本由生成引擎自动生成。
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iol_ibms_ttrd_accounting_secu_obj_his
CreateDate: 20180515
Logs:
    zjj 2018-05-15 新建脚本
*/
set timing on

-- 1 alter parallel
alter session force parallel query parallel 8;
alter session force parallel dml parallel 8;
-- alter session force parallel ddl parallel 8;
truncate table ibms_ttrd_accounting_secu_obj_his;

whenever sqlerror continue none ;
alter table ibms_ttrd_accounting_secu_obj_his add partition p_${batch_date} values (to_date(${batch_date},'yyyymmdd'));

insert /*+ append */ into ${iol_schema}.ibms_ttrd_accounting_secu_obj_his(
    obj_id -- 对象id
    ,tsk_id -- 任务id
    ,beg_date -- 开始日期
    ,end_date -- 结束日期
    ,ext_secu_acct_id -- 外部券账户
    ,secu_acct_id -- 内部券账户
    ,trade_grp_id -- 组合交易号
    ,i_code -- 金融工具代码
    ,a_type -- 金融工具资产类型
    ,m_type -- 金融工具资产类型
    ,trade_id -- 交易号
    ,extra_dim -- 额外维度
    ,real_volume -- 数量
    ,real_amount -- 余额
    ,real_cp -- 净价成本
    ,ai -- 应计利息
    ,ai_cost -- 利息成本
    ,chg_fv -- 公允价值变动
    ,due_amount -- 应收未收余额
    ,due_cp -- 应收未收净价成本
    ,due_ai -- 应收未收应计利息
    ,amrt_count -- 当天摊销业务次数
    ,amrt_date -- 摊销日期
    ,amrt_ir -- 利息调整
    ,prft_fv -- 公允价值损益
    ,prft_trd -- 买卖损益
    ,prft_ir -- 利息收入
    ,prft_ir_ai -- 应计利息利息收入
    ,prft_ir_amrt -- 摊销利息收入
    ,prft_ir_ai_hld -- 当前持仓应计利息利息收入
    ,prft_ir_amrt_hld -- 当前持仓摊销利息收入
    ,reclass_prft_fv -- 重分类公允价值损益
    ,impair -- 减值准备
    ,prft_impair -- 减值损失
    ,real_margin -- 期货保证金
    ,open_time -- 开仓时间
    ,update_time -- 更新时间
    ,prft_fee -- 费用
    ,due_fee -- 费用
    ,fee -- 费用成本
    ,amrt_cost_cp -- 摊余净价成本
    ,amrt_cost_ai -- 摊余利息成本
    ,amrt_ir_hp -- 利息调整(高精度)
    ,amrt_ytm -- 实际利率
    ,invest_ytm -- 投资收益率
    ,open_ytm -- 开仓收益率
    ,future_ai -- 预收息
    ,real_cp_noamrt -- 不摊销净价成本
    ,chg_fv_noamrt -- 不摊销公允价值变动
    ,prft_fv_noamrt -- 不摊销公允价值损益
    ,prft_trd_noamrt -- 不摊销买卖损益
    ,amrt_method -- 摊销算法
    ,real_volume_termcur -- 货币对反向实际数量
    ,real_amount_termcur -- 货币对反向实际面值
    ,due_amount_termcur -- 货币对反向结转面值
    ,real_cp_termcur -- 货币对反向实际成本
    ,due_cp_termcur -- 货币对反向结转成本
    ,prft_ir_amrt_rc -- 重分类利息收入（摊销部分）
    ,prft_ir_amrt_hld_rc -- 重分类利息收入（当前持仓摊销部分）
    ,amrt_cost_cp_rc -- 重分类摊余净价成本
    ,amrt_ytm_rc -- 重分类实际利率
    ,amrt_ir_hp_rc -- 重分类利息调整（高精度）
    ,calc_date -- 计提摊销截止日期
    ,ipr_state -- 减值状态：0-未减值，1-减值，2-核销
    ,ipr_prft_cp -- 成本减值损失
    ,ipr_prft_ai -- 利息减值损失
    ,ipr_cp -- 成本减值准备
    ,ipr_hx_cp -- 已核销成本
    ,ipr_hx_ai -- 已核销应计利息
    ,ipr_hx_due_ai -- 已核销应收未收利息
    ,ipr_bw_ai -- 表外应计利息
    ,ipr_bw_due_ai -- 表外应收未收利息
    ,amrt_date_rc -- 重分类摊销开始日期
    ,amrt_cost_ai_rc -- 重分类摊销开始日期利息成本
    ,open_date_rc -- 重分类开仓日期
    ,prft_ir_ai_calc_tax -- 应计利息收入增量
    ,tax_ai -- 应计增值税
    ,tax_due_ai -- 应付增值税
    ,tax_fee -- 费用收入税/支出税
    ,fv_currency -- 估值币种
    ,set_date -- 结算日期
    ,prft_fv_cash -- 已实现公允价值变动损益
    ,tax_ai_hld -- 当前持仓利息收入税/支出税
    ,open_ai -- 开仓利息成本
    ,open_ytm_opt -- 开仓行权收益率
    ,prft_ir_ai_fut -- 预收利息收入
    ,prft_ir_ai_cur -- 计提利息收入
    ,prft_ir_ai_due -- 应收利息收入
    ,prft_ir_ai_cash -- 实收利息收入
    ,tax_fut_ai -- 计提利息收入预收税
    ,tax_due_amrt -- 摊销利息收入应付增值税
    ,tax_due_amrt_rc -- 重分类后资本公积摊销收入应付增值税
    ,tax_due_trd -- 买卖损益应付增值税
    ,tax_due_fv -- 公允价值损益应付增值税
    ,tax_due_fv_reclass -- 重分类公允价值损益应付增值税
    ,tax_due_fv_cash -- 已实现公允价值损益应付增值税
    ,tax_due_fee -- 费用损益应付增值税
    ,due_chg_fv -- 结转公允价值变动
    ,due_volume -- 结转数量
    ,amrt_verify_code -- 摊销验证码
    ,amrt_verify_date -- 摊销验证日期
    ,prft_reclass -- 重分类损益
    ,close_set_date -- 平仓交割日期
    ,trade_inst_id -- 交易指令号
    ,custom_dim1 -- 扩展维度1
    ,ipr_period -- 减值阶段
    ,ipr_cp1 -- 阶段一减值准备
    ,ipr_cp2 -- 阶段二减值准备
    ,ipr_cp3 -- 阶段三减值准备
    ,ipr_prft_cp1 -- 阶段一减值损失
    ,ipr_prft_cp2 -- 阶段二减值损失
    ,ipr_prft_cp3 -- 阶段三减值损失
    ,amrt_start_ir_hp -- 摊销开始日期初利息调整余额(高精度)
    ,tax_amrt -- 摊销利息收入暂估税
    ,calc_tax_amrt_cur -- 计提摊销利息收入
    ,calc_tax_amrt_due -- 应收摊销利息收入
    ,calc_tax_amrt_cash -- 实收摊销利息收入
    ,tax_fv -- 未实现损益暂估税
    ,tax_ir -- 利息收入暂估税
    ,tax_due_ir -- 利息收入应付增值税
    ,prft_id -- 损益对象id
    ,deviation -- 偏离金额
    ,prft_ir_fut_ai -- 预收息利息收入
    ,obj_type -- 余额类型 -1 正常余额 1 逾期豁免余额
    ,etl_dt -- ETL处理日期
    ,etl_timestamp -- ETL处理时间戳
)
select
    obj_id -- 对象id
    ,tsk_id -- 任务id
    ,beg_date -- 开始日期
    ,end_date -- 结束日期
    ,ext_secu_acct_id -- 外部券账户
    ,secu_acct_id -- 内部券账户
    ,trade_grp_id -- 组合交易号
    ,i_code -- 金融工具代码
    ,a_type -- 金融工具资产类型
    ,m_type -- 金融工具资产类型
    ,trade_id -- 交易号
    ,extra_dim -- 额外维度
    ,real_volume -- 数量
    ,real_amount -- 余额
    ,real_cp -- 净价成本
    ,ai -- 应计利息
    ,ai_cost -- 利息成本
    ,chg_fv -- 公允价值变动
    ,due_amount -- 应收未收余额
    ,due_cp -- 应收未收净价成本
    ,due_ai -- 应收未收应计利息
    ,amrt_count -- 当天摊销业务次数
    ,amrt_date -- 摊销日期
    ,amrt_ir -- 利息调整
    ,prft_fv -- 公允价值损益
    ,prft_trd -- 买卖损益
    ,prft_ir -- 利息收入
    ,prft_ir_ai -- 应计利息利息收入
    ,prft_ir_amrt -- 摊销利息收入
    ,prft_ir_ai_hld -- 当前持仓应计利息利息收入
    ,prft_ir_amrt_hld -- 当前持仓摊销利息收入
    ,reclass_prft_fv -- 重分类公允价值损益
    ,impair -- 减值准备
    ,prft_impair -- 减值损失
    ,real_margin -- 期货保证金
    ,open_time -- 开仓时间
    ,update_time -- 更新时间
    ,prft_fee -- 费用
    ,due_fee -- 费用
    ,fee -- 费用成本
    ,amrt_cost_cp -- 摊余净价成本
    ,amrt_cost_ai -- 摊余利息成本
    ,amrt_ir_hp -- 利息调整(高精度)
    ,amrt_ytm -- 实际利率
    ,invest_ytm -- 投资收益率
    ,open_ytm -- 开仓收益率
    ,future_ai -- 预收息
    ,real_cp_noamrt -- 不摊销净价成本
    ,chg_fv_noamrt -- 不摊销公允价值变动
    ,prft_fv_noamrt -- 不摊销公允价值损益
    ,prft_trd_noamrt -- 不摊销买卖损益
    ,amrt_method -- 摊销算法
    ,real_volume_termcur -- 货币对反向实际数量
    ,real_amount_termcur -- 货币对反向实际面值
    ,due_amount_termcur -- 货币对反向结转面值
    ,real_cp_termcur -- 货币对反向实际成本
    ,due_cp_termcur -- 货币对反向结转成本
    ,prft_ir_amrt_rc -- 重分类利息收入（摊销部分）
    ,prft_ir_amrt_hld_rc -- 重分类利息收入（当前持仓摊销部分）
    ,amrt_cost_cp_rc -- 重分类摊余净价成本
    ,amrt_ytm_rc -- 重分类实际利率
    ,amrt_ir_hp_rc -- 重分类利息调整（高精度）
    ,calc_date -- 计提摊销截止日期
    ,ipr_state -- 减值状态：0-未减值，1-减值，2-核销
    ,ipr_prft_cp -- 成本减值损失
    ,ipr_prft_ai -- 利息减值损失
    ,ipr_cp -- 成本减值准备
    ,ipr_hx_cp -- 已核销成本
    ,ipr_hx_ai -- 已核销应计利息
    ,ipr_hx_due_ai -- 已核销应收未收利息
    ,ipr_bw_ai -- 表外应计利息
    ,ipr_bw_due_ai -- 表外应收未收利息
    ,amrt_date_rc -- 重分类摊销开始日期
    ,amrt_cost_ai_rc -- 重分类摊销开始日期利息成本
    ,open_date_rc -- 重分类开仓日期
    ,prft_ir_ai_calc_tax -- 应计利息收入增量
    ,tax_ai -- 应计增值税
    ,tax_due_ai -- 应付增值税
    ,tax_fee -- 费用收入税/支出税
    ,fv_currency -- 估值币种
    ,set_date -- 结算日期
    ,prft_fv_cash -- 已实现公允价值变动损益
    ,tax_ai_hld -- 当前持仓利息收入税/支出税
    ,open_ai -- 开仓利息成本
    ,open_ytm_opt -- 开仓行权收益率
    ,prft_ir_ai_fut -- 预收利息收入
    ,prft_ir_ai_cur -- 计提利息收入
    ,prft_ir_ai_due -- 应收利息收入
    ,prft_ir_ai_cash -- 实收利息收入
    ,tax_fut_ai -- 计提利息收入预收税
    ,tax_due_amrt -- 摊销利息收入应付增值税
    ,tax_due_amrt_rc -- 重分类后资本公积摊销收入应付增值税
    ,tax_due_trd -- 买卖损益应付增值税
    ,tax_due_fv -- 公允价值损益应付增值税
    ,tax_due_fv_reclass -- 重分类公允价值损益应付增值税
    ,tax_due_fv_cash -- 已实现公允价值损益应付增值税
    ,tax_due_fee -- 费用损益应付增值税
    ,due_chg_fv -- 结转公允价值变动
    ,due_volume -- 结转数量
    ,amrt_verify_code -- 摊销验证码
    ,amrt_verify_date -- 摊销验证日期
    ,prft_reclass -- 重分类损益
    ,close_set_date -- 平仓交割日期
    ,trade_inst_id -- 交易指令号
    ,custom_dim1 -- 扩展维度1
    ,ipr_period -- 减值阶段
    ,ipr_cp1 -- 阶段一减值准备
    ,ipr_cp2 -- 阶段二减值准备
    ,ipr_cp3 -- 阶段三减值准备
    ,ipr_prft_cp1 -- 阶段一减值损失
    ,ipr_prft_cp2 -- 阶段二减值损失
    ,ipr_prft_cp3 -- 阶段三减值损失
    ,amrt_start_ir_hp -- 摊销开始日期初利息调整余额(高精度)
    ,tax_amrt -- 摊销利息收入暂估税
    ,calc_tax_amrt_cur -- 计提摊销利息收入
    ,calc_tax_amrt_due -- 应收摊销利息收入
    ,calc_tax_amrt_cash -- 实收摊销利息收入
    ,tax_fv -- 未实现损益暂估税
    ,tax_ir -- 利息收入暂估税
    ,tax_due_ir -- 利息收入应付增值税
    ,prft_id -- 损益对象id
    ,deviation -- 偏离金额
    ,prft_ir_fut_ai -- 预收息利息收入
    ,' ' as obj_type -- 余额类型 -1 正常余额 1 逾期豁免余额
    ,etl_dt -- ETL处理日期
    ,etl_timestamp -- ETL处理时间
from iol.ibms_ttrd_accounting_secu_obj_his_bak_${batch_date}
where etl_dt = to_date(${batch_date}, 'yyyymmdd');

commit;
