-- Safe public sample: no real business data.
-- Demonstrates field-level lineage across enterprise warehouse layers.

CREATE TABLE ICL.CUSTOMER_DAILY_SNAPSHOT AS
SELECT
    c.CUST_ID,
    c.CUST_NAME,
    a.ACCT_BALANCE,
    CASE
        WHEN a.ACCT_BALANCE > 100000 THEN 'VIP'
        ELSE 'STANDARD'
    END AS CUSTOMER_TIER
FROM IML.CUSTOMER_PROFILE c
LEFT JOIN IOL.ACCOUNT_BALANCE a
    ON c.CUST_ID = a.CUST_ID;

INSERT INTO IDL.CUSTOMER_EXPORT
SELECT
    CUST_ID,
    CUST_NAME,
    CUSTOMER_TIER
FROM ICL.CUSTOMER_DAILY_SNAPSHOT
WHERE CUSTOMER_TIER = 'VIP';
