: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_ccrm_crss_ent_info_f
CreateDate: 20180529
FileName:   ${iel_data_path}/ccrm_crss_ent_info.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
t1.customerid
,t1.corpid
,t1.enterprisename
,t1.englishname
,t1.fictitiousperson
,t1.orgnature
,t1.financetype
,t1.enterprisebelong
,t1.industrytype
,t1.industrytype1
,t1.industrytype2
,t1.private
,t1.economytype
,t1.orgtype
,t1.mostbusiness
,t1.budgettype
,t1.rccurrency
,t1.registercapital
,t1.pccurrency
,t1.paiclupcapital
,t1.fundsource
,t1.totalassets
,t1.netassets
,t1.annualincome
,t1.scope
,t1.limit
,t1.creditdate
,t1.licenseno
,t1.licensedate
,t1.licensematurity
,t1.setupdate
,t1.inspectionyear
,t1.locksituation
,t1.taxno
,t1.banklicense
,t1.bankid
,t1.managearea
,t1.banchamount
,t1.exchangeid
,t1.registeradd
,t1.chargedepartment
,t1.officeadd
,t1.officezip
,t1.countrycode
,t1.regioncode
,t1.villagecode
,t1.villagename
,t1.relativetype
,t1.officetel
,t1.officefax
,t1.webadd
,t1.emailadd
,t1.employeenumber
,t1.mainproduction
,t1.newtechcorpornot
,t1.listingcorpornot
,t1.hasieright
,t1.hasdirectorate
,t1.basicbank
,t1.basicaccount
,t1.manageinfo
,t1.customerhistory
,t1.projectflag
,t1.realtyflag
,t1.workfieldarea
,t1.workfieldfee
,t1.accountdate
,t1.loancardno
,t1.loancardpassword
,t1.loancardinsyear
,t1.loancardinsresult
,t1.loanflag
,t1.financeornot
,t1.financebelong
,t1.creditbelong
,t1.creditlevel
,t1.evaluatedate
,t1.othercreditlevel
,t1.otherevaluatedate
,t1.otherorgname
,t1.inputorgid
,t1.inputuserid
,t1.inputdate
,t1.updateorgid
,t1.updateuserid
,t1.updatedate
,t1.remark
,t1.taxno1
,t1.fictitiouspersonid
,t1.groupflag
,t1.evaluatelevel
,t1.mybank
,t1.mybankaccount
,t1.otherbank
,t1.otherbankaccount
,t1.tempsaveflag
,t1.financedepttel
,t1.ecgroupflag
,t1.supercorpname
,t1.superloancardno
,t1.supercerttype
,t1.smeindustrytype
,t1.sellsum
,t1.supercertid
,t1.isblack
,t1.isdebt
,t1.isstrategycustomer
,t1.ifoversea
,t1.serviceupdateresult
,t1.rwacustomertype
,t1.businessstrategy
,t1.isnewsetup
,t1.isrelative
,t1.ifsme
,t1.locality
,t1.subjectbusiness
,t1.islimit
,t1.privateent
,t1.bankingsupervision
,t1.holdingtype
,t1.fiscalsource
,t1.lmcredittype
,t1.onlycapital
,t1.stratagemflag
,t1.isrelatedparty
,t1.fictitiouspersoncertificateid
,t1.corpstartdate
,t1.corpvaliditydate
,t1.corpregisteradd
,t1.registerdate
,t1.financedirectorname
,t1.mobilephone
,t1.mfcustomerid
,t1.custtp
,t1.custst
,t1.iscred
,t1.ispart
,t1.orgown
,t1.budgtp
,t1.ntlycd
,t1.crylev
,t1.mainfg
,t1.validt
,t1.liisau
,t1.others
,t1.idtfst
,t1.idcdad
,t1.contna
,t1.idtftp
,t1.idtfno
,t1.cmainf
,t1.hometl
,t1.othrtl
,t1.caiwno
,t1.caiwtp
,t1.offitl
,t1.mobitl
,t1.fictitiousmobile
,t1.fictitiousduty
,t1.finalevaluatedate
,t1.iscountrysidenterprise
,t1.financialgroupscope
,t1.financialgroupposition
,t1.industrialrestructuringtype
,t1.transformationandupgradeid
,t1.strategicemergingindustrytype
,t1.creditinstitutioncode
,t1.parentcompanyofficeadd
,t1.officeaddupdatedate
,t1.listingcorporation
,t1.shareholderstructuredate
,t1.hasiebusiness
,t1.orgdetail
,t1.orgstatus
,t1.organiztype
,t1.documenttype
,t1.documentno
,t1.financefiamtel
,t1.financeothertel
,t1.bankingtype
,t1.societyinstitutioncode
,t1.commercialregno
,t1.clyxcustomerid
,t1.onlylimit
,t1.scopecalculate
,t1.raterisklevel
,t1.industrytypeproportion
,t1.industrytypeproportion1
,t1.industrytypeproportion2
from ${idl_schema}.crss_ent_info t1
where start_dt <= to_date('${batch_date}','yyyymmdd') and end_dt > to_date('${batch_date}','yyyymmdd') and t1.etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/ccrm_crss_ent_info.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes