: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_cmm_corp_cust_basic_info_f
CreateDate: 20180529
FileName:   ${iel_data_path}/cmm_corp_cust_basic_info.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
t.ETL_DT as ETL_DT
,t.LP_ID as LP_ID
,t.CUST_ID as CUST_ID
,t.CUST_NAME as CUST_NAME
,t.CUST_EN_NAME as CUST_EN_NAME
,t.CUST_KIND_CD as CUST_KIND_CD
,t.OPEN_ACCT_DT as OPEN_ACCT_DT
,t.BELONG_ORG_ID as BELONG_ORG_ID
,t.OPEN_ACCT_ORG_ID as OPEN_ACCT_ORG_ID
,t.OPEN_ACCT_TELLER_ID as OPEN_ACCT_TELLER_ID
,t.OPEN_ACCT_CHN_CD as OPEN_ACCT_CHN_CD
,t.CREATE_CHN_CD as CREATE_CHN_CD
,t.CUST_MGR_ID as CUST_MGR_ID
,t.CUST_TYPE_CD as CUST_TYPE_CD
,t.CRDT_CUST_TYPE_CD as CRDT_CUST_TYPE_CD
,t.CUST_LEV_CD as CUST_LEV_CD
,t.DEPOSITR_CATE_CD as DEPOSITR_CATE_CD
,t.BAL_PAY_WAY_CD as BAL_PAY_WAY_CD
,t.CUST_STATUS_CD as CUST_STATUS_CD
,t.CORP_ANL_INCO as CORP_ANL_INCO
,t.CORP_YEAR_BUS_LMT as CORP_YEAR_BUS_LMT
,t.CORP_FOUND_DT as CORP_FOUND_DT
,t.CORP_SIZE_CD as CORP_SIZE_CD
,t.INDUS_CATEGY_CD as INDUS_CATEGY_CD
,t.INDUS_TYPE_CD as INDUS_TYPE_CD
,t.INDUS_TYPE_CD_CRDTC as INDUS_TYPE_CD_CRDTC
,t.PHONE_CRDTC as PHONE_CRDTC
,t.CORP_TYPE_CD as CORP_TYPE_CD
,t.CTY_RG_CD as CTY_RG_CD
,t.RG_CD as RG_CD
,t.ECON_CHAR_CD as ECON_CHAR_CD
,t.ECON_TYPE_CD as ECON_TYPE_CD
,t.ORGNZ_CD as ORGNZ_CD
,t.ORGNZ_TYPE_CD as ORGNZ_TYPE_CD
,t.NATNAL_ECON_DEPT_TYPE_CD as NATNAL_ECON_DEPT_TYPE_CD
,t.INDUS_LEVEL5_CLS_CD as INDUS_LEVEL5_CLS_CD
,t.INDUS_CRDT_RATING_CD as INDUS_CRDT_RATING_CD
,t.SOCI_CRDT_CD as SOCI_CRDT_CD
,t.BUS_LICS_NUM as BUS_LICS_NUM
,t.BUS_LICS_EXP_DT as BUS_LICS_EXP_DT
,t.NATION_TAX_RGST_CERT_NUM as NATION_TAX_RGST_CERT_NUM
,t.LOCAL_TAX_RGST_CERT_NUM as LOCAL_TAX_RGST_CERT_NUM
,t.FIN_LICS_NUM as FIN_LICS_NUM
,t.PBC_PAY_BANK_NO as PBC_PAY_BANK_NO
,t.ECON_ORGNZ_FORM_CD as ECON_ORGNZ_FORM_CD
,t.LOAN_CARD_NO as LOAN_CARD_NO
,t.OPER_RANGE as OPER_RANGE
,t.EMPLY_QTTY as EMPLY_QTTY
,t.CURR_CD as CURR_CD
,t.RGST_CAP as RGST_CAP
,t.RGST_ADDR as RGST_ADDR
,t.RGST_DT as RGST_DT
,t.RGSTION_CD as RGSTION_CD
,t.MANG_FIELD_PROP_CD as MANG_FIELD_PROP_CD
,t.CORP_RGSTION_TYPE as CORP_RGSTION_TYPE
,t.PAID_IN_CAPITAL as PAID_IN_CAPITAL
,t.PAID_IN_CAPITAL_CURR_CD as PAID_IN_CAPITAL_CURR_CD
,t.INVTOR_CTY_CD as INVTOR_CTY_CD
,t.MANG_FIELD_AREA as MANG_FIELD_AREA
,t.ASSET_TOT as ASSET_TOT
,t.NET_ASSET_TOT as NET_ASSET_TOT
,t.SINGLE_LP_FLG as SINGLE_LP_FLG
,t.HIGH_NEW_TECH_CORP_FLG as HIGH_NEW_TECH_CORP_FLG
,t.RELA_PARTY_FLG as RELA_PARTY_FLG
,t.RELA_GROUP_TYPE_CD as RELA_GROUP_TYPE_CD
,t.LP_ORG_NAME as LP_ORG_NAME
,t.LP_ORG_TYPE_CD as LP_ORG_TYPE_CD
,t.LP_ORG_CUST_ID as LP_ORG_CUST_ID
,t.GROUP_CUST_FLG as GROUP_CUST_FLG
,t.CBRC_SB_FLG as CBRC_SB_FLG
,t.LABOR_INTE_FLG as LABOR_INTE_FLG
,t.HOLD_TYPE_CD as HOLD_TYPE_CD
,t.OFF_SHORE_CUST_FLG as OFF_SHORE_CUST_FLG
,t.PRIT_ETP_FLG as PRIT_ETP_FLG
,t.CTYSD_CORP_FLG as CTYSD_CORP_FLG
,t.CORP_GROW_STAGE_CD as CORP_GROW_STAGE_CD
,t.LIST_CORP_TYPE_CD as LIST_CORP_TYPE_CD
,t.STRATE_NEW_INDUS_CLS_CD as STRATE_NEW_INDUS_CLS_CD
,t.LIST_CORP_FLG as LIST_CORP_FLG
,t.STRTG_CUST_FLG as STRTG_CUST_FLG
,t.OPEN_CAP as OPEN_CAP
,t.CRDT_CUST_FLG as CRDT_CUST_FLG
,t.STAMENT_FLG as STAMENT_FLG
,t.TAX_ORG_CATE_CD as TAX_ORG_CATE_CD
,t.TAX_RESDNT_CTY_CD as TAX_RESDNT_CTY_CD
,t.TAX_RESDNT_IDTI_CD as TAX_RESDNT_IDTI_CD
,t.BASIC_ACCT_OPEN_BANK_NAME as BASIC_ACCT_OPEN_BANK_NAME
,t.BASIC_ACCT_ACCT_NUM as BASIC_ACCT_ACCT_NUM
,t.TAX_NUM as TAX_NUM
,t.TAX_NUM_NULL_RS_DESCB as TAX_NUM_NULL_RS_DESCB
,t.BEL_THI_FLG as BEL_THI_FLG
,t.TRAST_TAX_REGI_CERT_FLG as TRAST_TAX_REGI_CERT_FLG
,t.CTY_KEY_ENTERP_FLG as CTY_KEY_ENTERP_FLG
,t.GROUP_CORP_FLG as GROUP_CORP_FLG
,t.GROUP_CUST_ID as GROUP_CUST_ID
,t.GROUP_PARENT_CORP_ID as GROUP_PARENT_CORP_ID
,t.LMT_OR_ENCRGE_INDUS_CD as LMT_OR_ENCRGE_INDUS_CD
,t.HAVE_BOD_FLG as HAVE_BOD_FLG
,t.GREEN_CRDT_CUST_FLG as GREEN_CRDT_CUST_FLG
,t.GREEN_CRDT_CLS_CD as GREEN_CRDT_CLS_CD
,t.SCI_TECH_CORP_CLS_CD as SCI_TECH_CORP_CLS_CD
,t.SCI_TECH_CORP_IDTFY_DT as SCI_TECH_CORP_IDTFY_DT
,t.EDU_HEA_FLG as EDU_HEA_FLG
,t.INC_FLG as INC_FLG
,t.ARAF_FLG as ARAF_FLG
,t.IS_MX_MGMT_RIGH_FLG as IS_MX_MGMT_RIGH_FLG
,t.ESCP_DEBT_CORP_FLG as ESCP_DEBT_CORP_FLG
,t.IS_MX_OPER_ITEM_FLG as IS_MX_OPER_ITEM_FLG
,t.RESDNT_FLG as RESDNT_FLG
,t.DOM_OVERS_FLG as DOM_OVERS_FLG
,t.WORK_ADDR as WORK_ADDR
,t.WORK_ADDR_ZIP_CD as WORK_ADDR_ZIP_CD
,t.POSTA_ADDR as POSTA_ADDR
,t.POSTA_ADDR_ZIP_CD as POSTA_ADDR_ZIP_CD
,t.PROD_MANG_ADDR as PROD_MANG_ADDR
,t.PROD_MANG_ADDR_ZIP_CD as PROD_MANG_ADDR_ZIP_CD
,t.MANG_SITE_CD as MANG_SITE_CD
,t.CRDT_CUST_RISK_RATING_CD as CRDT_CUST_RISK_RATING_CD
,t.CRDT_CUST_RISK_RATING_START_DT as CRDT_CUST_RISK_RATING_START_DT
,t.CRDT_CUST_RISK_RATING_EXP_DT as CRDT_CUST_RISK_RATING_EXP_DT
,t.OWNSP_TYPE_CD as OWNSP_TYPE_CD
,t.CORP_CLOSE_FLG as CORP_CLOSE_FLG
,t.GOVER_FIN_PLAT_FLG as GOVER_FIN_PLAT_FLG
,t.SHORT_CHECK_BLKLIST_FLG as SHORT_CHECK_BLKLIST_FLG
,t.FIR_LON_DT as FIR_LON_DT
,t.ORGNZ_SURVIV_STATUS_CD as ORGNZ_SURVIV_STATUS_CD
,t.CORP_IDTI_IDF_TYPE_CD as CORP_IDTI_IDF_TYPE_CD
,t.MAJOR_CONTRIOR_CNT as MAJOR_CONTRIOR_CNT
,t.ACTL_CTRLER_CNT as ACTL_CTRLER_CNT
,t.FIN_DEPT_PHONE as FIN_DEPT_PHONE
from ${idl_schema}.cmm_corp_cust_basic_info t 
where etl_dt = to_date('${batch_date}','yyyymmdd') ;" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/cmm_corp_cust_basic_info.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes