: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_evt_scps_city_wide_bill_tx_bus_flow_i
CreateDate: 20180529
FileName:   ${iel_data_path}/evt_scps_city_wide_bill_tx_bus_flow.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select
etl_dt
,evt_id
,lp_id
,ser_num
,proc_id
,root_proc_id
,flow_num
,upper_tran_amt
,lower_tran_amt
,tran_org_id
,city_wide_bill_tran_status_cd
,tran_status_descb
,memo_code
,tran_dt
,tran_tm
,batch_proc_sync_proc_center_flg
,batch_tot
,splt_cnt
,teller_id
,auth_teller_id
,entry_msg_flow_num
,entry_core_tran_flow_num
,entry_core_tran_dt
,entry_status_cd
,entry_org_id
,city_wide_bill_tx_bus_cd
,city_wide_bill_tx_bus_kind_cd
,bus_attr_cd
,exch_chn_cd
,exch_num_site
,exch_bank_no
,exch_dt
,bus_submit_status_cd
,vouch_kind_cd
,vouch_id
,cust_id
,cust_name
,curr_cd
,payer_name
,payer_acct_id
,payer_addr_desc
,pay_bank_bank_no
,pay_bank_name
,intnal_acct_flg
,recver_name
,recver_acct_id
,recver_addr_desc
,recvbl_bank_no
,recv_bank_name
,pay_msg_flow_num
,pay_msg_tran_dt
,pay_host_flow_num
,pay_host_tran_dt
,pay_bus_seq_num
,recver_info_rest_descb
,recver_info_proc_tm
,recver_info_proc_status_cd
,bill_cnt
,endors_number
,endors_lt_descb
,draw_dt
,tax_bill_flg
,auto_seal_batch_id
,present_cfm_batch_id
,clear_num_site
,clear_dt
,city_wide_in_main_tran_flow_num
,main_acct_que_info_desc
,acct_num_open_acct_org_id
,city_wide_bill_tx_acct_status_cd
,acct_num_bal_status_cd
,debit_crdt_flg
,rela_flow_num
,enter_acct_flg
,inacct_entry_status_cd
,inacct_bus_submit_status_cd
,inacct_entry_msg_flow_num
,inacct_entry_core_tran_flow
,inacct_entry_core_tran_dt
,inacct_entry_teller_id
,inacct_auth_teller_id
,inacct_tm
,agent_pay_bank_num
,revs_teller_id
,revs_auth_teller_id
,revs_submit_status_cd
,revs_msg_flow_num
,revs_core_tran_flow_num
,revs_core_tran_dt
,revs_tm
,revs_rs_descb
,present_cfm_oper_teller_id
,present_cfm_auth_teller_id
,present_cfm_tm
,check_teller_id
,check_tm
,post_enter_acct_teller_id
,post_enter_acct_auth_teller_id
,post_enter_acct_tm
,cancel_post_enter_acct_teller_id
,cancel_post_enter_acct_auth_teller_id
,cancel_post_enter_acct_tm
,micr
,init_batch_proc_id
,init_batch_flow_num
,in_seq_num
,in_bk_bank_no
,in_bank_name
,in_bus_init_way_cd
,in_bk_num_site_attr_cd
,present_bk_bank_no
,present_bank_name
,paper_bill_bus_flg
,on_acct_proc_id
,obank_disho_bill_acct_proc_way_cd
,disho_bill_type_cd
,disho_bill_reason_descb
,disho_bill_reason
,senti_acct_flg
,trigger_od_bus_flg
,od_amt
,espec_submit_flg
,postsc
from ${idl_schema}.evt_scps_city_wide_bill_tx_bus_flow t1
where etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/evt_scps_city_wide_bill_tx_bus_flow.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes