: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_icms_business_duebill_f
CreateDate: 20250612
FileName:   ${iel_data_path}/icms_business_duebill.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.serialno as serialno
,t1.putoutserialno as putoutserialno
,t1.contractserialno as contractserialno
,t1.occurdate as occurdate
,t1.occurtype as occurtype
,t1.vouchtype as vouchtype
,t1.customerid as customerid
,t1.customername as customername
,t1.productid as productid
,t1.currency as currency
,t1.businesssum as businesssum
,t1.termmonth as termmonth
,t1.termday as termday
,t1.putoutdate as putoutdate
,t1.maturity as maturity
,t1.actualmaturity as actualmaturity
,t1.ratemodel as ratemodel
,t1.baseratetype as baseratetype
,t1.baserate as baserate
,t1.ratefloattype as ratefloattype
,t1.executerate as executerate
,t1.bailratio as bailratio
,t1.bailsum as bailsum
,t1.bailaccount as bailaccount
,t1.repaytype as repaytype
,t1.paymenttype as paymenttype
,t1.repaycycle as repaycycle
,t1.balance as balance
,t1.normalbalance as normalbalance
,t1.overduebalance as overduebalance
,t1.dullbalance as dullbalance
,t1.badbalance as badbalance
,t1.extendtimes as extendtimes
,t1.innerinterestbalance as innerinterestbalance
,t1.outerinterestbalance as outerinterestbalance
,t1.capitalpenaltybalance as capitalpenaltybalance
,t1.interestpenaltybalance as interestpenaltybalance
,t1.overduedays as overduedays
,t1.owninterestdays as owninterestdays
,t1.ichangedate as ichangedate
,t1.graceperiod as graceperiod
,t1.reducereservesum as reducereservesum
,t1.predictlostsum as predictlostsum
,t1.finishtype as finishtype
,t1.finishdate as finishdate
,t1.belongdept as belongdept
,t1.offsheetflag as offsheetflag
,t1.islowrisk as islowrisk
,t1.badconfirmdate as badconfirmdate
,t1.classifyresult as classifyresult
,t1.classifydate as classifydate
,t1.advanceflag as advanceflag
,t1.businessstatus as businessstatus
,t1.mforgid as mforgid
,t1.relativeduebillno as relativeduebillno
,t1.loanno as loanno
,t1.remark as remark
,t1.operatedate as operatedate
,t1.operateuserid as operateuserid
,t1.operateorgid as operateorgid
,t1.inputuserid as inputuserid
,t1.inputorgid as inputorgid
,t1.inputdate as inputdate
,t1.updateuserid as updateuserid
,t1.updateorgid as updateorgid
,t1.updatedate as updatedate
,t1.corporgid as corporgid
,t1.repaydate as repaydate
,t1.mfcustomerid as mfcustomerid
,t1.settlementaccount as settlementaccount
,t1.overduedate as overduedate
,t1.oweinterestdate as oweinterestdate
,t1.classifyresulteleven as classifyresulteleven
,t1.overduerate as overduerate
,t1.mainorgid as mainorgid
,t1.remart as remart
,t1.vouchtype2 as vouchtype2
,t1.vouchtype3 as vouchtype3
,t1.rateadjusttype as rateadjusttype
,t1.rateadjustfrequency as rateadjustfrequency
,t1.floatrange as floatrange
,t1.settlementaccountname as settlementaccountname
,t1.loanaccountorgid as loanaccountorgid
,t1.overdueratefloattype as overdueratefloattype
,t1.overdueratefloatvalue as overdueratefloatvalue
,t1.putoutorgid as putoutorgid
,t1.dzhxstatus as dzhxstatus
,t1.classifyresultelevendate as classifyresultelevendate
,t1.loanaccountno as loanaccountno
,t1.migtflag as migtflag
,t1.loanstatus as loanstatus
,t1.zxzflag as zxzflag
,t1.assetflag as assetflag
,t1.migtcustomerid as migtcustomerid
,t1.migtbusinesstype as migtbusinesstype
,t1.migtoldvalue as migtoldvalue
,t1.wrndate as wrndate
,t1.repayamt as repayamt
,t1.prifirstduedate as prifirstduedate
,t1.intfirstduedate as intfirstduedate
,t1.compensateamt as compensateamt
,t1.yjintamt as yjintamt
,t1.csyjintamt as csyjintamt
,t1.ysintamt as ysintamt
,t1.csintamt as csintamt
,t1.yjodpamt as yjodpamt
,t1.csyjodpamt as csyjodpamt
,t1.ysodpamt as ysodpamt
,t1.csodpamt as csodpamt
,t1.odppostedctddr as odppostedctddr
,t1.odipostedctddr as odipostedctddr
,t1.yjodiamt as yjodiamt
,t1.wrnpriamt as wrnpriamt
,t1.wrnintamt as wrnintamt
,t1.wrnreceiptamt as wrnreceiptamt
,t1.intdate as intdate
,t1.accountbalance as accountbalance
,t1.accountuserbalance as accountuserbalance
,t1.termtype as termtype
,t1.insum as insum
,t1.interestinsum as interestinsum
,t1.exttradeno as exttradeno
,t1.fyjbalamt as fyjbalamt
,t1.periods as periods
,t1.remain_periods as remain_periods
,t1.lastclassifyresultten as lastclassifyresultten
,t1.lastclassifyresulttendate as lastclassifyresulttendate
,t1.classifyfivehchangedate as classifyfivehchangedate
,t1.tenclaind as tenclaind
,t1.lastclassifyresult as lastclassifyresult
,t1.lastclassifyresultdate as lastclassifyresultdate
,t1.npltransflag as npltransflag
,t1.reversalflag as reversalflag
,t1.risktype as risktype
,t1.ratefloatratioorbp as ratefloatratioorbp
,t1.loanaccountname as loanaccountname
,t1.odiflag as odiflag
,t1.odpflag as odpflag
,t1.compensatepotype as compensatepotype
,t1.gracestartdate as gracestartdate
,t1.loanserialno as loanserialno
,t1.whethertorestructuretheloan as whethertorestructuretheloan
,t1.restructuretheloantype as restructuretheloantype
,t1.ispensionindustry as ispensionindustry
,t1.gracetype as gracetype
,t1.gearprodflag as gearprodflag
,t1.absflag as absflag
,t1.intappltype as intappltype
,t1.rollfreq as rollfreq
,t1.acctspreadrate as acctspreadrate
,t1.intindflag as intindflag
,t1.intday as intday
,t1.inttype as inttype
,t1.interestbalance as interestbalance
,t1.paymentserialno as paymentserialno
,t1.actualoverduedays as actualoverduedays
,t1.notificationstatus as notificationstatus
,t1.principalbalance as principalbalance
,t1.tysumcp as tysumcp
,t1.originalloandeadline as originalloandeadline
,t1.settlementaccountbank as settlementaccountbank
,t1.settlementaccountnum as settlementaccountnum
,t1.restructuretheloandate as restructuretheloandate
,t1.shareamount as shareamount
,t1.overduecount as overduecount
,t1.firstoverduedate as firstoverduedate
,t1.contoverduedate as contoverduedate
,t1.prioverduedays as prioverduedays
,t1.intoverduedays as intoverduedays
,t1.prioverdueamt as prioverdueamt
,t1.intoverdueamt as intoverdueamt
,t1.subproductname as subproductname

from ${idl_schema}.icms_business_duebill t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/icms_business_duebill.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
