: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_aml_cmm_corp_loan_acct_info_f
CreateDate: 20180529
FileName:   ${iel_data_path}/aml_cmm_corp_loan_acct_info.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select etl_dt 
,lp_id 
,acct_id 
,acct_name 
,cust_id 
,cont_id 
,dubil_num 
,loan_distr_acct_num 
,loan_repay_num 
,int_sub_ps_stl_acct_num 
,entr_dep_acct_num 
,csner_dep_acct_num 
,inpwn_acct_num_id 
,out_acct_num 
,rela_bill_id 
,prod_id 
,subj_id 
,int_subj_id 
,loan_acct_status_cd 
,loan_tenor 
,loan_tenor_type_cd 
,loan_cate_cd 
,belong_bus_strip_line_cd 
,guar_way_cd 
,loan_usage_descb 
,acru_non_acru_cd 
,turn_non_acru_loan_dt 
,cust_mgr_id 
,open_acct_org_id 
,mgmt_org_id 
,acct_instit_id 
,open_acct_dt 
,distr_dt 
,value_dt 
,stop_accr_int_dt 
,exp_dt 
,clos_acct_dt 
,int_sub_flg 
,int_sub_ratio 
,int_sub_exp_day 
,entr_loan_comm_fee_coll_way 
,entr_loan_comm_fee_coll_ratio
,entr_loan_comm_fee 
,stop_accr_int_flg 
,impam_flg 
,crdt_distr_repay_plan_flg 
,finc_prod_flg 
,prepay_int_amort_flg 
,pric_auto_deduct_flg 
,int_auto_deduct_flg 
,acpt_flg 
,gover_fin_plat_loan_flg 
,tax_flg 
,wrt_off_flg 
,renew_flg 
,renew_cnt 
,allow_adv_repay_flg 
,repay_seq_no_cd 
,adv_repay_way_cd 
,margin_curr_cd 
,int_rat_base_type_cd 
,int_rat_curve_type_cd 
,base_rat 
,exec_int_rat 
,int_rat_adj_way_cd 
,int_rat_float_way_cd 
,int_rat_adj_ped_corp_cd 
,int_rat_adj_ped_freq 
,int_rat_flo_val 
,curr_int_rat_effect_dt 
,next_int_rat_adj_dt 
,comp_int_flg 
,int_set_way_cd 
,int_accr_way_cd 
,repay_way_cd 
,repay_ped_corp_cd 
,repay_ped 
,money_use_type 
,lmt_type 
,ovdue_flg 
,curr_ovdue_perds 
,ovdue_days 
,int_ovdue_days 
,ovdue_pric_bal 
,ovdue_int_amt 
,ovdue_comp_int_amt 
,fir_ovdue_dt 
,ovdue_int_rat 
,ovdue_int_rat_flo_val 
,tot_perds 
,curr_issue_perds 
,last_repay_dt 
,next_repay_dt 
,curr_cd 
,next_rpp_amt 
,next_repay_int_amt 
,td_acru_int 
,currt_acru_int 
,cont_amt 
,dubil_amt 
,distr_amt 
,nomal_pric 
,ovdue_pric 
,idle_pric 
,bad_debt_pric 
,recvbl_over_int 
,recvbl_acru_pnlt 
,recvbl_pnlt 
,acru_comp_int 
,recvbl_comp_int 
,recvbl_fee 
,wrt_off_pric 
,wrt_off_int 
,in_bs_over_int_bal 
,off_bs_over_int_bal 
,in_bs_int 
,off_bs_int 
,acm_recvbl_uncol_int_amt 
,repaid_pric 
,repaid_int 
,repaid_pnlt 
,repaid_comp_int 
,repaid_fee 
,pric_bal 
,currt_bal 
,cl_curr_currt_bal 
,ear_d_bal 
,ear_m_bal 
,ear_s_bal 
,ear_y_bal 
,y_acm_bal 
,s_acm_bal 
,m_acm_bal 
,cl_curr_ear_d_bal 
,cl_curr_ear_m_bal 
,cl_curr_ear_s_bal 
,cl_curr_ear_y_bal 
,cl_curr_y_acm_bal 
,cl_curr_ear_d_y_acm_bal 
,cl_curr_ear_m_y_acm_bal 
,cl_curr_ear_s_y_acm_bal 
,cl_curr_ear_y_y_acm_bal 
,cl_curr_s_acm_bal 
,cl_curr_ear_d_s_acm_bal 
,cl_curr_ear_s_s_acm_bal 
,cl_curr_ear_y_s_acm_bal 
,cl_curr_m_acm_bal 
,cl_curr_ear_d_m_acm_bal 
,cl_curr_ear_m_m_acm_bal 
,cl_curr_ear_y_m_acm_bal 
,job_cd 
,etl_timestamp from idl.aml_cmm_corp_loan_acct_info where etl_dt=to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/aml_cmm_corp_loan_acct_info.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes