: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_agt_loan_cont_info_h_f
CreateDate: 20250314
FileName:   ${iel_data_path}/agt_loan_cont_info_h.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.agt_id as agt_id
,t1.lp_id as lp_id
,t1.cont_id as cont_id
,t1.apv_flow_num as apv_flow_num
,t1.rela_cont_id as rela_cont_id
,t1.text_cont_id as text_cont_id
,t1.cust_id as cust_id
,t1.cust_name as cust_name
,t1.lmt_cont_flg as lmt_cont_flg
,t1.rela_old_cont_id as rela_old_cont_id
,t1.appl_way_cd as appl_way_cd
,t1.loan_distr_type_cd as loan_distr_type_cd
,t1.distr_mode_pay_cd as distr_mode_pay_cd
,t1.happ_dt as happ_dt
,t1.curr_cd as curr_cd
,t1.cont_amt as cont_amt
,t1.actl_out_acct_amt as actl_out_acct_amt
,t1.out_acct_dt as out_acct_dt
,t1.base_prod_id as base_prod_id
,t1.prod_id as prod_id
,t1.mon_tenor as mon_tenor
,t1.day_tenor as day_tenor
,t1.cont_effect_dt as cont_effect_dt
,t1.cont_exp_dt as cont_exp_dt
,t1.lmt_circl_flg as lmt_circl_flg
,t1.risk_type_cd as risk_type_cd
,t1.low_risk_bus_flg as low_risk_bus_flg
,t1.remote_bus_flg as remote_bus_flg
,t1.int_rat_mode_cd as int_rat_mode_cd
,t1.fix_int_rat as fix_int_rat
,t1.base_rat_type_cd as base_rat_type_cd
,t1.base_rat as base_rat
,t1.int_rat_float_type_cd as int_rat_float_type_cd
,t1.int_rat_adj_way_cd as int_rat_adj_way_cd
,t1.int_rat_flo_val as int_rat_flo_val
,t1.exec_int_rat as exec_int_rat
,t1.main_guar_way_cd as main_guar_way_cd
,t1.supp_guar_way_flg as supp_guar_way_flg
,t1.other_cond_descb as other_cond_descb
,t1.guar_way_cd_two as guar_way_cd_two
,t1.guar_way_cd_three as guar_way_cd_three
,t1.repay_way_cd as repay_way_cd
,t1.sub_guar_way_cd as sub_guar_way_cd
,t1.repay_ped as repay_ped
,t1.repay_ped_cd as repay_ped_cd
,t1.deflt_repay_day as deflt_repay_day
,t1.stl_acct_id as stl_acct_id
,t1.crdt_dir_cd as crdt_dir_cd
,t1.nat_std_indus_dir_cd as nat_std_indus_dir_cd
,t1.bank_int_indus_dir_cd as bank_int_indus_dir_cd
,t1.usage_descb as usage_descb
,t1.data_input_integy_flg as data_input_integy_flg
,t1.rsrv_amt as rsrv_amt
,t1.curr_bal as curr_bal
,t1.nomal_bal as nomal_bal
,t1.loan_ovdue_amt as loan_ovdue_amt
,t1.idle_bal as idle_bal
,t1.bad_debt_bal as bad_debt_bal
,t1.in_bs_over_int_bal as in_bs_over_int_bal
,t1.off_bs_over_int_bal as off_bs_over_int_bal
,t1.ovdue_pnlt_bal as ovdue_pnlt_bal
,t1.comp_int_bal as comp_int_bal
,t1.loan_ovdue_days as loan_ovdue_days
,t1.over_int_days as over_int_days
,t1.wrt_off_pric as wrt_off_pric
,t1.wrt_off_int as wrt_off_int
,t1.pre_loss_amt as pre_loss_amt
,t1.fir_idtfy_non_dt as fir_idtfy_non_dt
,t1.cont_status_cd as cont_status_cd
,t1.effect_dt as effect_dt
,t1.termnt_dt as termnt_dt
,t1.payoff_flg as payoff_flg
,t1.off_bs_flg as off_bs_flg
,t1.onl_bus_flg as onl_bus_flg
,t1.belong_strip_line_cd as belong_strip_line_cd
,t1.apv_status_cd as apv_status_cd
,t1.lmt_id as lmt_id
,t1.oper_teller_id as oper_teller_id
,t1.oper_org_id as oper_org_id
,t1.oper_dt as oper_dt
,t1.rgst_teller_id as rgst_teller_id
,t1.rgst_org_id as rgst_org_id
,t1.rgst_dt as rgst_dt
,t1.update_teller_id as update_teller_id
,t1.update_org_id as update_org_id
,t1.modif_dt as modif_dt
,t1.spec_ped_corp_cd as spec_ped_corp_cd
,t1.spec_ped_cd as spec_ped_cd
,t1.b_renew_exp_dt as b_renew_exp_dt
,t1.b_renew_amt as b_renew_amt
,t1.b_renew_exec_year_int_rat as b_renew_exec_year_int_rat
,t1.hxb_rela_party_flg as hxb_rela_party_flg
,t1.loan_usage_cd as loan_usage_cd
,t1.int_rat_adj_ped_cd as int_rat_adj_ped_cd
,t1.lmt_open_amt as lmt_open_amt
,t1.occu_lmt as occu_lmt
,t1.margin_curr_cd as margin_curr_cd
,t1.margin_ratio as margin_ratio
,t1.margin_amt as margin_amt
,t1.open_amt as open_amt
,t1.open_amt_stat as open_amt_stat
,t1.lmt_cont_id as lmt_cont_id
,t1.exec_mon_int_rat as exec_mon_int_rat
,t1.asset_thd_cls_cd as asset_thd_cls_cd
,t1.level5_cls_cd as level5_cls_cd
,t1.level5_cls_dt as level5_cls_dt
,t1.level11_cls_cd as level11_cls_cd
,t1.lon_post_mgmt_teller_id as lon_post_mgmt_teller_id
,t1.lon_post_mgmt_org_id as lon_post_mgmt_org_id
,t1.file_dt as file_dt
,t1.froz_flg as froz_flg
,t1.ovdue_exec_int_rat as ovdue_exec_int_rat
,t1.ovdue_int_rat_float_way_cd as ovdue_int_rat_float_way_cd
,t1.ovdue_int_rat_flo_val as ovdue_int_rat_flo_val
,t1.core_out_acct_org_id as core_out_acct_org_id
,t1.stl_acct_name as stl_acct_name
,t1.enter_id as enter_id
,t1.enter_name as enter_name
,t1.enter_open_acct_org_id as enter_open_acct_org_id
,t1.backup_status_cd as backup_status_cd
,t1.backup_lmt_cont_id as backup_lmt_cont_id
,t1.comm_fee_rat as comm_fee_rat
,t1.move_remark as move_remark
,t1.strtg_new_indus_type_cd as strtg_new_indus_type_cd
,t1.high_new_tech_corp_flg as high_new_tech_corp_flg
,t1.scen_tech_corp_flg as scen_tech_corp_flg
,t1.tech_inovt_corp_flg as tech_inovt_corp_flg
,t1.xxd_camp_lmt_flg as xxd_camp_lmt_flg
,t1.provi_for_aged_property_flg as provi_for_aged_property_flg
,t1.seed_loan_flg as seed_loan_flg
,t1.county_loan_flg as county_loan_flg
,t1.high_tech_property_flg as high_tech_property_flg
,t1.digit_econ_core_type_cd as digit_econ_core_type_cd
,t1.remark as remark
,t1.prod_gen_id as prod_gen_id
,t1.tran_bf_prod_id as tran_bf_prod_id
,t1.tran_bf_cust_id as tran_bf_cust_id
,t1.attach_rgst_bus_type_cd as attach_rgst_bus_type_cd
,t1.margin_acct_id as margin_acct_id
,t1.margin_tran_out_acct_id as margin_tran_out_acct_id
,t1.update_cnt as update_cnt
,t1.dubil_id as dubil_id
,t1.sign_lmt_cont_flg as sign_lmt_cont_flg
,t1.sign_paper_cont_flg as sign_paper_cont_flg
,t1.comm_fee_amt as comm_fee_amt
,t1.crdt_apv_aval_amt as crdt_apv_aval_amt
,t1.b_renew_cont_id as b_renew_cont_id
,t1.ocup_open_lmt_risk_type_cd as ocup_open_lmt_risk_type_cd
,t1.ocup_o_use_lmt_flg as ocup_o_use_lmt_flg
,t1.risk_mgmt_apv_aval_amt as risk_mgmt_apv_aval_amt
,t1.ifc_cnt_tot_apv_aval_amt as ifc_cnt_tot_apv_aval_amt
,t1.ifc_apved_lmt_cont_amt as ifc_apved_lmt_cont_amt
,t1.regroup_loan_flg as regroup_loan_flg
,t1.only_new_minorent_flg as only_new_minorent_flg
,t1.only_new_littlegiantent_flg as only_new_littlegiantent_flg
,t1.indent_tech_flg as indent_tech_flg
,t1.cul_property_flg as cul_property_flg
,t1.advanced_manu_flg as advanced_manu_flg
,t1.auto_que_lon_post_rept_flg as auto_que_lon_post_rept_flg

from ${idl_schema}.agt_loan_cont_info_h t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/agt_loan_cont_info_h.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
