: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_iol_wind_cbondbalancesheet_i
CreateDate: 20180529
FileName:   ${iel_data_path}/wind_cbondbalancesheet.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,replace(replace(t.object_id,chr(13),''),chr(10),'') as object_id
,replace(replace(t.s_info_compcode,chr(13),''),chr(10),'') as s_info_compcode
,replace(replace(t.ann_dt,chr(13),''),chr(10),'') as ann_dt
,replace(replace(t.report_period,chr(13),''),chr(10),'') as report_period
,replace(replace(t.statement_type,chr(13),''),chr(10),'') as statement_type
,replace(replace(t.crncy_code,chr(13),''),chr(10),'') as crncy_code
,t.monetary_cap as monetary_cap
,t.tradable_fin_assets as tradable_fin_assets
,t.notes_rcv as notes_rcv
,t.acct_rcv as acct_rcv
,t.oth_rcv as oth_rcv
,t.prepay as prepay
,t.dvd_rcv as dvd_rcv
,t.int_rcv as int_rcv
,t.inventories as inventories
,t.consumptive_bio_assets as consumptive_bio_assets
,t.deferred_exp as deferred_exp
,t.non_cur_assets_due_within_1y as non_cur_assets_due_within_1y
,t.settle_rsrv as settle_rsrv
,t.loans_to_oth_banks as loans_to_oth_banks
,t.prem_rcv as prem_rcv
,t.rcv_from_reinsurer as rcv_from_reinsurer
,t.rcv_from_ceded_insur_cont_rsrv as rcv_from_ceded_insur_cont_rsrv
,t.red_monetary_cap_for_sale as red_monetary_cap_for_sale
,t.oth_cur_assets as oth_cur_assets
,t.tot_cur_assets as tot_cur_assets
,t.fin_assets_avail_for_sale as fin_assets_avail_for_sale
,t.held_to_mty_invest as held_to_mty_invest
,t.long_term_eqy_invest as long_term_eqy_invest
,t.invest_real_estate as invest_real_estate
,t.time_deposits as time_deposits
,t.oth_assets as oth_assets
,t.long_term_rec as long_term_rec
,t.fix_assets as fix_assets
,t.const_in_prog as const_in_prog
,t.proj_matl as proj_matl
,t.fix_assets_disp as fix_assets_disp
,t.productive_bio_assets as productive_bio_assets
,t.oil_and_natural_gas_assets as oil_and_natural_gas_assets
,t.intang_assets as intang_assets
,t.r_and_d_costs as r_and_d_costs
,t.goodwill as goodwill
,t.long_term_deferred_exp as long_term_deferred_exp
,t.deferred_tax_assets as deferred_tax_assets
,t.loans_and_adv_granted as loans_and_adv_granted
,t.oth_non_cur_assets as oth_non_cur_assets
,t.tot_non_cur_assets as tot_non_cur_assets
,t.cash_deposits_central_bank as cash_deposits_central_bank
,t.asset_dep_oth_banks_fin_inst as asset_dep_oth_banks_fin_inst
,t.precious_metals as precious_metals
,t.derivative_fin_assets as derivative_fin_assets
,t.agency_bus_assets as agency_bus_assets
,t.subr_rec as subr_rec
,t.rcv_ceded_unearned_prem_rsrv as rcv_ceded_unearned_prem_rsrv
,t.rcv_ceded_claim_rsrv as rcv_ceded_claim_rsrv
,t.rcv_ceded_life_insur_rsrv as rcv_ceded_life_insur_rsrv
,t.rcv_ceded_lt_health_insur_rsrv as rcv_ceded_lt_health_insur_rsrv
,t.mrgn_paid as mrgn_paid
,t.insured_pledge_loan as insured_pledge_loan
,t.cap_mrgn_paid as cap_mrgn_paid
,t.independent_acct_assets as independent_acct_assets
,t.clients_cap_deposit as clients_cap_deposit
,t.clients_rsrv_settle as clients_rsrv_settle
,t.incl_seat_fees_exchange as incl_seat_fees_exchange
,t.rcv_invest as rcv_invest
,t.tot_assets as tot_assets
,t.st_borrow as st_borrow
,t.borrow_central_bank as borrow_central_bank
,t.deposit_received_ib_deposits as deposit_received_ib_deposits
,t.loans_oth_banks as loans_oth_banks
,t.tradable_fin_liab as tradable_fin_liab
,t.notes_payable as notes_payable
,t.acct_payable as acct_payable
,t.adv_from_cust as adv_from_cust
,t.fund_sales_fin_assets_rp as fund_sales_fin_assets_rp
,t.handling_charges_comm_payable as handling_charges_comm_payable
,t.empl_ben_payable as empl_ben_payable
,t.taxes_surcharges_payable as taxes_surcharges_payable
,t.int_payable as int_payable
,t.dvd_payable as dvd_payable
,t.oth_payable as oth_payable
,t.acc_exp as acc_exp
,t.deferred_inc as deferred_inc
,t.st_bonds_payable as st_bonds_payable
,t.payable_to_reinsurer as payable_to_reinsurer
,t.rsrv_insur_cont as rsrv_insur_cont
,t.acting_trading_sec as acting_trading_sec
,t.acting_uw_sec as acting_uw_sec
,t.non_cur_liab_due_within_1y as non_cur_liab_due_within_1y
,t.oth_cur_liab as oth_cur_liab
,t.tot_cur_liab as tot_cur_liab
,t.lt_borrow as lt_borrow
,t.bonds_payable as bonds_payable
,t.lt_payable as lt_payable
,t.specific_item_payable as specific_item_payable
,t.provisions as provisions
,t.deferred_tax_liab as deferred_tax_liab
,t.deferred_inc_non_cur_liab as deferred_inc_non_cur_liab
,t.oth_non_cur_liab as oth_non_cur_liab
,t.tot_non_cur_liab as tot_non_cur_liab
,t.liab_dep_oth_banks_fin_inst as liab_dep_oth_banks_fin_inst
,t.derivative_fin_liab as derivative_fin_liab
,t.cust_bank_dep as cust_bank_dep
,t.agency_bus_liab as agency_bus_liab
,t.oth_liab as oth_liab
,t.prem_received_adv as prem_received_adv
,t.deposit_received as deposit_received
,t.insured_deposit_invest as insured_deposit_invest
,t.unearned_prem_rsrv as unearned_prem_rsrv
,t.out_loss_rsrv as out_loss_rsrv
,t.life_insur_rsrv as life_insur_rsrv
,t.lt_health_insur_v as lt_health_insur_v
,t.independent_acct_liab as independent_acct_liab
,t.incl_pledge_loan as incl_pledge_loan
,t.claims_payable as claims_payable
,t.dvd_payable_insured as dvd_payable_insured
,t.tot_liab as tot_liab
,t.cap_stk as cap_stk
,t.cap_rsrv as cap_rsrv
,t.special_rsrv as special_rsrv
,t.surplus_rsrv as surplus_rsrv
,t.undistributed_profit as undistributed_profit
,t.less_tsy_stk as less_tsy_stk
,t.prov_nom_risks as prov_nom_risks
,t.cnvd_diff_foreign_curr_stat as cnvd_diff_foreign_curr_stat
,t.unconfirmed_invest_loss as unconfirmed_invest_loss
,t.minority_int as minority_int
,t.tot_shrhldr_eqy_excl_min_int as tot_shrhldr_eqy_excl_min_int
,t.tot_shrhldr_eqy_incl_min_int as tot_shrhldr_eqy_incl_min_int
,t.tot_liab_shrhldr_eqy as tot_liab_shrhldr_eqy
,replace(replace(t.comp_type_code,chr(13),''),chr(10),'') as comp_type_code
,replace(replace(t.actual_ann_dt,chr(13),''),chr(10),'') as actual_ann_dt
,t.spe_cur_assets_diff as spe_cur_assets_diff
,t.tot_cur_assets_diff as tot_cur_assets_diff
,t.spe_non_cur_assets_diff as spe_non_cur_assets_diff
,t.tot_non_cur_assets_diff as tot_non_cur_assets_diff
,t.spe_bal_assets_diff as spe_bal_assets_diff
,t.tot_bal_assets_diff as tot_bal_assets_diff
,t.spe_cur_liab_diff as spe_cur_liab_diff
,t.tot_cur_liab_diff as tot_cur_liab_diff
,t.spe_non_cur_liab_diff as spe_non_cur_liab_diff
,t.tot_non_cur_liab_diff as tot_non_cur_liab_diff
,t.spe_bal_liab_diff as spe_bal_liab_diff
,t.tot_bal_liab_diff as tot_bal_liab_diff
,t.spe_bal_shrhldr_eqy_diff as spe_bal_shrhldr_eqy_diff
,t.tot_bal_shrhldr_eqy_diff as tot_bal_shrhldr_eqy_diff
,t.spe_bal_liab_eqy_diff as spe_bal_liab_eqy_diff
,t.tot_bal_liab_eqy_diff as tot_bal_liab_eqy_diff
,t.audit_am as audit_am
,t.lt_payroll_payable as lt_payroll_payable
,t.other_comp_income as other_comp_income
,t.other_equity_tools as other_equity_tools
,t.other_equity_tools_p_shr as other_equity_tools_p_shr
,t.lending_funds as lending_funds
,t.accounts_receivable as accounts_receivable
,t.st_financing_payable as st_financing_payable
,t.payables as payables
,t.tot_shr as tot_shr
,t.hfs_assets as hfs_assets
,t.hfs_sales as hfs_sales
from iol.wind_cbondbalancesheet t
where etl_dt =to_date('${batch_date}','yyyymmdd');
" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/wind_cbondbalancesheet.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes