: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_crms_ods_a_d_ln_loan_info_ft_f
CreateDate: 20180529
FileName:   ${iel_data_path}/ODS_A_D_LN_LOAN_INFO_FT_${batch_date}_INC.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select date_id,
       period_id,
       lncf_no,
       acct_id,
       loan_no,
       branch_code,
       curr_code,
       acc_code,
       loan_tp,
       cms_cust_no,
       cbs_cust_no,
       cust_tp,
       cust_lv,
       cust_nm,
       credit_tp,
       businesstype,
       five_class,
       guar_mode,
       loan_dt,
       loan_sq,
       matu_dt,
       prln_tg,
       unpr_dt,
       cntr_ir,
       inrt_ir,
       ovdu_ir,
       retn_mode,
       paym_freq,
       paym_date_tp,
       prod_code,
       acpd_code,
       lncf_st,
       lsln_st,
       total_nm,
       current_nm,
       instm_amt,
       curr_dpay_nm,
       curr_paid_nm,
       curr_owe_nm,
       curr_arr_nm,
       loan_mon_tm,
       loan_quj_tm,
       loan_lef_tm,
       loan_exc_tm,
       loan_amt,
       loan_bal,
       edct_bal,
       loan_unheal_bal,
       loan_mon_cml,
       loan_quar_cml,
       loan_year_cml,
       loan_mon_avl,
       loan_quar_avl,
       loan_year_avl,
       loan_cnt,
       loan_mon_draw_cnt,
       loan_mon_draw_amt,
       loan_mon_recv_amt,
       loan_mon_recv_cnt,
       loan_mon_recv_inir,
       loan_mon_recv_otir,
       loan_mon_recv_lamf_ir,
       loan_mon_recv_insf_ir,
       loan_lnwv_amt,
       loan_lnwv_inir,
       loan_lnwv_otir,
       coac_id,
       acct_no,
       inpy_acct_no,
       cmit_acct_no,
       cmdp_acct_no,
       rmpt_code,
       rpmt_code,
       floa_rt,
       ovde_floa_rt,
       inrt_dt,
       nxin_dt,
       ip_code,
       az_code,
       indd_dt,
       idmu_dt,
       inds_tg,
       clos_dt,
       clos_seq,
       tax_tg,
       com_ovd_dt,
       hdin_tg,
       hdin_dt,
       hdin_seq,
       devl_tg,
       cntr_tp,
       rein_st,
       retn_dt,
       enpd_tp,
       enpd_op,
       enpd_amt,
       lnpp_code,
       cust_mg,
       fee_tp,
       fee_amt,
       paym_plan_tg,
       fina_if_tg,
       lnus_tp,
       cnsg_amt,
       ent_org_tp,
       ent_fina_tp,
       ent_be_lg,
       ent_indu_tp,
       ent_indu_tp1,
       ent_indu_tp2,
       ent_hold_tp,
       ent_scp,
       bank_cred_lv,
       outer_cred_lv,
       ent_if_grou,
       ent_if_ecgr,
       rwa_cust_tp,
       ent_if_rela,
       ent_if_sme,
       ent_if_loca,
       ent_if_limi,
       ent_if_pri,
       ent_if_bksv,
       credit_amt,
       abnor_bal,
       businesssum,
       overduebalance
  from ${idl_schema}.CRMS_ODS_A_D_LN_LOAN_INFO_FT
 where etl_dt = TO_DATE('${batch_date}', 'yyyymmdd');" \
        field="|#|" record="0x0a"  \
        file="${iel_data_path}/ODS_A_D_LN_LOAN_INFO_FT_${batch_date}_INC.dat" \
        charset=zhs16gbk
        safe=yes