: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_ccrm_wind_asharefinancialindicator_f
CreateDate: 20180529
FileName:   ${iel_data_path}/ccrm_wind_asharefinancialindicator.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
replace(replace(t1.object_id,chr(13),''),chr(10),'') as object_id
,replace(replace(t1.s_info_windcode,chr(13),''),chr(10),'') as s_info_windcode
,replace(replace(t1.wind_code,chr(13),''),chr(10),'') as wind_code
,replace(replace(t1.ann_dt,chr(13),''),chr(10),'') as ann_dt
,replace(replace(t1.report_period,chr(13),''),chr(10),'') as report_period
,replace(replace(t1.crncy_code,chr(13),''),chr(10),'') as crncy_code
,t1.s_fa_extraordinary as s_fa_extraordinary
,t1.s_fa_deductedprofit as s_fa_deductedprofit
,t1.s_fa_grossmargin as s_fa_grossmargin
,t1.s_fa_operateincome as s_fa_operateincome
,t1.s_fa_investincome as s_fa_investincome
,t1.s_stmnote_finexp as s_stmnote_finexp
,t1.s_stm_is as s_stm_is
,t1.s_fa_ebit as s_fa_ebit
,t1.s_fa_ebitda as s_fa_ebitda
,t1.s_fa_fcff as s_fa_fcff
,t1.s_fa_fcfe as s_fa_fcfe
,t1.s_fa_exinterestdebt_current as s_fa_exinterestdebt_current
,t1.s_fa_exinterestdebt_noncurrent as s_fa_exinterestdebt_noncurrent
,t1.s_fa_interestdebt as s_fa_interestdebt
,t1.s_fa_netdebt as s_fa_netdebt
,t1.s_fa_tangibleasset as s_fa_tangibleasset
,t1.s_fa_workingcapital as s_fa_workingcapital
,t1.s_fa_networkingcapital as s_fa_networkingcapital
,t1.s_fa_investcapital as s_fa_investcapital
,t1.s_fa_retainedearnings as s_fa_retainedearnings
,t1.s_fa_eps_basic as s_fa_eps_basic
,t1.s_fa_eps_diluted as s_fa_eps_diluted
,t1.s_fa_eps_diluted2 as s_fa_eps_diluted2
,t1.s_fa_bps as s_fa_bps
,t1.s_fa_ocfps as s_fa_ocfps
,t1.s_fa_grps as s_fa_grps
,t1.s_fa_orps as s_fa_orps
,t1.s_fa_surpluscapitalps as s_fa_surpluscapitalps
,t1.s_fa_surplusreserveps as s_fa_surplusreserveps
,t1.s_fa_undistributedps as s_fa_undistributedps
,t1.s_fa_retainedps as s_fa_retainedps
,t1.s_fa_cfps as s_fa_cfps
,t1.s_fa_ebitps as s_fa_ebitps
,t1.s_fa_fcffps as s_fa_fcffps
,t1.s_fa_fcfeps as s_fa_fcfeps
,t1.s_fa_netprofitmargin as s_fa_netprofitmargin
,t1.s_fa_grossprofitmargin as s_fa_grossprofitmargin
,t1.s_fa_cogstosales as s_fa_cogstosales
,t1.s_fa_expensetosales as s_fa_expensetosales
,t1.s_fa_profittogr as s_fa_profittogr
,t1.s_fa_saleexpensetogr as s_fa_saleexpensetogr
,t1.s_fa_adminexpensetogr as s_fa_adminexpensetogr
,t1.s_fa_finaexpensetogr as s_fa_finaexpensetogr
,t1.s_fa_impairtogr_ttm as s_fa_impairtogr_ttm
,t1.s_fa_gctogr as s_fa_gctogr
,t1.s_fa_optogr as s_fa_optogr
,t1.s_fa_ebittogr as s_fa_ebittogr
,t1.s_fa_roe as s_fa_roe
,t1.s_fa_roe_deducted as s_fa_roe_deducted
,t1.s_fa_roa2 as s_fa_roa2
,t1.s_fa_roa as s_fa_roa
,t1.s_fa_roic as s_fa_roic
,t1.s_fa_roe_yearly as s_fa_roe_yearly
,t1.s_fa_roa2_yearly as s_fa_roa2_yearly
,t1.s_fa_roe_avg as s_fa_roe_avg
,t1.s_fa_operateincometoebt as s_fa_operateincometoebt
,t1.s_fa_investincometoebt as s_fa_investincometoebt
,t1.s_fa_nonoperateprofittoebt as s_fa_nonoperateprofittoebt
,t1.s_fa_taxtoebt as s_fa_taxtoebt
,t1.s_fa_deductedprofittoprofit as s_fa_deductedprofittoprofit
,t1.s_fa_salescashintoor as s_fa_salescashintoor
,t1.s_fa_ocftoor as s_fa_ocftoor
,t1.s_fa_ocftooperateincome as s_fa_ocftooperateincome
,t1.s_fa_capitalizedtoda as s_fa_capitalizedtoda
,t1.s_fa_debttoassets as s_fa_debttoassets
,t1.s_fa_assetstoequity as s_fa_assetstoequity
,t1.s_fa_dupont_assetstoequity as s_fa_dupont_assetstoequity
,t1.s_fa_catoassets as s_fa_catoassets
,t1.s_fa_ncatoassets as s_fa_ncatoassets
,t1.s_fa_tangibleassetstoassets as s_fa_tangibleassetstoassets
,t1.s_fa_intdebttototalcap as s_fa_intdebttototalcap
,t1.s_fa_equitytototalcapital as s_fa_equitytototalcapital
,t1.s_fa_currentdebttodebt as s_fa_currentdebttodebt
,t1.s_fa_longdebtodebt as s_fa_longdebtodebt
,t1.s_fa_current as s_fa_current
,t1.s_fa_quick as s_fa_quick
,t1.s_fa_cashratio as s_fa_cashratio
,t1.s_fa_ocftoshortdebt as s_fa_ocftoshortdebt
,t1.s_fa_debttoequity as s_fa_debttoequity
,t1.s_fa_equitytodebt as s_fa_equitytodebt
,t1.s_fa_equitytointerestdebt as s_fa_equitytointerestdebt
,t1.s_fa_tangibleassettodebt as s_fa_tangibleassettodebt
,t1.s_fa_tangassettointdebt as s_fa_tangassettointdebt
,t1.s_fa_tangibleassettonetdebt as s_fa_tangibleassettonetdebt
,t1.s_fa_ocftodebt as s_fa_ocftodebt
,t1.s_fa_ocftointerestdebt as s_fa_ocftointerestdebt
,t1.s_fa_ocftonetdebt as s_fa_ocftonetdebt
,t1.s_fa_ebittointerest as s_fa_ebittointerest
,t1.s_fa_longdebttoworkingcapital as s_fa_longdebttoworkingcapital
,t1.s_fa_ebitdatodebt as s_fa_ebitdatodebt
,t1.s_fa_turndays as s_fa_turndays
,t1.s_fa_invturndays as s_fa_invturndays
,t1.s_fa_arturndays as s_fa_arturndays
,t1.s_fa_invturn as s_fa_invturn
,t1.s_fa_arturn as s_fa_arturn
,t1.s_fa_caturn as s_fa_caturn
,t1.s_fa_faturn as s_fa_faturn
,t1.s_fa_assetsturn as s_fa_assetsturn
,t1.s_fa_roa_yearly as s_fa_roa_yearly
,t1.s_fa_dupont_roa as s_fa_dupont_roa
,t1.s_stm_bs as s_stm_bs
,t1.s_fa_prefinexpense_opprofit as s_fa_prefinexpense_opprofit
,t1.s_fa_nonopprofit as s_fa_nonopprofit
,t1.s_fa_optoebt as s_fa_optoebt
,t1.s_fa_noptoebt as s_fa_noptoebt
,t1.s_fa_ocftoprofit as s_fa_ocftoprofit
,t1.s_fa_cashtoliqdebt as s_fa_cashtoliqdebt
,t1.s_fa_cashtoliqdebtwithinterest as s_fa_cashtoliqdebtwithinterest
,t1.s_fa_optoliqdebt as s_fa_optoliqdebt
,t1.s_fa_optodebt as s_fa_optodebt
,t1.s_fa_roic_yearly as s_fa_roic_yearly
,t1.s_fa_tot_faturn as s_fa_tot_faturn
,t1.s_fa_profittoop as s_fa_profittoop
,t1.s_qfa_operateincome as s_qfa_operateincome
,t1.s_qfa_investincome as s_qfa_investincome
,t1.s_qfa_deductedprofit as s_qfa_deductedprofit
,t1.s_qfa_eps as s_qfa_eps
,t1.s_qfa_netprofitmargin as s_qfa_netprofitmargin
,t1.s_qfa_grossprofitmargin as s_qfa_grossprofitmargin
,t1.s_qfa_expensetosales as s_qfa_expensetosales
,t1.s_qfa_profittogr as s_qfa_profittogr
,t1.s_qfa_saleexpensetogr as s_qfa_saleexpensetogr
,t1.s_qfa_adminexpensetogr as s_qfa_adminexpensetogr
,t1.s_qfa_finaexpensetogr as s_qfa_finaexpensetogr
,t1.s_qfa_impairtogr_ttm as s_qfa_impairtogr_ttm
,t1.s_qfa_gctogr as s_qfa_gctogr
,t1.s_qfa_optogr as s_qfa_optogr
,t1.s_qfa_roe as s_qfa_roe
,t1.s_qfa_roe_deducted as s_qfa_roe_deducted
,t1.s_qfa_roa as s_qfa_roa
,t1.s_qfa_operateincometoebt as s_qfa_operateincometoebt
,t1.s_qfa_investincometoebt as s_qfa_investincometoebt
,t1.s_qfa_deductedprofittoprofit as s_qfa_deductedprofittoprofit
,t1.s_qfa_salescashintoor as s_qfa_salescashintoor
,t1.s_qfa_ocftosales as s_qfa_ocftosales
,t1.s_qfa_ocftoor as s_qfa_ocftoor
,t1.s_fa_yoyeps_basic as s_fa_yoyeps_basic
,t1.s_fa_yoyeps_diluted as s_fa_yoyeps_diluted
,t1.s_fa_yoyocfps as s_fa_yoyocfps
,t1.s_fa_yoyop as s_fa_yoyop
,t1.s_fa_yoyebt as s_fa_yoyebt
,t1.s_fa_yoynetprofit as s_fa_yoynetprofit
,t1.s_fa_yoynetprofit_deducted as s_fa_yoynetprofit_deducted
,t1.s_fa_yoyocf as s_fa_yoyocf
,t1.s_fa_yoyroe as s_fa_yoyroe
,t1.s_fa_yoybps as s_fa_yoybps
,t1.s_fa_yoyassets as s_fa_yoyassets
,t1.s_fa_yoyequity as s_fa_yoyequity
,t1.s_fa_yoy_tr as s_fa_yoy_tr
,t1.s_fa_yoy_or as s_fa_yoy_or
,t1.s_qfa_yoygr as s_qfa_yoygr
,t1.s_qfa_cgrgr as s_qfa_cgrgr
,t1.s_qfa_yoysales as s_qfa_yoysales
,t1.s_qfa_cgrsales as s_qfa_cgrsales
,t1.s_qfa_yoyop as s_qfa_yoyop
,t1.s_qfa_cgrop as s_qfa_cgrop
,t1.s_qfa_yoyprofit as s_qfa_yoyprofit
,t1.s_qfa_cgrprofit as s_qfa_cgrprofit
,t1.s_qfa_yoynetprofit as s_qfa_yoynetprofit
,t1.s_qfa_cgrnetprofit as s_qfa_cgrnetprofit
,t1.s_fa_yoy_equity as s_fa_yoy_equity
,t1.rd_expense as rd_expense
,t1.waa_roe as waa_roe
,replace(replace(t1.s_info_compcode,chr(13),''),chr(10),'') as s_info_compcode
,t1.opdate as opdate
,replace(replace(t1.opmode,chr(13),''),chr(10),'') as opmode
from ${iol_schema}.wind_asharefinancialindicator t1
where etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/ccrm_wind_asharefinancialindicator.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes