: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_rpt_ibms_ttrd_otc_trade_i
CreateDate: 20180529
FileName:   ${iel_data_path}/rpt_ibms_ttrd_otc_trade.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select
 t1.sysordid as sysordid
,t1.orddate as orddate
,t1.ordtime as ordtime
,t1.condate as condate
,t1.contime as contime
,t1.insid as insid
,t1.intordid as intordid
,t1.extordid as extordid
,t1.custordid as custordid
,t1.extbizid as extbizid
,t1.operator as operator
,t1.trdtype as trdtype
,t1.cash_ext_accid as cash_ext_accid
,t1.cash_accid as cash_accid
,t1.secu_ext_accid as secu_ext_accid
,t1.secu_accid as secu_accid
,t1.partyid as partyid
,t1.cp_cash_accid as cp_cash_accid
,t1.cp_secu_accid as cp_secu_accid
,t1.i_code as i_code
,t1.a_type as a_type
,t1.m_type as m_type
,t1.i_name as i_name
,t1.ordcount as ordcount
,t1.ordprice as ordprice
,t1.ordamount as ordamount
,t1.trdfee as trdfee
,t1.setfee as setfee
,t1.setdays as setdays
,t1.setdate as setdate
,t1.thenmktprice as thenmktprice
,t1.thenmktprice_u as thenmktprice_u
,t1.ordstatus as ordstatus
,t1.errcode as errcode
,t1.errinfo as errinfo
,t1.bnd_settype as bnd_settype
,t1.bnd_netprice as bnd_netprice
,t1.bnd_aiamount as bnd_aiamount
,t1.remark as remark
,t1.reservetype as reservetype
,t1.cp_reservetype as cp_reservetype
,t1.reservechg as reservechg
,t1.cp_reservechg as cp_reservechg
,t1.reservevalue as reservevalue
,t1.cp_reservevalue as cp_reservevalue
,t1.resolve as resolve
,t1.trade_grp_id as trade_grp_id
,t1.ref_orddate as ref_orddate
,t1.ref_sysordid as ref_sysordid
,t1.ignore_flag as ignore_flag
,t1.exe_market as exe_market
,t1.trader as trader
,t1.trader_cp as trader_cp
,t1.dealtype as dealtype
,t1.agreenumber as agreenumber
,t1.eval_netprice as eval_netprice
,t1.ordsource as ordsource
,t1.deal_count as deal_count
,t1.deal_avg_netprice as deal_avg_netprice
,t1.deal_netamount as deal_netamount
,t1.deal_aiamount as deal_aiamount
,t1.deal_amount as deal_amount
,t1.bidaskid as bidaskid
,t1.relatedparty as relatedparty
,t1.terminate_amount as terminate_amount
,t1.setdate_terminate as setdate_terminate
,t1.agreementtype as agreementtype
,t1.partynametempority as partynametempority
,t1.party_zzdaccname as party_zzdaccname
,t1.seatno_cp as seatno_cp
,t1.executor as executor
,t1.union_sysordid as union_sysordid
,t1.party_zzdacccode as party_zzdacccode
,t1.party_bank_code as party_bank_code
,t1.party_acct_code as party_acct_code
,t1.party_bank_name as party_bank_name
,t1.party_acct_name as party_acct_name
,t1.dis_fee_kind_follow as dis_fee_kind_follow
,t1.dis_fee_kind as dis_fee_kind
,t1.grpid_sub as grpid_sub
,t1.imp_time as imp_time
,t1.eval_ytm as eval_ytm
,t1.bnd_ytm as bnd_ytm
,t1.update_time as update_time
,t1.due_ai as due_ai
,t1.operator_id as operator_id
,t1.executor_id as executor_id
,t1.due_cp as due_cp
,t1.real_ai as real_ai
,t1.real_cp as real_cp
,t1.real_fee as real_fee
,t1.due_fee as due_fee
,t1.ref_type as ref_type
,t1.is_remain as is_remain
,t1.trader_id as trader_id
,t1.trademodel as trademodel
,t1.settlemodel as settlemodel
,t1.ord_id as ord_id
,t1.insstatus as insstatus
,t1.entrust_ref_id as entrust_ref_id
,t1.close_trade_id as close_trade_id
,t1.ftprate as ftprate
,t1.conn_ordid as conn_ordid
,t1.two_effective_contract as two_effective_contract
,t1.source_type as source_type
,t1.settlestate as settlestate
,t1.navdate as navdate
,t1.qcurr_cash_ext_accid as qcurr_cash_ext_accid
,t1.qcurr_party_bank_code as qcurr_party_bank_code
,t1.qcurr_party_bank_name as qcurr_party_bank_name
,t1.qcurr_party_acct_code as qcurr_party_acct_code
,t1.qcurr_party_acct_name as qcurr_party_acct_name
,t1.party_mid_bank_acct_code as party_mid_bank_acct_code
,t1.party_mid_bank_name as party_mid_bank_name
,t1.party_mid_swift_code as party_mid_swift_code
,t1.qcurr_party_mid_bank_acct_code as qcurr_party_mid_bank_acct_code
,t1.qcurr_party_mid_bank_name as qcurr_party_mid_bank_name
,t1.qcurr_party_mid_swift_code as qcurr_party_mid_swift_code
,t1.party_swift_code as party_swift_code
,t1.qcurr_party_swift_code as qcurr_party_swift_code
,t1.spv_id as spv_id
,t1.his_tradeflag as his_tradeflag
,t1.his_ref_tradeid as his_ref_tradeid
,t1.his_trade_setdate as his_trade_setdate
,t1.party_pset as party_pset
,t1.party_pset_country as party_pset_country
,t1.party_agent_code_type as party_agent_code_type
,t1.party_agent_code_dss as party_agent_code_dss
,t1.party_agent_code as party_agent_code
,t1.party_agent_account as party_agent_account
,t1.party_code_type as party_code_type
,t1.party_code_dss as party_code_dss
,t1.party_code as party_code
,t1.party_account as party_account
,t1.si_id as si_id
,t1.party_i_bank_code as party_i_bank_code
,t1.party_i_swift_code as party_i_swift_code
,t1.split_inst_type as split_inst_type
,t1.cm_attr_parent as cm_attr_parent
,t1.cm_attr_master as cm_attr_master
,t1.cm_attr_merge as cm_attr_merge
,t1.cm_attr_mirror as cm_attr_mirror
,t1.cm_attr_relation as cm_attr_relation
,t1.cal_start_date as cal_start_date
,t1.cal_end_date as cal_end_date
,t1.strike_ytm as strike_ytm
,t1.settlement_type as settlement_type
,t1.aio_acct_no as aio_acct_no
,t1.acct_type as acct_type
,t1.user_name as user_name
,t1.contractparty as contractparty
,t1.marketing_manager_id as marketing_manager_id
,t1.marketing_org_id as marketing_org_id
,t1.com_date as com_date
,t1.party_branch as party_branch
,t1.max_val as max_val
,t1.min_val as min_val
,t1.collection_fst_fee as collection_fst_fee
,t1.transfer_type as transfer_type
,t1.secu_setdate as secu_setdate
,t1.csdc_netprice as csdc_netprice
,t1.ccdc_netprice as ccdc_netprice
,t1.shch_netprice as shch_netprice
,t1.se_netprice as se_netprice
,t1.ctrct_id as ctrct_id
,t1.platform as platform
,t1.invest_direction as invest_direction
,t1.contractversion as contractversion
,t1.final_invest as final_invest
,t1.associatednumber as associatednumber
,t1.fiveclass as fiveclass
,t1.prod_nature as prod_nature
,t1.trd_acc_code as trd_acc_code
,t1.store_code as store_code
,t1.quote_type as quote_type
,t1.unit_id as unit_id
,t1.curcount as curcount
,t1.can_div_amount as can_div_amount
,t1.is_remain_due_ai as is_remain_due_ai
,t1.is_impair as is_impair
,t1.option_group as option_group
,t1.entry_date as entry_date
,t1.party_pset_name as party_pset_name
,t1.relate_invest as relate_invest
,t1.settlement_place as settlement_place
,t1.trdfee_notset as trdfee_notset
,t1.daycounter as daycounter
,t1.remain_due_cp as remain_due_cp
,t1.include_inte as include_inte
,t1.exh_extordid as exh_extordid
,t1.exrcise_state as exrcise_state
,t1.sppiresult as sppiresult
,t1.sppiclass as sppiclass
,t1.mergeno as mergeno
,t1.resource_id as resource_id
,t1.party_relevance_info as party_relevance_info
,t1.full_flag as full_flag
,t1.brokerage_id as brokerage_id
,t1.brokerage_fee_info as brokerage_fee_info
,t1.released_credit_line as released_credit_line
,t1.out_range as out_range
,t1.interest_out as interest_out
,t1.book as book
,t1.xcc_trade_grp_id as xcc_trade_grp_id
,t1.xcc_pre_sysordid as xcc_pre_sysordid
,t1.pc1 as pc1
,t1.yhf as yhf
,t1.jsf as jsf
,t1.ghf as ghf
,t1.zgf as zgf
,t1.sxf as sxf
,t1.brkfee as brkfee
,t1.yjf as yjf
,t1.netyjf as netyjf
,t1.con_update_time as con_update_time
,t1.qcurr_party_recv_bank_name as qcurr_party_recv_bank_name
,t1.qcurr_party_recv_bank_swift as qcurr_party_recv_bank_swift
,t1.party_recv_bank_name as party_recv_bank_name
,t1.party_recv_bank_swift_code as party_recv_bank_swift_code
,t1.other_fee as other_fee
,t1.cli_ord_id as cli_ord_id
,t1.party_acc_code_type as party_acc_code_type
,t1.qcurr_party_acc_code_type as qcurr_party_acc_code_type
,t1.party_swift_type as party_swift_type
,t1.qcurr_party_swift_type as qcurr_party_swift_type
,t1.back_bank_code as back_bank_code
,t1.back_acct_code as back_acct_code
,t1.back_bank_name as back_bank_name
,t1.back_acct_name as back_acct_name
,t1.other_agree_item as other_agree_item
,t1.bank_group_mode as bank_group_mode
,t1.cash_setdate as cash_setdate
,t1.trd_fee_ext_secu_acct_id as trd_fee_ext_secu_acct_id
,t1.bnd_ytm_deviate as bnd_ytm_deviate
,t1.pre_bnt_ord_id as pre_bnt_ord_id
,t1.pre_remain_count as pre_remain_count
,t1.p_id as p_id
,t1.ftp_code as ftp_code
 from idl.ibms_ttrd_otc_trade T1
where replace(orddate,'-','')='${batch_date}';" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/rpt_ibms_ttrd_otc_trade.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes