: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_odss_psn_cst_mag_aum_i
CreateDate: 20180529
FileName:   ${iel_data_path}/odss_psn_cst_mag_aum_${batch_date}_i.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select
cc_blng_cst_mgr_no
,cc_org_no
,cc_aum_bal
,cc_cmn_dept_bal
,cc_sr_fnc
,cc_dept_bal
,cc_asgn_dpst
,cc_ndbt_bal
,cc_fund_bal
,cc_fnc_bal
,cc_tpc_bal
,cc_scl_isfee_bal
,cc_ln_bal
,cc_lday_aum_bal
,cc_lday_cmn_dept_bal
,cc_lday_sr_fnc
,cc_lday_dept_bal
,cc_lday_asgn_dpst
,cc_lday_ndbt_bal
,cc_lday_fund_bal
,cc_lday_fnc_bal
,cc_lday_tpc_bal
,cc_lday_scl_isfee_bal
,cc_lday_ln_bal
,cc_last_mn_aum_bal
,cc_last_mn_cmn_dept_bal
,cc_last_mn_sr_fnc
,cc_last_mn_dept_bal
,cc_last_mn_asgn_dpst
,cc_last_mn_ndbt_bal
,cc_last_mn_fund_bal
,cc_last_mn_fnc_bal
,cc_last_mn_tpc_bal
,cc_last_mn_scl_isfee_bal
,cc_last_mn_ln_bal
,cc_lyr_aum_bal
,cc_lyr_cmn_dept_bal
,cc_lyr_sr_fnc
,cc_lyr_dept_bal
,cc_lyr_asgn_dpst
,cc_lyr_ndbt_bal
,cc_lyr_fund_bal
,cc_lyr_fnc_bal
,cc_lyr_tpc_bal
,cc_lyr_scl_isfee_bal
,cc_lyr_ln_bal
,cc_lday_aum_bal_chng
,cc_lday_cmn_dept_bal_chng
,cc_lday_sr_fnc_chng
,cc_lday_dept_bal_chng
,cc_lday_asgn_dpst_chng
,cc_lday_ndbt_bal_chng
,cc_lday_fund_bal_chng
,cc_lday_fnc_chng
,cc_lday_tpc_chng
,cc_lday_scl_isfee_chng
,cc_lday_ln_chng
,cc_last_mn_aum_chng
,cc_last_mn_cmn_dept_chng
,cc_last_mn_sr_fnc_chng
,cc_last_mn_dept_bal_chng
,cc_last_mn_asgn_dpst_chng
,cc_last_mn_ndbt_bal_chng
,cc_last_mn_fund_bal_chng
,cc_last_mn_fnc_bal_chng
,cc_last_mn_tpc_bal_chng
,cc_last_mn_scl_isfee_bal_chng
,cc_last_mn_ln_bal_chng
,cc_lyr_aum_bal_chng
,cc_lyr_cmn_dept_bal_chng
,cc_lyr_sr_fnc_chng
,cc_lyr_dept_bal_chng
,cc_lyr_asgn_dpst_chng
,cc_lyr_ndbt_bal_chng
,cc_lyr_fund_bal_chng
,cc_lyr_fnc_bal_chng
,cc_lyr_tpc_bal_chng
,cc_lyr_scl_isfee_bal_chng
,cc_lyr_ln_bal_chng
,cc_aum_yavg
,cc_cmn_dept_yavg
,cc_sr_fnc_yavg
,cc_dept_yavg
,cc_asgn_dpst_yavg
,cc_ndbt_yavg
,cc_fund_yavg
,cc_fnc_yavg
,cc_tpc_yavg
,cc_scl_isfee_yavg
,cc_ln_yavg
,cc_aum_qavg
,cc_cmn_dept_qavg
,cc_sr_fnc_qavg
,cc_dept_qavg
,cc_asgn_dpst_qavg
,cc_ndbt_qavg
,cc_fund_qavg
,cc_fnc_qavg
,cc_tpc_qavg
,cc_scl_isfee_qavg
,cc_ln_qavg
,cc_aum_mavg
,cc_cmn_dept_mavg
,cc_sr_fnc_mavg
,cc_dept_mavg
,cc_asgn_dpst_mavg
,cc_ndbt_mavg
,cc_fund_mavg
,cc_fnc_mavg
,cc_tpc_mavg
,cc_scl_isfee_mavg
,cc_ln_mavg
,cc_lyr_aum_yavg
,cc_lyr_cmn_dept_yavg
,cc_lyr_sr_fnc_yavg
,cc_lyr_dept_yavg
,cc_lyr_asgn_dpst_yavg
,cc_lyr_ndbt_yavg
,cc_lyr_fund_yavg
,cc_lyr_fnc_yavg
,cc_lyr_tpc_yavg
,cc_lyr_scl_isfee_yavg
,cc_lyr_ln_yavg
,cc_data_dt
,cc_lday_e_fund_bal
,cc_e_fund_bal
,cc_last_mn_e_fund_bal
,cc_lyr_e_fund_bal
,cc_lday_e_fund_bal_chng
,cc_last_mn_e_fund_bal_chng
,cc_lyr_e_fund_bal_chng
,cc_e_fund_yavg
,cc_e_fund_qavg
,cc_e_fund_mavg
,cc_lyr_e_fund_yavg
,cc_lday_rmb_cur_bal
,cc_rmb_cur_dept_bal
,cc_last_mn_rmb_cur_bal
,cc_lyr_rmb_cur_bal
,cc_lday_rmb_cur_bal_chng
,cc_last_mn_rmb_cur_bal_chng
,cc_lyr_rmb_cur_bal_chng
,cc_rmb_cur_yavg
,cc_rmb_cur_qavg
,cc_rmb_cur_mavg
,cc_lyr_rmb_cur_yavg
,cc_lday_rmb_dpt_bal
,cc_rmb_dpt_dept_bal
,cc_last_mn_rmb_dpt_bal
,cc_lyr_rmb_dpt_bal
,cc_lday_rmb_dpt_bal_chng
,cc_last_mn_rmb_dpt_bal_chng
,cc_lyr_rmb_dpt_bal_chng
,cc_rmb_dpt_yavg
,cc_rmb_dpt_qavg
,cc_rmb_dpt_mavg
,cc_lyr_rmb_dpt_yavg
,cc_lday_fcy_cur_bal
,cc_fcy_cur_dept_bal
,cc_last_mn_fcy_cur_bal
,cc_lyr_fcy_cur_bal
,cc_lday_fcy_cur_bal_chng
,cc_last_mn_fcy_cur_bal_chng
,cc_lyr_fcy_cur_bal_chng
,cc_fcy_cur_yavg
,cc_fcy_cur_qavg
,cc_fcy_cur_mavg
,cc_lyr_fcy_cur_yavg
,cc_lday_fcy_dpt_bal
,cc_fcy_dpt_dept_bal
,cc_last_mn_fcy_dpt_bal
,cc_lyr_fcy_dpt_bal
,cc_lday_fcy_dpt_bal_chng
,cc_last_mn_fcy_dpt_bal_chng
,cc_lyr_fcy_dpt_bal_chng
,cc_fcy_dpt_yavg
,cc_fcy_dpt_qavg
,cc_fcy_dpt_mavg
,cc_lyr_fcy_dpt_yavg
,cc_lday_gold_bal
,cc_gold_bal
,cc_last_mn_gold_bal
,cc_lyr_gold_bal
,cc_lday_gold_bal_chng
,cc_last_mn_gold_bal_chng
,cc_lyr_gold_bal_chng
,cc_gold_yavg
,cc_gold_qavg
,cc_gold_mavg
,cc_lyr_gold_yavg
,cc_lday_ins_bal
,cc_ins_bal
,cc_last_mn_ins_bal
,cc_lyr_ins_bal
,cc_lday_ins_bal_chng
,cc_last_mn_ins_bal_chng
,cc_lyr_ins_bal_chng
,cc_ins_yavg
,cc_ins_qavg
,cc_ins_mavg
,cc_lyr_ins_yavg
from ${idl_schema}.odss_psn_cst_mag_aum
where etl_dt=to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/odss_psn_cst_mag_aum_${batch_date}_i.dat" \
        charset=zhs16gbk
        safe=yes