: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_crms_cms_business_approve_f
CreateDate: 20180529
FileName:   ${iel_data_path}/crms_cms_business_approve_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
serialno
,relativeserialno
,occurdate
,customerid
,customername
,businesstype
,businesssubtype
,occurtype
,currenylist
,currencymode
,businesstypelist
,calculatemode
,useorglist
,flowreduceflag
,contractflag
,subcontractflag
,selfuseflag
,creditaggreement
,relativeagreement
,loanflag
,totalsum
,ourrole
,reversibility
,billnum
,housetype
,lctermtype
,riskattribute
,suretype
,safeguardtype
,creditbusiness
,businesscurrency
,businesssum
,businessprop
,termyear
,termmonth
,termday
,lgterm
,baseratetype
,baserate
,ratefloattype
,ratefloat
,businessrate
,ictype
,iccyc
,pdgratio
,pdgsum
,pdgpaymethod
,pdgpayperiod
,promisesfeeratio
,promisesfeesum
,promisesfeeperiod
,promisesfeebegin
,mfeeratio
,mfeesum
,mfeepaymethod
,agentfee
,dealfee
,totalcast
,discountinterest
,purchaserinterest
,bargainorinterest
,discountsum
,bailratio
,bailcurrency
,bailsum
,bailaccount
,fineratetype
,finerate
,drawingtype
,firstdrawingdate
,drawingperiod
,paytimes
,paycyc
,graceperiod
,overdraftperiod
,oldlcno
,oldlctermtype
,oldlccurrency
,oldlcsum
,oldlcloadingdate
,oldlcvaliddate
,direction
,purpose
,planallocation
,immediacypaysource
,paysource
,corpuspaymethod
,interestpaymethod
,thirdparty1
,thirdpartyid1
,thirdparty2
,thirdpartyid2
,thirdparty3
,thirdpartyid3
,thirdpartyregion
,thirdpartyaccounts
,cargoinfo
,projectname
,operationinfo
,contextinfo
,securitiestype
,securitiesregion
,constructionarea
,usearea
,flag1
,flag2
,flag3
,tradecontractno
,invoiceno
,tradecurrency
,tradesum
,paymentdate
,operationmode
,vouchclass
,vouchtype
,vouchtype1
,vouchtype2
,vouchflag
,warrantor
,warrantorid
,othercondition
,guarantyvalue
,guarantyrate
,baseevaluateresult
,riskrate
,lowrisk
,otherarealoan
,lowriskbailsum
,originalputoutdate
,extendtimes
,lngotimes
,golntimes
,drtimes
,baseclassifyresult
,applytype
,bailrate
,finishorg
,describe1
,operateorgid
,operateuserid
,operatedate
,inputorgid
,inputuserid
,inputdate
,updatedate
,pigeonholedate
,remark
,paycurrency
,paydate
,flag4
,fundsource
,operatetype
,approvetype
,cycleflag
,classifyresult
,classifydate
,classifyfrequency
,vouchnewflag
,adjustratetype
,adjustrateterm
,rateadjustcyc
,fzanbalance
,acceptinttype
,ratio
,thirdpartyadd1
,thirdpartyzip1
,thirdpartyadd2
,thirdpartyzip2
,thirdpartyadd3
,thirdpartyzip3
,effectarea
,termdate1
,termdate2
,termdate3
,fixcyc
,describe2
,approveopinion
,tempsaveflag
,approvedate
,flag5
,creditcycle
,guarantyflag
,effectflag
,creditmode
,artificialno
,returntype
,holdbalance
,returnperiod
,loantermflag
,mainreturntype
,schemeno
,ltvvalue
,ratemode
,loanterm
,otherpurpose
,currency
,cguarantypeople
,buyhousetype
,buyhouseproperty
,houseareage
,houseprice
,housecount
,paymentmode
,fundserialno
,ctogetherborrower
,csinglnassure
,guarantyhouse
,abysum
,applyinsuranceflag
,sendchitflag
,ratecode
,calcterm
,classifyresulteleven
,reinforceflag
,approveopinion1
,accountno
,maturity
,istrans
,carbrand
,cartype
,carnumber
,chariotnumber
,motornumber
,rateopinion
,preeffectflag
,iscontinueoversee
,buyhousedetail
,thirdparty1type
,thirdorgname
,approveopinion6
,approveopinion7
,priattribute
from ${idl_schema}.crms_cms_business_approve
where etl_dt=to_date('${batch_date}','yyyymmdd');" \
        field="|#|" record="0x0a"  \
        file="${iel_data_path}/crms_cms_business_approve_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes