: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_ccrm_wind_cbondbalancesheet_i
CreateDate: 20180529
FileName:   ${iel_data_path}/ccrm_wind_cbondbalancesheet.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
replace(replace(t1.object_id,chr(13),''),chr(10),'') as object_id
,replace(replace(t1.s_info_compcode,chr(13),''),chr(10),'') as s_info_compcode
,replace(replace(t1.ann_dt,chr(13),''),chr(10),'') as ann_dt
,replace(replace(t1.report_period,chr(13),''),chr(10),'') as report_period
,replace(replace(t1.statement_type,chr(13),''),chr(10),'') as statement_type
,replace(replace(t1.crncy_code,chr(13),''),chr(10),'') as crncy_code
,t1.monetary_cap as monetary_cap
,t1.tradable_fin_assets as tradable_fin_assets
,t1.notes_rcv as notes_rcv
,t1.acct_rcv as acct_rcv
,t1.oth_rcv as oth_rcv
,t1.prepay as prepay
,t1.dvd_rcv as dvd_rcv
,t1.int_rcv as int_rcv
,t1.inventories as inventories
,t1.consumptive_bio_assets as consumptive_bio_assets
,t1.deferred_exp as deferred_exp
,t1.non_cur_assets_due_within_1y as non_cur_assets_due_within_1y
,t1.settle_rsrv as settle_rsrv
,t1.loans_to_oth_banks as loans_to_oth_banks
,t1.prem_rcv as prem_rcv
,t1.rcv_from_reinsurer as rcv_from_reinsurer
,t1.rcv_from_ceded_insur_cont_rsrv as rcv_from_ceded_insur_cont_rsrv
,t1.red_monetary_cap_for_sale as red_monetary_cap_for_sale
,t1.oth_cur_assets as oth_cur_assets
,t1.tot_cur_assets as tot_cur_assets
,t1.fin_assets_avail_for_sale as fin_assets_avail_for_sale
,t1.held_to_mty_invest as held_to_mty_invest
,t1.long_term_eqy_invest as long_term_eqy_invest
,t1.invest_real_estate as invest_real_estate
,t1.time_deposits as time_deposits
,t1.oth_assets as oth_assets
,t1.long_term_rec as long_term_rec
,t1.fix_assets as fix_assets
,t1.const_in_prog as const_in_prog
,t1.proj_matl as proj_matl
,t1.fix_assets_disp as fix_assets_disp
,t1.productive_bio_assets as productive_bio_assets
,t1.oil_and_natural_gas_assets as oil_and_natural_gas_assets
,t1.intang_assets as intang_assets
,t1.r_and_d_costs as r_and_d_costs
,t1.goodwill as goodwill
,t1.long_term_deferred_exp as long_term_deferred_exp
,t1.deferred_tax_assets as deferred_tax_assets
,t1.loans_and_adv_granted as loans_and_adv_granted
,t1.oth_non_cur_assets as oth_non_cur_assets
,t1.tot_non_cur_assets as tot_non_cur_assets
,t1.cash_deposits_central_bank as cash_deposits_central_bank
,t1.asset_dep_oth_banks_fin_inst as asset_dep_oth_banks_fin_inst
,t1.precious_metals as precious_metals
,t1.derivative_fin_assets as derivative_fin_assets
,t1.agency_bus_assets as agency_bus_assets
,t1.subr_rec as subr_rec
,t1.rcv_ceded_unearned_prem_rsrv as rcv_ceded_unearned_prem_rsrv
,t1.rcv_ceded_claim_rsrv as rcv_ceded_claim_rsrv
,t1.rcv_ceded_life_insur_rsrv as rcv_ceded_life_insur_rsrv
,t1.rcv_ceded_lt_health_insur_rsrv as rcv_ceded_lt_health_insur_rsrv
,t1.mrgn_paid as mrgn_paid
,t1.insured_pledge_loan as insured_pledge_loan
,t1.cap_mrgn_paid as cap_mrgn_paid
,t1.independent_acct_assets as independent_acct_assets
,t1.clients_cap_deposit as clients_cap_deposit
,t1.clients_rsrv_settle as clients_rsrv_settle
,t1.incl_seat_fees_exchange as incl_seat_fees_exchange
,t1.rcv_invest as rcv_invest
,t1.tot_assets as tot_assets
,t1.st_borrow as st_borrow
,t1.borrow_central_bank as borrow_central_bank
,t1.deposit_received_ib_deposits as deposit_received_ib_deposits
,t1.loans_oth_banks as loans_oth_banks
,t1.tradable_fin_liab as tradable_fin_liab
,t1.notes_payable as notes_payable
,t1.acct_payable as acct_payable
,t1.adv_from_cust as adv_from_cust
,t1.fund_sales_fin_assets_rp as fund_sales_fin_assets_rp
,t1.handling_charges_comm_payable as handling_charges_comm_payable
,t1.empl_ben_payable as empl_ben_payable
,t1.taxes_surcharges_payable as taxes_surcharges_payable
,t1.int_payable as int_payable
,t1.dvd_payable as dvd_payable
,t1.oth_payable as oth_payable
,t1.acc_exp as acc_exp
,t1.deferred_inc as deferred_inc
,t1.st_bonds_payable as st_bonds_payable
,t1.payable_to_reinsurer as payable_to_reinsurer
,t1.rsrv_insur_cont as rsrv_insur_cont
,t1.acting_trading_sec as acting_trading_sec
,t1.acting_uw_sec as acting_uw_sec
,t1.non_cur_liab_due_within_1y as non_cur_liab_due_within_1y
,t1.oth_cur_liab as oth_cur_liab
,t1.tot_cur_liab as tot_cur_liab
,t1.lt_borrow as lt_borrow
,t1.bonds_payable as bonds_payable
,t1.lt_payable as lt_payable
,t1.specific_item_payable as specific_item_payable
,t1.provisions as provisions
,t1.deferred_tax_liab as deferred_tax_liab
,t1.deferred_inc_non_cur_liab as deferred_inc_non_cur_liab
,t1.oth_non_cur_liab as oth_non_cur_liab
,t1.tot_non_cur_liab as tot_non_cur_liab
,t1.liab_dep_oth_banks_fin_inst as liab_dep_oth_banks_fin_inst
,t1.derivative_fin_liab as derivative_fin_liab
,t1.cust_bank_dep as cust_bank_dep
,t1.agency_bus_liab as agency_bus_liab
,t1.oth_liab as oth_liab
,t1.prem_received_adv as prem_received_adv
,t1.deposit_received as deposit_received
,t1.insured_deposit_invest as insured_deposit_invest
,t1.unearned_prem_rsrv as unearned_prem_rsrv
,t1.out_loss_rsrv as out_loss_rsrv
,t1.life_insur_rsrv as life_insur_rsrv
,t1.lt_health_insur_v as lt_health_insur_v
,t1.independent_acct_liab as independent_acct_liab
,t1.incl_pledge_loan as incl_pledge_loan
,t1.claims_payable as claims_payable
,t1.dvd_payable_insured as dvd_payable_insured
,t1.tot_liab as tot_liab
,t1.cap_stk as cap_stk
,t1.cap_rsrv as cap_rsrv
,t1.special_rsrv as special_rsrv
,t1.surplus_rsrv as surplus_rsrv
,t1.undistributed_profit as undistributed_profit
,t1.less_tsy_stk as less_tsy_stk
,t1.prov_nom_risks as prov_nom_risks
,t1.cnvd_diff_foreign_curr_stat as cnvd_diff_foreign_curr_stat
,t1.unconfirmed_invest_loss as unconfirmed_invest_loss
,t1.minority_int as minority_int
,t1.tot_shrhldr_eqy_excl_min_int as tot_shrhldr_eqy_excl_min_int
,t1.tot_shrhldr_eqy_incl_min_int as tot_shrhldr_eqy_incl_min_int
,t1.tot_liab_shrhldr_eqy as tot_liab_shrhldr_eqy
,replace(replace(t1.comp_type_code,chr(13),''),chr(10),'') as comp_type_code
,replace(replace(t1.actual_ann_dt,chr(13),''),chr(10),'') as actual_ann_dt
,t1.spe_cur_assets_diff as spe_cur_assets_diff
,t1.tot_cur_assets_diff as tot_cur_assets_diff
,t1.spe_non_cur_assets_diff as spe_non_cur_assets_diff
,t1.tot_non_cur_assets_diff as tot_non_cur_assets_diff
,t1.spe_bal_assets_diff as spe_bal_assets_diff
,t1.tot_bal_assets_diff as tot_bal_assets_diff
,t1.spe_cur_liab_diff as spe_cur_liab_diff
,t1.tot_cur_liab_diff as tot_cur_liab_diff
,t1.spe_non_cur_liab_diff as spe_non_cur_liab_diff
,t1.tot_non_cur_liab_diff as tot_non_cur_liab_diff
,t1.spe_bal_liab_diff as spe_bal_liab_diff
,t1.tot_bal_liab_diff as tot_bal_liab_diff
,t1.spe_bal_shrhldr_eqy_diff as spe_bal_shrhldr_eqy_diff
,t1.tot_bal_shrhldr_eqy_diff as tot_bal_shrhldr_eqy_diff
,t1.spe_bal_liab_eqy_diff as spe_bal_liab_eqy_diff
,t1.tot_bal_liab_eqy_diff as tot_bal_liab_eqy_diff
,t1.audit_am as audit_am
,t1.lt_payroll_payable as lt_payroll_payable
,t1.other_comp_income as other_comp_income
,t1.other_equity_tools as other_equity_tools
,t1.other_equity_tools_p_shr as other_equity_tools_p_shr
,t1.lending_funds as lending_funds
,t1.accounts_receivable as accounts_receivable
,t1.st_financing_payable as st_financing_payable
,t1.payables as payables
,t1.tot_shr as tot_shr
,t1.hfs_assets as hfs_assets
,t1.hfs_sales as hfs_sales
,to_date('${batch_date}','yyyymmdd') as opdate
,'' as opmode
from ${iol_schema}.wind_cbondbalancesheet t1
where etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/ccrm_wind_cbondbalancesheet.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes