: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_agt_loan_cont_info_f_w
CreateDate: 20180529
FileName:   ${iel_data_path}/agt_loan_cont_info_w.f.${batch_date}.dat
IF_mark:    f_w
Logs:
   zjj 2018-07-27 create t1emplate
' \
        query="select 
t1.etl_dt 
,t1.agt_id as agt_id
,t1.lp_id as lp_id
,t1.cont_id as cont_id
,t1.rela_apprv_flow_num as rela_apprv_flow_num
,t1.happ_dt as happ_dt
,t1.party_id as party_id
,t1.bus_breed_id as bus_breed_id
,t1.bus_sub_type_cd as bus_sub_type_cd
,t1.happ_type_cd as happ_type_cd
,t1.lmt_circl_flg as lmt_circl_flg
,t1.bank_fin_tot as bank_fin_tot
,t1.bill_qtty as bill_qtty
,t1.curr_cd as curr_cd
,t1.cont_amt as cont_amt
,t1.tenor_mon as t1enor_mon
,t1.base_rat as base_rat
,t1.int_rat_type_cd as int_rat_type_cd
,t1.int_rat_flo_val as int_rat_flo_val
,t1.exec_int_rat as exec_int_rat
,t1.charge_way_cd as charge_way_cd
,t1.comm_fee_ratio as comm_fee_ratio
,t1.comm_fee_amt as comm_fee_amt
,t1.margin_ratio as margin_ratio
,t1.margin_curr_cd as margin_curr_cd
,t1.margin_amt as margin_amt
,t1.margin_acct_id as margin_acct_id
,t1.pnlt_int_rat as pnlt_int_rat
,t1.draw_way_cd as draw_way_cd
,t1.init_lc_tenor_type_cd as init_lc_tenor_type_cd
,t1.loan_dir_indus_cd as loan_dir_indus_cd
,t1.loan_usage_descb as loan_usage_descb
,t1.repay_src_descb as repay_src_descb
,t1.distr_dt as distr_dt
,t1.exp_dt as exp_dt
,t1.trdpty_cust_name1 as t1rdpty_cust_name1
,t1.trdpty_cust_name2 as t1rdpty_cust_name2
,t1.trdpty_acct_id as t1rdpty_acct_id
,t1.rela_trade_cont_id as rela_trade_cont_id
,t1.trade_cont_amt as t1rade_cont_amt
,t1.lc_id as lc_id
,t1.main_guar_way_cd as main_guar_way_cd
,t1.guar_way_cd1 as guar_way_cd1
,t1.guar_way_cd2 as guar_way_cd2
,t1.other_guar_way_flg as other_guar_way_flg
,t1.major_guartor_name as major_guartor_name
,t1.major_guartor_id as major_guartor_id
,t1.low_risk_bus_flg as low_risk_bus_flg
,t1.remote_loan_flg as remote_loan_flg
,t1.appl_way_cd as appl_way_cd
,t1.distrd_loan_amt as distrd_loan_amt
,t1.curr_bal as curr_bal
,t1.nomal_bal as nomal_bal
,t1.ovdue_bal as ovdue_bal
,t1.idle_bal as idle_bal
,t1.bad_debt_bal as bad_debt_bal
,t1.in_bs_over_int_bal as in_bs_over_int_bal
,t1.off_bs_over_int_bal as off_bs_over_int_bal
,t1.pric_pnlt as pric_pnlt
,t1.int_pnlt as int_pnlt
,t1.level5_cls_cd as level5_cls_cd
,t1.termnt_dt as t1ermnt_dt
,t1.mgmt_org_id as mgmt_org_id
,t1.mgmt_teller_id as mgmt_teller_id
,t1.oper_org_id as oper_org_id
,t1.oper_teller_id as oper_teller_id
,t1.oper_dt as oper_dt
,t1.rgst_org_id as rgst_org_id
,t1.rgst_teller_id as rgst_teller_id
,t1.rgst_dt as rgst_dt
,t1.modif_dt as modif_dt
,t1.cap_src_cd as cap_src_cd
,t1.circl_flg as circl_flg
,t1.lmt_froz_flg as lmt_froz_flg
,t1.actl_text_cont_id as actl_text_cont_id
,t1.stl_acct_id as stl_acct_id
,t1.loan_enter_acct_acct_id as loan_enter_acct_acct_id
,t1.int_rat_adj_way_cd as int_rat_adj_way_cd
,t1.tenor as t1enor
,t1.distr_org_id as distr_org_id
,t1.temp_store_flg as t1emp_store_flg
,t1.froz_flg as froz_flg
,t1.expos_bal as expos_bal
,t1.turn_crdt_flg as t1urn_crdt_flg
,t1.mode_pay_cd as mode_pay_cd
,t1.level11_cls_cd as level11_cls_cd
,t1.guar_type_cd as guar_type_cd
,t1.crdt_type_cd as crdt_type_cd
,t1.valid_flg as valid_flg
,t1.cont_type_cd as cont_type_cd
,t1.loan_insure_flg as loan_insure_flg
,t1.ic_way_cd as ic_way_cd
,t1.repay_ped_cd as repay_ped_cd
,t1.int_rat_exec_way_cd as int_rat_exec_way_cd
,t1.loan_other_usage_descb as loan_other_usage_descb
,t1.sup_chain_fin_mode_bus_flg as sup_chain_fin_mode_bus_flg
,t1.imp_proj_loan_flg as imp_proj_loan_flg
,t1.surp_indus_cd as surp_indus_cd
,t1.cty_lmt_indus_flg as cty_lmt_indus_flg
,t1.gover_crdt_flg as gover_crdt_flg
,t1.cdb_crdt_flg as cdb_crdt_flg
,t1.fix_asset_crdt_flg as fix_asset_crdt_flg
,t1.discnt_bf_revw_flg as discnt_bf_revw_flg
,t1.pnlt_flg as pnlt_flg
,t1.loan_fin_supt_way_cd as loan_fin_supt_way_cd
,t1.agt_pay_int_flg as agt_pay_int_flg
,t1.negot_int_rat as negot_int_rat
,t1.negot_amt as negot_amt
,t1.loan_distr_status_cd as loan_distr_status_cd
,t1.termnt_cont_rs_rgst_dt as t1ermnt_cont_rs_rgst_dt
,t1.rela_cont_flow_num as rela_cont_flow_num
,t1.lc_amt as lc_amt
,t1.loan_src_cd as loan_src_cd
,t1.cont_invalid_dt as cont_invalid_dt
,t1.backup_effect_flg as backup_effect_flg
,t1.crdt_cont_id as crdt_cont_id
,t1.matn_flg as matn_flg
,t1.risk_type_cd as risk_type_cd
,t1.syn_loan_distr_amt as syn_loan_distr_amt
,t1.actl_fin_ps_id as actl_fin_ps_id
,t1.invest_way_cd as invest_way_cd
,t1.dir_ind_fund_flg as dir_ind_fund_flg
,t1.dir_makti_debt_eqty_flg as dir_makti_debt_eqty_flg
,t1.invo_gover_class_fin_flg as invo_gover_class_fin_flg
,t1.consm_serv_class_fin_flg as consm_serv_class_fin_flg
,t1.stl_dep_flg as stl_dep_flg
,t1.cota_opt_choice_flg as cota_opt_choice_flg
,t1.septbl_flg as septbl_flg
,t1.tran_asset_name as t1ran_asset_name
,t1.crdt_bus_flow_type_cd as crdt_bus_flow_type_cd
,t1.batch_data_src_cd as batch_data_src_cd
,t1.crdt_rg_cd as crdt_rg_cd
,t1.estate_fin_flg as estate_fin_flg
,t1.invo_gover_class_fin_flg1 as invo_gover_class_fin_flg1
,t1.consm_serv_class_fin_flg1 as consm_serv_class_fin_flg1
,t1.br_build_ifin_flg as br_build_ifin_flg
,t1.green_crdt_fin_flg as green_crdt_fin_flg
,t1.onl_bus_flg as onl_bus_flg
,t1.class_crdt_flg as class_crdt_flg
,t1.lmt_use_latest_dt as lmt_use_latest_dt
,t1.lmt_under_bus_latest_exp_dt as lmt_under_bus_latest_exp_dt
,t1.lmt_cont_id as lmt_cont_id
,t1.trade_cont_curr as t1rade_cont_curr
,t1.other_cond_request as other_cond_request
,t1.secd_repay_acct_id as secd_repay_acct_id
,t1.use_prod_cd as use_prod_cd
,t1.discnt_int_buyer_bear_ratio as discnt_int_buyer_bear_ratio
,t1.discnt_int_applit_pay_ratio as discnt_int_applit_pay_ratio
,t1.major_loan_cls_cd as major_loan_cls_cd
,t1.risk_expose_cls as risk_expose_cls
,t1.qual_centr_cntpty_flg as qual_centr_cntpty_flg
,t1.mgmt_mode_cd as mgmt_mode_cd
,t1.tran_market_type_cd as t1ran_market_type_cd
,t1.incre_crdt_way_cd as incre_crdt_way_cd
,t1.bill_uniq_idf as bill_uniq_idf
,t1.is_sup_chain_fin_bus_flg as is_sup_chain_fin_bus_flg
,t1.sup_chain_fin_bus_prod_cls_cd as sup_chain_fin_bus_prod_cls_cd
,t1.unify_repay_day as unify_repay_day
,t1.cntpty_strg as cntpty_strg
,t1.cntpty_co_years as cntpty_co_years
,t1.cntpty_sucs_tran_cnt as cntpty_sucs_tran_cnt
,t1.manu_cont_id as manu_cont_id
,t1.entr_loan_espec_dir_type_cd as entr_loan_espec_dir_type_cd
,t1.estate_loan_type_cd as estate_loan_type_cd
,t1.pente_type_cd as pente_type_cd
,t1.uder_asset_type_cd as uder_asset_type_cd
,t1.underly_prod_cls_flg as underly_prod_cls_flg
,t1.underly_prod_cls_lev_cd as underly_prod_cls_lev_cd
,t1.underly_prod_coll_amt as underly_prod_coll_amt
,t1.create_dt as create_dt 
,t1.update_dt as update_dt 
,t1.id_mark as id_mark 
,t1.job_cd
from ${idl_schema}.agt_loan_cont_info t1 
where etl_dt between to_date('${batch_date}','yyyymmdd')-6 and to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/agt_loan_cont_info_w.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes