: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_icms_business_contract_f
CreateDate: 20240924
FileName:   ${iel_data_path}/icms_business_contract.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.currency as currency
,t1.businesssum as businesssum
,t1.putoutsum as putoutsum
,t1.putoutdate as putoutdate
,t1.baseproduct as baseproduct
,t1.productid as productid
,t1.policyid as policyid
,t1.policyversionid as policyversionid
,t1.productclassify as productclassify
,t1.termmonth as termmonth
,t1.termday as termday
,t1.startdate as startdate
,t1.maturity as maturity
,t1.iscycle as iscycle
,t1.risktype as risktype
,t1.islowrisk as islowrisk
,t1.isremotebusiness as isremotebusiness
,t1.ratemodel as ratemodel
,t1.fixedrate as fixedrate
,t1.baseratetype as baseratetype
,t1.baserate as baserate
,t1.ratefloattype as ratefloattype
,t1.rateadjusttype as rateadjusttype
,t1.floatrange as floatrange
,t1.executerate as executerate
,t1.vouchtype as vouchtype
,t1.haveadditionalvouch as haveadditionalvouch
,t1.othervouchtype as othervouchtype
,t1.additioncommand as additioncommand
,t1.repaytype as repaytype
,t1.repaycycle as repaycycle
,t1.repaydate as repaydate
,t1.settlementaccount as settlementaccount
,t1.paymenttype as paymenttype
,t1.creditinvest as creditinvest
,t1.nationalindustrytype as nationalindustrytype
,t1.intraindustrytype as intraindustrytype
,t1.purpose as purpose
,t1.reservesum as reservesum
,t1.balance as balance
,t1.normalbalance as normalbalance
,t1.overduebalance as overduebalance
,t1.dullbalance as dullbalance
,t1.badbalance as badbalance
,t1.innerinterestbalance as innerinterestbalance
,t1.outerinterestbalance as outerinterestbalance
,t1.capitalpenaltybalance as capitalpenaltybalance
,t1.interestpenaltybalance as interestpenaltybalance
,t1.overduedays as overduedays
,t1.owninterestdays as owninterestdays
,t1.graceperiod as graceperiod
,t1.cancelsum as cancelsum
,t1.cancelinterest as cancelinterest
,t1.predictlostsum as predictlostsum
,t1.reducereservesum as reducereservesum
,t1.badconfirmdate as badconfirmdate
,t1.classifyresult as classifyresult
,t1.classifydate as classifydate
,t1.status as status
,t1.finishdate as finishdate
,t1.finishtype as finishtype
,t1.finishflag as finishflag
,t1.contracttype as contracttype
,t1.offsheetflag as offsheetflag
,t1.belongdept as belongdept
,t1.completeflag as completeflag
,t1.flowtype as flowtype
,t1.approvestatus as approvestatus
,t1.clno as clno
,t1.cleffectstatus as cleffectstatus
,t1.remark as remark
,t1.operateuserid as operateuserid
,t1.operateorgid as operateorgid
,t1.operatedate as operatedate
,t1.inputuserid as inputuserid
,t1.inputorgid as inputorgid
,t1.inputdate as inputdate
,t1.updateuserid as updateuserid
,t1.updateorgid as updateorgid
,t1.updatedate as updatedate
,t1.reinforceflag as reinforceflag
,t1.corporgid as corporgid
,t1.payfrequencyunit as payfrequencyunit
,t1.payfrequency as payfrequency
,t1.renewtermdate as renewtermdate
,t1.renewtotalsum as renewtotalsum
,t1.renewexecuteyearrate as renewexecuteyearrate
,t1.isbankrel as isbankrel
,t1.vouchtype3 as vouchtype3
,t1.vouchtype2 as vouchtype2
,t1.loanusetype as loanusetype
,t1.totalsum as totalsum
,t1.outstndlmt as outstndlmt
,t1.bailratio as bailratio
,t1.bailsum as bailsum
,t1.totalbalance as totalbalance
,t1.creditaggreement as creditaggreement
,t1.vouchtypeinner as vouchtypeinner
,t1.executemonthrate as executemonthrate
,t1.classifyresulteleven as classifyresulteleven
,t1.oldcreditaggreement as oldcreditaggreement
,t1.pigeonholedate as pigeonholedate
,t1.freezeflag as freezeflag
,t1.rateadjustfrequency as rateadjustfrequency
,t1.overduerate as overduerate
,t1.overdueratefloattype as overdueratefloattype
,t1.overdueratefloatvalue as overdueratefloatvalue
,t1.putoutorgid as putoutorgid
,t1.settlementaccountname as settlementaccountname
,t1.loanaccountno as loanaccountno
,t1.loanaccountname as loanaccountname
,t1.loanaccountorgid as loanaccountorgid
,t1.serialno as serialno
,t1.bapserialno as bapserialno
,t1.relacontractno as relacontractno
,t1.artificialno as artificialno
,t1.customerid as customerid
,t1.customername as customername
,t1.businessflag as businessflag
,t1.oldcontractno as oldcontractno
,t1.applytype as applytype
,t1.occurtype as occurtype
,t1.occurdate as occurdate
,t1.start_dt as start_dt
,t1.end_dt as end_dt
,t1.id_mark as id_mark
,t1.remart as remart
,t1.bailcurrency as bailcurrency
,t1.authostrdate as authostrdate
,t1.creditauthno as creditauthno
,t1.migtflag as migtflag
,t1.bailaccount as bailaccount
,t1.occupycreditbapserialno as occupycreditbapserialno
,t1.bailtransaccount as bailtransaccount
,t1.occupycredittype as occupycredittype
,t1.ispagercontract as ispagercontract
,t1.manageuserid as manageuserid
,t1.manageorgid as manageorgid
,t1.isquerycreditreport as isquerycreditreport
,t1.isoccupycredit as isoccupycredit
,t1.oldstatus as oldstatus
,t1.isonlinebusiness as isonlinebusiness
,t1.migtoldvalue as migtoldvalue
,t1.contractnobeforeextend as contractnobeforeextend
,t1.pdgratio as pdgratio
,t1.pdgsum as pdgsum
,t1.templeteurl as templeteurl
,t1.templeteno as templeteno
,t1.migtcustomerid as migtcustomerid
,t1.migtbusinesstype as migtbusinesstype
,t1.vouchflag as vouchflag
,t1.ratefloatratioorbp as ratefloatratioorbp
,t1.issignedcontract as issignedcontract
,t1.useexposuretype as useexposuretype

from ${idl_schema}.icms_business_contract t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/icms_business_contract.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
