: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_ncbs_rb_restraints_hist_f
CreateDate: 20221111
FileName:   ${iel_data_path}/ncbs_rb_restraints_hist.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,BASE_ACCT_NO
,CLIENT_NO
,INTERNAL_KEY
,REFERENCE
,RESTRAINT_TYPE
,USER_ID
,TERM
,TERM_TYPE
,CHANNEL_SEQ_NO
,COMPANY
,HELP_OPTION
,INIT_SEQ_NO
,IS_FROZEN
,LAST_STATUS
,MAIN_FLAG
,NARRATIVE
,RELEASE_LAW_NO
,RES_ACCT_RANGE
,RES_LAW_NO
,RES_PRIORITY
,RES_SEQ_NO
,RESTRAINT_JUDICIARY_NAME
,RESTRAINTS_STATUS
,SEQ_NO
,SOURCE_TYPE
,SUB_RESTRAINT_CLASS
,SYSTEM_PHASE
,THAW_OFFICER_NAME
,THAW_OTH_OFFICER_NAME
,UNDER_LIEN
,APPROVAL_DATE
,END_DATE
,LAST_CHANGE_DATE
,START_DATE
,TRAN_TIMESTAMP
,AUTH_USER_ID
,DEDUCTION_JUDICIARY_NAME
,JUDICIARY_DOCUMENT_ID
,JUDICIARY_DOCUMENT_ID2
,JUDICIARY_DOCUMENT_TYPE
,JUDICIARY_DOCUMENT_TYPE2
,JUDICIARY_OFFICER_NAME
,JUDICIARY_OTH_DOCUMENT_ID
,JUDICIARY_OTH_DOCUMENT_ID2
,JUDICIARY_OTH_DOCUMENT_TYPE
,JUDICIARY_OTH_DOCUMENT_TYPE2
,JUDICIARY_OTH_OFFICER_NAME
,LAST_CHANGE_USER_ID
,PLEDGED_AMT
,RELEASE_JUDICIARY_NAME
,THAW_DOCUMENT_ID
,THAW_DOCUMENT_ID2
,THAW_DOCUMENT_TYPE
,THAW_OTH_DOCUMENT_ID
,THAW_OTH_DOCUMENT_ID2
,THAW_OTH_DOCUMENT_TYPE
,THAW_OTH_DOCUMENT_TYPE2
,TRAN_BRANCH
,THAW_DOCUMENT_TYPE2
,RESERVE
,REACCOUNT_CD
,START_DT
,END_DT
,ID_MARK


from ${iol_schema}.ncbs_rb_restraints_hist t1
where start_dt <= to_date('${batch_date}','yyyymmdd') and end_dt >to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/ncbs_rb_restraints_hist.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
