: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_rcrs_pvp_loan_app_f
CreateDate: 20180529
FileName:   ${iel_data_path}/rcrs_pvp_loan_app.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select  
t.etl_dt
,t.serno
,t.prd_pk
,t.biz_type
,t.prd_name
,t.prd_type
,t.app_form
,t.cont_no
,t.bill_no
,t.funds_src
,t.account_class
,t.credit_class
,t.assure_class
,t.pledge_class
,t.impawn_class
,t.cus_id
,t.cus_name
,t.cur_type
,t.con_amount
,t.avail_amt
,t.loan_amount
,t.loan_start_date
,t.loan_end_date
,t.ruling_ir
,t.floating_rate
,t.reality_ir_y
,t.overdue_rate
,t.overdue_ir
,t.default_rate
,t.default_ir
,t.ci_rate
,t.ci_ir
,t.assure_means_main
,t.assure_means2
,t.assure_means3
,t.enter_account
,t.enter_account_name
,t.repayment_account
,t.repayment_acc_name
,t.mortgage_flg
,t.repayment_mode
,t.interest_acc_mode
,t.ir_adjust_mode
,t.delay_deduct_type
,t.loan_direction
,t.direction_name
,t.loan_form
,t.loan_nature
,t.loan_kind_ca
,t.biz_type_sub
,t.loan_use_type
,t.loan_type_ext
,t.delay_days
,t.discont_ind
,t.discont_id
,t.discont_type
,t.discont_acc
,t.discont_acc_name
,t.discount_rate
,t.discount_amount
,t.discont_acc2
,t.discont_acc_name2
,t.discount_rate2
,t.discount_amount2
,t.discont_acc3
,t.discont_acc_name3
,t.discount_rate3
,t.discount_amount3
,t.ass_acc
,t.ass_acc_name
,t.ass_sec_acc
,t.ass_sec_acc_name
,t.limit_ind
,t.pay_way
,t.benifit_acc
,t.benifit_amount
,t.benifit_bank_id
,t.benifit_bank
,t.benifit_name
,t.transfer_amount
,t.cash_amount
,t.proc_fee_amount
,t.transfer_dec
,t.chargeoff_ind
,t.chargeoff_dec
,t.dd_workflow_id
,t.approve_status
,t.input_id
,t.examinant_id
,t.investigator_id
,t.cus_manager
,t.apply_date
,t.input_date
,t.input_br_id
,t.investigator_br_id
,t.fina_br_id
,t.main_br_id
,t.own_system
,t.chargeoff_status
,t.src_account
,t.src_account_name
,t.biz_type_detail
,t.ir_exe_type
,t.int_rate_type
,t.int_rate_inc_opt
,t.int_rate_inc
,t.fixed_rate
,t.prd_userdf_name
,t.prd_userdf_type
,t.return_date
,t.chargeoff_manage
,t.consign_fund_protocol_no
,t.ispaf
,t.distribution_day
,t.money_origin_id
,t.overdue_type
,t.default_type
,t.ass_sec_acc_bal
,t.ass_sec_amt
,t.ass_sec_dep_date
,t.repayment_account1
,t.repayment_acc_name1
,t.cus_area
,t.loan_card_ind
,t.agriculture_type
,t.agriculture_use
,t.minor_entrp_range
,t.government_ind
,t.government_org_attribute
,t.government_platform
,t.ass_sec_ind
,t.guarantora_grp_ind
,t.loan_fund_whither
,t.interest_date
,t.cn_cont_no
,t.syndicated_proxy_id
,t.sec_money_ac
,t.sec_money_ac_name
,t.sec_money_init
,t.sec_money_rate
,t.freeze_no
,t.freeze_name
,t.freeze_amt
,t.farm_card_type
,t.check_finger
,t.loan_term
,t.term_time_type
,t.due_day
,t.pay_distance
,t.old_bill_no
,t.is_risk
,t.invst_concl
,t.security_money_ind_zy
,t.security_money_ac_no_zy
,t.security_money_child_acc_no_zy
,t.security_money_amt_zy
,t.security_money_ac_name_zy
,t.adv_rpay_flg
,t.made_rpay_plan
,t.enter_account_type
,t.repayment_account_type
,t.businum
,t.trade_serno
,t.repayment_date_confirm
,t.auth_review
,t.is_cl
,t.is_loan_anytime
,t.is_balloon
,t.last_term_amount
,t.last_term_percent
,t.tax_amount
,t.tax_account
,t.tax_account_name
,t.tax_account_type
,t.is_record_tax
,t.rate_type
,t.loan_rel_date
,t.start_dt
,t.end_dt
,t.id_mark
from  idl.rcrs_pvp_loan_app t
where start_dt <= to_date('${batch_date}','yyyymmdd')
 and end_dt > to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/rcrs_pvp_loan_app.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes