: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_hdws_mpcs_a68tszfstrx_i
CreateDate: 20180529
FileName:   ${iel_data_path}/hdws_mpcs_a68tszfstrx.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
 t1.mainseq
,t1.transdt
,t1.businesstrace
,t1.pckno
,t1.txtpcd
,t1.txcd
,t1.txid
,t1.cnsdt
,t1.instgpty
,t1.pkgbusinesstrace
,t1.pksqno
,t1.hosttrcd
,t1.fronttrcd
,t1.hostdate
,t1.hostnbr
,t1.crcycd
,t1.transamt
,t1.dbtrid
,t1.sndbrnname
,t1.cdtrid
,t1.rcvbrnname
,t1.payopenbank
,t1.payopenbanknm
,t1.payacct
,t1.payname
,t1.payaddr
,t1.rcvopenbank
,t1.rcvopenbanknm
,t1.rcvacct
,t1.rcvname
,t1.rcvaddr
,t1.orgnltxtpcd
,t1.orgnlcnsdt
,t1.orgnltxid
,t1.orgnlinstgpty
,t1.orgnlpkgbustrace
,t1.netgrnd
,t1.netgdt
,t1.transt
,t1.iotype
,t1.flag4
,t1.magebrn
,t1.oprtlr
,t1.chktlr
,t1.sndtlr
,t1.auttlr
,t1.oprbrn
,t1.sendbranch
,t1.autbrn
,t1.caclrs
,t1.processcode
,t1.rspncd
,t1.rspninf
,t1.rtncd
,t1.rtninf
,t1.rtrltd
,t1.diskno
,t1.clerdt
,t1.bperno
,t1.bpermg
,t1.levels
,t1.recdes
,t1.chksta
,t1.remark
,t1.prtcnt
,t1.transmitdt
,t1.feeflag
,t1.inoutflag
,t1.sacact
,t1.sacana
,t1.clendt
,t1.clenus
,t1.clrbrn
,t1.edhtno
,t1.edhtdt
,t1.endtlr
,t1.prdnbr
,t1.bookcd
,t1.cobkdt
,t1.booknbr
,t1.idtype
,t1.idno
,t1.transq
,t1.sdtrsq
,t1.paymod
,t1.opnwin
,t1.feamt1
,t1.feamt2
,t1.feamt3
,t1.calfee
,t1.chngti
,t1.rcdsta
,t1.prodcd
,t1.isinout
,t1.inacct
,t1.inname
,t1.landdealsts
,t1.checkdealsts
,t1.appenddatatable
,t1.appenddatadtltab
,t1.hangupreason
,t1.modifytlr
,t1.feetype
,t1.areacd
,t1.acctchckflg
,t1.servmode
,t1.realtmcdtflg
,t1.chflag
,t1.protocolnb
,t1.resndflg
,t1.bllind
,t1.blltp
,t1.billnb
,t1.channeldt
,t1.tranflowno
,t1.orgnlpksqno
,t1.corprtnid
,t1.pmtitmcd
,t1.pmtitmnm
,t1.billamount
,t1.feeamount
,t1.info2
,t1.od_flag
,t1.od_ovtranam
,t1.toaccountflag
,t1.autoflag
,t1.autocount
,t1.automsg
,t1.bindacct
,t1.bindacctnm
,t1.eflag
,t1.upporderid
,t1.intoaccounttype
,t1.accttype
,t1.bindacctopnbrn
,t1.branchid
,t1.tacctp
,t1.handleflag
,t1.custno
,t1.pmtid
from ${idl_schema}.hdws_mpcs_a68tszfstrx t1 
where etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/hdws_mpcs_a68tszfstrx.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes