: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_odss_ind_info_f
CreateDate: 20180529
FileName:   ${iel_data_path}/odss_ind_info_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select customerid
   ,fullname
   ,sex
   ,birthday
   ,certtype
   ,certid
   ,sino
   ,country
   ,nationality
   ,nativeplace
   ,politicalface
   ,marriage
   ,relativetype
   ,familyadd
   ,familyzip
   ,emailadd
   ,familytel
   ,mobiletelephone
   ,unitkind
   ,workcorp
   ,workadd
   ,worktel
   ,occupation
   ,position
   ,employrecord
   ,edurecord
   ,eduexperience
   ,edudegree
   ,graduateyear
   ,financebelong
   ,creditlevel
   ,evaluatedate
   ,balancesheet
   ,intro
   ,selfmonthincome
   ,familymonthincome
   ,incomesource
   ,population
   ,loancardno
   ,loancardinsyear
   ,farmersort
   ,regionalism
   ,staff
   ,creditfarmer
   ,riskinclination
   ,character
   ,dataquality
   ,inputorgid
   ,inputuserid
   ,inputdate
   ,updatedate
   ,remark
   ,updateorgid
   ,updateuserid
   ,commadd
   ,commzip
   ,nativeadd
   ,workzip
   ,headship
   ,workbegindate
   ,yearincome
   ,payaccount
   ,payaccountbank
   ,familystatus
   ,tempsaveflag
   ,certid18
   ,nativenature
   ,housevalue
   ,freecarcondition
   ,familyyearincomepercapita
   ,monthincome
   ,supportpopulations
   ,children
   ,currentworkyears
   ,age
   ,familytotalassets
   ,familytotalliabilities
   ,billstyle
   ,emergencycontact
   ,emergencycontactaddress
   ,emergencycontactmobilephone
   ,localcontract
   ,localcontractaddress
   ,localcontracttelephone
   ,localcontractmobilephone
   ,currentindustryworkyears
   ,workyears
   ,registeredcapital
   ,managementscope
   ,managementtype
   ,managementplace
   ,enterpriseyearincome
   ,enterpriseadd
   ,newcustomertype
   ,otherincome
   ,rentincome
   ,convertincome
   ,salaryincome
   ,takingsmonthly
   ,profitmarginmonthly
   ,stocklot
   ,debtmonthly
   ,housearea
   ,corparea
   ,cheatcheckresult
   ,lmcredittype
   ,isrelatedparty
   ,socialinsuranceflag
   ,localhouseflag
   ,localyear
   ,monthcashout
   ,corpextension
   ,corpzone
   ,department
   ,regioncodename
   ,firsttel
   ,housezone
   ,custen
   ,custtp
   ,isblak
   ,custst
   ,psrntg
   ,ntlycd
   ,rgstad
   ,lncdno
   ,lncdpw
   ,lncdtg
   ,ispart
   ,mainfg
   ,idtfst
   ,contna
   ,cmainf
   ,othrtl
   ,mailad
   ,mfcustomerid
   ,businessentityid
   ,businessentityname
   ,businessentityshinfo
   ,finalevaluatedate
   ,customermemberlevel
   ,ownertype
from ${idl_schema}.odss_ind_info
where etl_dt = TO_DATE('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/odss_ind_info_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes