: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_odss_daily_balance_i
CreateDate: 20180529
FileName:   ${iel_data_path}/odss_daily_balance_${batch_date}_i.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select LEDGER_NAME
,TRANSACTION_DATE
,PERIOD_NAME
,CODE_COMBINATION_ID
,CORE_CURRENCY_CODE
,CURRENCY_CODE
,TEMPLATE_ID
,CORE_COMPANY
,SEGMENT1
,SEGMENT2
,SEGMENT3
,SEGMENT4
,SEGMENT5
,SEGMENT6
,SEGMENT7
,SEGMENT8
,SEGMENT9
,YOD_BALANCE_DR
,YOD_BALANCE_CR
,YOD_FUN_BALANCE_DR
,YOD_FUN_BALANCE_CR
,YOD_USD_BALANCE_DR
,YOD_USD_BALANCE_CR
,YOD_REP_BALANCE_DR
,YOD_REP_BALANCE_CR
,YOD_REP_FUN_BALANCE_DR
,YOD_REP_FUN_BALANCE_CR
,YOD_REP_USD_BALANCE_DR
,YOD_REP_USD_BALANCE_CR
,DTD_BALANCE_DR
,DTD_BALANCE_CR
,DTD_FUN_BALANCE_DR
,DTD_FUN_BALANCE_CR
,DTD_USD_BALANCE_DR
,DTD_USD_BALANCE_CR
,EOD_BALANCE_DR
,EOD_BALANCE_CR
,EOD_FUN_BALANCE_DR
,EOD_FUN_BALANCE_CR
,EOD_USD_BALANCE_DR
,EOD_USD_BALANCE_CR
,EOD_REP_BALANCE_DR
,EOD_REP_BALANCE_CR
,EOD_REP_FUN_BALANCE_DR
,EOD_REP_FUN_BALANCE_CR
,EOD_REP_USD_BALANCE_DR
,EOD_REP_USD_BALANCE_CR
,TEN_DAYS_BEGIN_DR
,TEN_DAYS_BEGIN_CR
,TEN_DAYS_BEGIN_FUN_DR
,TEN_DAYS_BEGIN_FUN_CR
,TEN_DAYS_BEGIN_USD_DR
,TEN_DAYS_BEGIN_USD_CR
,MONTH_BEGIN_DR
,MONTH_BEGIN_CR
,MONTH_BEGIN_FUN_DR
,MONTH_BEGIN_FUN_CR
,MONTH_BEGIN_USD_DR
,MONTH_BEGIN_USD_CR
,QUARTER_BEGIN_DR
,QUARTER_BEGIN_CR
,QUARTER_BEGIN_FUN_DR
,QUARTER_BEGIN_FUN_CR
,QUARTER_BEGIN_USD_DR
,QUARTER_BEGIN_USD_CR
,HALF_YEAR_BEGIN_DR
,HALF_YEAR_BEGIN_CR
,HALF_YEAR_BEGIN_FUN_DR
,HALF_YEAR_BEGIN_FUN_CR
,HALF_YEAR_BEGIN_USD_DR
,HALF_YEAR_BEGIN_USD_CR
,YEAR_BEGIN_DR
,YEAR_BEGIN_CR
,YEAR_BEGIN_FUN_DR
,YEAR_BEGIN_FUN_CR
,YEAR_BEGIN_USD_DR
,YEAR_BEGIN_USD_CR
,MONTH_REP_BEGIN_DR
,MONTH_REP_BEGIN_CR
,MONTH_REP_BEGIN_FUN_DR
,MONTH_REP_BEGIN_FUN_CR
,MONTH_REP_BEGIN_USD_DR
,MONTH_REP_BEGIN_USD_CR
,QUARTER_REP_BEGIN_DR
,QUARTER_REP_BEGIN_CR
,QUARTER_REP_BEGIN_FUN_DR
,QUARTER_REP_BEGIN_FUN_CR
,QUARTER_REP_BEGIN_USD_DR
,QUARTER_REP_BEGIN_USD_CR
,HALF_REP_YEAR_BEGIN_DR
,HALF_REP_YEAR_BEGIN_CR
,HALF_REP_YEAR_BEGIN_FUN_DR
,HALF_REP_YEAR_BEGIN_FUN_CR
,HALF_REP_YEAR_BEGIN_USD_DR
,HALF_REP_YEAR_BEGIN_USD_CR
,YEAR_REP_BEGIN_DR
,YEAR_REP_BEGIN_CR
,YEAR_REP_BEGIN_FUN_DR
,YEAR_REP_BEGIN_FUN_CR
,YEAR_REP_BEGIN_USD_DR
,YEAR_REP_BEGIN_USD_CR
,MTM_BALANCE_DR
,MTM_BALANCE_CR
,MTM_FUN_BALANCE_DR
,MTM_FUN_BALANCE_CR
,MTM_USD_BALANCE_DR
,MTM_USD_BALANCE_CR
,QTQ_BALANCE_DR
,QTQ_BALANCE_CR
,QTQ_FUN_BALANCE_DR
,QTQ_FUN_BALANCE_CR
,QTQ_USD_BALANCE_DR
,QTQ_USD_BALANCE_CR
,HTH_BALANCE_DR
,HTH_BALANCE_CR
,HTH_FUN_BALANCE_DR
,HTH_FUN_BALANCE_CR
,HTH_USD_BALANCE_DR
,HTH_USD_BALANCE_CR
,YTY_BALANCE_DR
,YTY_BALANCE_CR
,YTY_FUN_BALANCE_DR
,YTY_FUN_BALANCE_CR
,YTY_USD_BALANCE_DR
,YTY_USD_BALANCE_CR
from ${idl_schema}.ODSS_DAILY_BALANCE
where etl_dt=to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/odss_daily_balance_${batch_date}_i.dat" \
        charset=zhs16gbk
        safe=yes