: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_cmm_retl_loan_acct_info_i_w
CreateDate: 20180529
FileName:   ${iel_data_path}/cmm_retl_loan_acct_info_w.i.${batch_date}.dat
IF_mark:    i_w
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
to_date('${batch_date}','yyyymmdd') as etl_dt
,t.lp_id
,t.acct_id
,t.acct_name
,t.cust_id
,t.cont_id
,t.dubil_num
,t.loan_distr_acct_num
,t.loan_repay_num
,t.std_prod_id
,t.prod_id
,t.subj_id
,t.init_pric_subj_id
,t.in_bs_int_subj_id
,t.off_bs_int_subj_id
,t.int_income_subj_id
,t.int_income_adj_subj_id
,t.acctnt_cate_cd
,t.bus_breed_id
,t.asset_thd_cls_cd
,t.loan_modal_cd
,t.loan_acct_status_cd
,t.unite_loan_cd
,t.priv_loan_flg
,t.promis_loan_flg
,t.circl_loan_flg
,t.deriv_loan_flg
,t.agent_loan_flg
,t.oots_accti_flg
,t.loan_modal_dg_subj_accti_flg
,t.loan_tenor
,t.loan_tenor_type_cd
,t.acru_non_acru_cd
,t.final_fin_dt
,t.open_acct_teller_id
,t.clos_acct_teller_id
,t.open_acct_org_id
,t.mgmt_org_id
,t.acct_instit_id
,t.open_acct_dt
,t.distr_dt
,t.value_dt
,t.exp_dt
,t.clos_acct_dt
,t.int_sub_flg
,t.renew_flg
,t.renew_cnt
,t.int_accr_rule
,t.int_accr_flg
,t.comp_int_flg
,t.pre_recv_int_way
,t.int_rat_adj_way_cd
,t.int_rat_base_type_cd
,t.base_rat_id
,t.base_rat
,t.exec_int_rat
,t.int_rat_float_way_cd
,t.int_rat_adj_ped_corp_cd
,t.int_rat_adj_ped_freq
,t.int_rat_flo_val
,t.curr_int_rat_effect_dt
,t.next_int_rat_adj_dt
,t.int_set_way_cd
,t.int_accr_way_cd
,t.ped_distr_flg
,t.distr_way_cd
,t.repay_way_cd
,t.repay_ped_corp_cd
,t.repay_ped
,t.allow_adv_repay_flg
,t.wrt_off_flg
,t.asset_tran_status_cd
,t.tran_bf_int_recvbl
,t.ovdue_flg
,t.ovdue_int_accr_way_cd
,t.ovdue_pnlt_float_way_cd
,t.pric_ovdue_flg
,t.int_ovdue_flg
,t.curr_ovdue_perds
,t.pric_ovdue_days
,t.int_ovdue_days
,t.ovdue_pric_bal
,t.ovdue_int_amt
,t.ovdue_comp_int_amt
,t.fir_ovdue_dt
,t.ovdue_int_rat
,t.ovdue_int_rat_flo_val
,t.tot_perds
,t.curr_issue_perds
,t.last_repay_dt
,t.curr_cd
,t.next_repay_dt
,t.next_rpp_amt
,t.next_repay_int_amt
,t.cont_amt
,t.dubil_amt
,t.distr_amt
,t.froz_distrd_amt
,t.distrd_amt
,t.td_acru_int
,t.td_int_income
,t.td_int_income_adj
,t.currt_acru_int
,t.nomal_pric
,t.ovdue_pric
,t.idle_pric
,t.bad_debt_pric
,t.loan_fund
,t.recvbl_acru_int
,t.coll_acru_int
,t.recvbl_acru_pnlt
,t.coll_acru_pnlt
,t.recvbl_pnlt
,t.coll_pnlt
,t.acru_comp_int
,t.recvbl_comp_int
,t.acru_int_sub
,t.recvbl_int_sub
,t.amorted_int
,t.wrt_off_pric
,t.wrt_off_int
,t.int_income
,t.wrt_off_advc_fee_bal
,t.wrt_off_advc_fee_amt
,t.recvbl_fine
,t.fine_inco
,t.resv
,t.recvbl_over_int
,t.coll_over_int
,t.in_bs_int
,t.off_bs_int
,t.acm_recvbl_uncol_int_amt
,t.repaid_pric
,t.repaid_int
,t.repaid_pnlt
,t.repaid_comp_int
,t.repaid_fee
,t.pric_bal
,t.currt_bal
,t.cl_curr_currt_bal
,t.ear_d_bal
,t.ear_m_bal
,t.ear_s_bal
,t.ear_y_bal
,t.y_acm_bal
,t.s_acm_bal
,t.m_acm_bal
,t.cl_curr_ear_d_bal
,t.cl_curr_ear_m_bal
,t.cl_curr_ear_s_bal
,t.cl_curr_ear_y_bal
,t.cl_curr_y_acm_bal
,t.cl_curr_ear_d_y_acm_bal
,t.cl_curr_ear_m_y_acm_bal
,t.cl_curr_ear_s_y_acm_bal
,t.cl_curr_ear_y_y_acm_bal
,t.cl_curr_s_acm_bal
,t.cl_curr_ear_d_s_acm_bal
,t.cl_curr_ear_s_s_acm_bal
,t.cl_curr_ear_y_s_acm_bal
,t.cl_curr_m_acm_bal
,t.cl_curr_ear_d_m_acm_bal
,t.cl_curr_ear_m_m_acm_bal
,t.cl_curr_ear_y_m_acm_bal
,t.y_avg_bal
,t.q_avg_bal
,t.m_avg_bal
,t.cl_curr_y_avg_bal
,t.cl_curr_q_avg_bal
,t.cl_curr_m_avg_bal
from ${idl_schema}.cmm_retl_loan_acct_info t
where etl_dt = to_date('${batch_date}','yyyymmdd')  ; " \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/cmm_retl_loan_acct_info_w.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes