: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_ibms_ttrd_otc_trade_f
CreateDate: 20180529
FileName:   ${iel_data_path}/ibms_ttrd_otc_trade.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
sysordid
,orddate
,ordtime
,condate
,contime
,insid
,intordid
,extordid
,custordid
,extbizid
,operator
,trdtype
,cash_ext_accid
,cash_accid
,secu_ext_accid
,secu_accid
,partyid
,cp_cash_accid
,cp_secu_accid
,i_code
,a_type
,m_type
,i_name
,ordcount
,ordprice
,ordamount
,trdfee
,setfee
,setdays
,setdate
,thenmktprice
,thenmktprice_u
,ordstatus
,errcode
,errinfo
,bnd_settype
,bnd_netprice
,bnd_aiamount
,remark
,reservetype
,cp_reservetype
,reservechg
,cp_reservechg
,reservevalue
,cp_reservevalue
,resolve
,trade_grp_id
,ref_orddate
,ref_sysordid
,ignore_flag
,exe_market
,trader
,trader_cp
,dealtype
,agreenumber
,eval_netprice
,ordsource
,deal_count
,deal_avg_netprice
,deal_netamount
,deal_aiamount
,deal_amount
,bidaskid
,relatedparty
,terminate_amount
,setdate_terminate
,agreementtype
,partynametempority
,party_zzdaccname
,seatno_cp
,executor
,union_sysordid
,party_zzdacccode
,party_bank_code
,party_acct_code
,party_bank_name
,party_acct_name
,dis_fee_kind_follow
,dis_fee_kind
,grpid_sub
,imp_time
,eval_ytm
,bnd_ytm
,update_time
,due_ai
,operator_id
,executor_id
,due_cp
,real_ai
,real_cp
,real_fee
,due_fee
,ref_type
,is_remain
,trader_id
,trademodel
,settlemodel
,ord_id
,insstatus
,entrust_ref_id
,close_trade_id
,ftprate
,conn_ordid
,two_effective_contract
,source_type
,settlestate
,navdate
,qcurr_cash_ext_accid
,qcurr_party_bank_code
,qcurr_party_bank_name
,qcurr_party_acct_code
,qcurr_party_acct_name
,party_mid_bank_acct_code
,party_mid_bank_name
,party_mid_swift_code
,qcurr_party_mid_bank_acct_code
,qcurr_party_mid_bank_name
,qcurr_party_mid_swift_code
,party_swift_code
,qcurr_party_swift_code
,spv_id
,his_tradeflag
,his_ref_tradeid
,his_trade_setdate
,party_pset
,party_pset_country
,party_agent_code_type
,party_agent_code_dss
,party_agent_code
,party_agent_account
,party_code_type
,party_code_dss
,party_code
,party_account
,si_id
,party_i_bank_code
,party_i_swift_code
,split_inst_type
,cm_attr_parent
,cm_attr_master
,cm_attr_merge
,cm_attr_mirror
,cm_attr_relation
,cal_start_date
,cal_end_date
,strike_ytm
,settlement_type
,aio_acct_no
,acct_type
,user_name
,contractparty
,marketing_manager_id
,marketing_org_id
,com_date
,party_branch
,max_val
,min_val
,collection_fst_fee
,transfer_type
,secu_setdate
,csdc_netprice
,ccdc_netprice
,shch_netprice
,se_netprice
,ctrct_id
,platform
,invest_direction
,contractversion
,final_invest
,associatednumber
,fiveclass
,prod_nature
,trd_acc_code
,store_code
,quote_type
,unit_id
,curcount
,can_div_amount
,is_remain_due_ai
,is_impair
,option_group
,entry_date
,party_pset_name
,relate_invest
,settlement_place
,trdfee_notset
,daycounter
,remain_due_cp
,include_inte
,exh_extordid
,exrcise_state
,sppiresult
,sppiclass
,mergeno
,resource_id
,party_relevance_info
,full_flag
,brokerage_id
,brokerage_fee_info
,released_credit_line
,out_range
,interest_out
,book
,xcc_trade_grp_id
,xcc_pre_sysordid
,to_date('${batch_date}','yyyymmdd') as etl_dt
,etl_timestamp
from idl.ibms_ttrd_otc_trade
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/ibms_ttrd_otc_trade.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes