: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_oass_crss_ind_info_i_w
CreateDate: 20180529
FileName:   ${iel_data_path}/oass_crss_ind_info_w.i.${batch_date}.dat
IF_mark:    i_w
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
t.customerid
,t.fullname
,t.sex
,t.birthday
,t.certtype
,t.certid
,t.sino
,t.country
,t.nationality
,t.nativeplace
,t.politicalface
,t.marriage
,t.relativetype
,t.familyadd
,t.familyzip
,t.emailadd
,t.familytel
,t.mobiletelephone
,t.unitkind
,t.workcorp
,t.workadd
,t.worktel
,t.occupation
,t.position
,t.employrecord
,t.edurecord
,t.eduexperience
,t.edudegree
,t.graduateyear
,t.financebelong
,t.creditlevel
,t.evaluatedate
,t.balancesheet
,t.intro
,t.selfmonthincome
,t.familymonthincome
,t.incomesource
,t.population
,t.loancardno
,t.loancardinsyear
,t.farmersort
,t.regionalism
,t.staff
,t.creditfarmer
,t.riskinclination
,t.character
,t.dataquality
,t.inputorgid
,t.inputuserid
,t.inputdate
,t.updatedate
,t.remark
,t.updateorgid
,t.updateuserid
,t.commadd
,t.commzip
,t.nativeadd
,t.workzip
,t.headship
,t.workbegindate
,t.yearincome
,t.payaccount
,t.payaccountbank
,t.familystatus
,t.tempsaveflag
,t.certid18
,t.nativenature
,t.housevalue
,t.freecarcondition
,t.familyyearincomepercapita
,t.monthincome
,t.supportpopulations
,t.children
,t.currentworkyears
,t.age
,t.familytotalassets
,t.familytotalliabilities
,t.billstyle
,t.emergencycontact
,t.emergencycontactaddress
,t.emergencycontactmobilephone
,t.localcontract
,t.localcontractaddress
,t.localcontracttelephone
,t.localcontractmobilephone
,t.currentindustryworkyears
,t.workyears
,t.registeredcapital
,t.managementscope
,t.managementtype
,t.managementplace
,t.enterpriseyearincome
,t.enterpriseadd
,t.newcustomertype
,t.otherincome
,t.rentincome
,t.convertincome
,t.salaryincome
,t.takingsmonthly
,t.profitmarginmonthly
,t.stocklot
,t.debtmonthly
,t.housearea
,t.corparea
,t.cheatcheckresult
,t.lmcredittype
,t.isrelatedparty
,t.socialinsuranceflag
,t.localhouseflag
,t.localyear
,t.monthcashout
,t.corpextension
,t.corpzone
,t.department
,t.regioncodename
,t.firsttel
,t.housezone
,t.custen
,t.custtp
,t.isblak
,t.custst
,t.psrntg
,t.ntlycd
,t.rgstad
,t.lncdno
,t.lncdpw
,t.lncdtg
,t.ispart
,t.mainfg
,t.idtfst
,t.contna
,t.cmainf
,t.othrtl
,t.mailad
,t.mfcustomerid
,t.businessentityid
,t.businessentityname
,t.businessentityshinfo
,t.finalevaluatedate
,t.customermemberlevel
,t.isrelative
,t.ownertype
,t.iscountryhousehold
,t.worknature
,t.posionlevel
,t.employeetype
,t.industryage
,t.regioncode
,t.firstemail
,t.bqueryresult
,t.risktype
,t.jobtype
,t.corptradeflag
,t.corpregisterdate
,t.registerfinancing
,t.preyeardpf
,t.incomeremark
,t.debtflag
,t.debtmonthlyremark
,t.bpcreditlevel
,t.creditremark
,t.consistentflag
,t.realtycontractcount
,t.bankrelativeflag
,t.creditresult
,t.alipayaccount
,t.jdaccount
,t.remark2
,t.otherbankcard
,t.certidaddress
,t.baseresidyear
,t.baseindustryyear
,t.managindustry
,t.debtorbusiness
,t.carsum
,t.housepvalue
,t.isinvestmentsm
,t.incomeratio
,t.socialsecyear
,t.accumuratio
,t.ishavework
,t.unsettledsum
,t.expectedsum
,t.maxposition
,t.creditcondit
,t.ishavembusiness
,t.isbaseemployee
,t.isbasebpay
,t.isbasebpaccount
,t.isbasebfaccount
,t.isbasebvipaccount
,t.isfammigration
,t.isnegationeva
,t.ispaydefault
,t.ishaveprefer
,t.creditguarantee
,t.isexcecase
,t.isoverrotio
,t.isoverhealth
,t.isbadbehavior
,t.ishavepower
,t.industyperesult
,t.ispenal
,t.isviolation
,t.isecondis
,t.isbreach
,t.managescale
,t.accumumount
,t.overduetimes
,t.allavgusedsum_last_six_month
,t.creditcardsum
,t.guarforothers
,t.dsblk
,t.customerisrelative
,t.guarantorisrelative
,t.busicerttype
,t.start_dt
,t.end_dt
,t.id_mark
,t.etl_timestamp
from ${idl_schema}.oass_crss_ind_info t
where start_dt <= to_date('${batch_date}','yyyymmdd') and  start_dt >= to_date('${batch_date}','yyyymmdd') -6 ;" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/oass_crss_ind_info_w.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes