: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_rcrs_ctr_loan_cont_f
CreateDate: 20180529
FileName:   ${iel_data_path}/rcrs_ctr_loan_cont.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select  
t.etl_dt
,t.cont_no
,t.serno
,t.cont_type
,t.prd_pk
,t.biz_type
,t.prd_name
,t.app_form
,t.cust_no
,t.cust_name
,t.biz_type_sub
,t.biz_type_detail
,t.loan_form
,t.loan_nature
,t.loan_kind_ca
,t.loan_type_ext
,t.loan_type_ext2
,t.currency_type
,t.approval_amt
,t.cont_amt
,t.total_issue_amt
,t.total_recyle_amt
,t.avail_amt
,t.term_time_type
,t.loan_term
,t.loan_start_date
,t.loan_end_date
,t.ruling_ir
,t.cal_floating_rate
,t.reality_ir_y
,t.overdue_rate
,t.overdue_ir
,t.default_rate
,t.default_ir
,t.ci_rate
,t.ci_ir
,t.ir_adjust_mode
,t.interest_acc_mode
,t.chargeoff_ind
,t.discont_ind
,t.discount_id
,t.mortgage_flg
,t.repayment_mode
,t.repayment_period
,t.assure_means_main
,t.assure_means2
,t.assure_means3
,t.loan_direction
,t.direction_name
,t.agriculture_type
,t.agriculture_use
,t.minor_entrp_range
,t.loan_use_type
,t.use_dec
,t.repayment_src_dec
,t.limit_ind
,t.guarantora_grp_ind
,t.copartner_ind
,t.loan_card_ind
,t.entrust_ind
,t.loan_type1
,t.loan_type2
,t.loan_type3
,t.loan_type4
,t.loan_type5
,t.loan_type6
,t.final_endorse_br_id
,t.final_endorse_date
,t.final_endorse_id
,t.sign_date
,t.change_date
,t.cont_state
,t.input_id
,t.cust_mgr
,t.input_br_id
,t.main_br_id
,t.fina_br_id
,t.old_bill_no
,t.cla_result
,t.cla_suggestion
,t.ir_exe_type
,t.responsible_man
,t.government_ind
,t.government_org_attribute
,t.government_platform
,t.int_rate_type
,t.int_rate_inc_opt
,t.int_rate_inc
,t.fixed_rate
,t.prd_userdf_type
,t.prd_userdf_name
,t.consign_loan_bgl_acct_no
,t.funds_src
,t.chargeoff_manage
,t.enter_account
,t.enter_account_name
,t.repayment_account
,t.repayment_acc_name
,t.prd_type
,t.ispaf
,t.cosurety_cont_no
,t.lead_arranger_ind
,t.cn_cont_no
,t.fldvalue01
,t.fldvalue02
,t.disaster_type
,t.carve_out_type
,t.farm_card_type
,t.overdue_type
,t.default_type
,t.spe_loan_type2
,t.repay_interest_mode
,t.repay_principal_rate
,t.add_interest_date
,t.cus_area
,t.syndicated_ind
,t.syndicated_type
,t.join_role
,t.syndicated_proxy_id
,t.government_financing
,t.gover_fina_su_relat
,t.gover_fina_attribute
,t.gover_fina_type
,t.gover_fina_direction
,t.gover_fina_repay_src_dec
,t.domain_policy_type
,t.old_cont_state
,t.cap_overdue_date
,t.int_overdue_date
,t.if_gw
,t.check_finger
,t.tourism_flag
,t.biz_type_ext
,t.biz_type_ext2
,t.proj_type
,t.syndicated_amt
,t.lmt_serno
,t.item_id
,t.is_risk
,t.print_cont_no
,t.last_upd_date
,t.loan_mode
,t.is_loan_anytime
,t.rate_select_type
,t.is_stage_repay
,t.int_cal_type
,t.pay_type
,t.is_prj_cooperate
,t.prj_cooperate_serno
,t.repayment_interval
,t.repayment_date_confirm
,t.is_bank_rel
,t.input_date
,t.intent_cop
,t.is_intent_cop
,t.enter_account_type
,t.repayment_account_type
,t.old_loan_amount
,t.old_loan_balance
,t.return_date
,t.creation_date
,t.is_pub_com
,t.pub_com
,t.is_cl
,t.pf_serno
,t.cop_acc_no
,t.cop_prj_type
,t.cop_cus_type
,t.opt_type
,t.is_balloon
,t.last_term_percent
,t.avg_mortagage_rate
,t.total_max_mortagage_amt
,t.remove_avail_amt
,t.is_sign
,t.amt_use_type
,t.trigg_amt
,t.basic_ccr_amt
,t.bill_term
,t.reality_ir_d
,t.cont_amt_chg_limit
,t.relate_no
,t.cancel_time
,t.floor_num
,t.is_jg_account
,t.rate_type
,t.sld_seq_num
,t.cltrl_contr_link_loc
,t.cltrl_contr_sign_dt
,t.start_dt
,t.end_dt
,t.id_mark
from idl.rcrs_ctr_loan_cont t
where start_dt <= to_date('${batch_date}','yyyymmdd')
 and end_dt > to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/rcrs_ctr_loan_cont.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes