: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_cmm_corp_loan_acct_info_i_w
CreateDate: 20180529
FileName:   ${iel_data_path}/cmm_corp_loan_acct_info_w.i.${batch_date}.dat
IF_mark:    i_w
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
to_date('${batch_date}','yyyymmdd') as etl_dt
,t.lp_id
,t.acct_id
,t.acct_name
,t.cust_id
,t.cont_id
,t.dubil_num
,t.loan_distr_acct_num
,t.loan_repay_num
,t.int_sub_ps_stl_acct_num
,t.entr_dep_acct_num
,t.csner_dep_acct_num
,t.inpwn_acct_num_id
,t.out_acct_num
,t.rela_bill_id
,t.std_prod_id
,t.prod_id
,t.subj_id
,t.init_pric_subj_id
,t.int_subj_id
,t.off_bs_int_subj_id
,t.int_income_subj_id
,t.loan_acct_status_cd
,t.loan_tenor
,t.loan_tenor_type_cd
,t.loan_cate_cd
,t.asset_thd_cls_cd
,t.belong_bus_strip_line_cd
,t.guar_way_cd
,t.loan_usage_descb
,t.acru_non_acru_cd
,t.turn_non_acru_loan_dt
,t.cust_mgr_id
,t.open_acct_org_id
,t.mgmt_org_id
,t.acct_instit_id
,t.open_acct_dt
,t.distr_dt
,t.value_dt
,t.stop_accr_int_dt
,t.exp_dt
,t.clos_acct_dt
,t.int_sub_flg
,t.int_sub_ratio
,t.int_sub_exp_day
,t.entr_loan_comm_fee_coll_way
,t.entr_loan_comm_fee_coll_ratio
,t.entr_loan_comm_fee
,t.int_accr_flg
,t.stop_accr_int_flg
,t.impam_flg
,t.crdt_distr_repay_plan_flg
,t.finc_prod_flg
,t.prepay_int_amort_flg
,t.pric_auto_deduct_flg
,t.int_auto_deduct_flg
,t.acpt_flg
,t.gover_fin_plat_loan_flg
,t.tax_flg
,t.wrt_off_flg
,t.renew_flg
,t.renew_cnt
,t.allow_adv_repay_flg
,t.repay_seq_no_cd
,t.adv_repay_way_cd
,t.margin_curr_cd
,t.int_rat_base_type_cd
,t.int_rat_curve_type_cd
,t.base_rat
,t.exec_int_rat
,t.int_rat_adj_way_cd
,t.int_rat_float_way_cd
,t.int_rat_adj_ped_corp_cd
,t.int_rat_adj_ped_freq
,t.int_rat_flo_val
,t.curr_int_rat_effect_dt
,t.next_int_rat_adj_dt
,t.comp_int_flg
,t.int_set_way_cd
,t.int_accr_way_cd
,t.repay_way_cd
,t.repay_ped_corp_cd
,t.repay_ped
,t.money_use_type
,t.lmt_type
,t.asset_tran_status_cd
,t.tran_bf_int_recvbl
,t.ovdue_flg
,t.pric_ovdue_flg
,t.int_ovdue_flg
,t.curr_ovdue_perds
,t.pric_ovdue_days
,t.int_ovdue_days
,t.ovdue_pric_bal
,t.ovdue_int_amt
,t.ovdue_comp_int_amt
,t.fir_ovdue_dt
,t.ovdue_int_rat
,t.ovdue_int_rat_flo_val
,t.tot_perds
,t.curr_issue_perds
,t.last_repay_dt
,t.next_repay_dt
,t.curr_cd
,t.next_rpp_amt
,t.next_repay_int_amt
,t.td_acru_int
,t.currt_acru_int
,t.td_int_income
,t.cont_amt
,t.dubil_amt
,t.distr_amt
,t.nomal_pric
,t.ovdue_pric
,t.idle_pric
,t.bad_debt_pric
,t.recvbl_over_int
,t.recvbl_acru_pnlt
,t.recvbl_pnlt
,t.acru_comp_int
,t.recvbl_comp_int
,t.recvbl_fee
,t.wrt_off_pric
,t.wrt_off_int
,t.in_bs_over_int_bal
,t.off_bs_over_int_bal
,t.in_bs_int
,t.off_bs_int
,t.acm_recvbl_uncol_int_amt
,t.repaid_pric
,t.repaid_int
,t.repaid_pnlt
,t.repaid_comp_int
,t.repaid_fee
,t.pric_bal
,t.currt_bal
,t.cl_curr_currt_bal
,t.ear_d_bal
,t.ear_m_bal
,t.ear_s_bal
,t.ear_y_bal
,t.y_acm_bal
,t.s_acm_bal
,t.m_acm_bal
,t.cl_curr_ear_d_bal
,t.cl_curr_ear_m_bal
,t.cl_curr_ear_s_bal
,t.cl_curr_ear_y_bal
,t.cl_curr_y_acm_bal
,t.cl_curr_ear_d_y_acm_bal
,t.cl_curr_ear_m_y_acm_bal
,t.cl_curr_ear_s_y_acm_bal
,t.cl_curr_ear_y_y_acm_bal
,t.cl_curr_s_acm_bal
,t.cl_curr_ear_d_s_acm_bal
,t.cl_curr_ear_s_s_acm_bal
,t.cl_curr_ear_y_s_acm_bal
,t.cl_curr_m_acm_bal
,t.cl_curr_ear_d_m_acm_bal
,t.cl_curr_ear_m_m_acm_bal
,t.cl_curr_ear_y_m_acm_bal
,t.y_avg_bal
,t.q_avg_bal
,t.m_avg_bal
,t.cl_curr_y_avg_bal
,t.cl_curr_q_avg_bal
,t.cl_curr_m_avg_bal
from ${idl_schema}.cmm_corp_loan_acct_info t
where etl_dt = to_date('${batch_date}','yyyymmdd') ; " \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/cmm_corp_loan_acct_info_w.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes