: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_rpt_crms_crm_cst_gath_info_f
CreateDate: 20180529
FileName:   ${iel_data_path}/rpt_crms_crm_cst_gath_info.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
to_date('${batch_date}','yyyymmdd') as cc_data_dt
,cc_cst_no
,cc_cst_nm
,cc_cst_sys_lvl
,cc_cst_svc_lvl
,cc_sex
,cc_ft_opac_time
,cc_mrtl_stat
,cc_brh_dt
,cc_age
,cc_ntnly
,cc_eth
,cc_ctf_tp
,cc_ctf_no
,cc_ep_flg
,cc_rcmd_cst
,cc_rcmd_user
,cc_mag_cst_mgr
,cc_mag_org
,cc_dbc_lvl
,cc_is_mrcnt
,cc_sys_cm_user
,cc_cst_risk_lv
,cc_concat_cif_cust_no
,cc_main_phone
,cc_cur_dpst_hld
,cc_dpt_dpst_hld
,cc_ln_hld
,cc_fnc_hld
,cc_fund_hld
,cce_fund_hld
,cc_ndbt_hld
,cc_psn_tpc_hld
,cc_psn_gold_hld
,cc_mbl_bnk_sgn
,cc_nwrk_bnk_sgn
,cc_tel_bnk_sgn
,cc_sms_sgn
,cc_pyrl_slry_sgn
,cc_agt_pymt_sgn
,cc_dbc_sgn
,cc_9mall_sgn
,cc_500mall_sgn
,cc_fund_vot_flg
,cc_message_bnk_sgn
,cc_it_ab_dpst_sgn
,cc_tmall_ac_sgn
,cc_eac_sgn
,cc_fxb_sp
,cc_auto_inst
,cc_tra_bg
,cc_trs_hld
,cc_aum_bal
,cc_aum_mavg
,cc_aum_qavg
,cc_aum_yavg
,cc_cmn_dept_bal
,cc_cmn_dept_mavg
,cc_cmn_dept_qavg
,cc_cmn_dept_yavg
,cc_sr_fnc
,cc_sr_fnc_mavg
,cc_sr_fnc_qavg
,cc_sr_fnc_yavg
,cc_nsr_fnc
,cc_nsr_fnc_mavg
,cc_nsr_fnc_qavg
,cc_nsr_fnc_yavg
,cc_dept_bal
,cc_dept_mavg
,cc_dept_qavg
,cc_dept_yavg
,cc_fund_bal
,cc_fund_mavg
,cc_fund_qavg
,cc_fund_yavg
,cc_fnc_bal
,cc_fnc_mavg
,cc_fnc_qavg
,cc_fnc_yavg
,cc_tpc_bal
,cc_tpc_mavg
,cc_tpc_qavg
,cc_tpc_yavg
,cc_scl_isfee_bal
,cc_scl_isfee_mavg
,cc_scl_isfee_qavg
,cc_scl_isfee_yavg
,cc_ln_bal
,cc_ln_mavg
,cc_ln_qavg
,cc_ln_yavg
,cc_e_fund_bal
,cc_e_fund_mavg
,cc_e_fund_qavg
,cc_e_fund_yavg
,cc_gold_bal
,cc_gold_mavg
,cc_gold_qavg
,cc_gold_yavg
,cc_nscr_aum_bal
,cc_nscr_aum_mavg
,cc_nscr_aum_qavg
,cc_nscr_aum_yavg
,cc_nscr_cmn_dept_bal
,cc_nscr_cmn_dept_mavg
,cc_nscr_cmn_dept_qavg
,cc_nscr_cmn_dept_yavg
,cc_nscr_sr_fnc
,cc_nscr_sr_fnc_mavg
,cc_nscr_sr_fnc_qavg
,cc_nscr_sr_fnc_yavg
,cc_nscr_nsr_fnc
,cc_nscr_nsr_fnc_mavg
,cc_nscr_nsr_fnc_qavg
,cc_nscr_nsr_fnc_yavg
,cc_nscr_dept_bal
,cc_nscr_dept_mavg
,cc_nscr_dept_qavg
,cc_nscr_dept_yavg
,cc_nscr_fund_bal
,cc_nscr_fund_mavg
,cc_nscr_fund_qavg
,cc_nscr_fund_yavg
,cc_nscr_fnc_bal
,cc_nscr_fnc_mavg
,cc_nscr_fnc_qavg
,cc_nscr_fnc_yavg
,cc_spd_dep
,cc_nscr_ins_bal
,cc_nscr_ins_yavg
,cc_nscr_ins_qavg
,cc_nscr_ins_mavg
,cc_nscr_gld_bal
,cc_nscr_gld_yavg
,cc_nscr_gld_qavg
,cc_nscr_gld_mavg
,cc_pg_bal
,cc_pg_mavg
,cc_pg_qavg
,cc_pg_yavg
,cc_nscr_pg_bal
,cc_nscr_pg_mavg
,cc_nscr_pg_qavg
,cc_nscr_pg_yavg
,cc_ysh_std
,cc_ysh_hld
,cc_phy_gold_hld
,cc_lday_aum_bal_chng
,cc_last_mn_aum_chng
,cc_lyr_aum_bal_chng
,cc_email
,cc_contt_cont
,cc_last_mn_aum_mavg_chng
,cc_last_mn_fnc_mavg_chng
,cc_last_mn_sr_fnc_mavg_chng
,cc_last_mn_nsr_fnc_mavg_chng
,cc_last_mn_dept_mavg_chng
,cc_last_mn_nscr_aum_mavg_chng
,cc_last_mn_nscr_fnc_mavg_chng
,last_mn_nscr_sr_fnc_mavg_chng
,last_mn_nscr_nsr_fnc_mavg_chng
,cc_last_mn_nscr_dept_mavg_chng
,cc_cst_sys_lvl_chng
,cc_pure_tmall_sgn
,cc_mag_cst_mgr_flg
,cc_fnc_sgn
,cc_fund_sgn
,cc_act_lvl
,cc_ctb_lvl
,cc_lyl_lvl
,cc_ent_crd_hld
,cc_esp_bal
,cc_esp_mavg
,cc_esp_qavg
,cc_esp_yavg
,cc_emp_shr_plan_hld
,cc_nscr_esp_bal
,cc_nscr_esp_mavg
,cc_nscr_esp_qavg
,cc_nscr_esp_yavg
from ${idl_schema}.crms_crm_cst_gath_info  t1
where t1.start_dt <= to_date('${batch_date}','yyyymmdd') and t1.end_dt > to_date('${batch_date}','yyyymmdd') and t1.etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/rpt_crms_crm_cst_gath_info.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes