: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_iof_pams_pam_aum_f
CreateDate: 20250604
FileName:   ${iel_data_path}/pams_pam_aum.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,aum_q_avg_bal
,aum_cp_q_mavg
,aum_cp_q_bal
,aum_cp_y_bal
,aum_cp_m_bal
,aum_cp_d_bal
,aum_cp_y_yavg
,aum_y_avg_bal
,aum_acct_bal
,aum_cp_w_bal
,aum_m_avg_bal
,aum_cp_y_mavg
,aum_cp_m_mavg
,e_fund_q_avg_bal
,e_fund_y_avg_bal
,e_fund_acct_bal
,e_fund_m_avg_bal
,t0_sr_q_avg_bal
,t0_sr_y_avg_bal
,t0_sr_acct_bal
,t0_cp_q_bal
,t0_cp_y_bal
,t0_cp_d_bal
,t0_cp_m_bal
,t0_cp_q_avg
,t0_cp_y_avg
,t0_cp_m_avg
,t0_sr_m_avg_bal
,t0_q_avg_bal
,t0_acct_cp_q_avg
,t0_y_avg_bal
,t0_acct_cp_y_avg
,t0_acct_bal
,t0_acct_cp_q_bal
,t0_acct_cp_y_bal
,t0_acct_cp_d_bal
,t0_acct_cp_m_bal
,t0_m_avg_bal
,t0_acct_cp_m_avg
,axc_q_avg_bal
,axc_cp_q_avg
,axc_y_avg_bal
,axc_cp_y_avg
,axc_acct_bal
,axc_cp_q_bal
,axc_cp_y_bal
,axc_cp_d_bal
,axc_cp_m_bal
,axc_m_avg_bal
,axc_cp_m_avg
,loan_mortgage_acct_bal
,nsr_acct_qavg
,nsr_cp_q_avg
,nsr_acct_yavg
,nsr_cp_y_avg
,nsr_acct_bal
,nsr_q_cp_bal
,nsr_y_cp_bal
,nsr_m_cp_bal
,nsr_acct_mavg
,nsr_cp_m_avg
,ensure_fee
,insure_acct_bal
,insure_cp_q_bal
,insure_cp_y_bal
,insure_cp_d_bal
,insure_cp_m_bal
,insure_cp_q_avg
,insure_q_avg_bal
,insure_acct_jz_bal
,insure_cp_y_avg
,insure_y_avg_bal
,insure_cp_m_avg
,insure_cp_w_bal
,insure_m_avg_bal
,cds_q_avg_bal
,cds_cp_q_avg
,cds_y_avg_bal
,cds_cp_y_avg
,cds_acct_bal
,cds_q_cp_bal
,cds_y_cp_bal
,cds_m_cp_bal
,cds_m_avg_bal
,cds_cp_m_avg
,decd_zr_sum
,dx_q_avg_bal
,sr_q_dx_q_avg_bal
,dx_y_avg_bal
,sr_y_dx_y_avg_bal
,dx_finc_bal
,sr_q_dx_finc_bal
,sr_y_dx_finc_bal
,sr_d_dx_finc_bal
,sr_m_dx_finc_bal
,sr_w_dx_finc_bal
,dx_m_avg_bal
,sr_m_dx_m_avg_bal
,t_agent_acct_qavg
,t_agent_acct_yavg
,t_agent_acct_bal
,t_agent_acct_jz_bal
,t_agent_acct_mavg
,third_acct_bal
,third_cp_q_bal
,third_cp_y_bal
,third_cp_d_bal
,third_cp_m_bal
,third_cp_q_avg
,third_cp_y_avg
,third_y_avg_bal
,third_m_avg_bal
,third_cp_m_avg
,dep_cp_q_avg
,dep_cp_y_avg
,dep_acct_bal
,dep_q_cp_bal
,dep_q_avg_bal
,dep_acct_jz_bal
,dep_y_cp_bal
,dep_y_avg_bal
,dep_m_avg_bal
,dep_m_cp_bal
,dep_cp_m_avg
,nt0_acct_bal
,nt0_cp_q_bal
,nt0_cp_y_bal
,nt0_cp_d_bal
,nt0_cp_m_bal
,nt0_cp_q_avg
,nt0_q_avg_bal
,nt0_cp_y_avg
,nt0_y_avg_bal
,nt0_m_avg_bal
,nt0_cp_m_avg
,sr_acct_qavg
,sr_cp_q_avg
,sr_acct_yavg
,sr_cp_y_avg
,sr_acct_bal
,sr_q_cp_bal
,sr_acct_jz_bal
,sr_y_cp_bal
,sr_m_cp_bal
,sr_acct_mavg
,sr_cp_m_avg
,fmone_cp_q_avg
,fmone_cp_y_avg
,fmone_acct_bal
,fmone_cp_q_bal
,fmone_cp_y_bal
,fmone_cp_d_bal
,fmone_cp_m_bal
,fmone_q_avg_bal
,fmone_y_avg_bal
,fmone_m_avg_bal
,fmone_cp_m_avg
,sr_d_cp_bal
,sr_w_cp_bal
,fin_cp_w_bal
,metals_cp_w_bal
,rm_q_avg_bal
,rm_y_avg_bal
,rm_acct_bal
,rm_m_avg_bal
,cur_y_cp_bal
,cur_acct_bal
,cur_q_cp_bal
,cur_q_avg_bal
,cur_acct_jz_bal
,cur_y_avg_bal
,cur_m_cp_bal
,cur_m_avg_bal
,mone_acct_bal
,mone_cp_q_bal
,mone_cp_y_bal
,mone_cp_d_bal
,mone_cp_m_bal
,mone_cp_q_avg
,mone_q_avg_bal
,mone_cp_y_avg
,mone_y_avg_bal
,mone_cp_m_avg
,mone_m_avg_bal
,fund_acct_qavg
,fund_acct_yavg
,fund_cp_w_bal
,fund_acct_bal
,fund_cp_q_bal
,fund_cp_y_bal
,fund_cp_d_bal
,fund_cp_m_bal
,fund_q_cp_bal
,fund_cp_q_avg
,fund_acct_jz_bal
,fund_y_cp_bal
,fund_cp_y_avg
,fund_m_cp_bal
,fund_cp_m_avg
,fund_acct_mavg
,ft_bal
,ft_cp_q_bal
,ft_cp_y_bal
,ft_cp_d_bal
,ft_cp_m_bal
,ft_cp_q_avg
,ft_q_avg
,ft_cp_y_avg
,ft_y_avg
,ft_cp_m_avg
,ft_m_avg
,loan_business_acct_bal
,replace(replace(t1.cust_id,chr(13),''),chr(10),'') as cust_id
,replace(replace(t1.asset_level,chr(13),''),chr(10),'') as asset_level
,fin_fdyk
,fin_profit_ratio
,fin_lj_profit
,replace(replace(t1.cust_name,chr(13),''),chr(10),'') as cust_name
,lc_zr_bal
,fin_acct_qavg
,fin_acct_yavg
,fin_acct_bal
,fin_cp_q_bal
,fin_cp_y_bal
,fin_cp_d_bal
,fin_cp_m_bal
,fin_cp_q_avg
,fin_acct_jz_bal
,fin_cp_y_avg
,fin_cp_m_avg
,fin_acct_mavg
,depfinc_avgq_bal
,depfinc_avgqcpq_bal
,depfinc_avgy_bal
,depfinc_avgycpy_bal
,depfinc_bal
,dept_acct_bal
,dept_cp_q_bal
,dept_cp_y_bal
,dept_cp_d_bal
,dept_cp_m_bal
,depfinc_cpq_bal
,dept_cp_q_avg
,dept_q_avg_bal
,depfinc_cpy_bal
,dept_cp_y_avg
,dept_y_avg_bal
,depfinc_cpd_bal
,depfinc_cpm_bal
,dept_cp_m_avg
,depfinc_cpw_bal
,dept_acct_mavg
,depfinc_avgm_bal
,depfinc_avgmcpm_bal
,loan_acct_yavg
,loan_acct_bal
,loan_cp_q_bal
,loan_cp_y_bal
,loan_cp_d_bal
,loan_cp_m_bal
,loan_cp_q_avg
,loan_q_avg_bal
,loan_cp_y_avg
,loan_cp_m_avg
,loan_acct_mavg
,loan_other_acct_bal
,metals_acct_bal
,metals_cp_q_bal
,metals_cp_y_bal
,metals_cp_d_bal
,metals_cp_m_bal
,metals_cp_q_avg
,metals_q_avg_bal
,metals_acct_jz_bal
,metals_cp_y_avg
,metals_y_avg_bal
,metals_m_avg_bal
,metals_cp_m_avg
,replace(replace(t1.et_dt,chr(13),''),chr(10),'') as et_dt
,replace(replace(t1.asset_level1,chr(13),''),chr(10),'') as asset_level1
,loan_consum_acct_bal
,new_q_avg_bal
,new_cp_q_avg
,new_y_avg_bal
,new_cp_y_avg
,new_acct_bal
,new_cp_q_bal
,new_cp_y_bal
,new_cp_d_bal
,new_cp_m_bal
,new_m_avg_bal
,new_cp_m_avg
,sdp_q_avg_bal
,sdp_y_avg_bal
,sdp_acct_bal
,sdp_m_avg_bal
,trust_acct_qavg
,trust_acct_yavg
,trust_acct_bal
,trust_cp_q_bal
,trust_cp_y_bal
,trust_cp_d_bal
,trust_cp_m_bal
,trust_cp_q_avg
,trust_acct_jz_bal
,trust_cp_y_avg
,trust_cp_m_avg
,trust_cp_w_bal
,trust_acct_mavg
,zy_q_avg_bal
,sr_q_zy_q_avg_bal
,zy_y_avg_bal
,sr_y_zy_y_avg_bal
,zy_finc_bal
,sr_q_zy_finc_bal
,sr_y_zy_finc_bal
,sr_d_zy_finc_bal
,sr_m_zy_finc_bal
,sr_w_zy_finc_bal
,zy_m_avg_bal
,sr_m_zy_m_avg_bal

from ${iol_schema}.pams_pam_aum t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/pams_pam_aum.f.${batch_date}.dat" \
        charset=utf8
        safe=yes
