: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_hdws_mpcs_a08tbetrx_i
CreateDate: 20180529
FileName:   ${iel_data_path}/hdws_mpcs_a08tbetrx.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
 t1.mainsq
,t1.opersq
,t1.businesstrace
,t1.bustype
,t1.servtype
,t1.dtlcmtno
,t1.transseq
,t1.pkcodt
,t1.pktype
,t1.hosttrcd
,t1.fronttrcd
,t1.transdt
,t1.consigndt
,t1.hostdate
,t1.hostnbr
,t1.crcycd
,t1.transamt
,t1.paybrn
,t1.payopenbrn
,t1.payacct
,t1.payname
,t1.payaddr
,t1.incobrn
,t1.incoacct
,t1.inconame
,t1.incoaddr
,t1.sndct
,t1.sndupbrn
,t1.sndbrn
,t1.rcvct
,t1.rcvupbrn
,t1.rcvbrn
,t1.billdt
,t1.billcd
,t1.orabustype
,t1.ptrasq
,t1.obaltp
,t1.obalod
,t1.obaldt
,t1.caclrs
,t1.cmpsam
,t1.inrate
,t1.refuam
,t1.transt
,t1.processcode
,t1.advest
,t1.vrseal
,t1.ckrvno
,t1.rndday
,t1.retudt
,t1.sdrvno
,t1.clerdt
,t1.bperno
,t1.bpermg
,t1.levels
,t1.oprtlr
,t1.chktlr
,t1.sndtlr
,t1.auttlr
,t1.stptlr
,t1.oprbrn
,t1.sendbranch
,t1.autbrn
,t1.recdes
,t1.chksta
,t1.remark
,t1.protocolnb
,t1.prtcnt
,t1.recvdt
,t1.transmitdt
,t1.blsecd
,t1.paydat
,t1.iotype
,t1.flag2
,t1.flag3
,t1.flag4
,t1.inoutflag
,t1.blrqno
,t1.sacact
,t1.sacana
,t1.clendt
,t1.clenus
,t1.clrbrn
,t1.clract
,t1.clrseq
,t1.prdnbr
,t1.tranbr
,t1.sdtrno
,t1.bkcode
,t1.cobkdt
,t1.cobkcd
,t1.idtype
,t1.idno
,t1.mxtram
,t1.transq
,t1.sdtrsq
,t1.paymod
,t1.opnwin
,t1.chngdt
,t1.bepssq
,t1.linkid
,t1.feamt1
,t1.feamt2
,t1.feamt3
,t1.feamt4
,t1.priamt
,t1.payamt
,t1.spiamt
,t1.edhtno
,t1.edhtdt
,t1.endtlr
,t1.chngti
,t1.magbrn
,t1.resv40
,t1.rcdver
,t1.rcdsta
,t1.prpktp
,t1.prclbk
,t1.prpkdt
,t1.prpksq
,t1.prodcd
,t1.isinout
,t1.inacct
,t1.inname
,t1.ourcnapsver
,t1.othercnapsver
,t1.landdealsts
,t1.checkdealsts
,t1.appenddatatable
,t1.appenddatadtltab
,t1.hangupreason
,t1.pkgbusinesstrace
,t1.pktype2
,t1.bustype2
,t1.servtype2
,t1.payopenbanknm
,t1.recvopenbanknm
,t1.modifytlr
,t1.feetype
,t1.eaccflg
,t1.od_flag
,t1.od_ovtranam
,t1.nextdayflag
,t1.autoflag
,t1.autocount
,t1.automsg
,t1.bindacct
,t1.bindacctnm
,t1.accttype
,t1.bindacctopnbrn
,t1.lsttranst
,t1.tacctp
,t1.limitorderid
,t1.isbindcard
,t1.globalseqno
,t1.returncode
,t1.returnmsg
,t1.transseqno
,t1.sendouttm
,t1.finaccountid
,t1.acct_typ_id
,t1.memocntt
,t1.acctchngflg
,t1.tagrmt
,t1.cdtrfiacctfg
,t1.inersettleacct
,t1.inersettlename
,t1.unisoccdtcd
,t1.regid
,t1.splchrgsreqtpcd
,t1.trnsmtdt
,t1.payupbrn
,t1.incoupbrn
,t1.agtflg
,t1.agtidtp
,t1.agtidno
,t1.agtname
,t1.agtphone
from ${idl_schema}.hdws_mpcs_a08tbetrx t1 
where etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/hdws_mpcs_a08tbetrx.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes