: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_iol_ibms_ttrd_otc_trade_f
CreateDate: 20221013
FileName:   ${iel_data_path}/ibms_ttrd_otc_trade.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.sysordid as sysordid
,replace(replace(t1.orddate,chr(13),''),chr(10),'') as orddate
,replace(replace(t1.ordtime,chr(13),''),chr(10),'') as ordtime
,replace(replace(t1.condate,chr(13),''),chr(10),'') as condate
,replace(replace(t1.contime,chr(13),''),chr(10),'') as contime
,replace(replace(t1.insid,chr(13),''),chr(10),'') as insid
,replace(replace(t1.intordid,chr(13),''),chr(10),'') as intordid
,replace(replace(t1.extordid,chr(13),''),chr(10),'') as extordid
,replace(replace(t1.custordid,chr(13),''),chr(10),'') as custordid
,replace(replace(t1.extbizid,chr(13),''),chr(10),'') as extbizid
,replace(replace(t1.operator,chr(13),''),chr(10),'') as operator
,replace(replace(t1.trdtype,chr(13),''),chr(10),'') as trdtype
,replace(replace(t1.cash_ext_accid,chr(13),''),chr(10),'') as cash_ext_accid
,replace(replace(t1.cash_accid,chr(13),''),chr(10),'') as cash_accid
,replace(replace(t1.secu_ext_accid,chr(13),''),chr(10),'') as secu_ext_accid
,replace(replace(t1.secu_accid,chr(13),''),chr(10),'') as secu_accid
,t1.partyid as partyid
,replace(replace(t1.cp_cash_accid,chr(13),''),chr(10),'') as cp_cash_accid
,replace(replace(t1.cp_secu_accid,chr(13),''),chr(10),'') as cp_secu_accid
,replace(replace(t1.i_code,chr(13),''),chr(10),'') as i_code
,replace(replace(t1.a_type,chr(13),''),chr(10),'') as a_type
,replace(replace(t1.m_type,chr(13),''),chr(10),'') as m_type
,replace(replace(t1.i_name,chr(13),''),chr(10),'') as i_name
,t1.ordcount as ordcount
,t1.ordprice as ordprice
,t1.ordamount as ordamount
,t1.trdfee as trdfee
,t1.setfee as setfee
,t1.setdays as setdays
,replace(replace(t1.setdate,chr(13),''),chr(10),'') as setdate
,t1.thenmktprice as thenmktprice
,t1.thenmktprice_u as thenmktprice_u
,t1.ordstatus as ordstatus
,t1.errcode as errcode
,replace(replace(t1.errinfo,chr(13),''),chr(10),'') as errinfo
,replace(replace(t1.bnd_settype,chr(13),''),chr(10),'') as bnd_settype
,t1.bnd_netprice as bnd_netprice
,t1.bnd_aiamount as bnd_aiamount
,replace(replace(t1.remark,chr(13),''),chr(10),'') as remark
,replace(replace(t1.reservetype,chr(13),''),chr(10),'') as reservetype
,replace(replace(t1.cp_reservetype,chr(13),''),chr(10),'') as cp_reservetype
,replace(replace(t1.reservechg,chr(13),''),chr(10),'') as reservechg
,replace(replace(t1.cp_reservechg,chr(13),''),chr(10),'') as cp_reservechg
,t1.reservevalue as reservevalue
,t1.cp_reservevalue as cp_reservevalue
,replace(replace(t1.resolve,chr(13),''),chr(10),'') as resolve
,replace(replace(t1.trade_grp_id,chr(13),''),chr(10),'') as trade_grp_id
,replace(replace(t1.ref_orddate,chr(13),''),chr(10),'') as ref_orddate
,t1.ref_sysordid as ref_sysordid
,replace(replace(t1.ignore_flag,chr(13),''),chr(10),'') as ignore_flag
,replace(replace(t1.exe_market,chr(13),''),chr(10),'') as exe_market
,replace(replace(t1.trader,chr(13),''),chr(10),'') as trader
,replace(replace(t1.trader_cp,chr(13),''),chr(10),'') as trader_cp
,t1.dealtype as dealtype
,replace(replace(t1.agreenumber,chr(13),''),chr(10),'') as agreenumber
,t1.eval_netprice as eval_netprice
,t1.ordsource as ordsource
,t1.deal_count as deal_count
,t1.deal_avg_netprice as deal_avg_netprice
,t1.deal_netamount as deal_netamount
,t1.deal_aiamount as deal_aiamount
,t1.deal_amount as deal_amount
,t1.bidaskid as bidaskid
,replace(replace(t1.relatedparty,chr(13),''),chr(10),'') as relatedparty
,t1.terminate_amount as terminate_amount
,replace(replace(t1.setdate_terminate,chr(13),''),chr(10),'') as setdate_terminate
,t1.agreementtype as agreementtype
,replace(replace(t1.partynametempority,chr(13),''),chr(10),'') as partynametempority
,replace(replace(t1.party_zzdaccname,chr(13),''),chr(10),'') as party_zzdaccname
,replace(replace(t1.seatno_cp,chr(13),''),chr(10),'') as seatno_cp
,replace(replace(t1.executor,chr(13),''),chr(10),'') as executor
,t1.union_sysordid as union_sysordid
,replace(replace(t1.party_zzdacccode,chr(13),''),chr(10),'') as party_zzdacccode
,replace(replace(t1.party_bank_code,chr(13),''),chr(10),'') as party_bank_code
,replace(replace(t1.party_acct_code,chr(13),''),chr(10),'') as party_acct_code
,replace(replace(t1.party_bank_name,chr(13),''),chr(10),'') as party_bank_name
,replace(replace(t1.party_acct_name,chr(13),''),chr(10),'') as party_acct_name
,replace(replace(t1.dis_fee_kind_follow,chr(13),''),chr(10),'') as dis_fee_kind_follow
,replace(replace(t1.dis_fee_kind,chr(13),''),chr(10),'') as dis_fee_kind
,replace(replace(t1.grpid_sub,chr(13),''),chr(10),'') as grpid_sub
,replace(replace(t1.imp_time,chr(13),''),chr(10),'') as imp_time
,t1.eval_ytm as eval_ytm
,t1.bnd_ytm as bnd_ytm
,replace(replace(t1.update_time,chr(13),''),chr(10),'') as update_time
,t1.due_ai as due_ai
,replace(replace(t1.operator_id,chr(13),''),chr(10),'') as operator_id
,replace(replace(t1.executor_id,chr(13),''),chr(10),'') as executor_id
,t1.due_cp as due_cp
,t1.real_ai as real_ai
,t1.real_cp as real_cp
,t1.real_fee as real_fee
,t1.due_fee as due_fee
,t1.ref_type as ref_type
,t1.is_remain as is_remain
,replace(replace(t1.trader_id,chr(13),''),chr(10),'') as trader_id
,replace(replace(t1.trademodel,chr(13),''),chr(10),'') as trademodel
,replace(replace(t1.settlemodel,chr(13),''),chr(10),'') as settlemodel
,replace(replace(t1.ord_id,chr(13),''),chr(10),'') as ord_id
,t1.insstatus as insstatus
,t1.entrust_ref_id as entrust_ref_id
,replace(replace(t1.close_trade_id,chr(13),''),chr(10),'') as close_trade_id
,t1.ftprate as ftprate
,replace(replace(t1.conn_ordid,chr(13),''),chr(10),'') as conn_ordid
,replace(replace(t1.two_effective_contract,chr(13),''),chr(10),'') as two_effective_contract
,t1.source_type as source_type
,t1.settlestate as settlestate
,replace(replace(t1.navdate,chr(13),''),chr(10),'') as navdate
,replace(replace(t1.qcurr_cash_ext_accid,chr(13),''),chr(10),'') as qcurr_cash_ext_accid
,replace(replace(t1.qcurr_party_bank_code,chr(13),''),chr(10),'') as qcurr_party_bank_code
,replace(replace(t1.qcurr_party_bank_name,chr(13),''),chr(10),'') as qcurr_party_bank_name
,replace(replace(t1.qcurr_party_acct_code,chr(13),''),chr(10),'') as qcurr_party_acct_code
,replace(replace(t1.qcurr_party_acct_name,chr(13),''),chr(10),'') as qcurr_party_acct_name
,replace(replace(t1.party_mid_bank_acct_code,chr(13),''),chr(10),'') as party_mid_bank_acct_code
,replace(replace(t1.party_mid_bank_name,chr(13),''),chr(10),'') as party_mid_bank_name
,replace(replace(t1.party_mid_swift_code,chr(13),''),chr(10),'') as party_mid_swift_code
,replace(replace(t1.qcurr_party_mid_bank_acct_code,chr(13),''),chr(10),'') as qcurr_party_mid_bank_acct_code
,replace(replace(t1.qcurr_party_mid_bank_name,chr(13),''),chr(10),'') as qcurr_party_mid_bank_name
,replace(replace(t1.qcurr_party_mid_swift_code,chr(13),''),chr(10),'') as qcurr_party_mid_swift_code
,replace(replace(t1.party_swift_code,chr(13),''),chr(10),'') as party_swift_code
,replace(replace(t1.qcurr_party_swift_code,chr(13),''),chr(10),'') as qcurr_party_swift_code
,t1.spv_id as spv_id
,t1.his_tradeflag as his_tradeflag
,t1.his_ref_tradeid as his_ref_tradeid
,replace(replace(t1.his_trade_setdate,chr(13),''),chr(10),'') as his_trade_setdate
,replace(replace(t1.party_pset,chr(13),''),chr(10),'') as party_pset
,replace(replace(t1.party_pset_country,chr(13),''),chr(10),'') as party_pset_country
,replace(replace(t1.party_agent_code_type,chr(13),''),chr(10),'') as party_agent_code_type
,replace(replace(t1.party_agent_code_dss,chr(13),''),chr(10),'') as party_agent_code_dss
,replace(replace(t1.party_agent_code,chr(13),''),chr(10),'') as party_agent_code
,replace(replace(t1.party_agent_account,chr(13),''),chr(10),'') as party_agent_account
,replace(replace(t1.party_code_type,chr(13),''),chr(10),'') as party_code_type
,replace(replace(t1.party_code_dss,chr(13),''),chr(10),'') as party_code_dss
,replace(replace(t1.party_code,chr(13),''),chr(10),'') as party_code
,replace(replace(t1.party_account,chr(13),''),chr(10),'') as party_account
,t1.si_id as si_id
,replace(replace(t1.party_i_bank_code,chr(13),''),chr(10),'') as party_i_bank_code
,replace(replace(t1.party_i_swift_code,chr(13),''),chr(10),'') as party_i_swift_code
,replace(replace(t1.split_inst_type,chr(13),''),chr(10),'') as split_inst_type
,t1.cm_attr_parent as cm_attr_parent
,t1.cm_attr_master as cm_attr_master
,t1.cm_attr_merge as cm_attr_merge
,t1.cm_attr_mirror as cm_attr_mirror
,t1.cm_attr_relation as cm_attr_relation
,replace(replace(t1.cal_start_date,chr(13),''),chr(10),'') as cal_start_date
,replace(replace(t1.cal_end_date,chr(13),''),chr(10),'') as cal_end_date
,t1.strike_ytm as strike_ytm
,replace(replace(t1.settlement_type,chr(13),''),chr(10),'') as settlement_type
,replace(replace(t1.aio_acct_no,chr(13),''),chr(10),'') as aio_acct_no
,replace(replace(t1.acct_type,chr(13),''),chr(10),'') as acct_type
,replace(replace(t1.user_name,chr(13),''),chr(10),'') as user_name
,replace(replace(t1.contractparty,chr(13),''),chr(10),'') as contractparty
,replace(replace(t1.marketing_manager_id,chr(13),''),chr(10),'') as marketing_manager_id
,replace(replace(t1.marketing_org_id,chr(13),''),chr(10),'') as marketing_org_id
,replace(replace(t1.com_date,chr(13),''),chr(10),'') as com_date
,replace(replace(t1.party_branch,chr(13),''),chr(10),'') as party_branch
,t1.max_val as max_val
,t1.min_val as min_val
,t1.collection_fst_fee as collection_fst_fee
,replace(replace(t1.transfer_type,chr(13),''),chr(10),'') as transfer_type
,replace(replace(t1.secu_setdate,chr(13),''),chr(10),'') as secu_setdate
,t1.csdc_netprice as csdc_netprice
,t1.ccdc_netprice as ccdc_netprice
,t1.shch_netprice as shch_netprice
,t1.se_netprice as se_netprice
,replace(replace(t1.ctrct_id,chr(13),''),chr(10),'') as ctrct_id
,replace(replace(t1.platform,chr(13),''),chr(10),'') as platform
,replace(replace(t1.invest_direction,chr(13),''),chr(10),'') as invest_direction
,t1.contractversion as contractversion
,replace(replace(t1.final_invest,chr(13),''),chr(10),'') as final_invest
,replace(replace(t1.associatednumber,chr(13),''),chr(10),'') as associatednumber
,t1.fiveclass as fiveclass
,replace(replace(t1.prod_nature,chr(13),''),chr(10),'') as prod_nature
,replace(replace(t1.trd_acc_code,chr(13),''),chr(10),'') as trd_acc_code
,replace(replace(t1.store_code,chr(13),''),chr(10),'') as store_code
,replace(replace(t1.quote_type,chr(13),''),chr(10),'') as quote_type
,replace(replace(t1.unit_id,chr(13),''),chr(10),'') as unit_id
,t1.curcount as curcount
,t1.can_div_amount as can_div_amount
,replace(replace(t1.is_remain_due_ai,chr(13),''),chr(10),'') as is_remain_due_ai
,replace(replace(t1.is_impair,chr(13),''),chr(10),'') as is_impair
,replace(replace(t1.option_group,chr(13),''),chr(10),'') as option_group
,replace(replace(t1.entry_date,chr(13),''),chr(10),'') as entry_date
,replace(replace(t1.party_pset_name,chr(13),''),chr(10),'') as party_pset_name
,replace(replace(t1.relate_invest,chr(13),''),chr(10),'') as relate_invest
,t1.settlement_place as settlement_place
,t1.trdfee_notset as trdfee_notset
,replace(replace(t1.daycounter,chr(13),''),chr(10),'') as daycounter
,replace(replace(t1.remain_due_cp,chr(13),''),chr(10),'') as remain_due_cp
,replace(replace(t1.include_inte,chr(13),''),chr(10),'') as include_inte
,replace(replace(t1.exh_extordid,chr(13),''),chr(10),'') as exh_extordid
,t1.exrcise_state as exrcise_state
,replace(replace(t1.sppiresult,chr(13),''),chr(10),'') as sppiresult
,replace(replace(t1.sppiclass,chr(13),''),chr(10),'') as sppiclass
,replace(replace(t1.mergeno,chr(13),''),chr(10),'') as mergeno
,replace(replace(t1.resource_id,chr(13),''),chr(10),'') as resource_id
,replace(replace(t1.party_relevance_info,chr(13),''),chr(10),'') as party_relevance_info
,replace(replace(t1.full_flag,chr(13),''),chr(10),'') as full_flag
,t1.brokerage_id as brokerage_id
,replace(replace(t1.brokerage_fee_info,chr(13),''),chr(10),'') as brokerage_fee_info
,t1.released_credit_line as released_credit_line
,replace(replace(t1.out_range,chr(13),''),chr(10),'') as out_range
,t1.interest_out as interest_out
,replace(replace(t1.book,chr(13),''),chr(10),'') as book
,replace(replace(t1.xcc_trade_grp_id,chr(13),''),chr(10),'') as xcc_trade_grp_id
,t1.xcc_pre_sysordid as xcc_pre_sysordid
,replace(replace(t1.cash_setdate,chr(13),''),chr(10),'') as cash_setdate
,t1.bnd_ytm_deviate as bnd_ytm_deviate
,replace(replace(t1.trd_fee_ext_secu_acct_id,chr(13),''),chr(10),'') as trd_fee_ext_secu_acct_id
,replace(replace(t1.pre_bnt_ord_id,chr(13),''),chr(10),'') as pre_bnt_ord_id
,t1.pre_remain_count as pre_remain_count
,replace(replace(t1.p_id,chr(13),''),chr(10),'') as p_id
,replace(replace(t1.party_acc_code_type,chr(13),''),chr(10),'') as party_acc_code_type
,replace(replace(t1.qcurr_party_acc_code_type,chr(13),''),chr(10),'') as qcurr_party_acc_code_type
,replace(replace(t1.ftp_code,chr(13),''),chr(10),'') as ftp_code
,replace(replace(t1.pc1,chr(13),''),chr(10),'') as pc1
,t1.yhf as yhf
,t1.jsf as jsf
,t1.ghf as ghf
,t1.zgf as zgf
,t1.sxf as sxf
,t1.brkfee as brkfee
,t1.yjf as yjf
,t1.netyjf as netyjf
,replace(replace(t1.con_update_time,chr(13),''),chr(10),'') as con_update_time
,replace(replace(t1.qcurr_party_recv_bank_name,chr(13),''),chr(10),'') as qcurr_party_recv_bank_name
,replace(replace(t1.qcurr_party_recv_bank_swift,chr(13),''),chr(10),'') as qcurr_party_recv_bank_swift
,replace(replace(t1.party_recv_bank_name,chr(13),''),chr(10),'') as party_recv_bank_name
,replace(replace(t1.party_recv_bank_swift_code,chr(13),''),chr(10),'') as party_recv_bank_swift_code
,t1.other_fee as other_fee
,replace(replace(t1.cli_ord_id,chr(13),''),chr(10),'') as cli_ord_id
,replace(replace(t1.party_swift_type,chr(13),''),chr(10),'') as party_swift_type
,replace(replace(t1.qcurr_party_swift_type,chr(13),''),chr(10),'') as qcurr_party_swift_type
,replace(replace(t1.back_bank_code,chr(13),''),chr(10),'') as back_bank_code
,replace(replace(t1.back_acct_code,chr(13),''),chr(10),'') as back_acct_code
,replace(replace(t1.back_bank_name,chr(13),''),chr(10),'') as back_bank_name
,replace(replace(t1.back_acct_name,chr(13),''),chr(10),'') as back_acct_name
,replace(replace(t1.other_agree_item,chr(13),''),chr(10),'') as other_agree_item
,replace(replace(t1.bank_group_mode,chr(13),''),chr(10),'') as bank_group_mode
,replace(replace(t1.apr_txn,chr(13),''),chr(10),'') as apr_txn
,replace(replace(t1.reply_code,chr(13),''),chr(10),'') as reply_code
,replace(replace(t1.incomeaccount,chr(13),''),chr(10),'') as incomeaccount
,replace(replace(t1.credit_occupation_type,chr(13),''),chr(10),'') as credit_occupation_type
,replace(replace(t1.is_appoint_time,chr(13),''),chr(10),'') as is_appoint_time
,replace(replace(t1.appoint_start_date,chr(13),''),chr(10),'') as appoint_start_date
,replace(replace(t1.appoint_end_date,chr(13),''),chr(10),'') as appoint_end_date
,replace(replace(t1.is_quarter_redeem,chr(13),''),chr(10),'') as is_quarter_redeem
,replace(replace(t1.redeem_date,chr(13),''),chr(10),'') as redeem_date
,t1.min_rate as min_rate
,t1.max_rate as max_rate
,t1.min_repo_interest as min_repo_interest
,t1.max_repo_interest as max_repo_interest
,replace(replace(t1.credit_id,chr(13),''),chr(10),'') as credit_id
,t1.confirm_status as confirm_status
,t1.confirmor as confirmor
,t1.confirm_i_id as confirm_i_id
,replace(replace(t1.guest_agreement_num,chr(13),''),chr(10),'') as guest_agreement_num
,replace(replace(t1.guest_business_num,chr(13),''),chr(10),'') as guest_business_num
,replace(replace(t1.credit_secu_type,chr(13),''),chr(10),'') as credit_secu_type

from ${iol_schema}.ibms_ttrd_otc_trade t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/ibms_ttrd_otc_trade.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
