: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_icms_bc_extend_t_f
CreateDate: 20221208
FileName:   ${iel_data_path}/icms_bc_extend_t.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.serialno as serialno
,t1.rivalname as rivalname
,t1.consigneename as consigneename
,t1.consigneecerttype as consigneecerttype
,t1.consigneecertid as consigneecertid
,t1.financier as financier
,t1.iscounterparty as iscounterparty
,t1.fundsource as fundsource
,t1.investway as investway
,t1.managemodel as managemodel
,t1.tradingassets as tradingassets
,t1.toindustryfund as toindustryfund
,t1.isdebttoequity as isdebttoequity
,t1.isgovernfinance as isgovernfinance
,t1.isconsumerfinance as isconsumerfinance
,t1.bondno as bondno
,t1.bondname as bondname
,t1.investkind as investkind
,t1.canseparate as canseparate
,t1.canbacktosale as canbacktosale
,t1.begindate as begindate
,t1.salebackenddate as salebackenddate
,t1.businessmarkettype as businessmarkettype
,t1.businessmarketname as businessmarketname
,t1.paymentdate as paymentdate
,t1.outerevaluate1 as outerevaluate1
,t1.outerevaluate2 as outerevaluate2
,t1.outerevaluate3 as outerevaluate3
,t1.couponrate as couponrate
,t1.transactionprice as transactionprice
,t1.transactionrate as transactionrate
,t1.transactoinamount as transactoinamount
,t1.transactiondate as transactiondate
,t1.creditincrementtype as creditincrementtype
,t1.islikeloan as islikeloan
,t1.isclassflag as isclassflag
,t1.productlevel as productlevel
,t1.productcollectmoney as productcollectmoney
,t1.finalinvestdirecttype as finalinvestdirecttype
,t1.mandatecustname as mandatecustname
,t1.mandatecustid as mandatecustid
,t1.acceptbankid as acceptbankid
,t1.billacptdate as billacptdate
,t1.billno as billno
,t1.billcurrency as billcurrency
,t1.billmaturity as billmaturity
,t1.chuantoutype as chuantoutype
,t1.econtractname as econtractname
,t1.econtracttype as econtracttype
,t1.guarantytype as guarantytype
,t1.guranteerate as guranteerate
,t1.contractitems as contractitems
,t1.isimportantloan as isimportantloan
,t1.importantloan as importantloan
,t1.operationtype as operationtype
,t1.acceptbankname as acceptbankname
,t1.backtosaletype as backtosaletype
,t1.beneficiaryname as beneficiaryname
,t1.beneficiaryyieldrate as beneficiaryyieldrate
,t1.beneficiaryacctno as beneficiaryacctno
,t1.ifgudingcredit as ifgudingcredit
,t1.manageratetype as manageratetype
,t1.othercondition as othercondition
,t1.subtotalprices as subtotalprices
,t1.ztacceptbankname as ztacceptbankname
,t1.ztacceptbankid as ztacceptbankid
,t1.relztacceptbankcustid as relztacceptbankcustid
,t1.iswhzt as iswhzt
,t1.corpuspaymethod as corpuspaymethod
,t1.creditattribute as creditattribute
,t1.depositratetype as depositratetype
,t1.expectyieldrate as expectyieldrate
,t1.tradecontractno as tradecontractno
,t1.acceptcustomerid as acceptcustomerid
,t1.entrustyieldtype as entrustyieldtype
,t1.isbalancedeposit as isbalancedeposit
,t1.isfillassetsinfo as isfillassetsinfo
,t1.raisefundpurpose as raisefundpurpose
,t1.raisemoneyaccountid as raisemoneyaccountid
,t1.repayinteresttype as repayinteresttype
,t1.businessinvoicesum as businessinvoicesum
,t1.financesupportmode as financesupportmode
,t1.businessinvoiceinfo as businessinvoiceinfo
,t1.businessinvoicetype as businessinvoicetype
,t1.entrustinterestrate as entrustinterestrate
,t1.rateexplain as rateexplain
,t1.circulatestockamount as circulatestockamount
,t1.issupplychainfinance as issupplychainfinance
,t1.supplychainfinancetype as supplychainfinancetype
,t1.businessinvoicecurrency as businessinvoicecurrency
,t1.entrustinterestratetype as entrustinterestratetype
,t1.gshy as gshy
,t1.baileename as baileename
,t1.gksxpz as gksxpz
,t1.issuer as issuer
,t1.pcline as pcline
,t1.sfgksx as sfgksx
,t1.sfzfsx as sfzfsx
,t1.zfsxfs as zfsxfs
,t1.zfsxlx as zfsxlx
,t1.ztrate as ztrate
,t1.billsum as billsum
,t1.enddate as enddate
,t1.tdtimes as tdtimes
,t1.tdyears as tdyears
,t1.trusteename as trusteename
,t1.billkind as billkind
,t1.billtype as billtype
,t1.deadline as deadline
,t1.issuesum as issuesum
,t1.sfgjxzhy as sfgjxzhy
,t1.tradesum as tradesum
,t1.alarmline as alarmline
,t1.custodianname as custodianname
,t1.depositno as depositno
,t1.isfarming as isfarming
,t1.repayremark as repayremark
,t1.stockcode as stockcode
,t1.stockname as stockname
,t1.tdstrenth as tdstrenth
,t1.absabnname as absabnname
,t1.bdindustry as bdindustry
,t1.billwriter as billwriter
,t1.entrustacc as entrustacc
,t1.issueprice as issueprice
,t1.issuescale as issuescale
,t1.partybname as partybname
,t1.priequname as priequname
,t1.subscriber as subscriber
,t1.useproduct as useproduct
,t1.contextinfo as contextinfo
,t1.drawingremark as drawingremark
,t1.contractsum as contractsum
,t1.depositname as depositname
,t1.directionrs as directionrs
,t1.drawingtype as drawingtype
,t1.issueamount as issueamount
,t1.mainproduct as mainproduct
,t1.stockamount as stockamount
,t1.consigneeid as consigneeid
,t1.rivalid as rivalid
,t1.start_dt as start_dt
,t1.end_dt as end_dt
,t1.id_mark as id_mark
,t1.accountcatagory as accountcatagory
,t1.datatype as datatype
,t1.migtflag as migtflag
,t1.salebackbegindate as salebackbegindate
,t1.assetno as assetno

from ${idl_schema}.icms_bc_extend_t t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/icms_bc_extend_t.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
