: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_rpt_crss_upl_business_apply_f
CreateDate: 20180529
FileName:   ${iel_data_path}/rpt_crss_upl_business_apply.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
serialno
,t1.relativeserialno
,t1.occurdate
,t1.customerid
,t1.customername
,t1.businesstype
,t1.businesssubtype
,t1.occurtype
,t1.fundsource
,t1.operatetype
,t1.currenylist
,t1.currencymode
,t1.businesstypelist
,t1.calculatemode
,t1.useorglist
,t1.cycleflag
,t1.flowreduceflag
,t1.contractflag
,t1.subcontractflag
,t1.selfuseflag
,t1.creditaggreement
,t1.relativeagreement
,t1.loanflag
,t1.totalsum
,t1.ourrole
,t1.reversibility
,t1.billnum
,t1.housetype
,t1.lctermtype
,t1.riskattribute
,t1.suretype
,t1.safeguardtype
,t1.businesscurrency
,t1.businesssum
,t1.businessprop
,t1.termyear
,t1.termmonth
,t1.termday
,t1.lgterm
,t1.baseratetype
,t1.baserate
,t1.ratefloattype
,t1.ratefloat
,t1.businessrate
,t1.ictype
,t1.iccyc
,t1.pdgratio
,t1.pdgsum
,t1.pdgpaymethod
,t1.pdgpayperiod
,t1.promisesfeeratio
,t1.promisesfeesum
,t1.promisesfeeperiod
,t1.promisesfeebegin
,t1.mfeeratio
,t1.mfeesum
,t1.mfeepaymethod
,t1.agentfee
,t1.dealfee
,t1.totalcast
,t1.discountinterest
,t1.purchaserinterest
,t1.bargainorinterest
,t1.discountsum
,t1.bailratio
,t1.bailcurrency
,t1.bailsum
,t1.bailaccount
,t1.fineratetype
,t1.finerate
,t1.drawingtype
,t1.firstdrawingdate
,t1.drawingperiod
,t1.paytimes
,t1.paycyc
,t1.graceperiod
,t1.overdraftperiod
,t1.oldlcno
,t1.oldlctermtype
,t1.oldlccurrency
,t1.oldlcsum
,t1.oldlcloadingdate
,t1.oldlcvaliddate
,t1.direction
,t1.purpose
,t1.planallocation
,t1.immediacypaysource
,t1.paysource
,t1.corpuspaymethod
,t1.interestpaymethod
,t1.thirdparty1
,t1.thirdpartyid1
,t1.thirdparty2
,t1.thirdpartyid2
,t1.thirdparty3
,t1.thirdpartyid3
,t1.thirdpartyregion
,t1.thirdpartyaccounts
,t1.cargoinfo
,t1.projectname
,t1.operationinfo
,t1.contextinfo
,t1.securitiestype
,t1.securitiesregion
,t1.constructionarea
,t1.usearea
,t1.flag1
,t1.flag2
,t1.flag3
,t1.tradecontractno
,t1.invoiceno
,t1.tradecurrency
,t1.tradesum
,t1.paymentdate
,t1.operationmode
,t1.vouchclass
,t1.vouchtype
,t1.vouchtype1
,t1.vouchtype2
,t1.vouchflag
,t1.warrantor
,t1.warrantorid
,t1.othercondition
,t1.guarantyvalue
,t1.guarantyrate
,t1.baseevaluateresult
,t1.riskrate
,t1.lowrisk
,t1.otherarealoan
,t1.lowriskbailsum
,t1.originalputoutdate
,t1.extendtimes
,t1.lngotimes
,t1.golntimes
,t1.drtimes
,t1.baseclassifyresult
,t1.applytype
,t1.bailrate
,t1.finishorg
,t1.operateorgid
,t1.operateuserid
,t1.operatedate
,t1.inputorgid
,t1.inputuserid
,t1.inputdate
,t1.updatedate
,t1.pigeonholedate
,t1.remark
,t1.flag4
,t1.paycurrency
,t1.paydate
,t1.describe1
,t1.describe2
,t1.classifyresult
,t1.classifydate
,t1.classifyfrequency
,t1.vouchnewflag
,t1.adjustratetype
,t1.adjustrateterm
,t1.rateadjustcyc
,t1.fzanbalance
,t1.acceptinttype
,t1.fixcyc
,t1.thirdpartyadd1
,t1.thirdpartyzip1
,t1.thirdpartyadd2
,t1.thirdpartyzip2
,t1.thirdpartyadd3
,t1.thirdpartyzip3
,t1.effectarea
,t1.termdate1
,t1.termdate2
,t1.termdate3
,t1.ratio
,t1.tempsaveflag
,t1.creditcycle
,t1.gainamount
,t1.gaincyc
,t1.holdcorpus
,t1.incomeorgid
,t1.mainrepaymentmethod
,t1.payaccountname
,t1.payaccountno
,t1.paymentmode
,t1.ratemode
,t1.flag5
,t1.defaultpaydate
,t1.batchpaymentflag
,t1.loanaccountno
,t1.loankind
,t1.introducerid
,t1.salechannelid
,t1.bar_code_no
,t1.schemeno
,t1.preapproverid
,t1.saleteamid
,t1.signedplace
,t1.purposetype
,t1.qualitycontrolflag
,t1.approvesum
,t1.approvelevel
,t1.trustaccname
,t1.trustfundacctname
,t1.flag7
,t1.usedbailsum
,t1.subbusinesstype
,t1.usedsum
,t1.orginalbusinessum
,t1.changetypeflag
,t1.guarinten
,t1.isreconsider
,t1.reconreason
,t1.iscompulsapproval
,t1.payaccountname2
,t1.payaccountno2
,t1.housenmber1
,t1.houseareacode1
,t1.houseadd1
,t1.housetype1
,t1.isguaranty1
,t1.persons1
,t1.havecount1
,t1.amount1
,t1.price1
,t1.housenmber2
,t1.houseareacode2
,t1.houseadd2
,t1.housetype2
,t1.isguaranty2
,t1.persons2
,t1.havecount2
,t1.amount2
,t1.price2
,t1.ifdkqy
,t1.iskyd
from ${idl_schema}.crss_upl_business_apply t1
where t1.start_dt <= to_date('${batch_date}','yyyymmdd') and t1.end_dt > to_date('${batch_date}','yyyymmdd') and t1.etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/rpt_crss_upl_business_apply.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes