: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idf_cmm_corp_loan_dubil_info_f
CreateDate: 20250804
FileName:   ${iel_data_path}/cmm_corp_loan_dubil_info.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.lp_id as lp_id
,t1.dubil_id as dubil_id
,t1.cont_id as cont_id
,t1.std_prod_id as std_prod_id
,t1.out_acct_flow_num as out_acct_flow_num
,t1.rela_dubil_id as rela_dubil_id
,t1.bill_num as bill_num
,t1.cust_id as cust_id
,t1.host_cust_id as host_cust_id
,t1.distr_acct_num as distr_acct_num
,t1.repay_num as repay_num
,t1.secd_repay_num as secd_repay_num
,t1.stl_acct_num as stl_acct_num
,t1.manu_cont_id as manu_cont_id
,t1.crdt_lmt_agt_id as crdt_lmt_agt_id
,t1.advc_flg as advc_flg
,t1.pre_recv_int_flg as pre_recv_int_flg
,t1.attach_rgst_dubil_flg as attach_rgst_dubil_flg
,t1.matn_flg as matn_flg
,t1.wrt_off_flg as wrt_off_flg
,t1.comp_int_flg as comp_int_flg
,t1.stop_accr_int_flg as stop_accr_int_flg
,t1.sign_crdt_cont_flg as sign_crdt_cont_flg
,t1.pric_auto_rtn_flg as pric_auto_rtn_flg
,t1.int_auto_rtn_flg as int_auto_rtn_flg
,t1.crdt_distr_repay_plan_flg as crdt_distr_repay_plan_flg
,t1.bus_breed_id as bus_breed_id
,t1.dubil_status_cd as dubil_status_cd
,t1.loan_happ_type_cd as loan_happ_type_cd
,t1.mode_pay_cd as mode_pay_cd
,t1.curr_cd as curr_cd
,t1.int_accr_way_cd as int_accr_way_cd
,t1.loan_type_cd as loan_type_cd
,t1.loan_level4_cls_cd as loan_level4_cls_cd
,t1.loan_level5_cls_cd as loan_level5_cls_cd
,t1.loan_level10_cls_cd as loan_level10_cls_cd
,t1.loan_level12_cls_cd as loan_level12_cls_cd
,t1.repay_way_cd as repay_way_cd
,t1.dir_indus_cd as dir_indus_cd
,t1.guar_way_cd as guar_way_cd
,t1.loan_kind_cd as loan_kind_cd
,t1.wrtoff_type_cd as wrtoff_type_cd
,t1.loan_tenor_type_cd as loan_tenor_type_cd
,t1.loan_tenor_seg_cd as loan_tenor_seg_cd
,t1.bill_kind_cd as bill_kind_cd
,t1.bill_med_cd as bill_med_cd
,t1.data_src_flg as data_src_flg
,t1.int_rat_adj_way_cd as int_rat_adj_way_cd
,t1.col_int_type_cd as col_int_type_cd
,t1.int_rat_adj_ped_corp_cd as int_rat_adj_ped_corp_cd
,t1.int_rat_adj_ped_freq as int_rat_adj_ped_freq
,t1.inst_loan_repay_way_cd as inst_loan_repay_way_cd
,t1.money_use_type_cd as money_use_type_cd
,t1.org_id as org_id
,t1.oper_org_id as oper_org_id
,t1.oper_teller_id as oper_teller_id
,t1.rgst_org_id as rgst_org_id
,t1.rgst_teller_id as rgst_teller_id
,t1.attach_rgst_check_teller_id as attach_rgst_check_teller_id
,t1.benefc_name as benefc_name
,t1.bnft_bk_no as bnft_bk_no
,t1.bnft_bk_name as bnft_bk_name
,t1.acpt_bank_no as acpt_bank_no
,t1.acpt_bank_name as acpt_bank_name
,t1.margin_acct_num as margin_acct_num
,t1.margin_curr_cd as margin_curr_cd
,t1.margin_amt as margin_amt
,t1.margin_ratio as margin_ratio
,t1.dubil_wrtoff_flow_num as dubil_wrtoff_flow_num
,t1.dubil_open_flow_num as dubil_open_flow_num
,t1.dubil_open_dt as dubil_open_dt
,t1.distr_dt as distr_dt
,t1.apot_exp_dt as apot_exp_dt
,t1.exec_exp_dt as exec_exp_dt
,t1.next_int_set_dt as next_int_set_dt
,t1.loan_cls_dt as loan_cls_dt
,t1.next_term_rpp_dt as next_term_rpp_dt
,t1.next_term_repay_int_dt as next_term_repay_int_dt
,t1.payoff_dt as payoff_dt
,t1.ovdue_dt as ovdue_dt
,t1.over_int_dt as over_int_dt
,t1.ovdue_days as ovdue_days
,t1.over_int_days as over_int_days
,t1.loan_ped as loan_ped
,t1.inst_loan_tot_perds as inst_loan_tot_perds
,t1.surp_perds as surp_perds
,t1.acm_debt_perds as acm_debt_perds
,t1.exec_int_rat as exec_int_rat
,t1.ovdue_int_rat as ovdue_int_rat
,t1.comm_fee_fee_rat as comm_fee_fee_rat
,t1.next_term_rpp_amt as next_term_rpp_amt
,t1.next_term_repay_int_amt as next_term_repay_int_amt
,t1.repay_num_bal as repay_num_bal
,t1.repay_num_aval_bal as repay_num_aval_bal
,t1.eh_issue_deduct_amt as eh_issue_deduct_amt
,t1.ovdue_int as ovdue_int
,t1.dubil_amt as dubil_amt
,t1.dubil_bal as dubil_bal
,t1.nomal_pric as nomal_pric
,t1.ovdue_pric as ovdue_pric
,t1.idle_pric as idle_pric
,t1.bad_debt_pric as bad_debt_pric
,t1.in_bs_over_int_bal as in_bs_over_int_bal
,t1.off_bs_over_int_bal as off_bs_over_int_bal
,t1.pric_pnlt as pric_pnlt
,t1.int_pnlt as int_pnlt
,t1.cap_ratio as cap_ratio
,t1.intnl_trad_fin_rela_id_2 as intnl_trad_fin_rela_id_2
,t1.asset_thd_cls_cd as asset_thd_cls_cd
,t1.pbc_inc_loan_flg as pbc_inc_loan_flg
,t1.refac_loan_status_cd as refac_loan_status_cd
,t1.crdtc_subm_bus_breed_cd as crdtc_subm_bus_breed_cd
,t1.crdtc_subm_bus_breed_descb as crdtc_subm_bus_breed_descb
,t1.base_rat as base_rat
,t1.edu_hea_flg as edu_hea_flg
,t1.file_int_accr_flg as file_int_accr_flg
,t1.refac_loan_batch_pkg_id as refac_loan_batch_pkg_id
,t1.refac_loan_batch_exp_dt as refac_loan_batch_exp_dt
,t1.refac_loan_use_int_rat as refac_loan_use_int_rat
,t1.level5_cls_idtfy_dt as level5_cls_idtfy_dt
,t1.entr_pay_amt as entr_pay_amt
,t1.bill_id as bill_id
,t1.bill_uniq_mark_id as bill_uniq_mark_id
,t1.overs_loan_flg as overs_loan_flg
,t1.margin_sub_acct_num as margin_sub_acct_num
,t1.recvbl_acct_name as recvbl_acct_name
,t1.recvbl_bank_name as recvbl_bank_name
,t1.acct_instit_id as acct_instit_id
,t1.comp_amt as comp_amt
,t1.ibank_asset_uniq_idf_id as ibank_asset_uniq_idf_id
,t1.rela_bus_id as rela_bus_id
,t1.belong_bus_strip_line_cd as belong_bus_strip_line_cd
,t1.regroup_loan_flg as regroup_loan_flg
,t1.regroup_loan_type_cd as regroup_loan_type_cd
,t1.int_rat_float_type_cd as int_rat_float_type_cd
,t1.acct_b_cate_cd as acct_b_cate_cd
,t1.dubil_sell_status_cd as dubil_sell_status_cd
,t1.tran_org_id as tran_org_id
,t1.lc_open_bank_id as lc_open_bank_id
,t1.repl_old_bond_flg as repl_old_bond_flg
,t1.rgst_dt as rgst_dt
,t1.update_dt as update_dt
,t1.agent_present_flg as agent_present_flg
,t1.prob_asset_flg as prob_asset_flg
,t1.cdd_flg as cdd_flg
,t1.sub_prod_id as sub_prod_id
,t1.inpwn_type_cd as inpwn_type_cd
,t1.green_crdt_cls_new as green_crdt_cls_new
,t1.suit_fee_bal as suit_fee_bal

from ${idl_schema}.cmm_corp_loan_dubil_info t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/cmm_corp_loan_dubil_info.f.${batch_date}.dat" \
        charset=utf8
        safe=yes
