: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_iol_crms_crm_cst_gath_info_f
CreateDate: 20180529
FileName:   ${iel_data_path}/crms_crm_cst_gath_info.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.cc_cst_no
,t1.cc_cst_nm
,t1.cc_cst_sys_lvl
,t1.cc_cst_svc_lvl
,t1.cc_sex
,t1.cc_ft_opac_time
,t1.cc_mrtl_stat
,t1.cc_brh_dt
,t1.cc_age
,t1.cc_ntnly
,t1.cc_eth
,t1.cc_ctf_tp
,t1.cc_ctf_no
,t1.cc_ep_flg
,t1.cc_rcmd_cst
,t1.cc_rcmd_user
,t1.cc_mag_cst_mgr
,t1.cc_mag_org
,t1.cc_dbc_lvl
,t1.cc_is_mrcnt
,t1.cc_sys_cm_user
,t1.cc_cst_risk_lv
,replace(replace(t1.cc_concat_cif_cust_no,chr(13),''),chr(10),'') as cc_concat_cif_cust_no
,t1.cc_main_phone
,t1.cc_cur_dpst_hld
,t1.cc_dpt_dpst_hld
,t1.cc_ln_hld
,t1.cc_fnc_hld
,t1.cc_fund_hld
,t1.cce_fund_hld
,t1.cc_ndbt_hld
,t1.cc_psn_tpc_hld
,t1.cc_psn_gold_hld
,t1.cc_mbl_bnk_sgn
,t1.cc_nwrk_bnk_sgn
,t1.cc_tel_bnk_sgn
,t1.cc_sms_sgn
,t1.cc_pyrl_slry_sgn
,t1.cc_agt_pymt_sgn
,t1.cc_dbc_sgn
,t1.cc_9mall_sgn
,t1.cc_500mall_sgn
,t1.cc_fund_vot_flg
,t1.cc_message_bnk_sgn
,t1.cc_it_ab_dpst_sgn
,t1.cc_tmall_ac_sgn
,t1.cc_eac_sgn
,t1.cc_fxb_sp
,t1.cc_auto_inst
,t1.cc_tra_bg
,t1.cc_trs_hld
,t1.cc_aum_bal
,t1.cc_aum_mavg
,t1.cc_aum_qavg
,t1.cc_aum_yavg
,t1.cc_cmn_dept_bal
,t1.cc_cmn_dept_mavg
,t1.cc_cmn_dept_qavg
,t1.cc_cmn_dept_yavg
,t1.cc_sr_fnc
,t1.cc_sr_fnc_mavg
,t1.cc_sr_fnc_qavg
,t1.cc_sr_fnc_yavg
,t1.cc_nsr_fnc
,t1.cc_nsr_fnc_mavg
,t1.cc_nsr_fnc_qavg
,t1.cc_nsr_fnc_yavg
,t1.cc_dept_bal
,t1.cc_dept_mavg
,t1.cc_dept_qavg
,t1.cc_dept_yavg
,t1.cc_fund_bal
,t1.cc_fund_mavg
,t1.cc_fund_qavg
,t1.cc_fund_yavg
,t1.cc_fnc_bal
,t1.cc_fnc_mavg
,t1.cc_fnc_qavg
,t1.cc_fnc_yavg
,t1.cc_tpc_bal
,t1.cc_tpc_mavg
,t1.cc_tpc_qavg
,t1.cc_tpc_yavg
,t1.cc_scl_isfee_bal
,t1.cc_scl_isfee_mavg
,t1.cc_scl_isfee_qavg
,t1.cc_scl_isfee_yavg
,t1.cc_ln_bal
,t1.cc_ln_mavg
,t1.cc_ln_qavg
,t1.cc_ln_yavg
,t1.cc_e_fund_bal
,t1.cc_e_fund_mavg
,t1.cc_e_fund_qavg
,t1.cc_e_fund_yavg
,t1.cc_gold_bal
,t1.cc_gold_mavg
,t1.cc_gold_qavg
,t1.cc_gold_yavg
,t1.cc_nscr_aum_bal
,t1.cc_nscr_aum_mavg
,t1.cc_nscr_aum_qavg
,t1.cc_nscr_aum_yavg
,t1.cc_nscr_cmn_dept_bal
,t1.cc_nscr_cmn_dept_mavg
,t1.cc_nscr_cmn_dept_qavg
,t1.cc_nscr_cmn_dept_yavg
,t1.cc_nscr_sr_fnc
,t1.cc_nscr_sr_fnc_mavg
,t1.cc_nscr_sr_fnc_qavg
,t1.cc_nscr_sr_fnc_yavg
,t1.cc_nscr_nsr_fnc
,t1.cc_nscr_nsr_fnc_mavg
,t1.cc_nscr_nsr_fnc_qavg
,t1.cc_nscr_nsr_fnc_yavg
,t1.cc_nscr_dept_bal
,t1.cc_nscr_dept_mavg
,t1.cc_nscr_dept_qavg
,t1.cc_nscr_dept_yavg
,t1.cc_nscr_fund_bal
,t1.cc_nscr_fund_mavg
,t1.cc_nscr_fund_qavg
,t1.cc_nscr_fund_yavg
,t1.cc_nscr_fnc_bal
,t1.cc_nscr_fnc_mavg
,t1.cc_nscr_fnc_qavg
,t1.cc_nscr_fnc_yavg
,t1.cc_spd_dep
,t1.cc_nscr_ins_bal
,t1.cc_nscr_ins_yavg
,t1.cc_nscr_ins_qavg
,t1.cc_nscr_ins_mavg
,t1.cc_nscr_gld_bal
,t1.cc_nscr_gld_yavg
,t1.cc_nscr_gld_qavg
,t1.cc_nscr_gld_mavg
,t1.cc_pg_bal
,t1.cc_pg_mavg
,t1.cc_pg_qavg
,t1.cc_pg_yavg
,t1.cc_nscr_pg_bal
,t1.cc_nscr_pg_mavg
,t1.cc_nscr_pg_qavg
,t1.cc_nscr_pg_yavg
,t1.cc_ysh_std
,t1.cc_ysh_hld
,t1.cc_phy_gold_hld
,t1.cc_lday_aum_bal_chng
,t1.cc_last_mn_aum_chng
,t1.cc_lyr_aum_bal_chng
,replace(replace(t1.cc_email,chr(13),''),chr(10),'') as cc_email
,replace(replace(t1.cc_contt_cont,chr(13),''),chr(10),'') as cc_contt_cont
,t1.cc_last_mn_aum_mavg_chng
,t1.cc_last_mn_fnc_mavg_chng
,t1.cc_last_mn_sr_fnc_mavg_chng
,t1.cc_last_mn_nsr_fnc_mavg_chng
,t1.cc_last_mn_dept_mavg_chng
,t1.cc_last_mn_nscr_aum_mavg_chng
,t1.cc_last_mn_nscr_fnc_mavg_chng
,t1.last_mn_nscr_sr_fnc_mavg_chng
,t1.last_mn_nscr_nsr_fnc_mavg_chng
,t1.cc_last_mn_nscr_dept_mavg_chng
,t1.cc_pure_tmall_sgn
,t1.cc_mag_cst_mgr_flg
,t1.cc_fnc_sgn
,t1.cc_fund_sgn
,t1.cc_act_lvl
,t1.cc_ctb_lvl
,t1.cc_lyl_lvl
,t1.cc_cst_sys_lvl_chng
,t1.cc_ent_crd_hld
,t1.cc_esp_bal
,t1.cc_esp_mavg
,t1.cc_esp_qavg
,t1.cc_esp_yavg
,t1.cc_emp_shr_plan_hld
,t1.cc_nscr_esp_bal
,t1.cc_nscr_esp_mavg
,t1.cc_nscr_esp_qavg
,t1.cc_nscr_esp_yavg
,t1.cc_psn_tpc_hld_1
,t1.cc_nscr_tpc_bal
,t1.cc_nscr_tpc_mavg
,t1.cc_nscr_tpc_qavg
,t1.cc_nscr_tpc_yavg
,t1.cc_vip_cst_flag
,t1.cc_bak_vip_cst_flag
,t1.cc_bef_mag_cst_mgr
,t1.cc_bef_mag_org
,t1.cc_mov_to_vipcen_dt
,t1.cc_tst_bal
,t1.cc_tst_mavg
,t1.cc_tst_qavg
,t1.cc_tst_yavg
,t1.cc_tst_hld
,t1.cc_sdp_dpst_hld
,t1.cc_sdp_dept_bal
,t1.cc_sdp_dept_mavg
,t1.cc_sdp_dept_qavg
,t1.cc_sdp_dept_yavg
,t1.start_dt
,t1.end_dt
,t1.id_mark
from iol.crms_crm_cst_gath_info t1
where t1.start_dt <= to_date('${batch_date}','yyyymmdd') and t1.end_dt > to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/crms_crm_cst_gath_info.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes