: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_crms_cms_upl_business_putout_f
CreateDate: 20180529
FileName:   ${iel_data_path}/crms_cms_upl_business_putout_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
serialno
,customerid
,customername
,businesstype
,businesscurrency
,businesssum
,termyear
,termmonth
,termday
,putoutdate
,maturity
,businessrate
,ictype
,iccyc
,paycyc
,corpuspaymethod
,subjectno
,dealbegintime
,dealendtime
,dealflag
,operateorgid
,operateuserid
,operatedate
,inputorgid
,inputuserid
,inputdate
,updatedate
,pigeonholedate
,remark
,occurdate
,baseratetype
,ratefloattype
,contractserialno
,duebillserialno
,artificialno
,relativeaccountno
,accountno
,loanaccountno
,loantype
,creditlineflag
,creditaggreement
,contractsum
,purpose
,adjustratetype
,fixcyc
,backrate
,acceptinttype
,preinttype
,resumeinttype
,secondpayaccount
,overinttype
,rateadjustcyc
,guarantyno
,riskrate
,consignaccountno
,mostlyduebillno
,negotiateno
,creditkind
,pdgsum
,pdgaccountno
,pdgpaymethod
,businesssubtype
,businesssubtype1
,exchangetype
,exchangestate
,exchangeserialno
,adjustrateterm
,projectno
,fzaccountno
,fzanbalance
,ccode
,cdate
,fzguabalance
,pztype
,billno
,gatheringname
,aboutbankname
,interserialno
,billresource
,bailaccount
,aboutbankid
,billsum
,ratetype
,billrisk
,openbankname
,openbankadd
,openbankzip
,type1
,type2
,type3
,type4
,type5
,type6
,type7
,aboutbankid2
,aboutbankname2
,aboutbankid3
,name1
,address1
,name2
,address2
,zip2
,address3
,term1
,term2
,term3
,vouchtype
,bailcurrency
,bailratio
,mfeepaymethod
,securitiestype
,type8
,type9
,thirdpartyaccounts
,thirdpartyid1
,ccyc
,loanterm
,relativeputoutno
,multi_loan_flag
,multi_pay_flag
,ass_mode
,trust_pay_flag
,fee_mode
,pay_mode
,act_flag
,repay_mode
,ass_type
,bran_code
,deal_bran_code
,accept_bank_no
,contract_no
,apply_no
,cust_no
,ext_contract_no
,lc_no
,acct_seqno
,bill_no
,lc_code
,trust_loan_acct_no
,bail_acct_no
,pay_acct_no
,release_acct_no
,drawing_acct_no
,payee_acct_no
,cust_acct_no
,loan_class
,new_loan_class
,bill_type
,cust_name
,drawing_name
,payee_acct_name
,accept_name
,ben_acct_name
,functionary
,bail_cur_code
,fee_cur_code
,loan_amt
,trust_charge_amt
,fee
,repay_amt
,credited_amt
,max_quota
,draft_amt
,bill_amt
,start_date
,due_date
,draw_date
,setup_date
,prof_day
,overdraft_day
,ext_day
,int_rate_market
,int_rate_cycle
,nor_int_code
,nor_rate_f_mode
,nor_rate_f_prop
,nor_int_rate
,ext_rate_f_prop
,ext_int_rate
,int_mode
,nor_rate_adj_mode
,ovd_rate_f_prop
,ovd_int_rate
,trust_charge_rate
,fee_rate
,real_int_rate
,prop
,pay_prin_intvl
,max_apply_month
,main_purpose
,payee_bank_no
,payee_bank_name
,bail_amt
,cur_code
,loan_bin
,loan_label
,loan_class_name
,avail_quota
,realtiveapplyserialno
,exchangedate
,deduct_min_amt
,rateserialno
,supply_acct_no
,ext_rafe_f_prop
,agent_flag
,mfcustomerid
,supply_acct_no2
,ext_day2
,ext_rafe_f_prop2
,supply_acct_no3
,ext_day3
,ext_rafe_f_prop3
,supply_acct_no4
,ext_day4
,ext_rafe_f_prop4
,supply_acct_no5
,ext_day5
,ext_rafe_f_prop5
,classify4change
,depositrate
,depositsum
,depositcurrency
,chowmatisticsum
,chowmatisticcurrency
,overfinerate
,chowmatisticrate
,repayplag
,latestpaydays
,elecflag
,discounttype
,interestenddate
,interestdays
,interest
,payinterest
,businessserialno
,elecexchangestate
,paymenttype
,loantermflag
,ratemode
,gaincyc
,gainamount
,mainrepaymentmethod
,repaymentmethod
,incomeorgid
,payaccountno
,putoutstatus
,holdcorpus
,defaultpaydate
,payaccountno1
,payaccountname
,payaccountname1
,amortizeterm
,graceperioddate
,pdgtype
,customstamptax
,loanaccountnotype
,defaultpayacctnotype
,trustaccno
,trustaccname
,trustaccnotype
,trustfundacctno
,trustfundacctname
,designatedate
,cyclemonths
,issmallcorporation
,istiexi
,subsidyprop
,repriceflag
,channelno
,flag7
,farmingtype
,paymentmode
,businesssource
,payaccountno2
,payaccountname2
,clearanceacctnotype
,trustdepositaccnotype
,paloaninsureid
,businessratetype
,payment
,payername
,payerbankname
,payerbankaccounts
,isavouch
,specialaccountno
,uncheckaccountno
,isgroupcredit
,pdgaccountnoname
,dkaccountno
,dkaccountname
,fineratemode
,finerate
,tempsaveflag
,paysource
,contextinfo
,drawingtype
,fineratetype
,fineratefloattype
,normalpayorder
,overduepayorder
,fineratefloat
,baserate
,ratefloat
,batchpaymentflag
,relativeduebillserialno
,clearanceacctno
,clearanceacctname
,loankind
,gjjratemode
,gjjbaseratetype
,gjjratefloattype
,gjjbaserate
,gjjratefloat
,gjjbusinessrate
,gjjrepaymentmethod
,gjjpaycyc
,gjjadjustratetype
,gjjgaincyc
,gjjgainamount
,gjjholdcorpus
,gjjamortizeterm
,gjjbusinesssum
,gjjmainrepaymentmethod
,gjjgraceperioddate
,gjjcyclemonths
,gjjdesignatedate
,sybusinesssum
,gjjfineratetype
,gjjfinerate
,gjjfineratemode
,gjjfineratefloattype
,gjjfineratefloat
,assistuserid
,relativebpserialno
,curtype
,payaccountnoattr
,trustaccountnoattr
,paymode
,issignuplloan
,repaymentplanflag
,userid
,begintime
,actualbegintime
,endtime
from ${idl_schema}.crms_cms_upl_business_putout
where etl_dt=to_date('${batch_date}','yyyymmdd');" \
        field="|#|" record="0x0a"  \
        file="${iel_data_path}/crms_cms_upl_business_putout_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes