: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idf_cmm_corp_loan_cont_info_f
CreateDate: 20250509
FileName:   ${iel_data_path}/cmm_corp_loan_cont_info.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.lp_id as lp_id
,t1.cont_id as cont_id
,t1.cust_id as cust_id
,t1.lmt_cont_id as lmt_cont_id
,t1.apv_flow_num as apv_flow_num
,t1.manu_cont_id as manu_cont_id
,t1.bus_breed_id as bus_breed_id
,t1.bus_sub_type_cd as bus_sub_type_cd
,t1.loan_happ_type_cd as loan_happ_type_cd
,t1.cont_type_cd as cont_type_cd
,t1.strtg_new_indus_type_cd as strtg_new_indus_type_cd
,t1.prod_type_cd as prod_type_cd
,t1.valid_flg_cd as valid_flg_cd
,t1.dir_indus_cd as dir_indus_cd
,t1.surp_indus_cd as surp_indus_cd
,t1.sub_guar_way_cd as sub_guar_way_cd
,t1.guar_type_cd as guar_type_cd
,t1.major_guar_way_cd as major_guar_way_cd
,t1.crdt_type_cd as crdt_type_cd
,t1.appl_way_cd as appl_way_cd
,t1.loan_fin_supt_way_cd as loan_fin_supt_way_cd
,t1.invest_way_cd as invest_way_cd
,t1.mgmt_mode_cd as mgmt_mode_cd
,t1.loan_level5_cls_cd as loan_level5_cls_cd
,t1.loan_level10_cls_cd as loan_level10_cls_cd
,t1.tenor_type_cd as tenor_type_cd
,t1.pric_repay_way_cd as pric_repay_way_cd
,t1.int_rat_float_way_cd as int_rat_float_way_cd
,t1.charge_way_cd as charge_way_cd
,t1.draw_way_cd as draw_way_cd
,t1.cap_src_cd as cap_src_cd
,t1.int_rat_adj_way_cd as int_rat_adj_way_cd
,t1.curr_cd as curr_cd
,t1.sup_chain_fin_bus_prod_cls_cd as sup_chain_fin_bus_prod_cls_cd
,t1.sup_chain_fin_bus_flg as sup_chain_fin_bus_flg
,t1.agent_patip_loan_flg as agent_patip_loan_flg
,t1.lmt_circl_flg as lmt_circl_flg
,t1.circl_flg as circl_flg
,t1.temp_store_flg as temp_store_flg
,t1.froz_flg as froz_flg
,t1.turn_crdt_flg as turn_crdt_flg
,t1.remote_loan_flg as remote_loan_flg
,t1.other_guar_way_flg as other_guar_way_flg
,t1.imp_proj_loan_flg as imp_proj_loan_flg
,t1.cty_lmt_indus_flg as cty_lmt_indus_flg
,t1.gover_crdt_flg as gover_crdt_flg
,t1.cdb_crdt_flg as cdb_crdt_flg
,t1.fix_asset_crdt_flg as fix_asset_crdt_flg
,t1.qual_centr_cntpty_flg as qual_centr_cntpty_flg
,t1.low_risk_bus_flg as low_risk_bus_flg
,t1.host_bank_no as host_bank_no
,t1.patip_loan_bank_no as patip_loan_bank_no
,t1.agent_bank_no as agent_bank_no
,t1.cntpty_strg as cntpty_strg
,t1.cntpty_co_years as cntpty_co_years
,t1.cntpty_sucs_tran_cnt as cntpty_sucs_tran_cnt
,t1.mgmt_org_id as mgmt_org_id
,t1.rgst_org_id as rgst_org_id
,t1.oper_org_id as oper_org_id
,t1.distr_org_id as distr_org_id
,t1.mgmt_teller_id as mgmt_teller_id
,t1.oper_teller_id as oper_teller_id
,t1.rgst_teller_id as rgst_teller_id
,t1.start_dt as start_dt
,t1.distr_dt as distr_dt
,t1.exp_dt as exp_dt
,t1.oper_dt as oper_dt
,t1.rgst_dt as rgst_dt
,t1.termnt_dt as termnt_dt
,t1.lmt_use_latest_dt as lmt_use_latest_dt
,t1.lmt_under_bus_latest_exp_dt as lmt_under_bus_latest_exp_dt
,t1.loan_usage_descb as loan_usage_descb
,t1.repay_src_descb as repay_src_descb
,t1.other_cond_request_descb as other_cond_request_descb
,t1.trdpty_cust_name1 as trdpty_cust_name1
,t1.trdpty_cust_name2 as trdpty_cust_name2
,t1.rela_cont_id as rela_cont_id
,t1.stl_acct_num as stl_acct_num
,t1.margin_acct_num as margin_acct_num
,t1.margin_curr_cd as margin_curr_cd
,t1.margin_ratio as margin_ratio
,t1.margin_amt as margin_amt
,t1.tran_market_type_cd as tran_market_type_cd
,t1.incre_crdt_way_cd as incre_crdt_way_cd
,t1.batch_data_src_cd as batch_data_src_cd
,t1.backup_lmt_effect_cd as backup_lmt_effect_cd
,t1.backup_lmt_cont_id as backup_lmt_cont_id
,t1.risk_type_cd as risk_type_cd
,t1.major_loan_cls_cd as major_loan_cls_cd
,t1.risk_expose_cls as risk_expose_cls
,t1.tran_asset_name as tran_asset_name
,t1.dir_ind_fund_flg as dir_ind_fund_flg
,t1.dir_makti_debt_eqty_flg as dir_makti_debt_eqty_flg
,t1.invo_gover_class_fin_flg as invo_gover_class_fin_flg
,t1.consm_serv_class_fin_flg as consm_serv_class_fin_flg
,t1.stl_dep_flg as stl_dep_flg
,t1.cota_opt_choice_flg as cota_opt_choice_flg
,t1.septbl_flg as septbl_flg
,t1.onl_bus_flg as onl_bus_flg
,t1.class_crdt_flg as class_crdt_flg
,t1.crdt_bus_flow_type_cd as crdt_bus_flow_type_cd
,t1.crdt_rg_cd as crdt_rg_cd
,t1.estate_fin_flg as estate_fin_flg
,t1.gover_class_fin_flg1 as gover_class_fin_flg1
,t1.br_build_ifin_flg as br_build_ifin_flg
,t1.green_crdt_fin_flg as green_crdt_fin_flg
,t1.trade_cont_id as trade_cont_id
,t1.trade_cont_curr_cd as trade_cont_curr_cd
,t1.trade_cont_amt as trade_cont_amt
,t1.bill_qtty as bill_qtty
,t1.discnt_bf_revw_flg as discnt_bf_revw_flg
,t1.discnt_int_buyer_bear_ratio as discnt_int_buyer_bear_ratio
,t1.discnt_int_applit_pay_ratio as discnt_int_applit_pay_ratio
,t1.agt_pay_int_flg as agt_pay_int_flg
,t1.bill_uniq_idf_id as bill_uniq_idf_id
,t1.trdpty_acct_id as trdpty_acct_id
,t1.loan_src_cd as loan_src_cd
,t1.comm_fee_rat as comm_fee_rat
,t1.comm_fee_amt as comm_fee_amt
,t1.lc_id as lc_id
,t1.lc_amt as lc_amt
,t1.syn_loan_distr_amt as syn_loan_distr_amt
,t1.tenor as tenor
,t1.base_rat as base_rat
,t1.int_rat_flo_val as int_rat_flo_val
,t1.exec_int_rat as exec_int_rat
,t1.bank_fin_tot as bank_fin_tot
,t1.open_bal as open_bal
,t1.cont_amt as cont_amt
,t1.cont_aval_bal as cont_aval_bal
,t1.acm_distr_amt as acm_distr_amt
,t1.acm_callbk_amt as acm_callbk_amt
,t1.occu_crdt_lmt as occu_crdt_lmt
,t1.surp_crdt_lmt as surp_crdt_lmt
,t1.entr_loan_espec_dir_cd as entr_loan_espec_dir_cd
,t1.underly_prod_cls_flg as underly_prod_cls_flg
,t1.underly_prod_cls_lev_cd as underly_prod_cls_lev_cd
,t1.estate_loan_type_cd as estate_loan_type_cd
,t1.final_dir_type_cd as final_dir_type_cd
,t1.pente_type_cd as pente_type_cd
,t1.underly_prod_coll_amt as underly_prod_coll_amt
,t1.file_int_accr_flg as file_int_accr_flg
,t1.ibank_bond_id as ibank_bond_id
,t1.trast_chn_cd as trast_chn_cd
,t1.syn_loan_tot_amt as syn_loan_tot_amt
,t1.agclt_flg as agclt_flg
,t1.agclt_loan_main_type_cd as agclt_loan_main_type_cd
,t1.agclt_loan_dir_cd as agclt_loan_dir_cd
,t1.plat_solv_cap_src_cd as plat_solv_cap_src_cd
,t1.buid_bus_guar_loan_flg as buid_bus_guar_loan_flg
,t1.buid_bus_guar_loan_type_cd as buid_bus_guar_loan_type_cd
,t1.ibank_tran_org_id as ibank_tran_org_id
,t1.out_acct_flg as out_acct_flg
,t1.asset_thd_cls_cd as asset_thd_cls_cd
,t1.secd_guar_way_cd as secd_guar_way_cd
,t1.imp_loan_proj as imp_loan_proj
,t1.fin_sys_cont_flg as fin_sys_cont_flg
,t1.loan_enter_acct_acct_num as loan_enter_acct_acct_num
,t1.base_rat_type_cd as base_rat_type_cd
,t1.int_rat_mode_cd as int_rat_mode_cd
,t1.rsrv_amt as rsrv_amt
,t1.std_prod_id as std_prod_id
,t1.ibank_asset_uniq_idf_id as ibank_asset_uniq_idf_id
,t1.aplv_flow_num as aplv_flow_num

from ${idl_schema}.cmm_corp_loan_cont_info t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/cmm_corp_loan_cont_info.f.${batch_date}.dat" \
        charset=utf8
        safe=yes
