: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_rpt_mpcs_a08tbetrx_i
CreateDate: 20180529
FileName:   ${iel_data_path}/rpt_mpcs_a08tbetrx.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select
 t1.mainsq as mainsq
,t1.opersq as opersq
,t1.businesstrace as businesstrace
,t1.bustype as bustype
,t1.servtype as servtype
,t1.dtlcmtno as dtlcmtno
,t1.transseq as transseq
,t1.pkcodt as pkcodt
,t1.pktype as pktype
,t1.hosttrcd as hosttrcd
,t1.fronttrcd as fronttrcd
,t1.transdt as transdt
,t1.consigndt as consigndt
,t1.hostdate as hostdate
,t1.hostnbr as hostnbr
,t1.crcycd as crcycd
,t1.transamt as transamt
,t1.paybrn as paybrn
,t1.payopenbrn as payopenbrn
,t1.payacct as payacct
,t1.payname as payname
,t1.payaddr as payaddr
,t1.incobrn as incobrn
,t1.incoacct as incoacct
,t1.inconame as inconame
,t1.incoaddr as incoaddr
,t1.sndct as sndct
,t1.sndupbrn as sndupbrn
,t1.sndbrn as sndbrn
,t1.rcvct as rcvct
,t1.rcvupbrn as rcvupbrn
,t1.rcvbrn as rcvbrn
,t1.billdt as billdt
,t1.billcd as billcd
,t1.orabustype as orabustype
,t1.ptrasq as ptrasq
,t1.obaltp as obaltp
,t1.obalod as obalod
,t1.obaldt as obaldt
,t1.caclrs as caclrs
,t1.cmpsam as cmpsam
,t1.inrate as inrate
,t1.refuam as refuam
,t1.transt as transt
,t1.processcode as processcode
,t1.advest as advest
,t1.vrseal as vrseal
,t1.ckrvno as ckrvno
,t1.rndday as rndday
,t1.retudt as retudt
,t1.sdrvno as sdrvno
,t1.clerdt as clerdt
,t1.bperno as bperno
,t1.bpermg as bpermg
,t1.levels as levels
,t1.oprtlr as oprtlr
,t1.chktlr as chktlr
,t1.sndtlr as sndtlr
,t1.auttlr as auttlr
,t1.stptlr as stptlr
,t1.oprbrn as oprbrn
,t1.sendbranch as sendbranch
,t1.autbrn as autbrn
,t1.recdes as recdes
,t1.chksta as chksta
,t1.remark as remark
,t1.protocolnb as protocolnb
,t1.prtcnt as prtcnt
,t1.recvdt as recvdt
,t1.transmitdt as transmitdt
,t1.blsecd as blsecd
,t1.paydat as paydat
,t1.iotype as iotype
,t1.flag2 as flag2
,t1.flag3 as flag3
,t1.flag4 as flag4
,t1.inoutflag as inoutflag
,t1.blrqno as blrqno
,t1.sacact as sacact
,t1.sacana as sacana
,t1.clendt as clendt
,t1.clenus as clenus
,t1.clrbrn as clrbrn
,t1.clract as clract
,t1.clrseq as clrseq
,t1.prdnbr as prdnbr
,t1.tranbr as tranbr
,t1.sdtrno as sdtrno
,t1.bkcode as bkcode
,t1.cobkdt as cobkdt
,t1.cobkcd as cobkcd
,t1.idtype as idtype
,t1.idno as idno
,t1.mxtram as mxtram
,t1.transq as transq
,t1.sdtrsq as sdtrsq
,t1.paymod as paymod
,t1.opnwin as opnwin
,t1.chngdt as chngdt
,t1.bepssq as bepssq
,t1.linkid as linkid
,t1.feamt1 as feamt1
,t1.feamt2 as feamt2
,t1.feamt3 as feamt3
,t1.feamt4 as feamt4
,t1.priamt as priamt
,t1.payamt as payamt
,t1.spiamt as spiamt
,t1.edhtno as edhtno
,t1.edhtdt as edhtdt
,t1.endtlr as endtlr
,t1.chngti as chngti
,t1.magbrn as magbrn
,t1.resv40 as resv40
,t1.rcdver as rcdver
,t1.rcdsta as rcdsta
,t1.prpktp as prpktp
,t1.prclbk as prclbk
,t1.prpkdt as prpkdt
,t1.prpksq as prpksq
,t1.prodcd as prodcd
,t1.isinout as isinout
,t1.inacct as inacct
,t1.inname as inname
,t1.ourcnapsver as ourcnapsver
,t1.othercnapsver as othercnapsver
,t1.landdealsts as landdealsts
,t1.checkdealsts as checkdealsts
,t1.appenddatatable as appenddatatable
,t1.appenddatadtltab as appenddatadtltab
,t1.hangupreason as hangupreason
,t1.pkgbusinesstrace as pkgbusinesstrace
,t1.pktype2 as pktype2
,t1.bustype2 as bustype2
,t1.servtype2 as servtype2
,t1.payopenbanknm as payopenbanknm
,t1.recvopenbanknm as recvopenbanknm
,t1.modifytlr as modifytlr
,t1.feetype as feetype
,t1.eaccflg as eaccflg
,t1.od_flag as od_flag
,t1.od_ovtranam as od_ovtranam
,t1.nextdayflag as nextdayflag
,t1.autoflag as autoflag
,t1.autocount as autocount
,t1.automsg as automsg
,t1.bindacct as bindacct
,t1.bindacctnm as bindacctnm
,t1.accttype as accttype
,t1.bindacctopnbrn as bindacctopnbrn
,t1.lsttranst as lsttranst
,t1.tacctp as tacctp
,t1.limitorderid as limitorderid
,t1.isbindcard as isbindcard
,t1.globalseqno as globalseqno
,t1.returncode as returncode
,t1.returnmsg as returnmsg
,t1.transseqno as transseqno
,t1.sendouttm as sendouttm
,t1.finaccountid as finaccountid
,t1.acct_typ_id as acct_typ_id
,t1.memocntt as memocntt
 from idl.mpcs_a08tbetrx T1
where transdt='${batch_date}' and t1.etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/rpt_mpcs_a08tbetrx.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes