: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_gzfh_tbproduct_f
CreateDate: 20180529
FileName:   ${iel_data_path}/gzfh_tbproduct_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select prd_code
,model_flag
,model_comment
,prd_type
,ta_code
,prd_name
,prd_name2
,vol_digit
,amt_digit
,nav_digit
,nav
,nav_date
,nav_days
,face_value
,iss_price
,asso_code
,prd_sponsor
,prd_trustee
,prd_manager
,dep_id
,branch_no
,ipo_start_date
,ipo_end_date
,estab_date
,income_date
,end_date
,interest_end_date
,income_end_date
,issue_fail_date
,alimit_end_date
,real_estab_date
,prd_min_bala
,prd_max_bala
,prd_min_shares
,prd_max_shares
,prd_issue_real_bala
,curr_scale
,div_modes
,div_mode
,inst_flag
,limit_flag
,liqu_mode
,liqu_mode2
,channels
,client_groups
,temp_flag
,control_flag
,control_flag2
,share_class
,issue_cfm_rate
,sub_mode
,sub_exp
,interest_way
,prd_attr
,risk_level
,grade
,status
,conv_flag
,prd_totvol
,tot_nav
,curr_type
,cost_curr_type
,income_curr_type
,cash_flag
,agio_type
,open_time
,close_time
,paper_no
,paper_name
,protocol_name
,psub_unit
,pfirst_amt
,papp_amt
,pmin_invest_amt
,pmin_hold
,pmin_red
,pmax_red
,pred_unit
,pmin_conv_vol
,pmin_red_vol
,pmax_amt
,pmax_accu_amt
,osub_unit
,ofirst_amt
,oapp_amt
,omin_invest_amt
,omin_hold
,omin_red
,omax_red
,ored_unit
,omin_conv_vol
,omin_red_vol
,omax_amt
,omax_accu_amt
,tot_client
,ipo_time
,order_date
,order_time
,book_buy_days
,book_sell_days
,book_buy_date
,book_sell_date
,dir_order_type
,dir_hold_day
,dir_free_date
,dir_start_date
,dir_start_time
,invest_fail_times
,debit_account
,crebit_account
,red_draw_account
,charge_account
,manage_account
,red_days
,div_days
,refund_days
,fail_days
,open_buy_days
,red_arr_date
,div_arr_date
,refund_arr_date
,fail_arr_date
,open_arr_date
,large_buy_rate
,large_red_rate
,real_red_amt_rate
,real_red_vol_rate
,real_red_max_vol
,base_days
,interest_days
,manage_days
,red_fare_rate
,conv_fare_rate
,manage_rate
,total_bonus
,cash_rate
,money_date
,corpus_rate
,evend_date
,tn_confirm
,guest_rate
,cycle_days
,trans_way
,int1
,int2
,amt1
,amt2
,amt3
,reserve1
,reserve2
,reserve3
,reserve4
,reserve5 from  ${idl_schema}.gzfh_tbproduct where etl_dt =to_date('${batch_date}','yyyymmdd');" \
        field="|#|" record="0x0a"  \
        file="${iel_data_path}/gzfh_tbproduct_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes