: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_odss_business_contract_f
CreateDate: 20180529
FileName:   ${iel_data_path}/odss_business_contract_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select serialno
   ,relativeserialno
   ,artificialno
   ,occurdate
   ,customerid
   ,customername
   ,businesstype
   ,oldbusinesstype
   ,businesssubtype
   ,occurtype
   ,creditdigest
   ,creditcycle
   ,credittype
   ,currenylist
   ,currencymode
   ,businesstypelist
   ,calculatemode
   ,useorglist
   ,flowreduceflag
   ,contractflag
   ,subcontractflag
   ,selfuseflag
   ,creditindex
   ,creditreducesum
   ,limitationterm
   ,useterm
   ,creditaggreement
   ,relativeagreement
   ,loanflag
   ,totalsum
   ,ourrole
   ,reversibility
   ,billnum
   ,housetype
   ,lctermtype
   ,riskattribute
   ,suretype
   ,safeguardtype
   ,creditbusiness
   ,businesscurrency
   ,businesssum
   ,businessprop
   ,termyear
   ,termmonth
   ,termday
   ,lgterm
   ,baseratetype
   ,baserate
   ,ratefloattype
   ,ratefloat
   ,businessrate
   ,ictype
   ,iccyc
   ,pdgratio
   ,pdgsum
   ,pdgpaymethod
   ,pdgpayperiod
   ,promisesfeeratio
   ,promisesfeesum
   ,promisesfeeperiod
   ,promisesfeebegin
   ,mfeeratio
   ,mfeesum
   ,mfeepaymethod
   ,agentfee
   ,dealfee
   ,totalcast
   ,discountinterest
   ,purchaserinterest
   ,bargainorinterest
   ,discountsum
   ,bailratio
   ,bailcurrency
   ,bailsum
   ,bailaccount
   ,fineratetype
   ,finerate
   ,drawingtype
   ,firstdrawingdate
   ,drawingperiod
   ,paytimes
   ,paycyc
   ,graceperiod
   ,overdraftperiod
   ,oldlcno
   ,oldlctermtype
   ,oldlccurrency
   ,oldlcsum
   ,oldlcloadingdate
   ,oldlcvaliddate
   ,direction
   ,purpose
   ,planallocation
   ,immediacypaysource
   ,paysource
   ,corpuspaymethod
   ,interestpaymethod
   ,putoutdate
   ,maturity
   ,thirdparty1
   ,thirdpartyid1
   ,thirdparty2
   ,thirdpartyid2
   ,thirdparty3
   ,thirdpartyid3
   ,thirdpartyregion
   ,thirdpartyaccounts
   ,cargoinfo
   ,projectname
   ,operationinfo
   ,contextinfo
   ,securitiestype
   ,securitiesregion
   ,constructionarea
   ,usearea
   ,flag1
   ,flag2
   ,flag3
   ,tradecontractno
   ,invoiceno
   ,tradecurrency
   ,tradesum
   ,lcno
   ,paymentdate
   ,operationmode
   ,begindate
   ,enddate
   ,vouchclass
   ,vouchtype
   ,vouchtype1
   ,vouchtype2
   ,vouchflag
   ,warrantor
   ,warrantorid
   ,othercondition
   ,guarantyvalue
   ,guarantyrate
   ,baseevaluateresult
   ,riskrate
   ,lowrisk
   ,otherarealoan
   ,lowriskbailsum
   ,applytype
   ,originalputoutdate
   ,extendtimes
   ,lngotimes
   ,golntimes
   ,drtimes
   ,guarantyno
   ,putoutsum
   ,actualputoutsum
   ,balance
   ,normalbalance
   ,overduebalance
   ,dullbalance
   ,badbalance
   ,interestbalance1
   ,interestbalance2
   ,finebalance1
   ,finebalance2
   ,overduedays
   ,oweinterestdays
   ,tabalance
   ,tainterestbalance
   ,tatimes
   ,lcatimes
   ,pbinterestsum
   ,pbmfeesum
   ,pbpdgsum
   ,pblegalcostsum
   ,polegalcostsum
   ,originalbaddate
   ,baseclassifyresult
   ,classifyresult
   ,classifytype
   ,classifydate
   ,classifyorgid
   ,reservesum
   ,expectlosssum
   ,bailrate
   ,finishorg
   ,finishtype
   ,finishdate
   ,describe1
   ,reinforceflag
   ,manageorgid
   ,manageuserid
   ,recoveryorgid
   ,recoveryuserid
   ,statorgid
   ,statuserid
   ,operateorgid
   ,operateuserid
   ,operatedate
   ,inputorgid
   ,inputuserid
   ,inputdate
   ,updatedate
   ,pigeonholedate
   ,remark
   ,flag4
   ,paycurrency
   ,paydate
   ,flag5
   ,classifysum1
   ,classifysum2
   ,classifysum3
   ,classifysum4
   ,classifysum5
   ,shifttype
   ,operatetype
   ,fundsource
   ,cycleflag
   ,creditfreezeflag
   ,shiftbalance
   ,classifyfrequency
   ,classifylevel
   ,vouchnewflag
   ,actualartificialno
   ,deleteflag
   ,accountno
   ,loanaccountno
   ,secondpayaccount
   ,adjustratetype
   ,adjustrateterm
   ,overinttype
   ,rateadjustcyc
   ,pdgaccountno
   ,deductdate
   ,fzanbalance
   ,acceptinttype
   ,ratio
   ,thirdpartyadd1
   ,thirdpartyzip1
   ,thirdpartyadd2
   ,thirdpartyzip2
   ,thirdpartyadd3
   ,thirdpartyzip3
   ,effectarea
   ,termdate1
   ,termdate2
   ,termdate3
   ,fixcyc
   ,describe2
   ,cancelsum
   ,cancelinterest
   ,loanterm
   ,putoutorgid
   ,tempsaveflag
   ,overduedate
   ,oweinterestdate
   ,freezeflag
   ,approvedate
   ,shiftstatus
   ,recoverycognorgid
   ,recoverycognuserid
   ,shiftdocdescribe
   ,guarantyflag
   ,totalbalance
   ,grouplineid
   ,transformtimes
   ,transformflag
   ,fundbackaccount
   ,requitalaccount
   ,paymentmode
   ,classifyresulteleven
   ,interestrateexplain
   ,guarantytype
   ,creditmode
   ,mainreturntype
   ,effectflag
   ,creditattribute
   ,isnewcustomertime
   ,isnewcustomer
   ,hasbothflag
   ,fundserialno
   ,ctogetherborrower
   ,csinglnassure
   ,guarantyhouse
   ,formerserialno
   ,abysum
   ,loadrelabarcode
   ,loanrelacontractno
   ,betterrateflag
   ,goldflag
   ,applyinsuranceflag
   ,sendchitflag
   ,introducerid
   ,presignflag
   ,signaddress
   ,sealtype
   ,oapproveflag
   ,operateusermind
   ,preapproverid
   ,buyaddress
   ,gracetermpay
   ,graceterm
   ,gracetermflag
   ,ratecode
   ,gaincyc
   ,gainamount
   ,calcterm
   ,returntype
   ,holdbalance
   ,returnperiod
   ,loantermflag
   ,schemeno
   ,ltvvalue
   ,ratemode
   ,otherpurpose
   ,cycleratio
   ,cguarantypeople
   ,buyhousetype
   ,buyhouseproperty
   ,houseareage
   ,housecount
   ,industrytype
   ,isfinance
   ,isimportantloan
   ,importantloan
   ,gshy
   ,sfgjxzhy
   ,zfsxfs
   ,zfsxlx
   ,sfzfsx
   ,gksxpz
   ,sfgksx
   ,ifgudingcredit
   ,benefitarea
   ,ifqueryflag
   ,lastclassifyresult
   ,mainproduct
   ,useproduct
   ,penalizeratesign
   ,financesupportmode
   ,rategenre
   ,ifagreementflag
   ,loanquality
   ,yearratebase
   ,penalizerateratio
   ,purchaserpaymentscale
   ,loanratio
   ,bearratio
   ,proposerpaymentscale
   ,compoundinterestratio
   ,tradeflag
   ,paymentname
   ,houseprice
   ,pawnremitratio
   ,pawnremitdate
   ,pawnremitsum
   ,loadingdate
   ,chargetype
   ,offerbilldate
   ,restbalancesum
   ,hasoutradio
   ,outradio
   ,terminateflag
   ,paystatus
   ,executestatus
   ,otherexecutestatus
   ,terminatestatus
   ,terminatereason
   ,inputdate1
   ,aggreementcontractputoutflag
   ,oldcreditline
   ,relativeserialno2
   ,lcsum
   ,carbrand
   ,cartype
   ,carnumber
   ,chariotnumber
   ,motornumber
   ,printeruserid
   ,whetherhousemortgage
   ,housenum
   ,houseadd
   ,buyhousedetail
   ,relativeapplyserialno
   ,thirdparty1type
   ,thirdorgname
   ,loansource
from ${idl_schema}.odss_business_contract
where etl_dt = TO_DATE('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/odss_business_contract_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes