: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_icrm_agt_loan_cont_info_f
CreateDate: 20180529
FileName:   ${iel_data_path}/icrm_agt_loan_cont_info.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select agt_id
,lp_id
,cont_id
,rela_apprv_flow_num
,happ_dt
,party_id
,bus_breed_id
,bus_sub_type_cd
,happ_type_cd
,lmt_circl_flg
,bank_fin_tot
,bill_qtty
,curr_cd
,cont_amt
,tenor_mon
,base_rat
,int_rat_type_cd
,int_rat_flo_val
,exec_int_rat
,charge_way_cd
,comm_fee_ratio
,comm_fee_amt
,margin_ratio
,margin_curr_cd
,margin_amt
,margin_acct_id
,pnlt_int_rat
,draw_way_cd
,init_lc_tenor_type_cd
,loan_dir_indus_cd
,loan_usage_descb
,repay_src_descb
,distr_dt
,exp_dt
,trdpty_cust_name1
,trdpty_cust_name2
,trdpty_acct_id
,rela_trade_cont_id
,trade_cont_amt
,lc_id
,main_guar_way_cd
,guar_way_cd1
,guar_way_cd2
,other_guar_way_flg
,major_guartor_name
,major_guartor_id
,low_risk_bus_flg
,remote_loan_flg
,appl_way_cd
,distrd_loan_amt
,curr_bal
,nomal_bal
,ovdue_bal
,idle_bal
,bad_debt_bal
,in_bs_over_int_bal
,off_bs_over_int_bal
,pric_pnlt
,int_pnlt
,level5_cls_cd
,termnt_dt
,mgmt_org_id
,mgmt_teller_id
,oper_org_id
,oper_teller_id
,oper_dt
,rgst_org_id
,rgst_teller_id
,rgst_dt
,modif_dt
,cap_src_cd
,circl_flg
,lmt_froz_flg
,actl_text_cont_id
,stl_acct_id
,loan_enter_acct_acct_id
,int_rat_adj_way_cd
,tenor
,distr_org_id
,temp_store_flg
,froz_flg
,expos_bal
,turn_crdt_flg
,mode_pay_cd
,level11_cls_cd
,guar_type_cd
,crdt_type_cd
,valid_flg
,cont_type_cd
,loan_insure_flg
,ic_way_cd
,repay_ped_cd
,int_rat_exec_way_cd
,loan_other_usage_descb
,sup_chain_fin_mode_bus_flg
,imp_proj_loan_flg
,surp_indus_cd
,cty_lmt_indus_flg
,gover_crdt_flg
,cdb_crdt_flg
,fix_asset_crdt_flg
,discnt_bf_revw_flg
,pnlt_flg
,loan_fin_supt_way_cd
,agt_pay_int_flg
,negot_int_rat
,negot_amt
,loan_distr_status_cd
,termnt_cont_rs_rgst_dt
,rela_cont_flow_num
,lc_amt
,loan_src_cd
,cont_invalid_dt
,backup_effect_flg
,crdt_cont_id
,matn_flg
,risk_type_cd
,syn_loan_distr_amt
,actl_fin_ps_id
,invest_way_cd
,dir_ind_fund_flg
,dir_makti_debt_eqty_flg
,invo_gover_class_fin_flg
,consm_serv_class_fin_flg
,stl_dep_flg
,cota_opt_choice_flg
,septbl_flg
,tran_asset_name
,crdt_bus_flow_type_cd
,batch_data_src_cd
,crdt_rg_cd
,estate_fin_flg
,invo_gover_class_fin_flg1
,consm_serv_class_fin_flg1
,br_build_ifin_flg
,green_crdt_fin_flg
,onl_bus_flg
,class_crdt_flg
,lmt_use_latest_dt
,lmt_under_bus_latest_exp_dt
,lmt_cont_id
,trade_cont_curr
,other_cond_request
,secd_repay_acct_id
,use_prod_cd
,discnt_int_buyer_bear_ratio
,discnt_int_applit_pay_ratio
,major_loan_cls_cd
,risk_expose_cls
,qual_centr_cntpty_flg
,mgmt_mode_cd
,tran_market_type_cd
,incre_crdt_way_cd
,bill_uniq_idf
,is_sup_chain_fin_bus_flg
,sup_chain_fin_bus_prod_cls_cd
,unify_repay_day
,etl_dt
,job_cd from idl.icrm_agt_loan_cont_info where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/icrm_agt_loan_cont_info.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes