: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_hdws_mpcs_a08thvtrx_i
CreateDate: 20180529
FileName:   ${iel_data_path}/hdws_mpcs_a08thvtrx.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select t1.mainseq
,t1.transseq
,t1.businesstrace
,t1.cmtno
,t1.hosttrcd
,t1.fronttrcd
,t1.transdt
,t1.consigndt
,t1.hostdate
,t1.hostnbr
,t1.ccynbr
,t1.transamt
,t1.spbrn
,t1.sndct
,t1.sndupbrn
,t1.sndbrn
,t1.paybrn
,t1.payopenbrn
,t1.payopenbanknm
,t1.payacct
,t1.payname
,t1.payaddr
,t1.rcvct
,t1.rcvupbrn
,t1.rcvbrn
,t1.incobrn
,t1.recvopenbanknm
,t1.incoacct
,t1.inconame
,t1.incoaddr
,t1.servtype
,t1.bustype
,t1.billdt
,t1.billcode
,t1.orasndbrn
,t1.oracmtno
,t1.cmpsamt
,t1.inrate
,t1.refuseamt
,t1.status
,t1.processcode
,t1.varseal
,t1.ckrvnbr
,t1.sndrvnbr
,t1.cleardt
,t1.errcode
,t1.errms
,t1.levels
,t1.oprtlr
,t1.chktlr
,t1.sndtlr
,t1.auttlr
,t1.stoptlr
,t1.oprbrn
,t1.sndtlrbrn
,t1.autbrn
,t1.seccode
,t1.chkstatus
,t1.info
,t1.note
,t1.note2
,t1.prtcnt
,t1.rcvdt
,t1.transmitdt
,t1.billseccode
,t1.paydt
,t1.wlflag
,t1.flag2
,t1.flag3
,t1.flag4
,t1.billrqcode
,t1.sacacct
,t1.sacname
,t1.crdt
,t1.crtlr
,t1.crbrn
,t1.cracct
,t1.crseq
,t1.prodnbr
,t1.tracenbr
,t1.sndtracenbr
,t1.bookcode
,t1.bookdate
,t1.bookseqno
,t1.idtype
,t1.idno
,t1.maxtransamt
,t1.transnbr
,t1.sndtransnbr
,t1.changtime
,t1.reserv40
,t1.rcdver
,t1.rcdstatus
,t1.paymod
,t1.openwintype
,t1.changdate
,t1.servnbr
,t1.magebrn
,t1.feeamt
,t1.feeamt1
,t1.feeamt2
,t1.feeamt3
,t1.linkid
,t1.endtlr
,t1.edhostnbr
,t1.edhostdt
,t1.prodcd
,t1.isinout
,t1.inacct
,t1.inname
,t1.ourcnapsver
,t1.othercnapsver
,t1.landdealsts
,t1.checkdealsts
,t1.appenddatatable
,t1.hangupreason
,t1.modifytlr
,t1.info2
,t1.cmtno2
,t1.bustype2
,t1.servtype2
,t1.feetype
,t1.eaccflg
,t1.srcsysssn
,t1.od_flag
,t1.od_ovtranam
,t1.nextdayflag
,t1.crotransamt
,t1.autoflag
,t1.autocount
,t1.automsg
,t1.bindacct
,t1.bindacctnm
,t1.accttype
,t1.bindacctopnbrn
,t1.tacctp
,t1.limitorderid
,t1.globalseqno
,t1.returncode
,t1.returnmsg
,t1.transseqno
,t1.sendouttm
,t1.acct_typ_id
,t1.finaccountid
,t1.memocntt
,t1.agtflg
,t1.agtidtp
,t1.agtidno
,t1.agtname
,t1.agtphone
from ${idl_schema}.hdws_mpcs_a08thvtrx t1 
where etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/hdws_mpcs_a08thvtrx.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes