: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_cmm_corp_loan_acct_info_f
CreateDate: 20241010
FileName:   ${iel_data_path}/cmm_corp_loan_acct_info.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.lp_id as lp_id
,t1.acct_id as acct_id
,t1.acct_name as acct_name
,t1.cust_id as cust_id
,t1.cont_id as cont_id
,t1.dubil_num as dubil_num
,t1.loan_distr_acct_num as loan_distr_acct_num
,t1.loan_repay_num as loan_repay_num
,t1.int_sub_ps_stl_acct_num as int_sub_ps_stl_acct_num
,t1.entr_dep_acct_num as entr_dep_acct_num
,t1.csner_dep_acct_num as csner_dep_acct_num
,t1.inpwn_acct_num_id as inpwn_acct_num_id
,t1.out_acct_num as out_acct_num
,t1.rela_bill_id as rela_bill_id
,t1.std_prod_id as std_prod_id
,t1.prod_id as prod_id
,t1.subj_id as subj_id
,t1.int_subj_id as int_subj_id
,t1.loan_acct_status_cd as loan_acct_status_cd
,t1.loan_tenor as loan_tenor
,t1.loan_tenor_type_cd as loan_tenor_type_cd
,t1.loan_cate_cd as loan_cate_cd
,t1.belong_bus_strip_line_cd as belong_bus_strip_line_cd
,t1.guar_way_cd as guar_way_cd
,t1.loan_usage_descb as loan_usage_descb
,t1.acru_non_acru_cd as acru_non_acru_cd
,t1.turn_non_acru_loan_dt as turn_non_acru_loan_dt
,t1.cust_mgr_id as cust_mgr_id
,t1.open_acct_org_id as open_acct_org_id
,t1.mgmt_org_id as mgmt_org_id
,t1.acct_instit_id as acct_instit_id
,t1.open_acct_dt as open_acct_dt
,t1.distr_dt as distr_dt
,t1.value_dt as value_dt
,t1.stop_accr_int_dt as stop_accr_int_dt
,t1.exp_dt as exp_dt
,t1.clos_acct_dt as clos_acct_dt
,t1.int_sub_flg as int_sub_flg
,t1.int_sub_ratio as int_sub_ratio
,t1.int_sub_exp_day as int_sub_exp_day
,t1.entr_loan_comm_fee_coll_way as entr_loan_comm_fee_coll_way
,t1.entr_loan_comm_fee_coll_ratio as entr_loan_comm_fee_coll_ratio
,t1.entr_loan_comm_fee as entr_loan_comm_fee
,t1.stop_accr_int_flg as stop_accr_int_flg
,t1.impam_flg as impam_flg
,t1.crdt_distr_repay_plan_flg as crdt_distr_repay_plan_flg
,t1.finc_prod_flg as finc_prod_flg
,t1.prepay_int_amort_flg as prepay_int_amort_flg
,t1.pric_auto_deduct_flg as pric_auto_deduct_flg
,t1.int_auto_deduct_flg as int_auto_deduct_flg
,t1.acpt_flg as acpt_flg
,t1.gover_fin_plat_loan_flg as gover_fin_plat_loan_flg
,t1.tax_flg as tax_flg
,t1.wrt_off_flg as wrt_off_flg
,t1.renew_flg as renew_flg
,t1.renew_cnt as renew_cnt
,t1.allow_adv_repay_flg as allow_adv_repay_flg
,t1.repay_seq_no_cd as repay_seq_no_cd
,t1.adv_repay_way_cd as adv_repay_way_cd
,t1.margin_curr_cd as margin_curr_cd
,t1.int_rat_base_type_cd as int_rat_base_type_cd
,t1.int_rat_curve_type_cd as int_rat_curve_type_cd
,t1.base_rat as base_rat
,t1.exec_int_rat as exec_int_rat
,t1.int_rat_adj_way_cd as int_rat_adj_way_cd
,t1.int_rat_float_way_cd as int_rat_float_way_cd
,t1.int_rat_adj_ped_corp_cd as int_rat_adj_ped_corp_cd
,t1.int_rat_adj_ped_freq as int_rat_adj_ped_freq
,t1.int_rat_flo_val as int_rat_flo_val
,t1.curr_int_rat_effect_dt as curr_int_rat_effect_dt
,t1.next_int_rat_adj_dt as next_int_rat_adj_dt
,t1.comp_int_flg as comp_int_flg
,t1.int_set_way_cd as int_set_way_cd
,t1.int_accr_way_cd as int_accr_way_cd
,t1.repay_way_cd as repay_way_cd
,t1.repay_ped_corp_cd as repay_ped_corp_cd
,t1.repay_ped as repay_ped
,t1.money_use_type as money_use_type
,t1.lmt_type as lmt_type
,t1.ovdue_flg as ovdue_flg
,t1.pric_ovdue_flg as pric_ovdue_flg
,t1.int_ovdue_flg as int_ovdue_flg
,t1.curr_ovdue_perds as curr_ovdue_perds
,t1.pric_ovdue_days as pric_ovdue_days
,t1.int_ovdue_days as int_ovdue_days
,t1.ovdue_pric_bal as ovdue_pric_bal
,t1.ovdue_int_amt as ovdue_int_amt
,t1.ovdue_comp_int_amt as ovdue_comp_int_amt
,t1.fir_ovdue_dt as fir_ovdue_dt
,t1.ovdue_int_rat as ovdue_int_rat
,t1.ovdue_int_rat_flo_val as ovdue_int_rat_flo_val
,t1.tot_perds as tot_perds
,t1.curr_issue_perds as curr_issue_perds
,t1.last_repay_dt as last_repay_dt
,t1.next_repay_dt as next_repay_dt
,t1.curr_cd as curr_cd
,t1.next_rpp_amt as next_rpp_amt
,t1.next_repay_int_amt as next_repay_int_amt
,t1.td_acru_int as td_acru_int
,t1.currt_acru_int as currt_acru_int
,t1.cont_amt as cont_amt
,t1.dubil_amt as dubil_amt
,t1.distr_amt as distr_amt
,t1.nomal_pric as nomal_pric
,t1.ovdue_pric as ovdue_pric
,t1.idle_pric as idle_pric
,t1.bad_debt_pric as bad_debt_pric
,t1.recvbl_over_int as recvbl_over_int
,t1.recvbl_acru_pnlt as recvbl_acru_pnlt
,t1.recvbl_pnlt as recvbl_pnlt
,t1.acru_comp_int as acru_comp_int
,t1.recvbl_comp_int as recvbl_comp_int
,t1.recvbl_fee as recvbl_fee
,t1.wrt_off_pric as wrt_off_pric
,t1.wrt_off_int as wrt_off_int
,t1.in_bs_over_int_bal as in_bs_over_int_bal
,t1.off_bs_over_int_bal as off_bs_over_int_bal
,t1.in_bs_int as in_bs_int
,t1.off_bs_int as off_bs_int
,t1.acm_recvbl_uncol_int_amt as acm_recvbl_uncol_int_amt
,t1.repaid_pric as repaid_pric
,t1.repaid_int as repaid_int
,t1.repaid_pnlt as repaid_pnlt
,t1.repaid_comp_int as repaid_comp_int
,t1.repaid_fee as repaid_fee
,t1.pric_bal as pric_bal
,t1.currt_bal as currt_bal
,t1.cl_curr_currt_bal as cl_curr_currt_bal
,t1.ear_d_bal as ear_d_bal
,t1.ear_m_bal as ear_m_bal
,t1.ear_s_bal as ear_s_bal
,t1.ear_y_bal as ear_y_bal
,t1.y_acm_bal as y_acm_bal
,t1.s_acm_bal as s_acm_bal
,t1.m_acm_bal as m_acm_bal
,t1.cl_curr_ear_d_bal as cl_curr_ear_d_bal
,t1.cl_curr_ear_m_bal as cl_curr_ear_m_bal
,t1.cl_curr_ear_s_bal as cl_curr_ear_s_bal
,t1.cl_curr_ear_y_bal as cl_curr_ear_y_bal
,t1.cl_curr_y_acm_bal as cl_curr_y_acm_bal
,t1.cl_curr_ear_d_y_acm_bal as cl_curr_ear_d_y_acm_bal
,t1.cl_curr_ear_m_y_acm_bal as cl_curr_ear_m_y_acm_bal
,t1.cl_curr_ear_s_y_acm_bal as cl_curr_ear_s_y_acm_bal
,t1.cl_curr_ear_y_y_acm_bal as cl_curr_ear_y_y_acm_bal
,t1.cl_curr_s_acm_bal as cl_curr_s_acm_bal
,t1.cl_curr_ear_d_s_acm_bal as cl_curr_ear_d_s_acm_bal
,t1.cl_curr_ear_s_s_acm_bal as cl_curr_ear_s_s_acm_bal
,t1.cl_curr_ear_y_s_acm_bal as cl_curr_ear_y_s_acm_bal
,t1.cl_curr_m_acm_bal as cl_curr_m_acm_bal
,t1.cl_curr_ear_d_m_acm_bal as cl_curr_ear_d_m_acm_bal
,t1.cl_curr_ear_m_m_acm_bal as cl_curr_ear_m_m_acm_bal
,t1.cl_curr_ear_y_m_acm_bal as cl_curr_ear_y_m_acm_bal
,t1.y_avg_bal as y_avg_bal
,t1.q_avg_bal as q_avg_bal
,t1.m_avg_bal as m_avg_bal
,t1.cl_curr_y_avg_bal as cl_curr_y_avg_bal
,t1.cl_curr_q_avg_bal as cl_curr_q_avg_bal
,t1.cl_curr_m_avg_bal as cl_curr_m_avg_bal
,t1.off_bs_int_subj_id as off_bs_int_subj_id
,t1.int_income_subj_id as int_income_subj_id
,t1.asset_thd_cls_cd as asset_thd_cls_cd
,t1.int_accr_flg as int_accr_flg
,t1.init_pric_subj_id as init_pric_subj_id
,t1.asset_tran_status_cd as asset_tran_status_cd
,t1.tran_bf_int_recvbl as tran_bf_int_recvbl
,t1.td_int_income as td_int_income
,t1.int_income_adj_subj_id as int_income_adj_subj_id
,t1.renew_exp_day as renew_exp_day
,t1.td_int_income_adj as td_int_income_adj
,t1.asset_tran_dt as asset_tran_dt
,t1.distr_flow_num as distr_flow_num
,t1.reval_way_cd as reval_way_cd
,t1.comn_loan_int_set_way_cd as comn_loan_int_set_way_cd
,t1.pric_ovdue_dt as pric_ovdue_dt
,t1.int_ovdue_dt as int_ovdue_dt
,t1.loan_num as loan_num
,t1.acru_aldy_impam_int_subj_id as acru_aldy_impam_int_subj_id
,t1.recvbl_int_paybl_adj_subj_id as recvbl_int_paybl_adj_subj_id
,t1.recvbl_uncol_int_subj_id as recvbl_uncol_int_subj_id
,t1.trade_fin_int_adj as trade_fin_int_adj
,t1.grace_period_pric as grace_period_pric
,t1.grace_period_int as grace_period_int
,t1.td_tax_income as td_tax_income
,t1.abs_flg as abs_flg
,t1.asset_tran_flg as asset_tran_flg
,t1.recvbl_uncol_int as recvbl_uncol_int
,t1.int_recvbl as int_recvbl
,t1.non_acru_int_recvbl as non_acru_int_recvbl
,t1.acru_aldy_impam_int as acru_aldy_impam_int
,t1.fir_renew_exp_dt as fir_renew_exp_dt
,t1.coll_acru_pnlt as coll_acru_pnlt
,t1.coll_pnlt as coll_pnlt
,t1.init_exp_dt as init_exp_dt
,t1.open_acct_timestamp as open_acct_timestamp
,t1.clos_acct_timestamp as clos_acct_timestamp
,t1.loan_modal_cd as loan_modal_cd

from ${idl_schema}.cmm_corp_loan_acct_info t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/cmm_corp_loan_acct_info.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
