: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_oass_agt_loan_cont_corp_loan_attach_info_h_i
CreateDate: 20230116
FileName:   ${iel_data_path}/oass_agt_loan_cont_corp_loan_attach_info_h.i.${batch_date}.dat
IF_mark:    i
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.cont_id as cont_id
,t1.trade_cont_tot_amt as trade_cont_tot_amt
,t1.fin_cont_flg as fin_cont_flg
,t1.cont_type_cd as cont_type_cd
,t1.trade_cont_id as trade_cont_id
,t1.lc_kind_cd as lc_kind_cd
,t1.lc_amt as lc_amt
,t1.lc_curr_cd as lc_curr_cd
,t1.lc_id as lc_id
,t1.load_bill_id as load_bill_id
,t1.batch_id as batch_id
,t1.setup_proj_batch_id as setup_proj_batch_id
,t1.lc_type_cd as lc_type_cd
,t1.aldy_acpt_fwd_lc_flg as aldy_acpt_fwd_lc_flg
,t1.lc_tenor_type_cd as lc_tenor_type_cd
,t1.lc_char_cd as lc_char_cd
,t1.fwd_pay_day_tenor as fwd_pay_day_tenor
,t1.fee_undertaker as fee_undertaker
,t1.other_fee_rat as other_fee_rat
,t1.cargo_name as cargo_name
,t1.cargo_underly as cargo_underly
,t1.cargo_traff_destination as cargo_traff_destination
,t1.traff_way_cd as traff_way_cd
,t1.cls_freq as cls_freq
,t1.mom_lics_id as mom_lics_id
,t1.mom_lics_curr_cd as mom_lics_curr_cd
,t1.mom_lics_amt as mom_lics_amt
,t1.acct_recvbl_net_amnt as acct_recvbl_net_amnt
,t1.gover_crdt_type_cd as gover_crdt_type_cd
,t1.tran_bg_descb as tran_bg_descb
,t1.fix_asset_crdt_flg as fix_asset_crdt_flg
,t1.entr_dep_ec_cls_cd as entr_dep_ec_cls_cd
,t1.pkg_ratio as pkg_ratio
,t1.guar_type_cd as guar_type_cd
,t1.entr_loan_cap_src_cd as entr_loan_cap_src_cd
,t1.nego_bank_cfm_flg as nego_bank_cfm_flg
,t1.discnt_int_buyer_bear_ratio as discnt_int_buyer_bear_ratio
,t1.discnt_bf_revw_flg as discnt_bf_revw_flg
,t1.qual_centr_cntpty_flg as qual_centr_cntpty_flg
,t1.margin_acct_id as margin_acct_id
,t1.margin_curr_cd as margin_curr_cd
,t1.margin_tran_out_acct_id as margin_tran_out_acct_id
,t1.col_turn_margin_acct_id as col_turn_margin_acct_id
,t1.margin_agt_rat as margin_agt_rat
,t1.margin_int_rat_type_cd as margin_int_rat_type_cd
,t1.margin_flo_val as margin_flo_val
,t1.margin_int_rat_float_type_cd as margin_int_rat_float_type_cd
,t1.margin_int_rat_float_way_cd as margin_int_rat_float_way_cd
,t1.margin_int_accr_method_cd as margin_int_accr_method_cd
,t1.margin_int_rat_level_cd as margin_int_rat_level_cd
,t1.csner_name as csner_name
,t1.repay_comnt_descb as repay_comnt_descb
,t1.start_up_bus_guar_loan_type_cd as start_up_bus_guar_loan_type_cd
,t1.consm_serv_class_fin_flg as consm_serv_class_fin_flg
,t1.pay_way_cd as pay_way_cd
,t1.draw_comnt_descb as draw_comnt_descb
,t1.loan_amt_ocup_tran_price_money_ratio as loan_amt_ocup_tran_price_money_ratio
,t1.trade_fin_mang_merchd as trade_fin_mang_merchd
,t1.draft_qtty as draft_qtty
,t1.discnt_commer_accpt_bil_cls_cd as discnt_commer_accpt_bil_cls_cd
,t1.commer_inv_id as commer_inv_id
,t1.commer_inv_type_cd as commer_inv_type_cd
,t1.commer_inv_curr_cd as commer_inv_curr_cd
,t1.commer_inv_amt as commer_inv_amt
,t1.other_lics_id as other_lics_id
,t1.other_lics_name as other_lics_name
,t1.hp_lics_id as hp_lics_id
,t1.arch_land_lics_id as arch_land_lics_id
,t1.plan_lics_id as plan_lics_id
,t1.cnstr_lics_id as cnstr_lics_id
,t1.dir_ind_fund_flg as dir_ind_fund_flg
,t1.entr_loan_espec_dir_cd as entr_loan_espec_dir_cd
,t1.start_up_bus_guar_loan_flg as start_up_bus_guar_loan_flg
,t1.entr_dep_acct_id as entr_dep_acct_id
,t1.underly_prod_id as underly_prod_id
,t1.prod_coll_amt as prod_coll_amt
,t1.underly_prod_cls_lev_cd as underly_prod_cls_lev_cd
,t1.surp_indus_cd as surp_indus_cd
,t1.buy_house_site_dist_cd as buy_house_site_dist_cd
,t1.agclt_flg as agclt_flg
,t1.cntpty_name as cntpty_name
,t1.cntpty_co_years as cntpty_co_years
,t1.cntpty_sucs_tran_cnt as cntpty_sucs_tran_cnt
,t1.cntpty_strg as cntpty_strg
,t1.other_cond_request_descb as other_cond_request_descb
,t1.imp_loan_proj_cd as imp_loan_proj_cd
,t1.agclt_loan_dir_cd as agclt_loan_dir_cd
,t1.distr_ratio as distr_ratio
,t1.obank_open_flg as obank_open_flg
,t1.capital_amt as capital_amt
,t1.mgers_name as mgers_name
,t1.trade_fin_prod_id as trade_fin_prod_id
,t1.benefc_local_cty_or_rg_cd as benefc_local_cty_or_rg_cd
,t1.buyer_name as buyer_name
,t1.agclt_loan_main_type_cd as agclt_loan_main_type_cd
,t1.issue_appl_form_id as issue_appl_form_id
,t1.csner_id as csner_id
,t1.imp_loan_proj_flg as imp_loan_proj_flg
,t1.discnt_int_rat_comnt_descb as discnt_int_rat_comnt_descb
,t1.factor_type_cd as factor_type_cd
,t1.agt_pay_int_flg as agt_pay_int_flg
,t1.start_work_dt as start_work_dt
,t1.cdb_crdt_flg as cdb_crdt_flg
,t1.provi_doc_dt as provi_doc_dt
,t1.actl_finer as actl_finer
,t1.discnt_applit_type_cd as discnt_applit_type_cd
,t1.invo_gover_class_fin_flg as invo_gover_class_fin_flg
,t1.loan_fin_supt_way_cd as loan_fin_supt_way_cd
,t1.three_old_trasf_city_update_proj_flg as three_old_trasf_city_update_proj_flg
,t1.syn_distrd_loan_amt as syn_distrd_loan_amt
,t1.cap_src_cd as cap_src_cd
,t1.gover_crdt_supt_way_cd as gover_crdt_supt_way_cd
,t1.crdtc_indus_dir_cd as crdtc_indus_dir_cd
,t1.sup_chain_fin_bus_prod_cls_cd as sup_chain_fin_bus_prod_cls_cd
,t1.proj_info_text_id as proj_info_text_id
,t1.exist_m_l_claus_flg as exist_m_l_claus_flg
,t1.benefc_name as benefc_name
,t1.entr_dep_curr_cd as entr_dep_curr_cd
,t1.prepay_acct_recvbl_flg as prepay_acct_recvbl_flg
,t1.acpt_bank_name as acpt_bank_name
,t1.distr_org_id as distr_org_id
,t1.cdb_crdt_prod_id as cdb_crdt_prod_id
,t1.loan_usage_tran_amt as loan_usage_tran_amt
,t1.gover_crdt_flg as gover_crdt_flg
,t1.dir_makti_debt_eqty_flg as dir_makti_debt_eqty_flg
,t1.major_incre_crdt_way_cd as major_incre_crdt_way_cd
,t1.m_l_ratio as m_l_ratio
,t1.loan_char_cd as loan_char_cd
,t1.sup_chain_fin_bus_flg as sup_chain_fin_bus_flg
,t1.advise_bank_name as advise_bank_name
,t1.tran_asset_name as tran_asset_name
,t1.loan_trast_way_cd as loan_trast_way_cd
,t1.payfan_type_cd as payfan_type_cd
,t1.remote_bus_flg as remote_bus_flg
,t1.estate_loan_type_cd as estate_loan_type_cd
,t1.discnt_int_applit_pay_ratio as discnt_int_applit_pay_ratio
,t1.proj_tot_invest_amt as proj_tot_invest_amt
,t1.cty_lmt_indus_flg as cty_lmt_indus_flg
,t1.loc_fin_plat_solv_cap_src_cd as loc_fin_plat_solv_cap_src_cd
,t1.acct_recvbl_prepay_way_cd as acct_recvbl_prepay_way_cd
,t1.draw_way_cd as draw_way_cd
,t1.repay_way_cd as repay_way_cd
,t1.overs_loan_flg as overs_loan_flg
,t1.start_dt as start_dt
,t1.end_dt as end_dt
,t1.id_mark as id_mark
,t1.agt_id as agt_id

from ${idl_schema}.oass_agt_loan_cont_corp_loan_attach_info_h t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/oass_agt_loan_cont_corp_loan_attach_info_h.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
