: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idf_icms_ba_personal_loan_f
CreateDate: 20250210
FileName:   ${iel_data_path}/icms_ba_personal_loan.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.serialno as serialno
,t1.usccno as usccno
,t1.flowflag as flowflag
,t1.isdiscount as isdiscount
,t1.authinfo as authinfo
,t1.groupavailexposure as groupavailexposure
,t1.othercontsigndate as othercontsigndate
,t1.companybusinesssum as companybusinesssum
,t1.parkingarea as parkingarea
,t1.certid as certid
,t1.isfirstpurchase as isfirstpurchase
,t1.downpayment as downpayment
,t1.paybankname as paybankname
,t1.sellercertid as sellercertid
,t1.mandaterequirement as mandaterequirement
,t1.buildingcompany as buildingcompany
,t1.cuscomrelation as cuscomrelation
,t1.insurance as insurance
,t1.loanaccountclearbank as loanaccountclearbank
,t1.feesum as feesum
,t1.yxserno as yxserno
,t1.discountratio as discountratio
,t1.mandatedepositcurrency as mandatedepositcurrency
,t1.determprice as determprice
,t1.evaluationname as evaluationname
,t1.onlineapproveresult as onlineapproveresult
,t1.applycustype as applycustype
,t1.iswhite as iswhite
,t1.mandatedepositaccounts as mandatedepositaccounts
,t1.passtime as passtime
,t1.repaymentdatetype as repaymentdatetype
,t1.businesslicence as businesslicence
,t1.presalepermitno as presalepermitno
,t1.guaranteeagreement as guaranteeagreement
,t1.isgroupcustomer as isgroupcustomer
,t1.returncapitalinterval as returncapitalinterval
,t1.insuranceperiod as insuranceperiod
,t1.insurername as insurername
,t1.stallprice as stallprice
,t1.iscancel as iscancel
,t1.returncapitalratio as returncapitalratio
,t1.purchasecontractid as purchasecontractid
,t1.recordrelativeserialno as recordrelativeserialno
,t1.groupcustomerid as groupcustomerid
,t1.relserialno as relserialno
,t1.guarantytype as guarantytype
,t1.companyname as companyname
,t1.isthreemonthnewcar as isthreemonthnewcar
,t1.isonline as isonline
,t1.housingprice as housingprice
,t1.propertycontractno as propertycontractno
,t1.esaepclassify as esaepclassify
,t1.businessname as businessname
,t1.enddate as enddate
,t1.telephone as telephone
,t1.evaluateprice as evaluateprice
,t1.imageupflag as imageupflag
,t1.phreceivableam as phreceivableam
,t1.suggestsum as suggestsum
,t1.authtelephone as authtelephone
,t1.isimage as isimage
,t1.payeename as payeename
,t1.parkingaddress as parkingaddress
,t1.applyaddr as applyaddr
,t1.isvendorassumeliability as isvendorassumeliability
,t1.sellername as sellername
,t1.informflag as informflag
,t1.loanratio as loanratio
,t1.vehiclecontractno as vehiclecontractno
,t1.balloonamortenddate as balloonamortenddate
,t1.investoinon as investoinon
,t1.otherloancontractno as otherloancontractno
,t1.mandatedepositsum as mandatedepositsum
,t1.propertycertid as propertycertid
,t1.evaluationcertid as evaluationcertid
,t1.contimageupflag as contimageupflag
,t1.payeeaccounttel as payeeaccounttel
,t1.suitesunitprice as suitesunitprice
,t1.mandateriskclassify as mandateriskclassify
,t1.financialbond as financialbond
,t1.propertyarea as propertyarea
,t1.applyamt as applyamt
,t1.insurancevariety as insurancevariety
,t1.isback as isback
,t1.resetamt as resetamt
,t1.housingname as housingname
,t1.channelcode as channelcode
,t1.enterprisecode as enterprisecode
,t1.propertytype as propertytype
,t1.excess as excess
,t1.isbankrel as isbankrel
,t1.ischeckcreditreport as ischeckcreditreport
,t1.housingsum as housingsum
,t1.businessclass as businessclass
,t1.purpose as purpose
,t1.checkresult as checkresult
,t1.insurflag as insurflag
,t1.insurancecontractno as insurancecontractno
,t1.isexception as isexception
,t1.startdate as startdate
,t1.callbackurl as callbackurl
,t1.finalresult as finalresult
,t1.housingform as housingform
,t1.fitmentprice as fitmentprice
,t1.repayinterval as repayinterval
,t1.indtype as indtype
,t1.taxcode as taxcode
,t1.buildingunitprice as buildingunitprice
,t1.vehicletype as vehicletype
,t1.availexposure as availexposure
,t1.companyid as companyid
,t1.graceperiod as graceperiod
,t1.personalbusinessloanstype as personalbusinessloanstype
,t1.isloananytime as isloananytime
,t1.housingaddress as housingaddress
,t1.repayratio as repayratio
,t1.signaddr as signaddr
,t1.evaluationcerttype as evaluationcerttype
,t1.paymentobject as paymentobject
,t1.certtype as certtype
,t1.relycompanyname as relycompanyname
,t1.paymenttype as paymenttype
,t1.feepayment as feepayment
,t1.paymentbasis as paymentbasis
,t1.propertyunitprice as propertyunitprice
,t1.compcertid as compcertid
,t1.groupcustcode as groupcustcode
,t1.payeeaccountno as payeeaccountno
,t1.isinsurance as isinsurance
,t1.isopenentsettleaccounts as isopenentsettleaccounts
,t1.compcerttype as compcerttype
,t1.vehicleprice as vehicleprice
,t1.housinglevel as housinglevel
,t1.isbusinessguarantee as isbusinessguarantee
,t1.localstrategicindustry as localstrategicindustry
,t1.migtflag as migtflag
,t1.cusgruoprelation as cusgruoprelation
,t1.corporgid as corporgid
,t1.relycompanycreditno as relycompanycreditno
,t1.baserateadjustper as baserateadjustper
,t1.feeratio as feeratio
,t1.companyquotacontrol as companyquotacontrol
,t1.suitesarea as suitesarea
,t1.isaddamt as isaddamt
,t1.groupcustname as groupcustname
,t1.buildingarea as buildingarea
,t1.creditscore as creditscore
,t1.remark as remark
,t1.paymentratio as paymentratio
,t1.loandirection as loandirection
,t1.groupcustomername as groupcustomername
,t1.isjgaccount as isjgaccount
,t1.creditimageupflag as creditimageupflag
,t1.creditincrmode as creditincrmode
,t1.referrerid as referrerid
,t1.iswthrmanuactclmt as iswthrmanuactclmt
,t1.recheckflag as recheckflag
,t1.consignerid as consignerid
,t1.ishouseinguangdong as ishouseinguangdong
,t1.worktype as worktype
,t1.bigloanpurpose as bigloanpurpose
,t1.title as title
,t1.riskcontrolback as riskcontrolback
,t1.cuscreditscore as cuscreditscore
,t1.cuscreditscorelevel as cuscreditscorelevel
,t1.cartype as cartype
,t1.greenloanpurpose as greenloanpurpose
,t1.companytype as companytype
,t1.employments as employments
,t1.busiincome as busiincome
,t1.assetstotal as assetstotal
,t1.industry as industry
,t1.custcreditlevel as custcreditlevel
,t1.loanpurposedetails as loanpurposedetails
,t1.highindustry as highindustry
,t1.economyindustry as economyindustry
,t1.intellectualindustry as intellectualindustry
,t1.cultureindustry as cultureindustry
,t1.isagriculture as isagriculture
,t1.strategicindustry as strategicindustry
,t1.custlabel as custlabel
,t1.warninginfo as warninginfo
,t1.subgreenconsumeloanpurpose as subgreenconsumeloanpurpose
,t1.isoperatingentinvolvespecialized as isoperatingentinvolvespecialized
,t1.ishightechnologyent as ishightechnologyent
,t1.istechnologyent as istechnologyent
,t1.isscientifictechent as isscientifictechent
,t1.isspecializedgiantent as isspecializedgiantent
,t1.isspecializedsmallandmident as isspecializedsmallandmident
,t1.istechnologysmallandmident as istechnologysmallandmident
,t1.isindustrysinglechampionent as isindustrysinglechampionent
,t1.isnationaltechnologinnovationent as isnationaltechnologinnovationent
,t1.isgarden as isgarden
,t1.productchannel as productchannel
,t1.iscentralizedofficestaff as iscentralizedofficestaff
,t1.cobsratio as cobsratio
,t1.workingmonth as workingmonth
,t1.flowbranchtype as flowbranchtype
,t1.isicmsfactory as isicmsfactory
,t1.guaranteecompanyname as guaranteecompanyname
,t1.runentyearincome as runentyearincome
,t1.lastyearentyearincome as lastyearentyearincome
,t1.yearincomerate as yearincomerate
,t1.operationloanbalanceskr as operationloanbalanceskr
,t1.otherworkcaptial as otherworkcaptial
,t1.isrelatedcompany as isrelatedcompany
,t1.intentguaramt as intentguaramt
,t1.guarcompanyterm as guarcompanyterm
,t1.comptaxgrade as comptaxgrade
,t1.iscompanyrelatedperson as iscompanyrelatedperson
,t1.recommendedamt as recommendedamt
,t1.recommendedterm as recommendedterm
,t1.otherlimitflag as otherlimitflag

from ${idl_schema}.icms_ba_personal_loan t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/icms_ba_personal_loan.f.${batch_date}.dat" \
        charset=utf8
        safe=yes
