: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_odss_buy_details_new_f
CreateDate: 20180529
FileName:   ${iel_data_path}/odss_buy_details_new_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
 ID
 ,TASK_TYPE
 ,BUY_TYPE
 ,BUY_CONTRACT_ID
 ,DRAFT_ID
 ,BUYBIZ_TYPE
 ,CENTRAL_BANKFLG
 ,INNER_FLAG
 ,SAME_CITY_FLAG
 ,VIRTUAL_FLAG
 ,PREVIOUS_HAND
 ,PAYMENT_DATE
 ,POSTPONE_DAYS
 ,PAYMENT_DAYS
 ,BAN_ENDRSMT_MK
 ,RPD_OPEN_DT
 ,RPD_DUE_DT
 ,RPD_INTRATE
 ,INTRST_RATE
 ,PAYMENT_MATURITY
 ,STTLM_MK
 ,REQ_REMARK
 ,RCV_REMARK
 ,PAYMENT_BY_BUYER
 ,PAY_AMOUNT
 ,RISK_FEES
 ,CREDIT_LINE_ID
 ,CREDIT_LINE
 ,APPLY_DATE
 ,AOACCNINF_ACTNO
 ,AOACCNINF_UBANK
 ,DSCNT_PROPS_ROLE
 ,DSCNT_PROPS_NAME
 ,DSCNT_PROPS_CMONID
 ,DSCNT_PROPS_ACTNO
 ,DSCNT_PROPS_UBANK
 ,DSCNT_PROPS_AGCY_UBANK
 ,DSCNT_ROLE
 ,DSCNT_CMONID
 ,DSCNT_NAME
 ,DSCNT_ACTNO
 ,DSCNT_UBANK
 ,CONTRACTNO
 ,INVC_NB
 ,BTCH_NO
 ,CREDIT_LINE_STATUS
 ,ACCEPT_STATUS
 ,CHECK_STATUS
 ,QUERY_ORDER
 ,QUERY_CONTENT
 ,QUERY_TYPE
 ,CHECK_RESULT
 ,CHECK_CONTENT
 ,QUERY_CHECK_ID
 ,FLAW_STATUS
 ,DISAFFIRM_STATUS
 ,RCV_PRXY_SGNTR
 ,ACCOUNT_DATE
 ,ACCOUNT_FLAG
 ,ACTLOG_ID
 ,ACCOUNT
 ,ENDST_DATE
 ,CANCEL_DATE
 ,INTEREST_STATUS
 ,CALC_STATUS
 ,BUY_STATUS
 ,SIG_MK
 ,CM_STATUS
 ,CM_ERR_PROCD
 ,ECDS_PRC_MSG
 ,TRF_REF
 ,TRF_ID
 ,SWT_BIZ_ID
 ,ENTITY_REGSTAT
 ,ENTITY_REG_ID
 ,VALUE1
 ,MISC
 ,LAST_UPD_OPER_ID
 ,LAST_UPD_TIME
 ,INTR_OFFSET
 ,STORAGE_FLAG
 ,STORAGE_DTL_ID
 ,RUN_CODE

from ${idl_schema}.odss_buy_details_new
where etl_dt=to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/odss_buy_details_new_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes