: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_crms_cms_upl_business_apply_f
CreateDate: 20180529
FileName:   ${iel_data_path}/crms_cms_upl_business_apply_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
serialno
,relativeserialno
,occurdate
,customerid
,customername
,businesstype
,businesssubtype
,occurtype
,fundsource
,operatetype
,currenylist
,currencymode
,businesstypelist
,calculatemode
,useorglist
,cycleflag
,flowreduceflag
,contractflag
,subcontractflag
,selfuseflag
,creditaggreement
,relativeagreement
,loanflag
,totalsum
,ourrole
,reversibility
,billnum
,housetype
,lctermtype
,riskattribute
,suretype
,safeguardtype
,businesscurrency
,businesssum
,businessprop
,termyear
,termmonth
,termday
,lgterm
,baseratetype
,baserate
,ratefloattype
,ratefloat
,businessrate
,ictype
,iccyc
,pdgratio
,pdgsum
,pdgpaymethod
,pdgpayperiod
,promisesfeeratio
,promisesfeesum
,promisesfeeperiod
,promisesfeebegin
,mfeeratio
,mfeesum
,mfeepaymethod
,agentfee
,dealfee
,totalcast
,discountinterest
,purchaserinterest
,bargainorinterest
,discountsum
,bailratio
,bailcurrency
,bailsum
,bailaccount
,fineratetype
,finerate
,drawingtype
,firstdrawingdate
,drawingperiod
,paytimes
,paycyc
,graceperiod
,overdraftperiod
,oldlcno
,oldlctermtype
,oldlccurrency
,oldlcsum
,oldlcloadingdate
,oldlcvaliddate
,direction
,purpose
,planallocation
,immediacypaysource
,paysource
,corpuspaymethod
,interestpaymethod
,thirdparty1
,thirdpartyid1
,thirdparty2
,thirdpartyid2
,thirdparty3
,thirdpartyid3
,thirdpartyregion
,thirdpartyaccounts
,cargoinfo
,projectname
,operationinfo
,contextinfo
,securitiestype
,securitiesregion
,constructionarea
,usearea
,flag1
,flag2
,flag3
,tradecontractno
,invoiceno
,tradecurrency
,tradesum
,paymentdate
,operationmode
,vouchclass
,vouchtype
,vouchtype1
,vouchtype2
,vouchflag
,warrantor
,warrantorid
,othercondition
,guarantyvalue
,guarantyrate
,baseevaluateresult
,riskrate
,lowrisk
,otherarealoan
,lowriskbailsum
,originalputoutdate
,extendtimes
,lngotimes
,golntimes
,drtimes
,baseclassifyresult
,applytype
,bailrate
,finishorg
,operateorgid
,operateuserid
,operatedate
,inputorgid
,inputuserid
,inputdate
,updatedate
,pigeonholedate
,remark
,flag4
,paycurrency
,paydate
,describe1
,describe2
,classifyresult
,classifydate
,classifyfrequency
,vouchnewflag
,adjustratetype
,adjustrateterm
,rateadjustcyc
,fzanbalance
,acceptinttype
,fixcyc
,thirdpartyadd1
,thirdpartyzip1
,thirdpartyadd2
,thirdpartyzip2
,thirdpartyadd3
,thirdpartyzip3
,effectarea
,termdate1
,termdate2
,termdate3
,ratio
,tempsaveflag
,creditcycle
,gainamount
,gaincyc
,holdcorpus
,incomeorgid
,mainrepaymentmethod
,payaccountname
,payaccountno
,paymentmode
,ratemode
,flag5
,defaultpaydate
,batchpaymentflag
,loanaccountno
,loankind
,introducerid
,salechannelid
,bar_code_no
,schemeno
,preapproverid
,saleteamid
,signedplace
,purposetype
,qualitycontrolflag
,approvesum
,approvelevel
,trustaccname
,trustfundacctname
,flag7
from ${idl_schema}.crms_cms_upl_business_apply
where etl_dt=to_date('${batch_date}','yyyymmdd');" \
        field="|#|" record="0x0a"  \
        file="${iel_data_path}/crms_cms_upl_business_apply_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes