: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_ibms_ttrd_cashlb_f
CreateDate: 20221105
FileName:   ${iel_data_path}/ibms_ttrd_cashlb.f.${batch_date}.dat
IF_mark:    f
Logs:
   sundexin
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,i_code
,a_type
,m_type
,currency
,country
,q_type
,i_name
,p_class
,par_value
,coupon
,start_date
,mtr_date
,term
,daycount
,i_code_bench
,a_type_bench
,m_type_bench
,issue_mode
,coupon_type
,payment_freq
,payment_conv
,first_regular_start_date
,fixing_date_offset
,fixing_date_conv
,reset_freq
,reset_conv
,initial_rate
,cap_rate
,issuer
,memo
,fpml
,imp_time
,chinesespell
,is_delete
,floor_rate
,update_user
,update_time
,account_user
,account_time
,initial_fixing_date
,first_payment_date
,party_id
,rate_multi
,overdue_rate
,volume
,mtr_mode
,ver_id
,beg_date
,end_date
,fstsettype
,endsettype
,fst_set_amount
,mtr_set_amount
,p_type
,issue_price
,settled_interest
,issuer_id
,usable_flag
,payment_date_offset
,sell_department
,repo_trade_variety
,acct_id
,auto_redepo
,repo_term
,stub_period_type
,m_i_code
,m_a_type
,m_m_type
,head_coupon
,payment
,credit_promotion_way
,i_id
,cash_date
,ishisdata
,s_type
,host_market
,autoredepo
,scale
,final_stub
,u_m_type
,u_a_type
,u_i_code
,is_occupy_bottom_credit
,credit_id
,interest_type
,term_spd
,p_start_date
,p_mtr_date
,calcconv
,cashing_date
,cashing_speed
,match_code
,p_i_code
,special_type
,weighted_coupon
,und_asset_type
,inv_order_id
,guarantee_way
,guarantee_infor
,actual_mtr_date
,pre_actual_mtr_date
,total_ai
,p_status
,draw_advance_rate
,post_interest_rate
,is_open_letter
,grace_day
,credit_amount
,extordid
,is_auto_calculate
,nominal_rate
,added_rate
,slotting_addrate
,slotting_rate
,slotting_daycounter
,trustee_rate
,trustee_daycounter
,other_rate
,other_daycounter
,nominal_daycounter
,credit_weight
,reply_code
,record_rate
,accounting_type
,product_rate
,rate_institution
,is_guaranteed
,expect_take_day
,bank_group_code
,coupon_prec
,apr_txn
,fee_rate
,handlingchargetotal
,usufruct_mtr_date
,shibor_coupon
,shibor_i_code
,shibor_a_type
,shibor_m_type
,paymentinfo_type
,start_dt
,end_dt
,id_mark
from idl.ibms_ttrd_cashlb t
where start_dt <=to_date('${batch_date}','yyyymmdd') and end_dt >to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/ibms_ttrd_cashlb.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes