: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idf_cmm_dep_acct_info_a1
CreateDate: 20250715
FileName:   ${iel_data_path}/cmm_dep_acct_info.a.${batch_date}.dat
IF_mark:    a
Logs:
' \
        query="select
t1.etl_dt
,t1.lp_id as lp_id
,t1.acct_id as acct_id
,t1.acct_name as acct_name
,t1.cust_acct_id as cust_acct_id
,t1.cust_acct_sub_acct_num as cust_acct_sub_acct_num
,t1.cust_id as cust_id
,t1.subj_id as subj_id
,t1.dep_kind_cd as dep_kind_cd
,t1.acct_cls_cd as acct_cls_cd
,t1.acct_type_cd as acct_type_cd
,t1.acct_attr_cd as acct_attr_cd
,t1.dep_term as dep_term
,t1.std_prod_id as std_prod_id
,t1.ext_prod_id as ext_prod_id
,t1.intnal_prod_id as intnal_prod_id
,t1.open_oa_apv_form_num as open_oa_apv_form_num
,t1.dep_acct_status_cd as dep_acct_status_cd
,t1.cust_type_cd as cust_type_cd
,t1.corp_acct_flg as corp_acct_flg
,t1.stop_pay_status_cd as stop_pay_status_cd
,t1.general_exch_flg as general_exch_flg
,t1.advise_dep_flg as advise_dep_flg
,t1.agt_dep_flg as agt_dep_flg
,t1.float_int_rat_flg as float_int_rat_flg
,t1.int_rat_float_way_cd as int_rat_float_way_cd
,t1.int_rat_adj_ped_corp_cd as int_rat_adj_ped_corp_cd
,t1.int_rat_adj_ped_freq as int_rat_adj_ped_freq
,t1.rc_flg as rc_flg
,t1.margin_flg as margin_flg
,t1.agree_dep_flg as agree_dep_flg
,t1.ibank_dep_flg as ibank_dep_flg
,t1.dep_basic_acct_flg as dep_basic_acct_flg
,t1.ec_flg as ec_flg
,t1.privavy_acct_flg as privavy_acct_flg
,t1.legal_acct_flg as legal_acct_flg
,t1.auto_redt_flg as auto_redt_flg
,t1.redted_cnt as redted_cnt
,t1.itg_dep_earliest_drawbl_dt as itg_dep_earliest_drawbl_dt
,t1.sleep_acct_flg as sleep_acct_flg
,t1.dormt_acct_flg as dormt_acct_flg
,t1.sal_acct_flg as sal_acct_flg
,t1.froz_flg as froz_flg
,t1.advd_draw_flg as advd_draw_flg
,t1.tranbl_flg as tranbl_flg
,t1.int_accr_base_cd as int_accr_base_cd
,t1.int_accr_flg as int_accr_flg
,t1.int_set_way_cd as int_set_way_cd
,t1.int_accr_way_cd as int_accr_way_cd
,t1.allow_od_flg as allow_od_flg
,t1.curr_cd as curr_cd
,t1.redt_way_cd as redt_way_cd
,t1.open_acct_chn_type_cd as open_acct_chn_type_cd
,t1.tran_chn_status_cd as tran_chn_status_cd
,t1.open_acct_dt as open_acct_dt
,t1.open_acct_tm as open_acct_tm
,t1.clos_acct_dt as clos_acct_dt
,t1.clos_acct_tm as clos_acct_tm
,t1.actv_dt as actv_dt
,t1.value_dt as value_dt
,t1.exp_dt as exp_dt
,t1.final_activ_acct_dt as final_activ_acct_dt
,t1.agree_dep_value_dt as agree_dep_value_dt
,t1.agree_dep_exp_dt as agree_dep_exp_dt
,t1.froz_dt as froz_dt
,t1.unfrz_dt as unfrz_dt
,t1.last_int_set_dt as last_int_set_dt
,t1.next_int_set_dt as next_int_set_dt
,t1.fir_value_dt as fir_value_dt
,t1.agree_int_rat as agree_int_rat
,t1.base_rat_type_cd as base_rat_type_cd
,t1.base_rat as base_rat
,t1.exec_int_rat as exec_int_rat
,t1.td_acru_int as td_acru_int
,t1.currt_acru_int as currt_acru_int
,t1.cust_mgr_id as cust_mgr_id
,t1.open_acct_teller_id as open_acct_teller_id
,t1.clos_acct_teller_id as clos_acct_teller_id
,t1.open_acct_org_id as open_acct_org_id
,t1.close_acct_org_id as close_acct_org_id
,t1.belong_org_id as belong_org_id
,t1.loc_flg as loc_flg
,t1.expe_higt_yld_rat as expe_higt_yld_rat
,t1.agree_dep_init_amt as agree_dep_init_amt
,t1.open_acct_amt as open_acct_amt
,t1.currt_bal as currt_bal
,t1.aval_bal as aval_bal
,t1.froz_amt as froz_amt
,t1.stop_pay_amt as stop_pay_amt
,t1.cl_curr_currt_bal as cl_curr_currt_bal
,t1.ear_d_bal as ear_d_bal
,t1.ear_m_bal as ear_m_bal
,t1.ear_s_bal as ear_s_bal
,t1.ear_y_bal as ear_y_bal
,t1.y_acm_bal as y_acm_bal
,t1.s_acm_bal as s_acm_bal
,t1.m_acm_bal as m_acm_bal
,t1.cl_curr_ear_d_bal as cl_curr_ear_d_bal
,t1.cl_curr_ear_m_bal as cl_curr_ear_m_bal
,t1.cl_curr_ear_s_bal as cl_curr_ear_s_bal
,t1.cl_curr_ear_y_bal as cl_curr_ear_y_bal
,t1.cl_curr_y_acm_bal as cl_curr_y_acm_bal
,t1.cl_curr_ear_d_y_acm_bal as cl_curr_ear_d_y_acm_bal
,t1.cl_curr_ear_m_y_acm_bal as cl_curr_ear_m_y_acm_bal
,t1.cl_curr_ear_s_y_acm_bal as cl_curr_ear_s_y_acm_bal
,t1.cl_curr_ear_y_y_acm_bal as cl_curr_ear_y_y_acm_bal
,t1.cl_curr_s_acm_bal as cl_curr_s_acm_bal
,t1.cl_curr_ear_d_s_acm_bal as cl_curr_ear_d_s_acm_bal
,t1.cl_curr_ear_s_s_acm_bal as cl_curr_ear_s_s_acm_bal
,t1.cl_curr_ear_y_s_acm_bal as cl_curr_ear_y_s_acm_bal
,t1.cl_curr_m_acm_bal as cl_curr_m_acm_bal
,t1.cl_curr_ear_d_m_acm_bal as cl_curr_ear_d_m_acm_bal
,t1.cl_curr_ear_m_m_acm_bal as cl_curr_ear_m_m_acm_bal
,t1.cl_curr_ear_y_m_acm_bal as cl_curr_ear_y_m_acm_bal
,t1.cds_liab_acct_num as cds_liab_acct_num
,t1.corp_supv_acct_flg as corp_supv_acct_flg
,t1.y_avg_bal as y_avg_bal
,t1.q_avg_bal as q_avg_bal
,t1.m_avg_bal as m_avg_bal
,t1.cl_curr_y_avg_bal as cl_curr_y_avg_bal
,t1.cl_curr_q_avg_bal as cl_curr_q_avg_bal
,t1.cl_curr_m_avg_bal as cl_curr_m_avg_bal
,t1.web_dep_flg as web_dep_flg
,t1.bill_pool_margin_flg as bill_pool_margin_flg
,t1.bill_pool_type_cd as bill_pool_type_cd
,t1.old_acct_id as old_acct_id
,t1.int_paybl_subj_id as int_paybl_subj_id
,t1.int_paybl_adj_subj_id as int_paybl_adj_subj_id
,t1.int_expns_subj_id as int_expns_subj_id
,t1.int_expns_adj_subj_id as int_expns_adj_subj_id
,t1.open_flow_num as open_flow_num
,t1.clos_flow_num as clos_flow_num
,t1.currt_int_paybl_adj as currt_int_paybl_adj
,t1.td_int_expns as td_int_expns
,t1.td_int_expns_adj as td_int_expns_adj
,t1.long_hang_acct_flg as long_hang_acct_flg
,t1.acct_usage_cd as acct_usage_cd
,t1.agt_dep_earliest_drawbl_dt as agt_dep_earliest_drawbl_dt
,t1.lowt_bal as lowt_bal
,t1.cash_flg as cash_flg
,t1.cust_acct_card_no as cust_acct_card_no
,t1.dep_char_cd as dep_char_cd
,t1.agree_dep_rels_dt as agree_dep_rels_dt
,t1.mater_acct_flg as mater_acct_flg
,t1.delay_pay_int_flg as delay_pay_int_flg
,t1.delay_pay_int_days as delay_pay_int_days
,t1.old_cust_acct_sub_acct_num as old_cust_acct_sub_acct_num
,t1.dep_term_tenor_type_cd as dep_term_tenor_type_cd
,t1.pd_id as pd_id
,t1.approval_id as approval_id
,t1.general_exch_org_id as general_exch_org_id
,t1.general_storage_flg as general_storage_flg
,t1.vtual_acct_flg as vtual_acct_flg
,t1.entry_flg as entry_flg
,t1.turn_dormt_acct_dt as turn_dormt_acct_dt
,t1.over_term_exec_int_rat as over_term_exec_int_rat
from ${idl_schema}.cmm_dep_acct_info t1
where etl_dt in (last_day(etl_dt), last_day(etl_dt) - 1) and etl_dt >= date '2021-07-17' " \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/cmm_dep_acct_info.a.${batch_date}.dat" \
        charset=utf8
        safe=yes
