: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_rcrs_acc_loan_f
CreateDate: 20180529
FileName:   ${iel_data_path}/rcrs_acc_loan.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select  t.etl_dt
,t.bill_no
,t.cont_no
,t.cn_cont_no
,t.prd_pk
,t.biz_type
,t.prd_name
,t.prd_type
,t.cus_id
,t.cus_name
,t.biz_type_sub
,t.account_class
,t.loan_account
,t.loan_form
,t.loan_nature
,t.loan_type_ext
,t.assure_means_main
,t.assure_means2
,t.assure_means3
,t.cur_type
,t.loan_amount
,t.loan_balance
,t.loan_start_date
,t.loan_end_date
,t.term_type
,t.orig_expi_date
,t.ruling_ir
,t.floating_rate
,t.reality_ir_y
,t.overdue_rate
,t.overdue_ir
,t.default_rate
,t.default_ir
,t.ci_rate
,t.ci_ir
,t.rece_int_cumu
,t.actual_int_cumu
,t.delay_int_cumu
,t.inner_int_cumu
,t.off_int_cumu
,t.inner_rece_int
,t.overdue_rece_int
,t.off_rece_int
,t.compound_rece_int
,t.inner_off_rece_int
,t.inner_actl_int
,t.overdue_actl_int
,t.off_actl_int
,t.compound_actl_int
,t.inner_off_actl_int
,t.normal_balance
,t.overdue_balance
,t.sluggish_balance
,t.doubtful_balance
,t.integral_y
,t.integral_q
,t.integral_m
,t.nor_rec_accu
,t.reo_rec_accu
,t.peel_rec_accu
,t.asset_rec_accu
,t.assure_rec_accu
,t.cancel_rec_accu
,t.policy_rec_accu
,t.dte_rec_accu
,t.roll_rec_accu
,t.max_balance_y
,t.max_balance_q
,t.max_balance_m
,t.mortgage_flg
,t.repayment_mode
,t.first_disb_date
,t.loan_direction
,t.revolving_times
,t.extension_times
,t.cap_overdue_date
,t.int_overdue_date
,t.over_times_current
,t.over_times_total
,t.max_times_total
,t.bad_loan_flag
,t.default_flag
,t.limit_ind
,t.loan_form4
,t.cla
,t.cla_date
,t.cla_pre
,t.cla_date_pre
,t.latest_repay_date
,t.cus_manager
,t.input_br_id
,t.fina_br_id
,t.main_br_id
,t.settl_date
,t.latest_date
,t.account_status
,t.biz_type_detail
,t.int_rate_type
,t.int_rate_inc_opt
,t.int_rate_inc
,t.fixed_rate
,t.prd_userdf_name
,t.prd_userdf_type
,t.syndicated_ind
,t.unpd_int_arr_prn
,t.unpd_arrs_int_bal
,t.unpd_arr_prn_bal
,t.act_int_arr_prn
,t.act_arrs_int_bal
,t.act_arr_prn_bal
,t.gl_class
,t.iscircle
,t.return_date
,t.act_write_off_int_rec
,t.unpd_write_off_int_rec
,t.unpd_prin_bal
,t.remark
,t.consign_fund_protocol_no
,t.psp_task_crt_date
,t.psp_task_cpt_date
,t.rsc_task_crt_date
,t.com_scale
,t.cus_type
,t.opt_cus_mgr
,t.ten_cla
,t.ten_cla_pre
,t.loan_card_ind
,t.agriculture_type
,t.agriculture_use
,t.minor_entrp_range
,t.government_ind
,t.government_org_attribute
,t.government_platform
,t.overdue_type
,t.default_type
,t.ir_exe_type
,t.guarantora_grp_ind
,t.jz
,t.core_account_status
,t.interest_date
,t.join_role
,t.syndicated_type
,t.lead_arranger_ind
,t.machine_cla_result
,t.machine_ten_cla_result
,t.period_ind
,t.period_term
,t.period_type
,t.distance_term
,t.proportion_scale
,t.devalue_sign
,t.accrue_money
,t.cla_cf
,t.cla_cf_date
,t.cla_cf_pre
,t.cla_cf_date_pre
,t.ten_cla_cf
,t.ten_cla_cf_date
,t.ten_cla_cf_pre
,t.ten_cla_cf_date_pre
,t.rsc_task_crt_date_pre
,t.ten_rsc_task_crt_date
,t.ten_rsc_task_crt_date_pre
,t.ten_cla_date
,t.ten_cla_date_pre
,t.rsc_model_id
,t.rsc_model_id_cf
,t.rsc_model_name
,t.rsc_model_name_cf
,t.auto_rate_reason
,t.auto_ten_rate_reason
,t.cla_rp
,t.ten_cla_rp
,t.int_repayment_total
,t.cap_repayment_curmonth
,t.int_repayment_curmonth
,t.inner_int_repayment_total
,t.inner_int_curmonth
,t.off_int_repayment_total
,t.off_int_repayment_curmonth
,t.repla_repayment_total
,t.repla_repayment_curmonth
,t.wrpff_prin_repayment_total
,t.wrpff_repayment_curmonth
,t.is_company
,t.cla_rp_lastyear
,t.cla_rp_lastmonth
,t.cla_rp_lastquarter
,t.ten_cla_rp_lastyear
,t.ten_cla_rp_lastmonth
,t.ten_cla_rp_lastquarter
,t.cap_overdue_days
,t.int_overdue_days
,t.max_overdue_days
,t.use_dec
,t.loan_balance_lastyear_end
,t.repayment_account
,t.precalcintdate
,t.tourism_flag
,t.delay_deduct_type
,t.moweput
,t.qoweput
,t.yoweput
,t.moweaccept
,t.qoweaccept
,t.yoweaccept
,t.mintaccept
,t.qintaccept
,t.yintaccept
,t.mshloudint
,t.qshloudint
,t.yshloudint
,t.pay_way
,t.src_account
,t.repayment_acc_name
,t.ir_floating_term
,t.cancel_date
,t.input_id
,t.last_upd_date
,t.cap_repayment_total
,t.enter_account
,t.enter_account_name
,t.interest_acc_mode
,t.enter_account_type
,t.repayment_account_type
,t.create_user_id
,t.ir_adjust_mode
,t.ten_cla_ind
,t.is_cl
,t.is_balloon
,t.last_term_amount
,t.cla_fina_update_id
,t.cla_update_reason
,t.inner_account
,t.interest
,t.penalty_interest
,t.recipe
,t.advance_payment
,t.debts_status
,t.off_balance_interest
,t.inner_balance_interest
,t.asset_three_type_cd
,t.rate_type
,t.zxz_flag
,t.start_dt
,t.end_dt
,t.id_mark
from idl.rcrs_acc_loan t
where start_dt <= to_date('${batch_date}','yyyymmdd')
 and end_dt > to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/rcrs_acc_loan.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes