: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_iol_glms_gl_code_combinations_f_w
CreateDate: 20180529
FileName:   ${iel_data_path}/glms_gl_code_combinations_w.f.${batch_date}.dat
IF_mark:    f_w
Logs:
   zjj 2018-07-27 create template
' \
        query="select code_combination_id,last_update_date,last_updated_by,chart_of_accounts_id,detail_posting_allowed_flag,detail_budgeting_allowed_flag,account_type,enabled_flag,summary_flag,segment1,segment2,segment3,segment4,segment5,segment6,segment7,segment8,segment9,segment10,segment11,segment12,segment13,segment14,segment15,segment16,segment17,segment18,segment19,segment20,segment21,segment22,segment23,segment24,segment25,segment26,segment27,segment28,segment29,segment30,replace(replace(description,chr(10),''),chr(13),'') as description,template_id,allocation_create_flag,start_date_active,end_date_active,replace(replace(attribute1,chr(10),''),chr(13),'') as attribute1,replace(replace(attribute2,chr(10),''),chr(13),'') as attribute2,replace(replace(attribute3,chr(10),''),chr(13),'') as attribute3,replace(replace(attribute4,chr(10),''),chr(13),'') as attribute4,replace(replace(attribute5,chr(10),''),chr(13),'') as attribute5,replace(replace(attribute6,chr(10),''),chr(13),'') as attribute6,replace(replace(attribute7,chr(10),''),chr(13),'') as attribute7,replace(replace(attribute8,chr(10),''),chr(13),'') as attribute8,replace(replace(attribute9,chr(10),''),chr(13),'') as attribute9,replace(replace(attribute10,chr(10),''),chr(13),'') as attribute10,replace(replace(context,chr(10),''),chr(13),'') as context,segment_attribute1,segment_attribute2,segment_attribute3,segment_attribute4,segment_attribute5,segment_attribute6,segment_attribute7,segment_attribute8,segment_attribute9,segment_attribute10,segment_attribute11,segment_attribute12,segment_attribute13,segment_attribute14,segment_attribute15,segment_attribute16,segment_attribute17,segment_attribute18,segment_attribute19,segment_attribute20,segment_attribute21,segment_attribute22,segment_attribute23,segment_attribute24,segment_attribute25,segment_attribute26,segment_attribute27,segment_attribute28,segment_attribute29,segment_attribute30,segment_attribute31,segment_attribute32,segment_attribute33,segment_attribute34,segment_attribute35,segment_attribute36,segment_attribute37,segment_attribute38,segment_attribute39,segment_attribute40,segment_attribute41,segment_attribute42,reference1,reference2,reference3,reference4,reference5,jgzz_recon_flag,jgzz_recon_context,preserve_flag,refresh_flag,igi_balanced_budget_flag,company_cost_center_org_id,revaluation_id,ledger_segment,ledger_type_code,alternate_code_combination_id,start_dt,end_dt,id_mark,etl_timestamp from iol.glms_gl_code_combinations where start_dt between to_date('${batch_date}', 'yyyymmdd') - 6 and to_date('${batch_date}', 'yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/glms_gl_code_combinations_w.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes