: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_icps_afa_jzck_filedetail_a
CreateDate: 20250305
FileName:   ${iel_data_path}/icps_afa_jzck_filedetail.a.${batch_date}.dat
IF_mark:    a
Logs:
' \
        query="select
t1.etl_dt
,t1.productcode as productcode
,t1.workdate as workdate
,t1.agentserialno as agentserialno
,t1.worktime as worktime
,t1.reqid as reqid
,t1.reqbatno as reqbatno
,t1.reqtype as reqtype
,t1.opttype as opttype
,t1.applyseq as applyseq
,t1.applytype as applytype
,t1.applyorgcode as applyorgcode
,t1.targetorgcode as targetorgcode
,t1.subjecttype as subjecttype
,t1.casetype as casetype
,t1.caseno as caseno
,t1.emergencylevel as emergencylevel
,t1.sendtime as sendtime
,t1.taskid as taskid
,t1.origtaskid as origtaskid
,t1.username as username
,t1.idtype as idtype
,t1.idno as idno
,t1.accountno as accountno
,t1.accountnumber as accountnumber
,t1.accounttype as accounttype
,t1.accountopenbankname as accountopenbankname
,t1.accountopenbankcode as accountopenbankcode
,t1.controlcontent as controlcontent
,t1.timetype as timetype
,t1.starttime as starttime
,t1.endtime as endtime
,t1.frozentype as frozentype
,t1.amount as amount
,t1.currency as currency
,t1.frozedbalance as frozedbalance
,t1.accountbalance as accountbalance
,t1.accountavaiablebalance as accountavaiablebalance
,t1.hostfreezeserial as hostfreezeserial
,t1.hostdate as hostdate
,t1.formerapplicationdepartment as formerapplicationdepartment
,t1.formerfrozenbalance as formerfrozenbalance
,t1.formerfrozenexpiretime as formerfrozenexpiretime
,t1.unfrozedbalance as unfrozedbalance
,t1.execunitname as execunitname
,t1.execunitno as execunitno
,t1.handler as handler
,t1.telephone as telephone
,t1.handleraddress as handleraddress
,t1.handleridtype as handleridtype
,t1.handleridno as handleridno
,t1.handlerworkidno as handlerworkidno
,t1.handlerofficeidno as handlerofficeidno
,t1.helper as helper
,t1.helpertelephone as helpertelephone
,t1.helperidtype as helperidtype
,t1.helperidno as helperidno
,t1.documentname as documentname
,t1.documentno as documentno
,t1.origcaseno as origcaseno
,t1.assetsname as assetsname
,t1.assetstype as assetstype
,t1.units as units
,t1.ischange as ischange
,t1.execaccountname as execaccountname
,t1.execaccountbankname as execaccountbankname
,t1.execaccountbankcode as execaccountbankcode
,t1.execaccount as execaccount
,t1.execaccounttype as execaccounttype
,t1.tradebusistep as tradebusistep
,t1.tradestatus as tradestatus
,t1.dealcode as dealcode
,t1.dealmsg as dealmsg
,t1.remark as remark
,t1.remark1 as remark1
,t1.remark2 as remark2
,t1.remark3 as remark3
,t1.tradesystem as tradesystem
,t1.tradetype as tradetype
,t1.procemode as procemode
,t1.telphone as telphone
,t1.cxzl as cxzl
,t1.applicationorgname as applicationorgname
,t1.glbl_seq_no as glbl_seq_no
,t1.applicationtype as applicationtype
,t1.fileid as fileid
,t1.formerccy as formerccy
,t1.transserialnumber as transserialnumber
,t1.transferamount as transferamount
,t1.transfertime as transfertime
,t1.applicationtime as applicationtime
,t1.result as result
,t1.withdrawaltime as withdrawaltime
,t1.tellerno as tellerno
,t1.brno as brno
,t1.author as author
,t1.manager as manager
,t1.helpermobilephone as helpermobilephone
,t1.upddate as upddate
,t1.updtime as updtime
,t1.ckwh as ckwh
,t1.cpxszl as cpxszl
,t1.feedbackorgname as feedbackorgname
,t1.fksjhm as fksjhm
,t1.feedbackremark as feedbackremark
,t1.buslicense as buslicense
,t1.dqh as dqh
,t1.hclx as hclx
,t1.hcsxje as hcsxje
,t1.thawmode as thawmode
,t1.deltellerno as deltellerno
,t1.delbrno as delbrno
,t1.jrcpbh as jrcpbh
,t1.cardno as cardno
,t1.kzzt as kzzt
,t1.lczh as lczh
,t1.pztxlx as pztxlx
,t1.pztxmc as pztxmc
,t1.requesttxcode as requesttxcode
,t1.responsetxcode as responsetxcode
,t1.qqrbgdh as qqrbgdh
,t1.busiserno as busiserno
,t1.threeinone as threeinone
,t1.se as se
,t1.skse as skse
,t1.sfdysxje as sfdysxje
,t1.sfxd as sfxd
,t1.unfrozedtype as unfrozedtype
,t1.xcrbgdh as xcrbgdh
,t1.ydjah as ydjah
,t1.zffs as zffs
,t1.location as location
,t1.transferoutaccountnumber as transferoutaccountnumber
,t1.transferoutaccountname as transferoutaccountname
,t1.transferoutbankid as transferoutbankid
,t1.transferoutbankname as transferoutbankname
,t1.zjhkzh as zjhkzh
,t1.orgcode as orgcode
,t1.froflag as froflag
,t1.exchangetype as exchangetype
,t1.querycontent as querycontent
,t1.fhbz as fhbz
,t1.fklx as fklx
,t1.isfrozed as isfrozed
,t1.orighelperidtype as orighelperidtype
,t1.orighandleridtype as orighandleridtype
,t1.origidtype as origidtype
,t1.newaccountno as newaccountno
,t1.querydata as querydata
,t1.uploadflag as uploadflag
,t1.bankcode as bankcode
,t1.bankname as bankname
,t1.istransee as istransee
,t1.prtsendflag as prtsendflag

from ${idl_schema}.icps_afa_jzck_filedetail t1
where t1.workdate <= '${batch_date}'" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/icps_afa_jzck_filedetail.a.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
