: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idf_crps_cmm_unite_wl_dubil_info_morning_f
CreateDate: 20251229
FileName:   ${iel_data_path}/crps_cmm_unite_wl_dubil_info_morning.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
etl_dt
,lp_id
,dubil_id
,std_prod_id
,prod_id
,cust_id
,subj_id
,acctnt_cate_cd
,enter_acct_acct_num
,repay_num
,rela_agt_id
,rela_appl_flow_num
,curr_cd
,bus_breed_id
,loan_type_cd
,asset_thd_cls_cd
,dubil_status_cd
,loan_usage_cd
,dir_indus_cd
,cont_status_cd
,loan_level4_cls_cd
,loan_level5_cls_cd
,loan_level10_cls_cd
,loan_level12_cls_cd
,acru_non_acru_cd
,repay_way_cd
,int_set_way_cd
,int_accr_way_cd
,int_rat_adj_way_cd
,int_rat_adj_ped_corp_cd
,int_rat_adj_ped_freq
,int_rat_base_type_cd
,int_rat_float_way_cd
,int_rat_float_dir_cd
,int_rat_flo_val
,pric_repay_freq_cd
,int_repay_freq_cd
,guar_way_cd
,enter_acct_acct_num_type
,repay_num_type
,intnal_carr_flg
,dom_overs_flg
,int_accr_flg
,comp_int_flg
,ovdue_flg
,wrt_off_flg
,open_acct_dt
,distr_dt
,value_dt
,exp_dt
,payoff_dt
,last_repay_dt
,next_repay_dt
,curr_int_rat_effect_dt
,next_int_rat_adj_dt
,cust_mgr_id
,open_acct_org_id
,mgmt_org_id
,acct_instit_id
,tot_perds
,curr_issue_perds
,surp_perds
,ovdue_perds
,pric_ovdue_flg
,int_ovdue_flg
,pric_ovdue_days
,int_ovdue_days
,grace_period_days
,inst_comm_fee_rat
,base_rat
,exec_int_rat
,ovdue_int_rat
,daily_exec_int_rat
,cont_amt
,dubil_amt
,distr_amt
,bank_contri_ratio
,td_acru_int
,currt_acru_int
,nomal_pric
,ovdue_pric
,idle_pric
,bad_debt_pric
,wrt_off_pric
,nomal_int
,ovdue_int
,wrt_off_int
,ovdue_pric_pnlt
,ovdue_int_pnlt
,recvbl_over_int
,recvbl_acru_pnlt
,recvbl_pnlt
,recvbl_fee
,in_bs_over_int_bal
,off_bs_over_int_bal
,in_bs_int
,off_bs_int
,acm_recvbl_uncol_int_amt
,repaid_nomal_pric
,repaid_ovdue_pric
,repaid_nomal_int
,repaid_ovdue_int
,repaid_ovdue_pric_pnlt
,repaid_ovdue_int_pnlt
,repaid_fee
,pric_bal
,currt_bal
,cl_curr_currt_bal
,ear_d_bal
,ear_m_bal
,ear_s_bal
,ear_y_bal
,y_acm_bal
,s_acm_bal
,m_acm_bal
,cl_curr_ear_d_bal
,cl_curr_ear_m_bal
,cl_curr_ear_s_bal
,cl_curr_ear_y_bal
,cl_curr_y_acm_bal
,cl_curr_ear_d_y_acm_bal
,cl_curr_ear_m_y_acm_bal
,cl_curr_ear_s_y_acm_bal
,cl_curr_ear_y_y_acm_bal
,cl_curr_s_acm_bal
,cl_curr_ear_d_s_acm_bal
,cl_curr_ear_s_s_acm_bal
,cl_curr_ear_y_s_acm_bal
,cl_curr_m_acm_bal
,cl_curr_ear_d_m_acm_bal
,cl_curr_ear_m_m_acm_bal
,cl_curr_ear_y_m_acm_bal
,y_avg_bal
,q_avg_bal
,m_avg_bal
,cl_curr_y_avg_bal
,cl_curr_q_avg_bal
,cl_curr_m_avg_bal
,init_tot_perds
,white_list_cust_flg
,cont_id
,init_distr_amt
,init_distr_dt
,init_exp_dt

from ${idl_schema}.crps_cmm_unite_wl_dubil_info t1
where etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/crps_cmm_unite_wl_dubil_info_morning.f.${batch_date}.dat" \
        charset=utf8
        safe=yes