: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idf_icms_bp_extend_d_f
CreateDate: 20251201
FileName:   ${iel_data_path}/icms_bp_extend_d.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.serialno as serialno
,t1.billtype as billtype
,t1.careflag as careflag
,t1.paybankname as paybankname
,t1.keyno as keyno
,t1.tradesum1 as tradesum1
,t1.chaggeaddress as chaggeaddress
,t1.tradesum2 as tradesum2
,t1.resumeinttype as resumeinttype
,t1.linkname as linkname
,t1.aboutbankname as aboutbankname
,t1.bailpdrifm as bailpdrifm
,t1.bfintg as bfintg
,t1.accountopenbankname as accountopenbankname
,t1.bailmaturity as bailmaturity
,t1.capitalreturnflag as capitalreturnflag
,t1.migtflag as migtflag
,t1.fbsnumber as fbsnumber
,t1.assureorgid as assureorgid
,t1.invoicenumber as invoicenumber
,t1.tradetype1 as tradetype1
,t1.bailexchangestate as bailexchangestate
,t1.cdexchangedate as cdexchangedate
,t1.acptdate as acptdate
,t1.loantype as loantype
,t1.czflag as czflag
,t1.paymode as paymode
,t1.acceptorname as acceptorname
,t1.othertxbalance as othertxbalance
,t1.accountnocustomer as accountnocustomer
,t1.tradedate1 as tradedate1
,t1.acceptorbankname as acceptorbankname
,t1.compoundintratio as compoundintratio
,t1.textno as textno
,t1.instrt as instrt
,t1.tradecurrecy2 as tradecurrecy2
,t1.repaymentplanflag as repaymentplanflag
,t1.chargephone as chargephone
,t1.tradetermmonth2 as tradetermmonth2
,t1.ratestartmode as ratestartmode
,t1.autocontrolflag as autocontrolflag
,t1.loantermthing as loantermthing
,t1.bailfxfltp as bailfxfltp
,t1.gatheringname as gatheringname
,t1.principalaccountno as principalaccountno
,t1.openbankname as openbankname
,t1.aboutbankname2 as aboutbankname2
,t1.preinttype as preinttype
,t1.loantermcontrolflag as loantermcontrolflag
,t1.acceptancebank as acceptancebank
,t1.tradedate2 as tradedate2
,t1.otherdraweracctno as otherdraweracctno
,t1.principalsubaccountno as principalsubaccountno
,t1.continuepayflag as continuepayflag
,t1.billno as billno
,t1.approveorgid as approveorgid
,t1.clientaccountno as clientaccountno
,t1.repayexchangestate as repayexchangestate
,t1.chargename as chargename
,t1.commercetype as commercetype
,t1.tradetermmonth1 as tradetermmonth1
,t1.dprinpaymethod as dprinpaymethod
,t1.lprtype as lprtype
,t1.loanaccountnoorgname as loanaccountnoorgname
,t1.isrz as isrz
,t1.period as period
,t1.approveuserid as approveuserid
,t1.traderate1 as traderate1
,t1.repurchaseflag as repurchaseflag
,t1.deposittermtype as deposittermtype
,t1.linkphone as linkphone
,t1.termtype as termtype
,t1.loanaccountnocustomer as loanaccountnocustomer
,t1.pdgpaypercent2 as pdgpaypercent2
,t1.bailinterestrate as bailinterestrate
,t1.cdexchangeno as cdexchangeno
,t1.businesssubtype as businesssubtype
,t1.tradeserialno1 as tradeserialno1
,t1.txregister as txregister
,t1.amlresult as amlresult
,t1.compoundintfloatvalue as compoundintfloatvalue
,t1.paysum as paysum
,t1.name1 as name1
,t1.fundsource as fundsource
,t1.stopintflag as stopintflag
,t1.lnbal as lnbal
,t1.acceptorbankno as acceptorbankno
,t1.confirmingbank as confirmingbank
,t1.chargefax as chargefax
,t1.pdgsum2 as pdgsum2
,t1.depositbaserate as depositbaserate
,t1.lcsum as lcsum
,t1.traderate2 as traderate2
,t1.tradecurrecy1 as tradecurrecy1
,t1.isfinanceguarantee as isfinanceguarantee
,t1.putoutno as putoutno
,t1.bailpdrifd as bailpdrifd
,t1.depositterm as depositterm
,t1.billclass as billclass
,t1.tradesum3 as tradesum3
,t1.tradecurrecy3 as tradecurrecy3
,t1.queryabnormitything as queryabnormitything
,t1.creditaggreement as creditaggreement
,t1.exchangetype as exchangetype
,t1.bailterm as bailterm
,t1.bailpdrifv as bailpdrifv
,t1.interestreturnflag as interestreturnflag
,t1.compoundintflag as compoundintflag
,t1.chargepost as chargepost
,t1.isbankaccount as isbankaccount
,t1.fixcyc as fixcyc
,t1.ordinaryormonthly as ordinaryormonthly
,t1.unpaidbankname as unpaidbankname
,t1.approvedate as approvedate
,t1.linkemail as linkemail
,t1.discountsum as discountsum
,t1.loanaccountno2 as loanaccountno2
,t1.abnormitything as abnormitything
,t1.tradeserialno2 as tradeserialno2
,t1.bailinterestmethod as bailinterestmethod
,t1.trantp as trantp
,t1.poolfinancingflag as poolfinancingflag
,t1.isbelongterm as isbelongterm
,t1.contractsignfee as contractsignfee
,t1.aboutbankid as aboutbankid
,t1.isfixedrate as isfixedrate
,t1.opencustomer as opencustomer
,t1.sellstatus as sellstatus
,t1.otherreceivedbankno as otherreceivedbankno
,t1.otherreceivedname as otherreceivedname
,t1.otherreceivedaccname as otherreceivedaccname
,t1.otherreceivedbankname as otherreceivedbankname
,t1.creditbeneficiary as creditbeneficiary
,t1.actualloanaccountno as actualloanaccountno
,t1.replaceolddept as replaceolddept
,t1.isproxydp as isproxydp
,t1.sqdkze as sqdkze
,t1.socialcreditcode as socialcreditcode
,t1.buychannel as buychannel
,t1.islinkoutpay as islinkoutpay
,t1.post as post
,t1.payinterestcustomer as payinterestcustomer
,t1.purchasercustflag as purchasercustflag
,t1.othercustomerid as othercustomerid
,t1.othercustomername as othercustomername
,t1.finalmerger as finalmerger
,t1.lcsumrate as lcsumrate
,t1.linkchargeintflag as linkchargeintflag
,t1.isactualddamtflag as isactualddamtflag
,t1.maxpdrifv as maxpdrifv
,t1.ismergeentrpayment as ismergeentrpayment
,t1.ownfunds as ownfunds
,t1.ownfundsacctno as ownfundsacctno
,t1.ownfundsacctname as ownfundsacctname
,t1.ownfundsacctccy as ownfundsacctccy
,t1.arrivalnumbers as arrivalnumbers
,t1.claimamount as claimamount
,t1.businessamount as businessamount
,t1.marketflows as marketflows
,t1.servicecontent as servicecontent
,t1.scanstatus as scanstatus
,t1.priceorderno as priceorderno
,t1.priceapprovestatus as priceapprovestatus
,t1.priceenddate as priceenddate
,t1.pledgetype as pledgetype
,t1.submitputoutcentertime as submitputoutcentertime
,t1.iscentralizedaccount as iscentralizedaccount
,t1.issuedbusinessno as issuedbusinessno
,t1.bhstartdate as bhstartdate
,t1.bhmaturity as bhmaturity
,t1.guaranteebusinessno as guaranteebusinessno
,t1.guaranteesum as guaranteesum
,t1.issuedate as issuedate
,t1.guaranteeputoutstatus as guaranteeputoutstatus
,t1.isreplenishment as isreplenishment
,t1.scanuserid as scanuserid
,t1.scanusername as scanusername
,t1.bizuniqueno as bizuniqueno
,t1.isxdapprove as isxdapprove
,t1.isignoreresult as isignoreresult

from ${idl_schema}.icms_bp_extend_d t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/icms_bp_extend_d.f.${batch_date}.dat" \
        charset=utf8
        safe=yes
