: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_odss_flw_t_corp_reg_f
CreateDate: 20180529
FileName:   ${iel_data_path}/odss_flw_t_corp_reg_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
id
,main_flow_id
,scan_seq_no
,process_inst_id
,fun_code
,fr_org_code
,tr_date
,biz_code
,voucher_code
,voucher_no
,cust_id
,chs_acct_flag
,chs_account
,biz_cd_flag
,spec_acct_type
,rcv_pay_rang
,biz_account
,acct_type
,acct_char
,acct_specie
,chk_fund_flag
,cust_name
,ab_cust_name
,english_name
,cst_corp_code
,seal_cr_code
,telephone
,addr_type
,postcode
,contact_address
,fin_contect_name
,pst_bll_address
,curr_type
,amount
,draw_reason
,sf_scp_flag
,cal_accr_flag
,pst_bll_flag
,cur_acct_type
,pndg_rec_methoed
,sf_scope
,acct_status
,attor_opr_code
,attor_opr_name
,attor_org_code
,renw_scan_flag
,print_count
,acct_open_date
,cf_flag
,cf_properies
,tr_account
,accpt_accr_account
,int_rate_cert
,int_rt_operation
,int_rt_cal_code
,int_rt
,fee_ratio
,reserve_amt
,inval_date
,cls_acct_date
,update_time
,chk_star_date
,avl_date
,app_used_date
,fr_tlr_opr_no
,level_a_chrg_code
,level_a_pin
,level_b_chrg_code
,level_b_pin
,fst_chk_opr_code
,check_option
,check_remark
,check_date
,sec_chk_opr_code
,re_check_option
,re_check_remark
,re_check_date
,bk_chrg_opr_code
,charge_option
,charge_remark
,puc_check_flag
,puc_chk_opr_code
,puc_chk_option
,puc_chk_remark
,puc_chk_date
,puc_chrg_opr_code
,check_status
,check_fall_reason
,succ_flag
,status
,back_oper_center_id
,obtain_opr_code
,deposit_type
,organiz_code
,registerfund
,district_code
,operate_scope
,papers_kind
,papers_id
,customs_id
,fund_quality
,papers_type
,papers_number
,principal_name
,perpers_inval_date
,papers_type2
,papers_number2
,perpers_inval_date2
,fax
,principal_perp_invaldt
,principal_contact_type
,fin_papers_type
,principal_papers_type
,principal_papers_number
,fin_papers_number
,fin_papers_invaldt
,fin_contact_type
,resident_flag
,register_type
,trade_type
,economic_organiz_type
,company_scope
,nat_economic_b_type
,nat_economic_s_type
,tax_register_flag
,tax_devision_prove
,nat_register_no
,local_register_no
,company_name
,company_certificate
,compay_organiz_code
,compay_organiz_invaldt
,compay_fin_name
,company_fin_paptype
,company_fin_papno
,shareholder_num
,shareholder_no
,shareholder_name
,account_date
,account_type
,flag_no
,follow_no
,shareholder_papers_invaldt
,tx_code
,shareholder_defend_flag
,acct_useing
,out_ticket_certificate
,draw_type
,store_type
,check_count_code
,cal_accr_type
,accpt_accr_third
,cust_name_third
,host_no
,receive_no
,bankcode_result
,bankcode_reason
,blacklist_result
,blacklist_reason
,fast_gallery
,last_patch_date
,patch_over
,is_proxy
,proxy_papers_name
,proxy_papers_type
,proxy_papers_number
,proxy_papers_invaldt
,visit_service
,whether_new_visitor
,raw_scan_seq_no
,host_trade_date
,if_seal_mirror
,is_ahead_approval
,is_net_silver_contract
,approve_no
,approve_date
,patch_type
,call_result
,call_channel
,if_seal_card
,call_question_result
,call_record_file_id
,call_record
,principal_contact_phone
,if_people_bank_input
,seal_step
,batch_from
,open_bank_no
,seal_chg_reason
,principal_sex
,is_sms_contract
,sms_notice_limit
,is_sms_notice
,is_sms_notice_no_limit
,sms_contract_if_succeed
,net_silver_contract_succeed
,sealmode
,address
,zip
,linkman
,phone
,mobilephone
,sendmode
,check_acct_sign
,is_bank_corp_contract
,proxy_papers_phone
,call_contact_person1
,call_contact_person2
,call_contact_person3
,call_position1
,call_position2
,call_position3
,call_contact_tel1
,call_contact_tel2
,call_contact_tel3
,call_phone1
,call_phone2
,call_phone3
,csec_node_id
,acct_name
,account_active_date
,account_active_flag
,call_contact_person4
,call_position4
,call_contact_tel4
,call_phone4
,pbank_info_input_state
,is_need_pbank_input
,basis_service_apply
,register_curr_type
,account_escape_check
,acc_esc_less_check
,check_one
,sub_account_no
,change_type
,account_name_con_type
,account_name_prefix
,account_name_suffix
,construction_department_name
,construction_legal_id_type
,construction_legal_id_code
,construction_depart_postcode
,construction_department__add
,settlement_type
,withdraw_mark
,withdraw_approvals
,acc_change_type
,construction_depart_phone
,not_tax_register_material
,superior_fin_type
,compay_fin_type
,fund_manage_name
,organiz_credit_code
,fund_manage_papers_type
,fund_manage_papers_number
,pbank_input_reason
,acctno_type
,account_open_reason
,insubacctno
,call_tout_flag
,call_iout_user_id
,call_tout_charge_id
,urgent_days
,out_call
,perpers_id_inval_date
,contact_name
,cust_phone
,pre_seqno
,pre_status
,pre_remark
,organiz_invaldt
,organiz_credit_invaldt
,holdna1
,holdcerttp1
,holdcertno1
,holdvalidt1
,holdna2
,holdcerttp2
,holdcertno2
,holdvalidt2
,checktype
,company_fin_invaldt
,sdflag
,bcreason
,acc_seqno
,pre_mark
,pre_approve_user
,pre_approve_time
,principal_kind
,company_fin_kind
,trust_name1
,trust_id_type1
,trust_id_no1
,trust_name2
,trust_id_type2
,trust_id_no2
,accredit_name1
,accredit_id_type1
,accredit_id_no1
,accredit_name2
,accredit_id_type2
,accredit_id_no2
,proxy_items
,reg_depm
,organiz_tp
,reg_notp
,reg_no
,econ_tp
,found_date
,up_reg_notp
,up_reg_no
,up_organiz_credit_code
,accredit_legalname
,accredit_legalidtype
,accredit_legalidno
,proxy_items_other
,acsttg
,funds_escape_check
,call_orders
,all_escape_check
,not_funds_escape_check
,other_busi_check
,principal_funds_check
,fin_contect_funds_check
,chrg_funds_check1
,chrg_funds_check2
,funds_must_check
,produce_addr
,credit_no
,workers
,income
,properties
,organ_type
,up_organiz_name
,up_organiz_code
,submit_state
,trade_type_detail
from ${idl_schema}.odss_flw_t_corp_reg
where etl_dt=to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/odss_flw_t_corp_reg_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes