: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_pbss_flw_t_corp_reg_f
CreateDate: 20180529
FileName:   ${iel_data_path}/pbss_flw_t_corp_reg.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
    to_date('${batch_date}','yyyymmdd') as etl_dt
    ,accredit_id_type1
    ,accredit_id_no1
    ,accredit_name2
    ,accredit_id_type2
    ,accredit_id_no2
    ,proxy_items
    ,reg_depm
    ,organiz_tp
    ,reg_notp
    ,reg_no
    ,econ_tp
    ,found_date
    ,up_reg_notp
    ,up_reg_no
    ,up_organiz_credit_code
    ,accredit_legalname
    ,accredit_legalidtype
    ,accredit_legalidno
    ,proxy_items_other
    ,acsttg
    ,funds_escape_check
    ,call_orders
    ,all_escape_check
    ,not_funds_escape_check
    ,other_busi_check
    ,principal_funds_check
    ,fin_contect_funds_check
    ,chrg_funds_check1
    ,chrg_funds_check2
    ,funds_must_check
    ,produce_addr
    ,credit_no
    ,workers
    ,income
    ,properties
    ,organ_type
    ,up_organiz_name
    ,up_organiz_code
    ,submit_state
    ,trade_type_detail
    ,sign_type
    ,is_other_manage
    ,apply_type
    ,bond_code
    ,bond_name
    ,bond_acct
    ,bond_new_acct
    ,is_fund_acct
    ,fund_acct_type
    ,send_type
    ,old_acct
    ,new_acct
    ,transfer_reason
    ,low_paper_id
    ,trun_in_acct
    ,transfer_fund_code
    ,transfer_fund_lot
    ,is_fund_trade
    ,fund_trade_type
    ,fund_name
    ,fund_code
    ,is_subscribe
    ,subscribe_amt
    ,is_redeem
    ,redeem_sum
    ,huge_redeem_tpye
    ,is_smart_invest
    ,first_invest_amt
    ,invest_date
    ,later_invest_type
    ,later_invest_optp
    ,invest_fixed_amt
    ,invest_remain_ratio
    ,invest_per_add_amt
    ,invest_period_opyp
    ,invest_period_type
    ,later_invest_period
    ,invest_deadline_optp
    ,invest_deadline_type
    ,time_invest_deadline
    ,invest_number
    ,invest_amt_sum
    ,savings_invest_optp
    ,invest_code
    ,is_smart_redeem
    ,first_redeem_sum
    ,redeem_date
    ,later_redeem_type
    ,later_redeem_optp
    ,redeem_fixed_amt
    ,redeem_remain_ratio
    ,redeem_per_add_amt
    ,redeem_period_opyp
    ,redeem_period_type
    ,redeem_period
    ,redeem_deadline_optp
    ,redeem_deadline_type
    ,redeem_deadline
    ,redeem_number
    ,redeem_amt_sum
    ,smart_redeem_optp
    ,redeem_code
    ,is_fund_change
    ,changed_fund_name
    ,changed_fund_code
    ,changed_fund_sum
    ,is_fund_deposit
    ,deposit_fund_name
    ,deposit_fund_code
    ,deposit_fund_sum
    ,deposit_brcna
    ,is_day_withdraw
    ,ori_scan_seqno
    ,is_share_change
    ,is_cash_share
    ,is_share_invest
    ,is_finance
    ,finance_optp
    ,finance_apply
    ,finance_product_name
    ,finance_product_code
    ,finance_product_deadline
    ,finance_product_curr
    ,finance_amt
    ,finance_amt_zh
    ,netb_acct1
    ,netb_acct1_optp
    ,netb_acct2
    ,netb_acct2_optp
    ,netb_acct3
    ,netb_acct3_optp
    ,netbapplys
    ,netb_add_type
    ,netb_add_apps
    ,netb_cancel_type
    ,netb_cancel_apps
    ,peoxy_phone
    ,peoxy_email
    ,acct
    ,fin_quotient
    ,fin_ori_entrust_no
    ,fin_ori_entrust_date
    ,is_fund_contract
    ,fundopflag
    ,fin_manager_id
    ,szsecno
    ,shsecno
    ,minorflag
    ,fundnewacct
    ,fund_contract_if_succeed
    ,is_third_manage_contract
    ,cobank
    ,ori_acct
    ,ori_brcode
    ,bond_pass
    ,third_manage_if_succeed
    ,is_smart_cat_contract
    ,smart_cat_opflag
    ,smart_cat_sign_kind
    ,is_invest_contract
    ,invest_opflag
    ,invest_contract_if_succeed
    ,is_quickin_contract
    ,quickin_opflag
    ,chan_save_tp
    ,chan_save_deadline
    ,chan_save_amt
    ,save_low_amt
    ,chan_save_multiple
    ,quickin_contract_if_succeed
    ,third_ma_apply_tp
    ,third_ma_new_acct
    ,is_acctfund_contract
    ,acctfund_sign_type
    ,is_bill_send
    ,acctfund_ori_acct
    ,nontrade_chan_reason
    ,legal_paper_id
    ,nontrade_to_acct
    ,chan_fund_code
    ,chan_fund_sum
    ,is_tradefund_contract
    ,tradefund_sign_type
    ,tradefund_name
    ,tradefund_code
    ,invest_period_optp
    ,time_invest_code
    ,time_redeem_code
    ,third_manage_optp
    ,finance_deadline
    ,is_cat_sign
    ,fund_acct
    ,fund_acct_brcno
    ,finance_amt_ch
    ,quickin_leave_amt
    ,quickin_leave_amt_other
    ,netb_apply_ac_info
    ,netb_ac_backs
    ,netb_op_choice
    ,netb_password_optp
    ,netb_netphone_optp
    ,ukey_optp
    ,is_sms_set_phone
    ,is_net_trans_limit_set
    ,is_mob_trans_limit_set
    ,telb_sign_type
    ,is_telb_appoint_phone
    ,telb_appoint_phone_optp
    ,direct_trans_optp
    ,is_direct_trans_ac_set
    ,sms_set_phone_optp
    ,tel_n_trnsf_optp
    ,fin_new_acct
    ,fin_new_open_brcno
    ,cust_changes
    ,redeem_back_tp
    ,changed_back_tp
    ,deposit_trade_no
    ,finance_contract_if_succeed
    ,clientgroup
    ,acccycle
    ,check_contact
    ,isfcfnct
    ,daylimit
    ,txntimeslimit
    ,yearlimit
    ,is_fcfnct_succeed
    ,custom_daylimit
    ,custom_txntimeslimit
    ,custom_yearlimit
    ,ifchangecorpseal
    ,taxresident
    ,taxarea
    ,taxarea2
    ,taxarea3
    ,taxnumber
    ,taxnumber2
    ,taxnumber3
    ,taxnullreason
    ,taxstatement
    ,corporgtype
    ,taxnullreason2
    ,taxnullreason3
    ,other_reason_1
    ,other_reason_2
    ,other_reason_3
    ,holdna3
    ,controller_1_surname
    ,controller_1_givenname
    ,controller_1_taxresident
    ,controller_1_birthdate
    ,controller_1_taxarea_1
    ,controller_1_taxnumber_1
    ,controller_1_taxnullreason_1
    ,controller_1_other_reason_1
    ,controller_1_taxarea_2
    ,controller_1_taxnumber_2
    ,controller_1_taxnullreason_2
    ,controller_1_other_reason_2
    ,controller_1_taxarea_3
    ,controller_1_taxnumber_3
    ,controller_1_taxnullreason_3
    ,controller_1_other_reason_3
    ,controller_1_type
    ,id
    ,main_flow_id
    ,scan_seq_no
    ,process_inst_id
    ,fun_code
    ,fr_org_code
    ,tr_date
    ,biz_code
    ,voucher_code
    ,voucher_no
    ,cust_id
    ,chs_acct_flag
    ,chs_account
    ,biz_cd_flag
    ,spec_acct_type
    ,rcv_pay_rang
    ,biz_account
    ,acct_type
    ,acct_char
    ,acct_specie
    ,chk_fund_flag
    ,cust_name
    ,ab_cust_name
    ,english_name
    ,cst_corp_code
    ,seal_cr_code
    ,telephone
    ,addr_type
    ,postcode
    ,contact_address
    ,fin_contect_name
    ,pst_bll_address
    ,curr_type
    ,amount
    ,draw_reason
    ,sf_scp_flag
    ,cal_accr_flag
    ,pst_bll_flag
    ,cur_acct_type
    ,pndg_rec_methoed
    ,sf_scope
    ,acct_status
    ,attor_opr_code
    ,attor_opr_name
    ,attor_org_code
    ,renw_scan_flag
    ,print_count
    ,acct_open_date
    ,cf_flag
    ,cf_properies
    ,tr_account
    ,accpt_accr_account
    ,int_rate_cert
    ,int_rt_operation
    ,int_rt_cal_code
    ,int_rt
    ,fee_ratio
    ,reserve_amt
    ,inval_date
    ,cls_acct_date
    ,update_time
    ,deposit_type
    ,operate_scope
    ,papers_type
    ,papers_number
    ,principal_name
    ,perpers_inval_date
    ,principal_perp_invaldt
    ,principal_contact_type
    ,fin_papers_type
    ,principal_papers_type
    ,principal_papers_number
    ,fin_papers_number
    ,fin_papers_invaldt
    ,fin_contact_type
    ,proxy_papers_name
    ,proxy_papers_type
    ,proxy_papers_number
    ,proxy_papers_invaldt
    ,principal_contact_phone
    ,proxy_papers_phone
    ,acct_name
    ,pre_seqno
    ,appointbrcode
    ,papers_contact_address
    ,papers_principal_name
    ,papers_papers_number
    ,papers_cust_name
    ,papers_registerfund
    ,papers_operate_scope
    ,registerfund
    ,approve_no
    ,people_area_code
    ,change_type
    ,receive_no
from idl.pbss_flw_t_corp_reg
  where etl_dt = to_date('${batch_date}','yyyymmdd') " \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/pbss_flw_t_corp_reg.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes