: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_odss_business_apply_f
CreateDate: 20180529
FileName:   ${iel_data_path}/odss_business_apply_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select serialno
   ,relativeserialno
   ,occurdate
   ,customerid
   ,customername
   ,businesstype
   ,businesssubtype
   ,occurtype
   ,fundsource
   ,operatetype
   ,currenylist
   ,currencymode
   ,businesstypelist
   ,calculatemode
   ,useorglist
   ,cycleflag
   ,flowreduceflag
   ,contractflag
   ,subcontractflag
   ,selfuseflag
   ,creditaggreement
   ,relativeagreement
   ,loanflag
   ,totalsum
   ,ourrole
   ,reversibility
   ,billnum
   ,housetype
   ,lctermtype
   ,riskattribute
   ,suretype
   ,safeguardtype
   ,businesscurrency
   ,businesssum
   ,businessprop
   ,termyear
   ,termmonth
   ,termday
   ,lgterm
   ,baseratetype
   ,baserate
   ,ratefloattype
   ,ratefloat
   ,businessrate
   ,ictype
   ,iccyc
   ,pdgratio
   ,pdgsum
   ,pdgpaymethod
   ,pdgpayperiod
   ,promisesfeeratio
   ,promisesfeesum
   ,promisesfeeperiod
   ,promisesfeebegin
   ,mfeeratio
   ,mfeesum
   ,mfeepaymethod
   ,agentfee
   ,dealfee
   ,totalcast
   ,discountinterest
   ,purchaserinterest
   ,bargainorinterest
   ,discountsum
   ,bailratio
   ,bailcurrency
   ,bailsum
   ,bailaccount
   ,fineratetype
   ,finerate
   ,drawingtype
   ,firstdrawingdate
   ,drawingperiod
   ,paytimes
   ,paycyc
   ,graceperiod
   ,overdraftperiod
   ,oldlcno
   ,oldlctermtype
   ,oldlccurrency
   ,oldlcsum
   ,oldlcloadingdate
   ,oldlcvaliddate
   ,direction
   ,purpose
   ,planallocation
   ,immediacypaysource
   ,paysource
   ,corpuspaymethod
   ,interestpaymethod
   ,thirdparty1
   ,thirdpartyid1
   ,thirdparty2
   ,thirdpartyid2
   ,thirdparty3
   ,thirdpartyid3
   ,thirdpartyregion
   ,thirdpartyaccounts
   ,cargoinfo
   ,projectname
   ,operationinfo
   ,contextinfo
   ,securitiestype
   ,securitiesregion
   ,constructionarea
   ,usearea
   ,flag1
   ,flag2
   ,flag3
   ,tradecontractno
   ,invoiceno
   ,tradecurrency
   ,tradesum
   ,paymentdate
   ,operationmode
   ,vouchclass
   ,vouchtype
   ,vouchtype1
   ,vouchtype2
   ,vouchflag
   ,warrantor
   ,warrantorid
   ,othercondition
   ,guarantyvalue
   ,guarantyrate
   ,baseevaluateresult
   ,riskrate
   ,lowrisk
   ,otherarealoan
   ,lowriskbailsum
   ,originalputoutdate
   ,extendtimes
   ,lngotimes
   ,golntimes
   ,drtimes
   ,baseclassifyresult
   ,applytype
   ,bailrate
   ,finishorg
   ,operateorgid
   ,operateuserid
   ,operatedate
   ,inputorgid
   ,inputuserid
   ,inputdate
   ,updatedate
   ,pigeonholedate
   ,remark
   ,flag4
   ,paycurrency
   ,paydate
   ,describe1
   ,describe2
   ,classifyresult
   ,classifydate
   ,classifyfrequency
   ,vouchnewflag
   ,adjustratetype
   ,adjustrateterm
   ,rateadjustcyc
   ,fzanbalance
   ,acceptinttype
   ,fixcyc
   ,thirdpartyadd1
   ,thirdpartyzip1
   ,thirdpartyadd2
   ,thirdpartyzip2
   ,thirdpartyadd3
   ,thirdpartyzip3
   ,effectarea
   ,termdate1
   ,termdate2
   ,termdate3
   ,ratio
   ,tempsaveflag
   ,flag5
   ,creditcycle
   ,guarantyflag
   ,isliquidity
   ,isfixed
   ,isproject
   ,nrelativecontractno
   ,relativeaggreement
   ,signedplace
   ,otherdatum
   ,ltvvalue
   ,savetype
   ,channel
   ,buyno
   ,betterrateflag
   ,entname
   ,introducerid
   ,orderno
   ,gracetermflag
   ,graceterm
   ,holdbalance
   ,dunloanratio
   ,preapproverid
   ,fundserialno
   ,mainreturntype
   ,cguarantypeople
   ,turnratio
   ,salechannelid
   ,bar_code_no
   ,poundagerate
   ,approvedate
   ,isnewcustomer
   ,salemode
   ,loanpreference
   ,approvelevel
   ,schemeno
   ,abysum
   ,loadrelabarcode
   ,otherdatumremark
   ,greensetdate
   ,gaincyc
   ,csinglnassure
   ,sellerinformation
   ,accountopenfee
   ,ratemode
   ,loanrelacontractno
   ,formerserialno
   ,tradebarcode
   ,feetype
   ,houseareage
   ,otherpurpose
   ,hasbothflag
   ,currency
   ,ctogetherborrower
   ,isnewcustomertime
   ,applyinsuranceflag
   ,accountexpenses
   ,guarantyhouse
   ,datatype
   ,greenflag
   ,gracetermpay
   ,dunloanresource
   ,spreadername
   ,pddid
   ,carintroducername
   ,approveresult
   ,buyhouseproperty
   ,gatheringcardid
   ,loantermflag
   ,loanpurposeamt
   ,moneyproportion
   ,dundepositno
   ,gainamount
   ,commissionfee
   ,feemethod
   ,presignflag
   ,returnperiod
   ,houseprice
   ,signaddress
   ,housecount
   ,paymentmode
   ,ratecode
   ,calcterm
   ,approvesum
   ,edumfee
   ,buyaddress
   ,gatheringname
   ,paytype
   ,crdid
   ,paymentcardid
   ,operateusermind
   ,buyhousetype
   ,faremoneytype
   ,sendchitflag
   ,oapproveflag
   ,loanterm
   ,schemenofalg
   ,schemenoflag
   ,returntype
   ,saleteamid
   ,dealerid
   ,loantrustfee
   ,deductaccno
   ,backfee
   ,cycleratio
   ,goldflag
   ,sealtype
   ,transferaccount
   ,ratedescribe
   ,creditmode
   ,isfinance
   ,industrytype
   ,artificialno
   ,analystno
   ,isrelative
   ,effectflag
   ,customertype
   ,archiveflag
   ,changeflag
   ,originalserialno
   ,flag
   ,ifcommerce
   ,mortgagecreditserialno
   ,mortgagecreditowner
   ,isstraight
   ,professionalflag
   ,suremodel
   ,issme
   ,transcount
   ,accountno
   ,maturity
   ,istrans
   ,carbrand
   ,cartype
   ,carnumber
   ,chariotnumber
   ,motornumber
   ,financialcreditserialno
   ,financialcreditowner
   ,isfinancialcredit
   ,financialmodel
   ,issmeandretail
   ,ruleid
from ${idl_schema}.odss_business_apply
where etl_dt = TO_DATE('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/odss_business_apply_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes