: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_hdws_ibms_ttrd_accounting_secu_obj_his_i
CreateDate: 20180529
FileName:   ${iel_data_path}/hdws_ibms_ttrd_accounting_secu_obj_his.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
 t1.obj_id
,t1.tsk_id
,t1.beg_date
,t1.end_date
,t1.ext_secu_acct_id
,t1.secu_acct_id
,t1.trade_grp_id
,t1.i_code
,t1.a_type
,t1.m_type
,t1.trade_id
,t1.extra_dim
,t1.real_volume
,t1.real_amount
,t1.real_cp
,t1.ai
,t1.ai_cost
,t1.chg_fv
,t1.due_amount
,t1.due_cp
,t1.due_ai
,t1.amrt_count
,t1.amrt_date
,t1.amrt_ir
,t1.prft_fv
,t1.prft_trd
,t1.prft_ir
,t1.prft_ir_ai
,t1.prft_ir_amrt
,t1.prft_ir_ai_hld
,t1.prft_ir_amrt_hld
,t1.reclass_prft_fv
,t1.impair
,t1.prft_impair
,t1.real_margin
,t1.open_time
,t1.update_time
,t1.prft_fee
,t1.due_fee
,t1.fee
,t1.amrt_cost_cp
,t1.amrt_cost_ai
,t1.amrt_ir_hp
,t1.amrt_ytm
,t1.invest_ytm
,t1.open_ytm
,t1.future_ai
,t1.real_cp_noamrt
,t1.chg_fv_noamrt
,t1.prft_fv_noamrt
,t1.prft_trd_noamrt
,t1.amrt_method
,t1.real_volume_termcur
,t1.real_amount_termcur
,t1.due_amount_termcur
,t1.real_cp_termcur
,t1.due_cp_termcur
,t1.prft_ir_amrt_rc
,t1.prft_ir_amrt_hld_rc
,t1.amrt_cost_cp_rc
,t1.amrt_ytm_rc
,t1.amrt_ir_hp_rc
,t1.calc_date
,t1.ipr_state
,t1.ipr_prft_cp
,t1.ipr_prft_ai
,t1.ipr_cp
,t1.ipr_hx_cp
,t1.ipr_hx_ai
,t1.ipr_hx_due_ai
,t1.ipr_bw_ai
,t1.ipr_bw_due_ai
,t1.amrt_date_rc
,t1.amrt_cost_ai_rc
,t1.open_date_rc
,t1.prft_ir_ai_calc_tax
,t1.tax_ai
,t1.tax_due_ai
,t1.tax_fee
,t1.fv_currency
,t1.set_date
,t1.prft_fv_cash
,t1.tax_ai_hld
,t1.open_ai
,t1.open_ytm_opt
,t1.prft_ir_ai_fut
,t1.prft_ir_ai_cur
,t1.prft_ir_ai_due
,t1.prft_ir_ai_cash
,t1.tax_fut_ai
,t1.tax_due_amrt
,t1.tax_due_amrt_rc
,t1.tax_due_trd
,t1.tax_due_fv
,t1.tax_due_fv_reclass
,t1.tax_due_fv_cash
,t1.tax_due_fee
,t1.due_chg_fv
,t1.due_volume
,t1.amrt_verify_code
,t1.amrt_verify_date
,t1.prft_reclass
,t1.close_set_date
,t1.trade_inst_id
,t1.custom_dim1
,t1.ipr_period
,t1.ipr_cp1
,t1.ipr_cp2
,t1.ipr_cp3
,t1.ipr_prft_cp1
,t1.ipr_prft_cp2
,t1.ipr_prft_cp3
,t1.amrt_start_ir_hp
,t1.tax_amrt
,t1.calc_tax_amrt_cur
,t1.calc_tax_amrt_due
,t1.calc_tax_amrt_cash
,t1.tax_fv
,t1.tax_ir
,t1.tax_due_ir
,t1.prft_id
,t1.deviation
,t1.prft_ir_fut_ai
from ${idl_schema}.hdws_ibms_ttrd_accounting_secu_obj_his t1 
where etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/hdws_ibms_ttrd_accounting_secu_obj_his.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes