: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_ftps_rpt_rst_ftp261_i
CreateDate: 20180529
FileName:   ${iel_data_path}/ftps_rpt_rst_ftp261.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select
etl_dt
,acct_no
,s_acct_no
,t_acct_no
,data_dt
,share_percent
,price_unit_cd
,prod_cd
,core_prod_cd
,credit_prod_cd
,industry_cd
,subject_cd
,currency_cd
,acct_org_cd
,assess_org_cd
,bond_categ_cd
,al_flag
,biz_flag
,biz_line_cd
,data_src
,channel_cd
,interest_adjust_type_cd
,cust_id
,cust_name
,mgr_id
,mgr_name
,cust_size_cd
,cust_type_cd
,accrual_basis_cd
,original_term
,original_term_mult
,start_dt
,maturity_dt
,open_dt
,close_dt
,last_payment_dt
,next_payment_dt
,payment_type_cd
,payment_freq
,payment_freq_mult
,last_repricing_dt
,next_repricing_dt
,repricing_freq
,repricing_freq_mult
,overdue_flag
,position_inc_dt
,agmt_deposit_flag
,excess_reserce_flag
,iflock_flag
,loan_class_cd
,cur_bal
,accbal_month
,accbal_quar
,accbal_year
,exercise_interest_rate
,base_ftp_rate
,mid_ftp_rate
,final_ftp_rate
,lock_spread
,base_unlock_ftp_rate
,mid_unlock_ftp_rate
,final_unlock_ftp_rate
,accint_day
,accint_month
,accint_quar
,accint_year
,base_ftp_accint_day
,base_ftp_accint_month
,base_ftp_accint_quar
,base_ftp_accint_year
,mid_ftp_accint_day
,mid_ftp_accint_month
,mid_ftp_accint_quar
,mid_ftp_accint_year
,final_ftp_accint_day
,final_ftp_accint_month
,final_ftp_accint_quar
,final_ftp_accint_year
,base_unlock_ftp_accint_day
,base_unlock_ftp_accint_month
,base_unlock_ftp_accint_quar
,base_unlock_ftp_accint_year
,mid_unlock_ftp_accint_day
,mid_unlock_ftp_accint_month
,mid_unlock_ftp_accint_quar
,mid_unlock_ftp_accint_year
,final_unlock_ftp_accint_day
,final_unlock_ftp_accint_month
,final_unlock_ftp_accint_quar
,final_unlock_ftp_accint_year
,adjust_01_rate
,adjust_01_accint_day
,adjust_01_accint_month
,adjust_01_accint_quar
,adjust_01_accint_year
,adjust_02_rate
,adjust_02_accint_day
,adjust_02_accint_month
,adjust_02_accint_quar
,adjust_02_accint_year
,adjust_03_rate
,adjust_03_accint_day
,adjust_03_accint_month
,adjust_03_accint_quar
,adjust_03_accint_year
,adjust_04_rate
,adjust_04_accint_day
,adjust_04_accint_month
,adjust_04_accint_quar
,adjust_04_accint_year
,adjust_05_rate
,adjust_05_accint_day
,adjust_05_accint_month
,adjust_05_accint_quar
,adjust_05_accint_year
,adjust_06_rate
,adjust_06_accint_day
,adjust_06_accint_month
,adjust_06_accint_quar
,adjust_06_accint_year
,adjust_07_rate
,adjust_07_accint_day
,adjust_07_accint_month
,adjust_07_accint_quar
,adjust_07_accint_year
,adjust_08_rate
,adjust_08_accint_day
,adjust_08_accint_month
,adjust_08_accint_quar
,adjust_08_accint_year
,adjust_09_rate
,adjust_09_accint_day
,adjust_09_accint_month
,adjust_09_accint_quar
,adjust_09_accint_year
,adjust_10_rate
,adjust_10_accint_day
,adjust_10_accint_month
,adjust_10_accint_quar
,adjust_10_accint_year
,adjust_11_rate
,adjust_11_accint_day
,adjust_11_accint_month
,adjust_11_accint_quar
,adjust_11_accint_year
,adjust_12_rate
,adjust_12_accint_day
,adjust_12_accint_month
,adjust_12_accint_quar
,adjust_12_accint_year
,adjust_13_rate
,adjust_13_accint_day
,adjust_13_accint_month
,adjust_13_accint_quar
,adjust_13_accint_year
,adjust_14_rate
,adjust_14_accint_day
,adjust_14_accint_month
,adjust_14_accint_quar
,adjust_14_accint_year
,adjust_15_rate
,adjust_15_accint_day
,adjust_15_accint_month
,adjust_15_accint_quar
,adjust_15_accint_year
,adjust_16_rate
,adjust_16_accint_day
,adjust_16_accint_month
,adjust_16_accint_quar
,adjust_16_accint_year
,adjust_17_rate
,adjust_17_accint_day
,adjust_17_accint_month
,adjust_17_accint_quar
,adjust_17_accint_year
,adjust_18_rate
,adjust_18_accint_day
,adjust_18_accint_month
,adjust_18_accint_quar
,adjust_18_accint_year
,adjust_19_rate
,adjust_19_accint_day
,adjust_19_accint_month
,adjust_19_accint_quar
,adjust_19_accint_year
,adjust_20_rate
,adjust_20_accint_day
,adjust_20_accint_month
,adjust_20_accint_quar
,adjust_20_accint_year
,inc_spred_accint_day
,inc_spred_accint_month
,inc_spred_accint_quar
,inc_spred_accint_year
,exchange_to_cny_rate
,exchange_to_usd_rate
from ${idl_schema}.ftps_rpt_rst_ftp261 t1
where etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/ftps_rpt_rst_ftp261.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes