: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_icms_ent_info_f
CreateDate: 20221208
FileName:   ${iel_data_path}/icms_ent_info.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.basicbank as basicbank
,t1.basicaccount as basicaccount
,t1.mybank as mybank
,t1.mybankaccount as mybankaccount
,t1.otherbank as otherbank
,t1.otherbankaccount as otherbankaccount
,t1.accountdate as accountdate
,t1.creditdate as creditdate
,t1.evaluatedate as evaluatedate
,t1.remark as remark
,t1.inputuserid as inputuserid
,t1.inputorgid as inputorgid
,t1.inputdate as inputdate
,t1.updateuserid as updateuserid
,t1.updateorgid as updateorgid
,t1.updatedate as updatedate
,t1.swiftcode as swiftcode
,t1.financeorglicence as financeorglicence
,t1.financeorgcode as financeorgcode
,t1.countryrisk as countryrisk
,t1.corpid as corpid
,t1.corporgid as corporgid
,t1.registerregioncode as registerregioncode
,t1.economictype as economictype
,t1.countrycode as countrycode
,t1.fictitiousperson as fictitiousperson
,t1.fictitiouspersonid as fictitiouspersonid
,t1.listingcorpornot as listingcorpornot
,t1.hasiebusiness as hasiebusiness
,t1.registerdate as registerdate
,t1.mcompanyname as mcompanyname
,t1.mcompanycerttype as mcompanycerttype
,t1.mcompanycertid as mcompanycertid
,t1.firstloandate as firstloandate
,t1.subjectbusiness as subjectbusiness
,t1.industrytypeforrs as industrytypeforrs
,t1.strategicemergingindustrytype as strategicemergingindustrytype
,t1.corporationgrowthstage as corporationgrowthstage
,t1.organiztype as organiztype
,t1.orgdetail as orgdetail
,t1.ifoversea as ifoversea
,t1.rwacustomertype as rwacustomertype
,t1.isnewsetup as isnewsetup
,t1.privateent as privateent
,t1.bankingsupervision as bankingsupervision
,t1.bankingtype as bankingtype
,t1.isdebt as isdebt
,t1.islimit as islimit
,t1.laborintensiveentflag as laborintensiveentflag
,t1.holdingtype as holdingtype
,t1.iscountrysidenterprise as iscountrysidenterprise
,t1.isblack as isblack
,t1.locality as locality
,t1.isfreshcust as isfreshcust
,t1.lmcredittype as lmcredittype
,t1.businessstrategy as businessstrategy
,t1.industrialrestructuringtype as industrialrestructuringtype
,t1.transformationandupgradeid as transformationandupgradeid
,t1.orgstatus as orgstatus
,t1.onlylimit as onlylimit
,t1.shareholderstructuredate as shareholderstructuredate
,t1.clyxcustomerid as clyxcustomerid
,t1.chargedepartment as chargedepartment
,t1.isrelativetrade as isrelativetrade
,t1.corpidetitytype as corpidetitytype
,t1.fundsource as fundsource
,t1.fiscalsource as fiscalsource
,t1.serviceupdateresult as serviceupdateresult
,t1.governmentlevel as governmentlevel
,t1.isrelatedparty as isrelatedparty
,t1.managearea as managearea
,t1.financecorpid as financecorpid
,t1.otherorgname as otherorgname
,t1.corpstartdate as corpstartdate
,t1.isdlfr as isdlfr
,t1.ispart as ispart
,t1.isoverseas as isoverseas
,t1.authflag as authflag
,t1.isinvestcust as isinvestcust
,t1.distributestatus as distributestatus
,t1.customertype as customertype
,t1.ifsme as ifsme
,t1.fictitiouspersoncertificateid as fictitiouspersoncertificateid
,t1.fictitiousmobile as fictitiousmobile
,t1.registeradd as registeradd
,t1.newregioncode as newregioncode
,t1.financedirectorname as financedirectorname
,t1.mobilephone as mobilephone
,t1.loancardpassword as loancardpassword
,t1.projectflag as projectflag
,t1.realtyflag as realtyflag
,t1.isstrategycustomer as isstrategycustomer
,t1.financefiamtel as financefiamtel
,t1.financeothertel as financeothertel
,t1.actualcontrollercounts as actualcontrollercounts
,t1.investmencounts as investmencounts
,t1.financetype2 as financetype2
,t1.greencategory as greencategory
,t1.governmentltype as governmentltype
,t1.upbelongcustid as upbelongcustid
,t1.stateownedentholdingflag as stateownedentholdingflag
,t1.acceptbankid as acceptbankid
,t1.acceptbankname as acceptbankname
,t1.creditinstitutioncode as creditinstitutioncode
,t1.societyinstitutioncode as societyinstitutioncode
,t1.customerid as customerid
,t1.customername as customername
,t1.englishname as englishname
,t1.licenseno as licenseno
,t1.licensebegin as licensebegin
,t1.licensematurity as licensematurity
,t1.nationaltaxno as nationaltaxno
,t1.landtaxno as landtaxno
,t1.setupdate as setupdate
,t1.loancardno as loancardno
,t1.loancardflag as loancardflag
,t1.supercorpname as supercorpname
,t1.supercertid as supercertid
,t1.supercerttype as supercerttype
,t1.superloancardno as superloancardno
,t1.enttype as enttype
,t1.entscale as entscale
,t1.calcuentscale as calcuentscale
,t1.orgtype as orgtype
,t1.orgform as orgform
,t1.orgbelong as orgbelong
,t1.industrytype as industrytype
,t1.ecgroupflag as ecgroupflag
,t1.registercurrency as registercurrency
,t1.registeramount as registeramount
,t1.financedepttel as financedepttel
,t1.emailadd as emailadd
,t1.finarunarea as finarunarea
,t1.finabranchnum as finabranchnum
,t1.listingcorptype as listingcorptype
,t1.employeenumber as employeenumber
,t1.salesamount as salesamount
,t1.generalassets as generalassets
,t1.entindustrytype as entindustrytype
,t1.financetype as financetype
,t1.businessscope as businessscope
,t1.customerhistory as customerhistory
,t1.importrightsflag as importrightsflag
,t1.creditlevel as creditlevel
,t1.workfieldarea as workfieldarea
,t1.workfieldfee as workfieldfee
,t1.manageinfo as manageinfo
,t1.mainproduction as mainproduction
,t1.paidcurrency as paidcurrency
,t1.paidamount as paidamount
,t1.groupflag as groupflag
,t1.start_dt as start_dt
,t1.end_dt as end_dt
,t1.id_mark as id_mark
,t1.ratifydate as ratifydate
,t1.commercialregisterno as commercialregisterno
,t1.taxpayerregisterno as taxpayerregisterno
,t1.survivalstatus as survivalstatus
,t1.environmentrisktype as environmentrisktype
,t1.migtflag as migtflag
,t1.corpregisteradd as corpregisteradd
,t1.corpvaliditydate as corpvaliditydate
,t1.platformaffiliatetype as platformaffiliatetype
,t1.platformlawtype as platformlawtype
,t1.techcorpidentifytime as techcorpidentifytime
,t1.techcorptype as techcorptype
,t1.isgovernmentplarform as isgovernmentplarform
,t1.migtoldvalue as migtoldvalue
,t1.firstloanflag as firstloanflag
,t1.actualcontroller as actualcontroller

from ${idl_schema}.icms_ent_info t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/icms_ent_info.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
