: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_iol_crss_upl_business_approve_i_w
CreateDate: 20180529
FileName:   ${iel_data_path}/crss_upl_business_approve_w.i.${batch_date}.dat
IF_mark:    i_w
Logs:
   zjj 2018-07-27 create template
' \
        query="select serialno,relativeserialno,occurdate,customerid,replace(replace(customername,chr(10),''),chr(13),'') as customername,businesstype,businesssubtype,occurtype,currenylist,currencymode,businesstypelist,calculatemode,useorglist,flowreduceflag,contractflag,subcontractflag,selfuseflag,creditaggreement,relativeagreement,loanflag,totalsum,ourrole,reversibility,billnum,housetype,lctermtype,riskattribute,suretype,safeguardtype,creditbusiness,businesscurrency,businesssum,businessprop,termyear,termmonth,termday,lgterm,baseratetype,baserate,ratefloattype,ratefloat,businessrate,ictype,iccyc,pdgratio,pdgsum,pdgpaymethod,pdgpayperiod,promisesfeeratio,promisesfeesum,promisesfeeperiod,promisesfeebegin,mfeeratio,mfeesum,mfeepaymethod,agentfee,dealfee,totalcast,discountinterest,purchaserinterest,bargainorinterest,discountsum,bailratio,bailcurrency,bailsum,bailaccount,fineratetype,finerate,drawingtype,firstdrawingdate,drawingperiod,paytimes,paycyc,graceperiod,overdraftperiod,oldlcno,oldlctermtype,oldlccurrency,oldlcsum,oldlcloadingdate,oldlcvaliddate,direction,purpose,planallocation,immediacypaysource,paysource,corpuspaymethod,interestpaymethod,thirdparty1,thirdpartyid1,thirdparty2,thirdpartyid2,thirdparty3,thirdpartyid3,thirdpartyregion,thirdpartyaccounts,cargoinfo,projectname,operationinfo,contextinfo,securitiestype,securitiesregion,constructionarea,usearea,flag1,flag2,flag3,tradecontractno,invoiceno,tradecurrency,tradesum,paymentdate,operationmode,vouchclass,vouchtype,vouchtype1,vouchtype2,vouchflag,replace(replace(warrantor,chr(10),''),chr(13),'') as warrantor,warrantorid,othercondition,guarantyvalue,guarantyrate,baseevaluateresult,riskrate,lowrisk,otherarealoan,lowriskbailsum,originalputoutdate,extendtimes,lngotimes,golntimes,drtimes,baseclassifyresult,applytype,bailrate,finishorg,describe1,operateorgid,operateuserid,operatedate,inputorgid,inputuserid,inputdate,updatedate,pigeonholedate,remark,paycurrency,paydate,flag4,fundsource,operatetype,approvetype,cycleflag,classifyresult,classifydate,classifyfrequency,vouchnewflag,adjustratetype,adjustrateterm,rateadjustcyc,fzanbalance,acceptinttype,ratio,thirdpartyadd1,thirdpartyzip1,thirdpartyadd2,thirdpartyzip2,thirdpartyadd3,thirdpartyzip3,effectarea,termdate1,termdate2,termdate3,fixcyc,describe2,approveopinion,tempsaveflag,creditcycle,cyclemonths,holdcorpus,incomeorgid,mainrepaymentmethod,replace(replace(payaccountname,chr(10),''),chr(13),'') as payaccountname,payaccountno,paymentmode,ratemode,flag5,defaultpaydate,batchpaymentflag,loanaccountno,loankind,classifyresulteleven,effectflag,approvedate,creditmode,riskacctno,riskacctname,risksum,otherfee,subbusinesstype,payaccountname2,payaccountno2,start_dt,end_dt,id_mark,etl_timestamp from iol.crss_upl_business_approve where start_dt between to_date('${batch_date}', 'yyyymmdd') - 6 and to_date('${batch_date}', 'yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/crss_upl_business_approve_w.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes