: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_hdws_ibms_ttrd_otc_trade_i
CreateDate: 20180529
FileName:   ${iel_data_path}/hdws_ibms_ttrd_otc_trade.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select t1.sysordid
,t1.orddate
,t1.ordtime
,t1.condate
,t1.contime
,t1.insid
,t1.intordid
,t1.extordid
,t1.custordid
,t1.extbizid
,t1.operator
,t1.trdtype
,t1.cash_ext_accid
,t1.cash_accid
,t1.secu_ext_accid
,t1.secu_accid
,t1.partyid
,t1.cp_cash_accid
,t1.cp_secu_accid
,t1.i_code
,t1.a_type
,t1.m_type
,t1.i_name
,t1.ordcount
,t1.ordprice
,t1.ordamount
,t1.trdfee
,t1.setfee
,t1.setdays
,t1.setdate
,t1.thenmktprice
,t1.thenmktprice_u
,t1.ordstatus
,t1.errcode
,t1.errinfo
,t1.bnd_settype
,t1.bnd_netprice
,t1.bnd_aiamount
,t1.remark
,t1.reservetype
,t1.cp_reservetype
,t1.reservechg
,t1.cp_reservechg
,t1.reservevalue
,t1.cp_reservevalue
,t1.resolve
,t1.trade_grp_id
,t1.ref_orddate
,t1.ref_sysordid
,t1.ignore_flag
,t1.exe_market
,t1.trader
,t1.trader_cp
,t1.dealtype
,t1.agreenumber
,t1.eval_netprice
,t1.ordsource
,t1.deal_count
,t1.deal_avg_netprice
,t1.deal_netamount
,t1.deal_aiamount
,t1.deal_amount
,t1.bidaskid
,t1.relatedparty
,t1.terminate_amount
,t1.setdate_terminate
,t1.agreementtype
,t1.partynametempority
,t1.party_zzdaccname
,t1.seatno_cp
,t1.executor
,t1.union_sysordid
,t1.party_zzdacccode
,t1.party_bank_code
,t1.party_acct_code
,t1.party_bank_name
,t1.party_acct_name
,t1.dis_fee_kind_follow
,t1.dis_fee_kind
,t1.grpid_sub
,t1.imp_time
,t1.eval_ytm
,t1.bnd_ytm
,t1.update_time
,t1.due_ai
,t1.operator_id
,t1.executor_id
,t1.due_cp
,t1.real_ai
,t1.real_cp
,t1.real_fee
,t1.due_fee
,t1.ref_type
,t1.is_remain
,t1.trader_id
,t1.trademodel
,t1.settlemodel
,t1.ord_id
,t1.insstatus
,t1.entrust_ref_id
,t1.close_trade_id
,t1.ftprate
,t1.conn_ordid
,t1.two_effective_contract
,t1.source_type
,t1.settlestate
,t1.navdate
,t1.qcurr_cash_ext_accid
,t1.qcurr_party_bank_code
,t1.qcurr_party_bank_name
,t1.qcurr_party_acct_code
,t1.qcurr_party_acct_name
,t1.party_mid_bank_acct_code
,t1.party_mid_bank_name
,t1.party_mid_swift_code
,t1.qcurr_party_mid_bank_acct_code
,t1.qcurr_party_mid_bank_name
,t1.qcurr_party_mid_swift_code
,t1.party_swift_code
,t1.qcurr_party_swift_code
,t1.spv_id
,t1.his_tradeflag
,t1.his_ref_tradeid
,t1.his_trade_setdate
,t1.party_pset
,t1.party_pset_country
,t1.party_agent_code_type
,t1.party_agent_code_dss
,t1.party_agent_code
,t1.party_agent_account
,t1.party_code_type
,t1.party_code_dss
,t1.party_code
,t1.party_account
,t1.si_id
,t1.party_i_bank_code
,t1.party_i_swift_code
,t1.split_inst_type
,t1.cm_attr_parent
,t1.cm_attr_master
,t1.cm_attr_merge
,t1.cm_attr_mirror
,t1.cm_attr_relation
,t1.cal_start_date
,t1.cal_end_date
,t1.strike_ytm
,t1.settlement_type
,t1.aio_acct_no
,t1.acct_type
,t1.user_name
,t1.contractparty
,t1.marketing_manager_id
,t1.marketing_org_id
,t1.com_date
,t1.party_branch
,t1.max_val
,t1.min_val
,t1.collection_fst_fee
,t1.transfer_type
,t1.secu_setdate
,t1.csdc_netprice
,t1.ccdc_netprice
,t1.shch_netprice
,t1.se_netprice
,t1.ctrct_id
,t1.platform
,t1.invest_direction
,t1.contractversion
,t1.final_invest
,t1.associatednumber
,t1.fiveclass
,t1.prod_nature
,t1.trd_acc_code
,t1.store_code
,t1.quote_type
,t1.unit_id
,t1.curcount
,t1.can_div_amount
,t1.is_remain_due_ai
,t1.is_impair
,t1.option_group
,t1.entry_date
,t1.party_pset_name
,t1.relate_invest
,t1.settlement_place
,t1.trdfee_notset
,t1.daycounter
,t1.remain_due_cp
,t1.include_inte
,t1.exh_extordid
,t1.exrcise_state
,t1.sppiresult
,t1.sppiclass
,t1.mergeno
,t1.resource_id
,t1.party_relevance_info
,t1.full_flag
,t1.brokerage_id
,t1.brokerage_fee_info
,t1.released_credit_line
,t1.out_range
,t1.interest_out
,t1.book
,t1.xcc_trade_grp_id
,t1.xcc_pre_sysordid
,t1.pc1
,t1.yhf
,t1.jsf
,t1.ghf
,t1.zgf
,t1.sxf
,t1.brkfee
,t1.yjf
,t1.netyjf
,t1.con_update_time
,t1.qcurr_party_recv_bank_name
,t1.qcurr_party_recv_bank_swift
,t1.party_recv_bank_name
,t1.party_recv_bank_swift_code
,t1.other_fee
,t1.cli_ord_id
,t1.party_acc_code_type
,t1.qcurr_party_acc_code_type
,t1.party_swift_type
,t1.qcurr_party_swift_type
,t1.back_bank_code
,t1.back_acct_code
,t1.back_bank_name
,t1.back_acct_name
,t1.other_agree_item
,t1.bank_group_mode
,t1.cash_setdate
,t1.trd_fee_ext_secu_acct_id
,t1.bnd_ytm_deviate
,t1.pre_bnt_ord_id
,t1.pre_remain_count
,t1.p_id
,t1.ftp_code
from ${idl_schema}.hdws_ibms_ttrd_otc_trade t1 
where etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/hdws_ibms_ttrd_otc_trade.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes