: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idf_cmm_retl_loan_acct_info_f
CreateDate: 20240829
FileName:   ${iel_data_path}/cmm_retl_loan_acct_info.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.lp_id as lp_id
,t1.acct_id as acct_id
,t1.acct_name as acct_name
,t1.cust_id as cust_id
,t1.cont_id as cont_id
,t1.dubil_num as dubil_num
,t1.loan_distr_acct_num as loan_distr_acct_num
,t1.loan_repay_num as loan_repay_num
,t1.std_prod_id as std_prod_id
,t1.prod_id as prod_id
,t1.subj_id as subj_id
,t1.acctnt_cate_cd as acctnt_cate_cd
,t1.bus_breed_id as bus_breed_id
,t1.asset_thd_cls_cd as asset_thd_cls_cd
,t1.loan_modal_cd as loan_modal_cd
,t1.loan_acct_status_cd as loan_acct_status_cd
,t1.unite_loan_cd as unite_loan_cd
,t1.priv_loan_flg as priv_loan_flg
,t1.promis_loan_flg as promis_loan_flg
,t1.circl_loan_flg as circl_loan_flg
,t1.deriv_loan_flg as deriv_loan_flg
,t1.agent_loan_flg as agent_loan_flg
,t1.oots_accti_flg as oots_accti_flg
,t1.loan_modal_dg_subj_accti_flg as loan_modal_dg_subj_accti_flg
,t1.loan_tenor as loan_tenor
,t1.loan_tenor_type_cd as loan_tenor_type_cd
,t1.acru_non_acru_cd as acru_non_acru_cd
,t1.final_fin_dt as final_fin_dt
,t1.open_acct_teller_id as open_acct_teller_id
,t1.clos_acct_teller_id as clos_acct_teller_id
,t1.open_acct_org_id as open_acct_org_id
,t1.mgmt_org_id as mgmt_org_id
,t1.acct_instit_id as acct_instit_id
,t1.open_acct_dt as open_acct_dt
,t1.distr_dt as distr_dt
,t1.value_dt as value_dt
,t1.exp_dt as exp_dt
,t1.clos_acct_dt as clos_acct_dt
,t1.int_sub_flg as int_sub_flg
,t1.renew_flg as renew_flg
,t1.renew_cnt as renew_cnt
,t1.int_accr_rule as int_accr_rule
,t1.int_accr_flg as int_accr_flg
,t1.comp_int_flg as comp_int_flg
,t1.pre_recv_int_way as pre_recv_int_way
,t1.int_rat_adj_way_cd as int_rat_adj_way_cd
,t1.int_rat_base_type_cd as int_rat_base_type_cd
,t1.base_rat_id as base_rat_id
,t1.base_rat as base_rat
,t1.exec_int_rat as exec_int_rat
,t1.int_rat_float_way_cd as int_rat_float_way_cd
,t1.int_rat_adj_ped_corp_cd as int_rat_adj_ped_corp_cd
,t1.int_rat_adj_ped_freq as int_rat_adj_ped_freq
,t1.int_rat_flo_val as int_rat_flo_val
,t1.curr_int_rat_effect_dt as curr_int_rat_effect_dt
,t1.next_int_rat_adj_dt as next_int_rat_adj_dt
,t1.int_set_way_cd as int_set_way_cd
,t1.int_accr_way_cd as int_accr_way_cd
,t1.ped_distr_flg as ped_distr_flg
,t1.distr_way_cd as distr_way_cd
,t1.repay_way_cd as repay_way_cd
,t1.repay_ped_corp_cd as repay_ped_corp_cd
,t1.repay_ped as repay_ped
,t1.allow_adv_repay_flg as allow_adv_repay_flg
,t1.wrt_off_flg as wrt_off_flg
,t1.ovdue_flg as ovdue_flg
,t1.ovdue_int_accr_way_cd as ovdue_int_accr_way_cd
,t1.ovdue_pnlt_float_way_cd as ovdue_pnlt_float_way_cd
,t1.pric_ovdue_flg as pric_ovdue_flg
,t1.int_ovdue_flg as int_ovdue_flg
,t1.curr_ovdue_perds as curr_ovdue_perds
,t1.pric_ovdue_days as pric_ovdue_days
,t1.int_ovdue_days as int_ovdue_days
,t1.ovdue_pric_bal as ovdue_pric_bal
,t1.ovdue_int_amt as ovdue_int_amt
,t1.ovdue_comp_int_amt as ovdue_comp_int_amt
,t1.fir_ovdue_dt as fir_ovdue_dt
,t1.ovdue_int_rat as ovdue_int_rat
,t1.ovdue_int_rat_flo_val as ovdue_int_rat_flo_val
,t1.tot_perds as tot_perds
,t1.curr_issue_perds as curr_issue_perds
,t1.last_repay_dt as last_repay_dt
,t1.curr_cd as curr_cd
,t1.next_repay_dt as next_repay_dt
,t1.next_rpp_amt as next_rpp_amt
,t1.next_repay_int_amt as next_repay_int_amt
,t1.cont_amt as cont_amt
,t1.dubil_amt as dubil_amt
,t1.distr_amt as distr_amt
,t1.froz_distrd_amt as froz_distrd_amt
,t1.distrd_amt as distrd_amt
,t1.td_acru_int as td_acru_int
,t1.currt_acru_int as currt_acru_int
,t1.nomal_pric as nomal_pric
,t1.ovdue_pric as ovdue_pric
,t1.idle_pric as idle_pric
,t1.bad_debt_pric as bad_debt_pric
,t1.loan_fund as loan_fund
,t1.recvbl_acru_int as recvbl_acru_int
,t1.coll_acru_int as coll_acru_int
,t1.recvbl_acru_pnlt as recvbl_acru_pnlt
,t1.coll_acru_pnlt as coll_acru_pnlt
,t1.recvbl_pnlt as recvbl_pnlt
,t1.coll_pnlt as coll_pnlt
,t1.acru_comp_int as acru_comp_int
,t1.recvbl_comp_int as recvbl_comp_int
,t1.acru_int_sub as acru_int_sub
,t1.recvbl_int_sub as recvbl_int_sub
,t1.amorted_int as amorted_int
,t1.wrt_off_pric as wrt_off_pric
,t1.wrt_off_int as wrt_off_int
,t1.int_income as int_income
,t1.wrt_off_advc_fee_bal as wrt_off_advc_fee_bal
,t1.wrt_off_advc_fee_amt as wrt_off_advc_fee_amt
,t1.recvbl_fine as recvbl_fine
,t1.fine_inco as fine_inco
,t1.resv as resv
,t1.recvbl_over_int as recvbl_over_int
,t1.coll_over_int as coll_over_int
,t1.in_bs_int as in_bs_int
,t1.off_bs_int as off_bs_int
,t1.acm_recvbl_uncol_int_amt as acm_recvbl_uncol_int_amt
,t1.repaid_pric as repaid_pric
,t1.repaid_int as repaid_int
,t1.repaid_pnlt as repaid_pnlt
,t1.repaid_comp_int as repaid_comp_int
,t1.repaid_fee as repaid_fee
,t1.pric_bal as pric_bal
,t1.currt_bal as currt_bal
,t1.cl_curr_currt_bal as cl_curr_currt_bal
,t1.ear_d_bal as ear_d_bal
,t1.ear_m_bal as ear_m_bal
,t1.ear_s_bal as ear_s_bal
,t1.ear_y_bal as ear_y_bal
,t1.y_acm_bal as y_acm_bal
,t1.s_acm_bal as s_acm_bal
,t1.m_acm_bal as m_acm_bal
,t1.cl_curr_ear_d_bal as cl_curr_ear_d_bal
,t1.cl_curr_ear_m_bal as cl_curr_ear_m_bal
,t1.cl_curr_ear_s_bal as cl_curr_ear_s_bal
,t1.cl_curr_ear_y_bal as cl_curr_ear_y_bal
,t1.cl_curr_y_acm_bal as cl_curr_y_acm_bal
,t1.cl_curr_ear_d_y_acm_bal as cl_curr_ear_d_y_acm_bal
,t1.cl_curr_ear_m_y_acm_bal as cl_curr_ear_m_y_acm_bal
,t1.cl_curr_ear_s_y_acm_bal as cl_curr_ear_s_y_acm_bal
,t1.cl_curr_ear_y_y_acm_bal as cl_curr_ear_y_y_acm_bal
,t1.cl_curr_s_acm_bal as cl_curr_s_acm_bal
,t1.cl_curr_ear_d_s_acm_bal as cl_curr_ear_d_s_acm_bal
,t1.cl_curr_ear_s_s_acm_bal as cl_curr_ear_s_s_acm_bal
,t1.cl_curr_ear_y_s_acm_bal as cl_curr_ear_y_s_acm_bal
,t1.cl_curr_m_acm_bal as cl_curr_m_acm_bal
,t1.cl_curr_ear_d_m_acm_bal as cl_curr_ear_d_m_acm_bal
,t1.cl_curr_ear_m_m_acm_bal as cl_curr_ear_m_m_acm_bal
,t1.cl_curr_ear_y_m_acm_bal as cl_curr_ear_y_m_acm_bal
,t1.y_avg_bal as y_avg_bal
,t1.q_avg_bal as q_avg_bal
,t1.m_avg_bal as m_avg_bal
,t1.cl_curr_y_avg_bal as cl_curr_y_avg_bal
,t1.cl_curr_q_avg_bal as cl_curr_q_avg_bal
,t1.cl_curr_m_avg_bal as cl_curr_m_avg_bal
,t1.init_pric_subj_id as init_pric_subj_id
,t1.asset_tran_status_cd as asset_tran_status_cd
,t1.tran_bf_int_recvbl as tran_bf_int_recvbl
,t1.td_int_income as td_int_income
,t1.in_bs_int_subj_id as in_bs_int_subj_id
,t1.off_bs_int_subj_id as off_bs_int_subj_id
,t1.int_income_subj_id as int_income_subj_id
,t1.int_income_adj_subj_id as int_income_adj_subj_id
,t1.td_int_income_adj as td_int_income_adj
,t1.irr_repay_way_cd as irr_repay_way_cd
,t1.renew_exp_dt as renew_exp_dt
,t1.asset_tran_dt as asset_tran_dt
,t1.pric_ovdue_dt as pric_ovdue_dt
,t1.int_ovdue_dt as int_ovdue_dt
,t1.loan_num as loan_num
,t1.acru_aldy_impam_int_subj_id as acru_aldy_impam_int_subj_id
,t1.recvbl_int_paybl_adj_subj_id as recvbl_int_paybl_adj_subj_id
,t1.recvbl_uncol_int_subj_id as recvbl_uncol_int_subj_id
,t1.grace_period_pric as grace_period_pric
,t1.grace_period_int as grace_period_int
,t1.out_acct_num as out_acct_num
,t1.init_exp_dt as init_exp_dt
,t1.abs_flg as abs_flg
,t1.asset_tran_flg as asset_tran_flg
,t1.recvbl_uncol_int as recvbl_uncol_int
,t1.int_recvbl as int_recvbl
,t1.non_acru_int_recvbl as non_acru_int_recvbl
,t1.acru_aldy_impam_int as acru_aldy_impam_int
,t1.fir_renew_exp_dt as fir_renew_exp_dt
,t1.open_acct_timestamp as open_acct_timestamp
,t1.clos_acct_timestamp as clos_acct_timestamp

from ${idl_schema}.cmm_retl_loan_acct_info t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/cmm_retl_loan_acct_info.f.${batch_date}.dat" \
        charset=utf8
        safe=yes
