: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_cmm_corp_loan_cont_info_i_w
CreateDate: 20180529
FileName:   ${iel_data_path}/cmm_corp_loan_cont_info_w.i.${batch_date}.dat
IF_mark:    i_w
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
to_date('${batch_date}','yyyymmdd') as etl_dt
,t.lp_id
,t.cont_id
,t.cust_id
,t.lmt_cont_id
,t.apv_flow_num
,t.manu_cont_id
,t.bus_breed_id
,t.bus_sub_type_cd
,t.loan_happ_type_cd
,t.cont_type_cd
,t.entr_loan_espec_dir_cd
,t.strtg_new_indus_type_cd
,t.prod_type_cd
,t.valid_flg_cd
,t.dir_indus_cd
,t.surp_indus_cd
,t.sub_guar_way_cd
,t.guar_type_cd
,t.major_guar_way_cd
,t.crdt_type_cd
,t.appl_way_cd
,t.loan_fin_supt_way_cd
,t.invest_way_cd
,t.mgmt_mode_cd
,t.loan_level5_cls_cd
,t.loan_level10_cls_cd
,t.tenor_type_cd
,t.pric_repay_way_cd
,t.int_rat_float_way_cd
,t.charge_way_cd
,t.draw_way_cd
,t.cap_src_cd
,t.int_rat_adj_way_cd
,t.curr_cd
,t.sup_chain_fin_bus_prod_cls_cd
,t.sup_chain_fin_bus_flg
,t.agent_patip_loan_flg
,t.lmt_circl_flg
,t.circl_flg
,t.temp_store_flg
,t.froz_flg
,t.turn_crdt_flg
,t.remote_loan_flg
,t.other_guar_way_flg
,t.imp_proj_loan_flg
,t.cty_lmt_indus_flg
,t.gover_crdt_flg
,t.cdb_crdt_flg
,t.fix_asset_crdt_flg
,t.qual_centr_cntpty_flg
,t.low_risk_bus_flg
,t.host_bank_no
,t.patip_loan_bank_no
,t.agent_bank_no
,t.cntpty_strg
,t.cntpty_co_years
,t.cntpty_sucs_tran_cnt
,t.mgmt_org_id
,t.rgst_org_id
,t.oper_org_id
,t.distr_org_id
,t.mgmt_teller_id
,t.oper_teller_id
,t.rgst_teller_id
,t.start_dt
,t.distr_dt
,t.exp_dt
,t.oper_dt
,t.rgst_dt
,t.termnt_dt
,t.lmt_use_latest_dt
,t.lmt_under_bus_latest_exp_dt
,t.loan_usage_descb
,t.repay_src_descb
,t.other_cond_request_descb
,t.trdpty_cust_name1
,t.trdpty_cust_name2
,t.rela_cont_id
,t.stl_acct_num
,t.margin_acct_num
,t.margin_curr_cd
,t.margin_ratio
,t.margin_amt
,t.tran_market_type_cd
,t.incre_crdt_way_cd
,t.batch_data_src_cd
,t.backup_lmt_effect_cd
,t.backup_lmt_cont_id
,t.risk_type_cd
,t.major_loan_cls_cd
,t.risk_expose_cls
,t.underly_prod_cls_flg
,t.underly_prod_cls_lev_cd
,t.tran_asset_name
,t.dir_ind_fund_flg
,t.dir_makti_debt_eqty_flg
,t.invo_gover_class_fin_flg
,t.consm_serv_class_fin_flg
,t.stl_dep_flg
,t.cota_opt_choice_flg
,t.septbl_flg
,t.onl_bus_flg
,t.class_crdt_flg
,t.ibank_bond_id
,t.crdt_bus_flow_type_cd
,t.crdt_rg_cd
,t.estate_fin_flg
,t.estate_loan_type_cd
,t.final_dir_type_cd
,t.pente_type_cd
,t.gover_class_fin_flg1
,t.br_build_ifin_flg
,t.green_crdt_fin_flg
,t.trade_cont_id
,t.trade_cont_curr_cd
,t.trade_cont_amt
,t.bill_qtty
,t.discnt_bf_revw_flg
,t.discnt_int_buyer_bear_ratio
,t.discnt_int_applit_pay_ratio
,t.agt_pay_int_flg
,t.bill_uniq_idf_id
,t.trdpty_acct_id
,t.loan_src_cd
,t.comm_fee_rat
,t.comm_fee_amt
,t.lc_id
,t.lc_amt
,t.syn_loan_distr_amt
,t.tenor
,t.base_rat
,t.int_rat_flo_val
,t.exec_int_rat
,t.bank_fin_tot
,t.open_bal
,t.underly_prod_coll_amt
,t.cont_amt
,t.cont_aval_bal
,t.acm_distr_amt
,t.acm_callbk_amt
,t.occu_crdt_lmt
,t.surp_crdt_lmt
from ${idl_schema}.cmm_corp_loan_cont_info t
where etl_dt = to_date('${batch_date}','yyyymmdd')  ; " \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/cmm_corp_loan_cont_info_w.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes