: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_iol_crss_flow_opinion_i_w
CreateDate: 20180529
FileName:   ${iel_data_path}/crss_flow_opinion_w.i.${batch_date}.dat
IF_mark:    i_w
Logs:
   zjj 2018-07-27 create template
' \
        query="select replace(replace(serialno, chr(10), ''), chr(13), '') as serialno,
       replace(replace(opinionno, chr(10), ''), chr(13), '') as opinionno,
       replace(replace(objecttype, chr(10), ''), chr(13), '') as objecttype,
       replace(replace(objectno, chr(10), ''), chr(13), '') as objectno,
       replace(replace(customerid, chr(10), ''), chr(13), '') as customerid,
       replace(replace(customername, chr(10), ''), chr(13), '') as customername,
       replace(replace(businesscurrency, chr(10), ''), chr(13), '') as businesscurrency,
       replace(replace(businesssum, chr(10), ''), chr(13), '') as businesssum,
       replace(replace(termyear, chr(10), ''), chr(13), '') as termyear,
       replace(replace(termmonth, chr(10), ''), chr(13), '') as termmonth,
       replace(replace(termday, chr(10), ''), chr(13), '') as termday,
       replace(replace(baseratetype, chr(10), ''), chr(13), '') as baseratetype,
       replace(replace(ratefloattype, chr(10), ''), chr(13), '') as ratefloattype,
       replace(replace(ratefloat, chr(10), ''), chr(13), '') as ratefloat,
       replace(replace(bailcurrency, chr(10), ''), chr(13), '') as bailcurrency,
       replace(replace(businessrate, chr(10), ''), chr(13), '') as businessrate,
       replace(replace(bailratio, chr(10), ''), chr(13), '') as bailratio,
       replace(replace(bailsum, chr(10), ''), chr(13), '') as bailsum,
       replace(replace(pdgratio, chr(10), ''), chr(13), '') as pdgratio,
       replace(replace(pdgsum, chr(10), ''), chr(13), '') as pdgsum,
       replace(replace(baserate, chr(10), ''), chr(13), '') as baserate,
       replace(replace(phasechoice, chr(10), ''), chr(13), '') as phasechoice,
       replace(replace(phaseopinion, chr(10), ''), chr(13), '') as phaseopinion,
       replace(replace(phaseopinion1, chr(10), ''), chr(13), '') as phaseopinion1,
       replace(replace(phaseopinion2, chr(10), ''), chr(13), '') as phaseopinion2,
       replace(replace(phaseopinion3, chr(10), ''), chr(13), '') as phaseopinion3,
       replace(replace(inputorg, chr(10), ''), chr(13), '') as inputorg,
       replace(replace(inputuser, chr(10), ''), chr(13), '') as inputuser,
       replace(replace(inputtime, chr(10), ''), chr(13), '') as inputtime,
       replace(replace(updateuser, chr(10), ''), chr(13), '') as updateuser,
       replace(replace(updatetime, chr(10), ''), chr(13), '') as updatetime,
       replace(replace(approveflag, chr(10), ''), chr(13), '') as approveflag,
       replace(replace(approvephaseno, chr(10), ''), chr(13), '') as approvephaseno,
       replace(replace(provisioninfo, chr(10), ''), chr(13), '') as provisioninfo,
       replace(replace(condition3, chr(10), ''), chr(13), '') as condition3,
       replace(replace(conditionflag3, chr(10), ''), chr(13), '') as conditionflag3,
       replace(replace(reasoncode1, chr(10), ''), chr(13), '') as reasoncode1,
       replace(replace(reasoncode2, chr(10), ''), chr(13), '') as reasoncode2,
       replace(replace(holdbalance, chr(10), ''), chr(13), '') as holdbalance,
       replace(replace(adjustratetype, chr(10), ''), chr(13), '') as adjustratetype,
       replace(replace(returnperiod, chr(10), ''), chr(13), '') as returnperiod,
       replace(replace(returntype, chr(10), ''), chr(13), '') as returntype,
       replace(replace(ratemode, chr(10), ''), chr(13), '') as ratemode,
       replace(replace(loanterm, chr(10), ''), chr(13), '') as loanterm,
       replace(replace(mainreturntype, chr(10), ''), chr(13), '') as mainreturntype,
       replace(replace(classifyresulteleven, chr(10), ''), chr(13), '') as classifyresulteleven,
       replace(replace(totalsum, chr(10), ''), chr(13), '') as totalsum,
       replace(replace(maturity, chr(10), ''), chr(13), '') as maturity,
       replace(replace(classifyresult, chr(10), ''), chr(13), '') as classifyresult,
       replace(replace(phaseopinion4, chr(10), ''), chr(13), '') as phaseopinion4,
       replace(replace(ratedescribe, chr(10), ''), chr(13), '') as ratedescribe,
       replace(replace(cycleratio, chr(10), ''), chr(13), '') as cycleratio,
       replace(replace(condition2, chr(10), ''), chr(13), '') as condition2,
       replace(replace(conditionflag2, chr(10), ''), chr(13), '') as conditionflag2,
       replace(replace(condition1, chr(10), ''), chr(13), '') as condition1,
       replace(replace(conditionflag1, chr(10), ''), chr(13), '') as conditionflag1,
       replace(replace(gaincyc, chr(10), ''), chr(13), '') as gaincyc,
       replace(replace(gainamount, chr(10), ''), chr(13), '') as gainamount,
       replace(replace(violationinfo, chr(10), ''), chr(13), '') as violationinfo,
       replace(replace(reasoncode3, chr(10), ''), chr(13), '') as reasoncode3,
       replace(replace(approveuserid, chr(10), ''), chr(13), '') as approveuserid,
       replace(replace(approvedate, chr(10), ''), chr(13), '') as approvedate,
       replace(replace(phaseopinion5, chr(10), ''), chr(13), '') as phaseopinion5,
       replace(replace(attribute1, chr(10), ''), chr(13), '') as attribute1,
       replace(replace(attribute2, chr(10), ''), chr(13), '') as attribute2,
       replace(replace(attribute3, chr(10), ''), chr(13), '') as attribute3,
       replace(replace(remark1, chr(10), ''), chr(13), '') as remark1,
       replace(replace(rateopinion, chr(10), ''), chr(13), '') as rateopinion,
       replace(replace(classify, chr(10), ''), chr(13), '') as classify,
       replace(replace(evaluateadvice, chr(10), ''), chr(13), '') as evaluateadvice,
       replace(replace(groupname, chr(10), ''), chr(13), '') as groupname,
       replace(replace(groupbusinesssum, chr(10), ''), chr(13), '') as groupbusinesssum,
       replace(replace(enttype, chr(10), ''), chr(13), '') as enttype,
       replace(replace(probjecttype, chr(10), ''), chr(13), '') as probjecttype,
       replace(replace(customerbusinesssum, chr(10), ''), chr(13), '') as customerbusinesssum,
       replace(replace(customertotalsum, chr(10), ''), chr(13), '') as customertotalsum,
       replace(replace(relativation, chr(10), ''), chr(13), '') as relativation,
       replace(replace(businesstype, chr(10), ''), chr(13), '') as businesstype,
       replace(replace(attribute, chr(10), ''), chr(13), '') as attribute,
       replace(replace(guarantytype, chr(10), ''), chr(13), '') as guarantytype,
       replace(replace(phaseopinion6, chr(10), ''), chr(13), '') as phaseopinion6,
       replace(replace(phaseopinion7, chr(10), ''), chr(13), '') as phaseopinion7,
       replace(replace(isshowphaseopinion3, chr(10), ''), chr(13), '') as isshowphaseopinion3,
       replace(replace(priattribute, chr(10), ''), chr(13), '') as priattribute,
       replace(replace(customerinlevel, chr(10), ''), chr(13), '') as customerinlevel,
       replace(replace(jxhjbusinesssum, chr(10), ''), chr(13), '') as jxhjbusinesssum,
       replace(replace(jxhjtermmonth, chr(10), ''), chr(13), '') as jxhjtermmonth,
       replace(replace(jxhjbailratio, chr(10), ''), chr(13), '') as jxhjbailratio,
       replace(replace(isneedtjcommittee, chr(10), ''), chr(13), '') as isneedtjcommittee,
       replace(replace(isautoapprove, chr(10), ''), chr(13), '') as isautoapprove,
       replace(replace(onlineamount, chr(10), ''), chr(13), '') as onlineamount,
       replace(replace(businesssumentpart, chr(10), ''), chr(13), '') as businesssumentpart,
       replace(replace(totalsumentpart, chr(10), ''), chr(13), '') as totalsumentpart,
       replace(replace(businesssumtypart, chr(10), ''), chr(13), '') as businesssumtypart,
       replace(replace(totalsumtypart, chr(10), ''), chr(13), '') as totalsumtypart,
       replace(replace(isyeartocheck, chr(10), ''), chr(13), '') as isyeartocheck,
       replace(replace(meettype, chr(10), ''), chr(13), '') as meettype,
       replace(replace(votecount, chr(10), ''), chr(13), '') as votecount,
       replace(replace(phaseopinion8, chr(10), ''), chr(13), '') as phaseopinion8,
       replace(replace(phaseopinion9, chr(10), ''), chr(13), '') as phaseopinion9,
       replace(replace(financepurpose, chr(10), ''), chr(13), '') as financepurpose,
       start_dt,
       end_dt,
       id_mark,
       etl_timestamp
  from iol.crss_flow_opinion
 where start_dt between to_date('${batch_date}', 'yyyymmdd') - 6 and to_date('${batch_date}', 'yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/crss_flow_opinion_w.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes