: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_odss_flw_t_per_reg_f
CreateDate: 20180529
FileName:   ${iel_data_path}/odss_flw_t_per_reg_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
id
,process_inst_id
,main_flow_id
,scan_seq_no
,fr_org_code
,tr_date
,biz_code
,voucher_code
,voucher_no
,cash_cd_flag
,cust_id
,cust_name
,english_name
,sex
,cert_type
,cert_code
,crt_cert_organ
,birthday
,weblock_flag
,education
,occupation
,rank
,income
,company
,home_address
,fix_telephone
,office_phone
,home_phone
,mobile
,contact_address
,postcode
,acct_type
,spec_type
,sf_scp_flag
,curr_type
,cf_flag
,fee_drw_type
,spec_time
,amount
,biz_password
,biz_account
,open_acct_password
,tr_account
,tr_password
,tr_psbk_no
,cust_fst_level
,attor_opr_code
,attor_opr_name
,attor_org_code
,cust_fin_level
,print_count
,level_dn_flag
,ret_reason
,level_a_chrg_code
,level_a_pin
,level_b_chrg_code
,level_b_pin
,fr_tlr_opr_no
,bk_chrg_opr_code
,bk_chrg_opr_propose
,bk_auth_flag
,puc_check_flag
,puc_chk_opr_code
,puc_check_option
,puc_chk_remark
,check_option
,check_remark
,check_opr_code
,puc_chk_date
,cr_check_option
,cr_check_remark
,update_flag
,check_status
,check_fall_reason
,succ_flag
,status
,back_oper_center_id
,draw_reason
,home_addr_type
,company_type
,obtain_opr_code
,educations
,commission
,email
,often_site
,relation
,nationality
,pro_name
,pro_type
,pro_fashion
,app_checking
,pro_checking
,is_porxy
,accept_no
,trane_code
,idtfna_name
,pro_cert_code
,is_net_silver_contract
,open_flag
,group_flag
,netb_passwd
,netb_left_msg
,netb_sign_mobile
,netb_sec_model
,netb_sec_type
,netb_sec_no
,netb_dynamic_opt_no
,netb_dynamic_card_no
,netb_is_transfer
,netb_ac_limit_pertrs
,netb_ac_limit_perday
,cert_date
,id_address
,is_sms_contract
,is_tel_contract
,tel_passwd
,tel_num1
,tel_num2
,tel_num3
,tel_num4
,tel_num5
,tel_num6
,is_tel_n_trnsf
,is_tel_n_trnsf_default_limit
,tel_n_trnsf_single_limit
,tel_n_trnsf_day_limit
,is_tel_d_trnsf
,is_tel_d_trnsf_no_limit
,tel_d_trnsf_single_limit
,tel_d_trnsf_day_limit
,payee_name1
,payee_accno1
,payee_bank_name1
,payee_name2
,payee_accno2
,payee_bank_name2
,sms_notice_limit
,is_tel_any_phone
,is_sms_notice
,is_sms_notice_no_limit
,sec_node_id
,proxy_sex
,proxy_idtdt
,proxy_id_address
,sms_contract_if_succeed
,tel_contract_if_succeed
,net_silver_contract_succeed
,is_netb_default_limit
,prsntg
,staffflag
,custlv
,risklv
,wkutad
,roleid
,worktx
,csec_node_id
,netb_csec_passwd
,transfer_channel
,mobile_ac_limit_pertrs
,mobile_ac_limit_perday
,is_mobile_default_limit
,fax
,area_code
,cust_flag
,truth_flag
,trnamt
,activate_flag
,save_flag
,save_sum
,voucherty
,activate_success_flag
,save_success_flag
,id_check_result
,mobile_open_status
,account_update_flag
,submit_status
,netb_biz_type
,often_site_eq_id_addr
,net_ukey
,card_type
,card_rank
,bankbooktp
,self_help_transfer
,pre_seqno
,pre_status
,pre_remark
,acc_seqno
,pre_mark
,pre_approve_user
,pre_approve_time
,is_finance_contract
,sendfreq
,sendmode
,risklevel
,clientgroup
,chnlflag
,finance_contract_succeed
,finance_acctno
,open_brcno
,cust_mgrno
,sms_cust_sign
,fee_acct_no
,fee_acct_brcno
,fee_acct_nodeno
,contact_phone
,attbrn
,new_password
,new_account
,chactg
,stpytg
,rplsfs
,submit_state
,netopflag
,smsopflag
,finopflag
,delukey
,bgnamt
,allopflag
,trtmrs
,loss_date
,loss_reg_no
,coopcd
,chiptg
,rpcdtg
,undays
,payway
,ltcardno
,ltopentag
,ltacctbrtype
,ltifincome
,ltremark
,is_lt_contract
,lt_contract_if_succeed
from ${idl_schema}.odss_flw_t_per_reg
where etl_dt=to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/odss_flw_t_per_reg_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes