: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_pirs_o_cms_guaranty_info_f
CreateDate: 20180529
FileName:   ${iel_data_path}/pirs_o_cms_guaranty_info_${batch_date}_f.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select guarantyid
,guarantytype
,guarantystatus
,ownerid
,ownername
,ownertype
,rate
,custguarantytype
,subjectno
,relativeaccount
,guarantyrightid
,otherguarantyright
,guarantyname
,guarantysubtype
,guarantyownway
,guarantyusing
,guarantylocation
,guarantyamount
,guarantyamount1
,guarantyamount2
,guarantyresouce
,guarantydate
,begindate
,ownertime
,guarantydescript
,aboutotherid1
,aboutotherid2
,aboutotherid3
,aboutotherid4
,purpose
,aboutsum1
,aboutsum2
,aboutrate
,guarantyana
,guarantyprice
,evalmethod
,evalorgid
,evalorgname
,evaldate
,evalnetvalue
,confirmvalue
,guarantyrate
,thirdparty1
,thirdparty2
,thirdparty3
,guarantydescribe1
,guarantydescribe2
,guarantydescribe3
,flag1
,flag2
,flag3
,flag4
,guarantyregno
,guarantyregorg
,guarantyregdate
,guarantywodate
,insurecertno
,otherassumpsit
,inputorgid
,inputuserid
,inputdate
,updateuserid
,updatedate
,remark
,sapvouchtype
,certtype
,certid
,loancardno
,guarantycurrency
,evalcurrency
,guarantydescribe4
,status
,eguarantyquality
,eguarantyamount
,eguarantyname
,eguarantyright
,eguarantyshare
,eguarantyowner
,eguarantyothersituation
,pledgename
,evaluatenetvalue
,spareyear
,buytime
,buyprice
,unitprice
,guarantynumber
,insurefirmname
,insuredate
,insuresum
,insurecontent
,nowstate
,ifguarantyflag
,rwaguarantytype
,guarantypublishtype
,evaluatemeans
,ifsure
,islowrisk
,drawee
,ownerrelative
,enddate
,custodyability
,impawncustody
,mortgagepledgevalue
,jointowner
,flag5
,commercebackdrop
,querycase
,chamberlain
,putoutorgid
,trandt
,transq
,otherguarrigper
,ischange
,newhnmber
,newhaddress
,zqno
,guarantycompany
,commercialhousingcontract
,chitnd
,carbrand
,cartype
,carnumber
,chariotnumber
,motornumber
,subguarantyrightid from idl.pirs_o_cms_guaranty_info where etl_dt =to_date('${batch_date}','yyyymmdd');" \
        field="|#|" record="0x0a"  \
        file="${iel_data_path}/pirs_o_cms_guaranty_info_${batch_date}_f.dat" \
        charset=zhs16gbk
        safe=yes