: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_pirs_crss_business_duebill_f
CreateDate: 20180529
FileName:   ${iel_data_path}/pirs_crss_business_duebill.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query=" select 
t1.serialno as serialno
,t1.relativeserialno1 as relativeserialno1
,t1.relativeserialno2 as relativeserialno2
,t1.subjectno as subjectno
,t1.mfcustomerid as mfcustomerid
,t1.customerid as customerid
,t1.customername as customername
,t1.businesstype as businesstype
,t1.businesssubtype as businesssubtype
,t1.businessstatus as businessstatus
,t1.businesscurrency as businesscurrency
,t1.businesssum as businesssum
,t1.putoutdate as putoutdate
,t1.maturity as maturity
,t1.actualmaturity as actualmaturity
,t1.businessrate as businessrate
,t1.actualbusinessrate as actualbusinessrate
,t1.ictype as ictype
,t1.iccyc as iccyc
,t1.paytimes as paytimes
,t1.paycyc as paycyc
,t1.corpuspaymethod as corpuspaymethod
,t1.extendtimes as extendtimes
,t1.reorgtimes as reorgtimes
,t1.renewtimes as renewtimes
,t1.golntimes as golntimes
,t1.balance as balance
,t1.normalbalance as normalbalance
,t1.overduebalance as overduebalance
,t1.dullbalance as dullbalance
,t1.badbalance as badbalance
,t1.interestbalance1 as interestbalance1
,t1.interestbalance2 as interestbalance2
,t1.finebalance1 as finebalance1
,t1.finebalance2 as finebalance2
,t1.receivebalance as receivebalance
,t1.payedbalance as payedbalance
,t1.overduedays as overduedays
,t1.payaccount as payaccount
,t1.putoutaccount as putoutaccount
,t1.paybackaccount as paybackaccount
,t1.payinterestaccount as payinterestaccount
,t1.oweinterestdays as oweinterestdays
,t1.tabalance as tabalance
,t1.tainterestbalance as tainterestbalance
,t1.tatimes as tatimes
,t1.lcatimes as lcatimes
,t1.saledate as saledate
,t1.finishtype as finishtype
,t1.finishdate as finishdate
,t1.mfareaid as mfareaid
,t1.mforgid as mforgid
,t1.mfuserid as mfuserid
,t1.operateorgid as operateorgid
,t1.operateuserid as operateuserid
,t1.inputorgid as inputorgid
,t1.inputuserid as inputuserid
,t1.inputdate as inputdate
,t1.updatedate as updatedate
,t1.inoutflag as inoutflag
,t1.dealflag as dealflag
,t1.occurdate as occurdate
,t1.businessprop as businessprop
,t1.benefitcorp as benefitcorp
,t1.actualtermmonth as actualtermmonth
,t1.actualtermday as actualtermday
,t1.baseratetype as baseratetype
,t1.baserate as baserate
,t1.ratefloattype as ratefloattype
,t1.ratefloat as ratefloat
,t1.timsflag as timsflag
,t1.bailratio as bailratio
,t1.logoutdate as logoutdate
,t1.cancellogoutdate as cancellogoutdate
,t1.bailsum as bailsum
,t1.bailaccount as bailaccount
,t1.purpose as purpose
,t1.advanceflag as advanceflag
,t1.relativeduebillno as relativeduebillno
,t1.actualartificialno as actualartificialno
,t1.accountno as accountno
,t1.loanaccountno as loanaccountno
,t1.secondpayaccount as secondpayaccount
,t1.adjustratetype as adjustratetype
,t1.adjustrateterm as adjustrateterm
,t1.overinttype as overinttype
,t1.rateadjustcyc as rateadjustcyc
,t1.pdgaccountno as pdgaccountno
,t1.deductdate as deductdate
,t1.fzanbalance as fzanbalance
,t1.acceptinttype as acceptinttype
,t1.ratio as ratio
,t1.thirdpartyadd1 as thirdpartyadd1
,t1.thirdpartyzip1 as thirdpartyzip1
,t1.thirdpartyadd2 as thirdpartyadd2
,t1.thirdpartyzip2 as thirdpartyzip2
,t1.termdate1 as termdate1
,t1.termdate2 as termdate2
,t1.termdate3 as termdate3
,t1.describe2 as describe2
,t1.fixcyc as fixcyc
,t1.thirdparty1 as thirdparty1
,t1.thirdpartyid1 as thirdpartyid1
,t1.thirdparty2 as thirdparty2
,t1.thirdparty3 as thirdparty3
,t1.type1 as type1
,t1.type2 as type2
,t1.type3 as type3
,t1.billno as billno
,t1.flag1 as flag1
,t1.flag2 as flag2
,t1.flag3 as flag3
,t1.thirdpartyregion as thirdpartyregion
,t1.thirdpartyaccounts as thirdpartyaccounts
,t1.cargoinfo as cargoinfo
,t1.securitiestype as securitiestype
,t1.securitiesregion as securitiesregion
,t1.aboutbankid2 as aboutbankid2
,t1.aboutbankname2 as aboutbankname2
,t1.aboutbankid3 as aboutbankid3
,t1.aboutbankname as aboutbankname
,t1.aboutbankid as aboutbankid
,t1.oldlctermtype as oldlctermtype
,t1.negotiateno as negotiateno
,t1.creditkind as creditkind
,t1.gatheringname as gatheringname
,t1.preinttype as preinttype
,t1.resumeinttype as resumeinttype
,t1.guarantyno as guarantyno
,t1.pztype as pztype
,t1.graceperiod as graceperiod
,t1.oldlcvaliddate as oldlcvaliddate
,t1.mfeepaymethod as mfeepaymethod
,t1.describe1 as describe1
,t1.tradecontractno as tradecontractno
,t1.loantype as loantype
,t1.fixterm as fixterm
,t1.cancelsum as cancelsum
,t1.cancelinterest as cancelinterest
,t1.bailacount as bailacount
,t1.classify4 as classify4
,t1.classifyresult as classifyresult
,t1.returntype as returntype
,t1.bailpercent as bailpercent
,t1.paymenttype as paymenttype
,t1.termsfreq as termsfreq
,t1.overduedate as overduedate
,t1.oweinterestdate as oweinterestdate
,t1.lcstatus as lcstatus
,t1.ichangedate as ichangedate
,t1.vouchtype as vouchtype
,t1.actualbusinessratefix as actualbusinessratefix
,t1.lastclassifyresult as lastclassifyresult
,t1.classifyresulteleven as classifyresulteleven
,t1.guaranteeno as guaranteeno
,t1.surplusphases as surplusphases
,t1.eacmprincipal as eacmprincipal
,t1.overduerate as overduerate
,t1.mainorgid as mainorgid
,t1.loanspecies as loanspecies
,t1.advanceflagsum as advanceflagsum
,t1.advanceflagno as advanceflagno
,t1.compensationsum as compensationsum
,t1.logouttype as logouttype
,t1.logoutno as logoutno
,t1.openno as openno
,t1.opendate as opendate
,t1.premiumrate as premiumrate
,t1.benefitcorpbank as benefitcorpbank
,t1.benefitcorpname as benefitcorpname
,t1.overdueinterest as overdueinterest
,t1.fixflag as fixflag
,t1.intdate as intdate
,t1.accountbalance as accountbalance
,t1.accountuserbalance as accountuserbalance
,t1.termtype as termtype
,t1.termmonthtype as termmonthtype
,t1.insum as insum
,t1.interestinsum as interestinsum
,t1.classifydate as classifydate
,t1.nextperiodreturnprincipaldate as nextperiodreturnprincipaldate
,t1.nextperiodreturnprincipalsum as nextperiodreturnprincipalsum
,t1.nextperiodreturninterestdate as nextperiodreturninterestdate
,t1.nextperiodreturninterestsum as nextperiodreturninterestsum
,t1.duebalance as duebalance
,t1.balancechangedate as balancechangedate
,t1.oldictype as oldictype
,t1.isinuse as isinuse
,t1.dzhxstatus as dzhxstatus
,t1.hxtype as hxtype
,t1.hxinrate as hxinrate
,t1.hxoutrate as hxoutrate
,t1.legal as legal
,t1.reinforcechecker as reinforcechecker
,t1.batchno as batchno
,t1.tcustomerid as tcustomerid
,t1.tcustomername as tcustomername
,t1.transdate as transdate
,t1.billtype as billtype
,t1.billkind as billkind
,t1.datatype as datatype
,t1.acceptbankid as acceptbankid
,t1.acceptbankname as acceptbankname
,t1.keyno as keyno
,t1.istran as istran
,'' as data_date
from ${idl_schema}.crss_business_duebill t1
where start_dt <= to_date('${batch_date}','yyyymmdd') and end_dt > to_date('${batch_date}','yyyymmdd') and t1.etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/pirs_crss_business_duebill.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes