: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_iol_ibms_ttrd_cashlb_f_w
CreateDate: 20180529
FileName:   ${iel_data_path}/ibms_ttrd_cashlb_w.f.${batch_date}.dat
IF_mark:    f_w
Logs:
   zjj 2018-07-27 create template
' \
        query="select i_code,a_type,m_type,currency,country,q_type,replace(replace(i_name,chr(10),''),chr(13),'') as i_name,replace(replace(p_class,chr(10),''),chr(13),'') as p_class,par_value,coupon,start_date,mtr_date,term,daycount,i_code_bench,a_type_bench,m_type_bench,issue_mode,coupon_type,payment_freq,payment_conv,first_regular_start_date,fixing_date_offset,fixing_date_conv,reset_freq,reset_conv,initial_rate,cap_rate,replace(replace(issuer,chr(10),''),chr(13),'') as issuer,replace(replace(memo,chr(10),''),chr(13),'') as memo,replace(replace(fpml,chr(10),''),chr(13),'') as fpml,imp_time,chinesespell,is_delete,floor_rate,replace(replace(update_user,chr(10),''),chr(13),'') as update_user,update_time,account_user,account_time,initial_fixing_date,first_payment_date,party_id,rate_multi,overdue_rate,volume,mtr_mode,ver_id,beg_date,end_date,fstsettype,endsettype,fst_set_amount,mtr_set_amount,p_type,issue_price,replace(replace(settled_interest,chr(10),''),chr(13),'') as settled_interest,issuer_id,usable_flag,payment_date_offset,replace(replace(sell_department,chr(10),''),chr(13),'') as sell_department,repo_trade_variety,acct_id,auto_redepo,repo_term,stub_period_type,m_i_code,m_a_type,m_m_type,head_coupon,payment,credit_promotion_way,i_id,cash_date,ishisdata,s_type,host_market,autoredepo,scale,final_stub,u_m_type,u_a_type,u_i_code,is_occupy_bottom_credit,credit_id,interest_type,term_spd,p_start_date,p_mtr_date,calcconv,cashing_date,cashing_speed,replace(replace(match_code,chr(10),''),chr(13),'') as match_code,replace(replace(p_i_code,chr(10),''),chr(13),'') as p_i_code,special_type,weighted_coupon,und_asset_type,inv_order_id,guarantee_way,replace(replace(guarantee_infor,chr(10),''),chr(13),'') as guarantee_infor,actual_mtr_date,pre_actual_mtr_date,total_ai,p_status,draw_advance_rate,post_interest_rate,is_open_letter,grace_day,credit_amount,extordid,is_auto_calculate,nominal_rate,added_rate,slotting_addrate,slotting_rate,slotting_daycounter,trustee_rate,trustee_daycounter,other_rate,other_daycounter,nominal_daycounter,credit_weight,replace(replace(reply_code,chr(10),''),chr(13),'') as reply_code,record_rate,accounting_type,replace(replace(product_rate,chr(10),''),chr(13),'') as product_rate,replace(replace(rate_institution,chr(10),''),chr(13),'') as rate_institution,start_dt,end_dt,id_mark,etl_timestamp from iol.ibms_ttrd_cashlb where start_dt between to_date('${batch_date}', 'yyyymmdd') - 6 and to_date('${batch_date}', 'yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/ibms_ttrd_cashlb_w.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes