: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_iol_crss_guaranty_info_i_w
CreateDate: 20180529
FileName:   ${iel_data_path}/crss_guaranty_info_w.i.${batch_date}.dat
IF_mark:    i_w
Logs:
   zjj 2018-07-27 create template
' \
        query="select guarantyid,guarantytype,guarantystatus,ownerid,replace(replace(ownername,chr(10),''),chr(13),'') as ownername,ownertype,rate,custguarantytype,subjectno,relativeaccount,replace(replace(guarantyrightid,chr(10),''),chr(13),'') as guarantyrightid,replace(replace(otherguarantyright,chr(10),''),chr(13),'') as otherguarantyright,replace(replace(guarantyname,chr(10),''),chr(13),'') as guarantyname,guarantysubtype,guarantyownway,guarantyusing,replace(replace(guarantylocation,chr(10),''),chr(13),'') as guarantylocation,guarantyamount,guarantyamount1,guarantyamount2,guarantyresouce,guarantydate,begindate,ownertime,replace(replace(guarantydescript,chr(10),''),chr(13),'') as guarantydescript,aboutotherid1,aboutotherid2,aboutotherid3,aboutotherid4,purpose,aboutsum1,aboutsum2,aboutrate,guarantyana,guarantyprice,evalmethod,evalorgid,replace(replace(evalorgname,chr(10),''),chr(13),'') as evalorgname,evaldate,evalnetvalue,confirmvalue,guarantyrate,thirdparty1,thirdparty2,thirdparty3,replace(replace(guarantydescribe1,chr(10),''),chr(13),'') as guarantydescribe1,replace(replace(guarantydescribe2,chr(10),''),chr(13),'') as guarantydescribe2,replace(replace(guarantydescribe3,chr(10),''),chr(13),'') as guarantydescribe3,flag1,flag2,flag3,flag4,guarantyregno,guarantyregorg,guarantyregdate,guarantywodate,insurecertno,otherassumpsit,inputorgid,inputuserid,inputdate,updateuserid,updatedate,replace(replace(remark,chr(10),''),chr(13),'') as remark,sapvouchtype,certtype,certid,loancardno,guarantycurrency,evalcurrency,guarantydescribe4,status,eguarantyquality,eguarantyamount,eguarantyname,eguarantyright,eguarantyshare,eguarantyowner,eguarantyothersituation,replace(replace(pledgename,chr(10),''),chr(13),'') as pledgename,evaluatenetvalue,spareyear,buytime,buyprice,unitprice,guarantynumber,insurefirmname,insuredate,insuresum,insurecontent,nowstate,ifguarantyflag,rwaguarantytype,guarantypublishtype,evaluatemeans,ifsure,islowrisk,drawee,ownerrelative,enddate,custodyability,impawncustody,mortgagepledgevalue,jointowner,flag5,commercebackdrop,querycase,chamberlain,putoutorgid,trandt,transq,otherguarrigper,ischange,newhnmber,newhaddress,zqno,replace(replace(guarantycompany,chr(10),''),chr(13),'') as guarantycompany,commercialhousingcontract,chitnd,carbrand,cartype,carnumber,chariotnumber,motornumber,subguarantyrightid,recordlogno,updateflag,inputoffice,tempsaveflag,grteac,account,fpflag,fpserialno,swtbizid,isinuse,hbname1,hbname2,qzname,bwstartdate,djendtime,hbdate,qzendtime,ifbwhs,approveno,ypguarantytype,ypguarantyid,start_dt,end_dt,id_mark,etl_timestamp from iol.crss_guaranty_info where start_dt between to_date('${batch_date}', 'yyyymmdd') - 6 and to_date('${batch_date}', 'yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/crss_guaranty_info_w.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes