: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_icms_bc_extend_d_f
CreateDate: 20221208
FileName:   ${iel_data_path}/icms_bc_extend_d.f.${batch_date}.dat
IF_mark:    f
Logs:
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,t1.serialno as serialno
,t1.tradesum as tradesum
,t1.isrz as isrz
,t1.creditattribute as creditattribute
,t1.tradecontractno as tradecontractno
,t1.lctype as lctype
,t1.lcsum as lcsum
,t1.lccurrency as lccurrency
,t1.lcno as lcno
,t1.thirdpartyaccounts as thirdpartyaccounts
,t1.pwwh as pwwh
,t1.lxpw as lxpw
,t1.lcopertype as lcopertype
,t1.lccdflag as lccdflag
,t1.lctermtype as lctermtype
,t1.lcquality as lcquality
,t1.destination1 as destination1
,t1.oldlcloadingdate as oldlcloadingdate
,t1.graceperiod as graceperiod
,t1.costpersontype as costpersontype
,t1.mfeeratio as mfeeratio
,t1.rateexplain as rateexplain
,t1.cargoinfo as cargoinfo
,t1.totalcast as totalcast
,t1.destination2 as destination2
,t1.oldlcno as oldlcno
,t1.oldlccurrency as oldlccurrency
,t1.oldlcsum as oldlcsum
,t1.discountsum as discountsum
,t1.zfsxlx as zfsxlx
,t1.contextinfo as contextinfo
,t1.ifgudingcredit as ifgudingcredit
,t1.moneytype as moneytype
,t1.restbalancesum as restbalancesum
,t1.guarantytype as guarantytype
,t1.othercondition as othercondition
,t1.mandatesource as mandatesource
,t1.isyfconfirmed as isyfconfirmed
,t1.purchaserpayintratio as purchaserpayintratio
,t1.ifqueryflag as ifqueryflag
,t1.iscounterparty as iscounterparty
,t1.bailaccount as bailaccount
,t1.bailcurrency as bailcurrency
,t1.bailtransaccount as bailtransaccount
,t1.guarantybailaccount as guarantybailaccount
,t1.interestrate as interestrate
,t1.fxfltp as fxfltp
,t1.pdrifv as pdrifv
,t1.pdrifd as pdrifd
,t1.pdrifm as pdrifm
,t1.interestmethod as interestmethod
,t1.termcd as termcd
,t1.mandatecustname as mandatecustname
,t1.repayremark as repayremark
,t1.ventureguarantytype as ventureguarantytype
,t1.isconsumerfinance as isconsumerfinance
,t1.lcpaymethod as lcpaymethod
,t1.drawingremark as drawingremark
,t1.loantraderatio as loantraderatio
,t1.mainproduct as mainproduct
,t1.billnum as billnum
,t1.discountdrafttype as discountdrafttype
,t1.businessinvoiceinfo as businessinvoiceinfo
,t1.businessinvoicetype as businessinvoicetype
,t1.businessinvoicecurrency as businessinvoicecurrency
,t1.businessinvoicesum as businessinvoicesum
,t1.qtxkzbh as qtxkzbh
,t1.qtxkz as qtxkz
,t1.hpxkzbh as hpxkzbh
,t1.jsydxkzbh as jsydxkzbh
,t1.ghxkzbh as ghxkzbh
,t1.sgxkzbh as sgxkzbh
,t1.corpuspaymethod as corpuspaymethod
,t1.toindustryfund as toindustryfund
,t1.consignmentloandirect as consignmentloandirect
,t1.isventureguaranty as isventureguaranty
,t1.securitiestype as securitiestype
,t1.mandatedepacctno as mandatedepacctno
,t1.bondno as bondno
,t1.productcollectmoney as productcollectmoney
,t1.productlevel as productlevel
,t1.gshy as gshy
,t1.purchaserregion as purchaserregion
,t1.isfarming as isfarming
,t1.rivalname as rivalname
,t1.farmingloandirect as farmingloandirect
,t1.businessprop as businessprop
,t1.registerinotherbank as registerinotherbank
,t1.zbj as zbj
,t1.consigneename as consigneename
,t1.consigneecerttype as consigneecerttype
,t1.consigneecertid as consigneecertid
,t1.useproduct as useproduct
,t1.beneficiarycountryname as beneficiarycountryname
,t1.purchasername as purchasername
,t1.farmingsubjecttype as farmingsubjecttype
,t1.lcapplyserialno as lcapplyserialno
,t1.mandatecustid as mandatecustid
,t1.isimportantloan as isimportantloan
,t1.discountratenote as discountratenote
,t1.factoringtype as factoringtype
,t1.ifagreementflag as ifagreementflag
,t1.kgrq as kgrq
,t1.sfgksx as sfgksx
,t1.offerbilldate as offerbilldate
,t1.financier as financier
,t1.discountcusttype as discountcusttype
,t1.isgovernfinance as isgovernfinance
,t1.financesupportmode as financesupportmode
,t1.issjorcs as issjorcs
,t1.yffdkje as yffdkje
,t1.fundsource as fundsource
,t1.zfsxfs as zfsxfs
,t1.directionrs as directionrs
,t1.classifyfrequency as classifyfrequency
,t1.supplychainfinancetype as supplychainfinancetype
,t1.projectartificialno as projectartificialno
,t1.hasoutradio as hasoutradio
,t1.beneficiaryname as beneficiaryname
,t1.tradecurrency as tradecurrency
,t1.isyfreceive as isyfreceive
,t1.acceptbankname as acceptbankname
,t1.tdyears as tdyears
,t1.putoutorgid as putoutorgid
,t1.gksxpz as gksxpz
,t1.loantradesum as loantradesum
,t1.sfzfsx as sfzfsx
,t1.isdebttoequity as isdebttoequity
,t1.creditincrementtype as creditincrementtype
,t1.outradio as outradio
,t1.loanquality as loanquality
,t1.issupplychainfinance as issupplychainfinance
,t1.noticebankname as noticebankname
,t1.tdtimes as tdtimes
,t1.paymentname as paymentname
,t1.tradingassets as tradingassets
,t1.loanhandlechannel as loanhandlechannel
,t1.thirdparty1type as thirdparty1type
,t1.otherarealoan as otherarealoan
,t1.realestateloantype as realestateloantype
,t1.proposerpaymentscale as proposerpaymentscale
,t1.xmztz as xmztz
,t1.sfgjxzhy as sfgjxzhy
,t1.tdstrenth as tdstrenth
,t1.locfinancefundsource as locfinancefundsource
,t1.importantloan as importantloan
,t1.duepaymethod as duepaymethod
,t1.drawingtype as drawingtype
,t1.start_dt as start_dt
,t1.end_dt as end_dt
,t1.id_mark as id_mark
,t1.careerguaranteeloantype as careerguaranteeloantype
,t1.farmingloanuse as farmingloanuse
,t1.iscareerguaranteeloan as iscareerguaranteeloan
,t1.platformpaycashsource as platformpaycashsource
,t1.farmingloantype as farmingloantype
,t1.isforeign as isforeign
,t1.migtflag as migtflag
,t1.guaranteehprojecttype as guaranteehprojecttype
,t1.landuseno as landuseno
,t1.landusedate as landusedate
,t1.landplanpermitno as landplanpermitno
,t1.landplanpermitdate as landplanpermitdate
,t1.constructpermitdate as constructpermitdate
,t1.projectplanpermitdate as projectplanpermitdate
,t1.buyername as buyername
,t1.sellername as sellername
,t1.tradetransactioncontent as tradetransactioncontent

from ${idl_schema}.icms_bc_extend_d t1
where etl_dt = to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/icms_bc_extend_d.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes
