: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_rcrs_cus_indiv_i
CreateDate: 20180529
FileName:   ${iel_data_path}/rcrs_cus_indiv.i.${batch_date}.dat
IF_mark:    i
Logs:
   zjj 2018-07-27 create template
' \
        query="select  
t.etl_dt
,t.inner_cus_id
,t.cus_id
,t.mng_br_id
,t.cus_type
,t.cus_name
,t.indiv_sex
,t.cert_type
,t.cert_code
,t.indiv_id_exp_dt
,t.agri_flg
,t.cus_bank_rel
,t.com_hold_stk_amt
,t.bank_duty
,t.indiv_ntn
,t.indiv_brt_place
,t.indiv_houh_reg_add
,t.indiv_dt_of_birth
,t.indiv_pol_st
,t.indiv_edt
,t.indiv_dgr
,t.indiv_mar_st
,t.indiv_heal_st
,t.post_addr
,t.post_code
,t.area_code
,t.area_name
,t.phone
,t.fphone
,t.mobile
,t.fax_code
,t.email
,t.indiv_rsd_addr
,t.indiv_zip_code
,t.indiv_rsd_st
,t.indiv_soc_scr
,t.indiv_hobby
,t.indiv_occ
,t.indiv_com_name
,t.indiv_com_typ
,t.indiv_com_fld
,t.indiv_com_phn
,t.indiv_com_fax
,t.indiv_com_addr
,t.indiv_com_zip_code
,t.indiv_com_cnt_name
,t.indiv_work_job_y
,t.indiv_com_job_ttl
,t.indiv_crtfctn
,t.indiv_ann_incm
,t.indiv_sal_acc_bank
,t.indiv_sal_acc_no
,t.indiv_sps_name
,t.indiv_sps_id_typ
,t.indiv_sps_id_code
,t.indiv_scom_name
,t.indiv_sps_occ
,t.indiv_sps_duty
,t.indiv_sps_mincm
,t.indiv_sps_phn
,t.indiv_sps_mphn
,t.indiv_sps_job_dt
,t.com_rel_dgr
,t.com_init_loan_date
,t.indiv_hld_acnt
,t.hold_card
,t.passport_flg
,t.crd_grade
,t.crd_date
,t.remark
,t.cust_mgr
,t.main_br_id
,t.input_id
,t.input_br_id
,t.input_date
,t.last_upd_id
,t.last_upd_date
,t.cus_status
,t.indiv_com_fld_name
,t.crd_end_dt
,t.indiv_psp_crtfctn
,t.indiv_sps_mar_code
,t.cus_id_rel
,t.work_resume
,t.accredit_status
,t.former_name
,t.lay_off_flag
,t.lay_off_code
,t.loan_card_flg
,t.loan_card_id
,t.loan_card_pwd
,t.loan_card_eff_flg
,t.loan_card_audit_dt
,t.businesses_flag
,t.vocation_type
,t.family_population
,t.family_labor_population
,t.reg_state_code
,t.card_org_name
,t.sps_remark
,t.if_micro_business_owner
,t.if_industrial_areas
,t.issue_info
,t.card_id
,t.indiv_month_income
,t.yes_no_contract
,t.yes_no_vip_cus
,t.yes_no_annexamine
,t.indiv_province
,t.indiv_city
,t.core_cus_id
,t.whetherbankblacklist
,t.indiv_id_st_dt
,t.nationality
,t.houh_reg_property
,t.local_reg_time
,t.has_children
,t.children_situation
,t.family_month_income
,t.has_car
,t.car_cost
,t.has_other_code
,t.other_code
,t.working_condition
,t.work_unit_size
,t.working_life
,t.working_stablity
,t.urgency_name
,t.relation
,t.urgency_tel
,t.urgency_address
,t.urgency_zip_code
,t.cosurety_cont_no
,t.other_code_type
,t.authentica_type
,t.house_cost
,t.identity_card
,t.is_rcrs_cus
,t.indiv_soc_years
,t.relative_name1
,t.relative_type1
,t.relative_phone1
,t.relative_name2
,t.relative_type2
,t.relative_phone2
,t.relative_name3
,t.relative_type3
,t.relative_phone3
,t.relative_name4
,t.relative_type4
,t.relative_phone4
,t.relative_fphone1
,t.relative_fphone2
,t.relative_fphone3
,t.relative_fphone4
,t.email2
,t.qq
,t.wechat
,t.tenpay
,t.sinablog
,t.taobao_account
,t.alipay
,t.jingdong_account
,t.is_cl
,t.indiv_com_no
,t.indiv_addr_no
,t.is_relative
,t.rel_no
,t.work_no
,t.addr_no
,t.family_addr_no
,t.businesses_flag_1
,t.is_limit_apply
,t.pass_type
,t.pass_code
,t.register_type
,t.start_dt
,t.end_dt
,t.id_mark
from idl.rcrs_cus_indiv t
where start_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/rcrs_cus_indiv.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes