: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_pirs_crss_business_putout_f
CreateDate: 20180529
FileName:   ${iel_data_path}/pirs_crss_business_putout.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select 
serialno
,customerid
,customername
,businesstype
,businesscurrency
,businesssum
,termyear
,termmonth
,termday
,putoutdate
,maturity
,businessrate
,ictype
,iccyc
,paycyc
,corpuspaymethod
,subjectno
,dealbegintime
,dealendtime
,dealflag
,operateorgid
,operateuserid
,operatedate
,inputorgid
,inputuserid
,inputdate
,updatedate
,pigeonholedate
,remark
,occurdate
,baseratetype
,baserate
,ratefloattype
,ratefloat
,contractserialno
,duebillserialno
,artificialno
,relativeaccountno
,accountno
,loanaccountno
,loantype
,creditlineflag
,creditaggreement
,contractsum
,purpose
,adjustratetype
,fixcyc
,backrate
,acceptinttype
,preinttype
,resumeinttype
,secondpayaccount
,overinttype
,rateadjustcyc
,guarantyno
,riskrate
,consignaccountno
,mostlyduebillno
,negotiateno
,creditkind
,pdgsum
,pdgaccountno
,pdgpaymethod
,businesssubtype
,businesssubtype1
,exchangetype
,exchangestate
,exchangeserialno
,adjustrateterm
,projectno
,fzaccountno
,fzanbalance
,ccode
,cdate
,fzguabalance
,pztype
,billno
,gatheringname
,aboutbankname
,interserialno
,billresource
,bailaccount
,aboutbankid
,billsum
,ratetype
,billrisk
,openbankname
,openbankadd
,openbankzip
,type1
,type2
,type3
,type4
,type5
,type6
,type7
,aboutbankid2
,aboutbankname2
,aboutbankid3
,name1
,address1
,name2
,address2
,zip2
,address3
,term1
,term2
,term3
,vouchtype
,bailcurrency
,bailratio
,mfeepaymethod
,securitiestype
,type8
,type9
,thirdpartyaccounts
,thirdpartyid1
,ccyc
,loanterm
,relativeputoutno
,printtimes
,tempsaveflag
,paymentmode
,greenchannelflag
,lowrisk
,iswritecont
,putoutorgid
,principalaccountno
,clientaccountno
,lendingorgid
,capitalreturnflag
,interestreturnflag
,rategenre
,installmentsmenthod
,overduefloat
,overduerate
,period
,commitmentflag
,commitmenttype
,principalsubaccountno
,paymenttype
,compoundintflag
,termtype
,pdgpaypercent
,corpuspaydate
,purposetype
,repaymentplanflag
,stopintflag
,commissionpaysum
,loancommitmentno
,approveorgid
,approveuserid
,approvedate
,corpuspaymenthod
,receiversubaccountno
,receiveraccountno
,dischargesflag
,dischargesaccountno
,dischargespercent
,dischargesdate
,exchangetime
,bailsubaccount
,bailsum
,assureorgid
,direction
,bailterm
,bailexchangestate
,repayexchangestate
,queryabnormitything
,abnormitything
,loantermthing
,fbsnumber
,invoicenumber
,sfgksx
,gksxpz
,sfzfsx
,zfsxlx
,sfgjxzhy
,gshy
,dktx
,commercetype
,paymode
,zfsxfs
,paymodedesc
,isfinanceguarantee
,accountnoorgname
,accountnocustomer
,loanaccountnocustomer
,loanaccountnoorgname
,operationtype
,paysum
,manualpay
,keyno
,billclass
,billtype
,careflag
,repurchaseflag
,discountsum
,billbusinesstype
,putoutno
,batchno
,addcertificateflag
,waitecertificateflag
,otherdraweracctno
,othertxbalance
,czflag
,lcsum
,carbrand
,cartype
,carnumber
,chariotnumber
,motornumber
,acptdate
,interestmethod
,interestrate
,bailmaturity
,receivername
,isfromebank
,orginalduebill
,loankind
,tradeserialno1
,tradeserialno2
,tradecurrecy1
,tradecurrecy2
,tradecurrecy3
,tradesum1
,tradesum2
,tradesum3
,tradedate1
,tradedate2
,tradetermmonth1
,tradetermmonth2
,tradetermmonth3
,traderate1
,traderate2
,tradetype1
,bfintg
,paybankname
,isinuse
,bailtransaccount
,daynum
,lncmam
,ovdrmi
,loanam
,accountno1
,oblopt
,bengdt
,lontyp
,odrputoutdate
,odrmaturity
,whitelist
,putoutcontrol
,txregister
,loantermcontrolflag
,acceptor
,acceptorbankno
,acceptorbankname
,fxfltp
,pdrifd
,pdrifm
,pdrifv
,jxhjduebillno
,odrnextmonth
,odrfreeinterest
,amorfg
,trantp
,amorsq
,exchangedate
,exchangeno
,isrz
,financier
,hxtycapitalsource
,adjustratedate
,countbasis
,bigcreditbankid
,principalaccountname
,principalbankname
,accountindir
,ret_msg
,clearingtype
,ishxbank
,hxtypurpose
,'' data_date
from ${idl_schema}.crss_business_putout t1
where start_dt <= to_date('${batch_date}','yyyymmdd') and end_dt > to_date('${batch_date}','yyyymmdd') and t1.etl_dt = to_date('${batch_date}','yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/pirs_crss_business_putout.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes