: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_iol_crss_business_duebill_i_w
CreateDate: 20180529
FileName:   ${iel_data_path}/crss_business_duebill_w.i.${batch_date}.dat
IF_mark:    i_w
Logs:
   zjj 2018-07-27 create template
' \
        query="select serialno,relativeserialno1,relativeserialno2,subjectno,mfcustomerid,customerid,replace(replace(customername,chr(10),''),chr(13),'') as customername,businesstype,businesssubtype,businessstatus,businesscurrency,businesssum,putoutdate,maturity,actualmaturity,businessrate,actualbusinessrate,ictype,iccyc,paytimes,paycyc,corpuspaymethod,extendtimes,reorgtimes,renewtimes,golntimes,balance,normalbalance,overduebalance,dullbalance,badbalance,interestbalance1,interestbalance2,finebalance1,finebalance2,receivebalance,payedbalance,overduedays,payaccount,putoutaccount,paybackaccount,payinterestaccount,oweinterestdays,tabalance,tainterestbalance,tatimes,lcatimes,saledate,finishtype,finishdate,mfareaid,mforgid,mfuserid,operateorgid,operateuserid,inputorgid,inputuserid,inputdate,updatedate,inoutflag,dealflag,occurdate,businessprop,benefitcorp,actualtermmonth,actualtermday,baseratetype,baserate,ratefloattype,ratefloat,timsflag,bailratio,logoutdate,cancellogoutdate,bailsum,bailaccount,purpose,advanceflag,relativeduebillno,actualartificialno,accountno,loanaccountno,secondpayaccount,adjustratetype,adjustrateterm,overinttype,rateadjustcyc,pdgaccountno,deductdate,fzanbalance,acceptinttype,ratio,thirdpartyadd1,thirdpartyzip1,thirdpartyadd2,thirdpartyzip2,termdate1,termdate2,termdate3,describe2,fixcyc,thirdparty1,thirdpartyid1,thirdparty2,thirdparty3,type1,type2,type3,billno,flag1,flag2,flag3,thirdpartyregion,thirdpartyaccounts,cargoinfo,securitiestype,securitiesregion,aboutbankid2,aboutbankname2,aboutbankid3,aboutbankname,aboutbankid,oldlctermtype,negotiateno,creditkind,gatheringname,preinttype,resumeinttype,guarantyno,pztype,graceperiod,oldlcvaliddate,mfeepaymethod,describe1,tradecontractno,loantype,fixterm,cancelsum,cancelinterest,bailacount,classify4,classifyresult,returntype,bailpercent,paymenttype,termsfreq,overduedate,oweinterestdate,lcstatus,ichangedate,vouchtype,actualbusinessratefix,lastclassifyresult,classifyresulteleven,guaranteeno,surplusphases,eacmprincipal,overduerate,mainorgid,loanspecies,advanceflagsum,advanceflagno,compensationsum,logouttype,logoutno,openno,opendate,premiumrate,benefitcorpbank,benefitcorpname,overdueinterest,fixflag,intdate,accountbalance,accountuserbalance,termtype,termmonthtype,insum,interestinsum,classifydate,nextperiodreturnprincipaldate,nextperiodreturnprincipalsum,nextperiodreturninterestdate,nextperiodreturninterestsum,duebalance,balancechangedate,oldictype,isinuse,dzhxstatus,hxtype,hxinrate,hxoutrate,legal,reinforcechecker,batchno,tcustomerid,tcustomername,transdate,billtype,billkind,datatype,acceptbankid,acceptbankname,keyno,istran,start_dt,end_dt,id_mark,etl_timestamp from iol.crss_business_duebill where start_dt between to_date('${batch_date}', 'yyyymmdd') - 6 and to_date('${batch_date}', 'yyyymmdd');" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/crss_business_duebill_w.i.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes