: '
Purpose:    unload config for sqluldr2
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py yyyymmdd iel_idl_crss_ent_info_f
CreateDate: 20180529
FileName:   ${iel_data_path}/crss_ent_info.f.${batch_date}.dat
IF_mark:    f
Logs:
   zjj 2018-07-27 create template
' \
        query="select
to_date('${batch_date}','yyyymmdd') as etl_dt
,customerid
,corpid
,enterprisename
,englishname
,fictitiousperson
,orgnature
,financetype
,enterprisebelong
,industrytype
,industrytype1
,industrytype2
,private
,economytype
,orgtype
,mostbusiness
,budgettype
,rccurrency
,registercapital
,pccurrency
,paiclupcapital
,fundsource
,totalassets
,netassets
,annualincome
,scope
,limit
,creditdate
,licenseno
,licensedate
,licensematurity
,setupdate
,inspectionyear
,locksituation
,taxno
,banklicense
,bankid
,managearea
,banchamount
,exchangeid
,registeradd
,chargedepartment
,officeadd
,officezip
,countrycode
,regioncode
,villagecode
,villagename
,relativetype
,officetel
,officefax
,webadd
,emailadd
,employeenumber
,mainproduction
,newtechcorpornot
,listingcorpornot
,hasieright
,hasdirectorate
,basicbank
,basicaccount
,manageinfo
,customerhistory
,projectflag
,realtyflag
,workfieldarea
,workfieldfee
,accountdate
,loancardno
,loancardpassword
,loancardinsyear
,loancardinsresult
,loanflag
,financeornot
,financebelong
,creditbelong
,creditlevel
,evaluatedate
,othercreditlevel
,otherevaluatedate
,otherorgname
,inputorgid
,inputuserid
,inputdate
,updateorgid
,updateuserid
,updatedate
,remark
,taxno1
,fictitiouspersonid
,groupflag
,evaluatelevel
,mybank
,mybankaccount
,otherbank
,otherbankaccount
,tempsaveflag
,financedepttel
,ecgroupflag
,supercorpname
,superloancardno
,supercerttype
,smeindustrytype
,sellsum
,supercertid
,isblack
,isdebt
,isstrategycustomer
,ifoversea
,serviceupdateresult
,rwacustomertype
,businessstrategy
,isnewsetup
,isrelative
,ifsme
,locality
,subjectbusiness
,islimit
,privateent
,bankingsupervision
,holdingtype
,fiscalsource
,lmcredittype
,onlycapital
,stratagemflag
,isrelatedparty
,fictitiouspersoncertificateid
,corpstartdate
,corpvaliditydate
,corpregisteradd
,registerdate
,financedirectorname
,mobilephone
,mfcustomerid
,custtp
,custst
,iscred
,ispart
,orgown
,budgtp
,ntlycd
,crylev
,mainfg
,validt
,liisau
,others
,idtfst
,idcdad
,contna
,idtftp
,idtfno
,cmainf
,hometl
,othrtl
,caiwno
,caiwtp
,offitl
,mobitl
,fictitiousmobile
,fictitiousduty
,finalevaluatedate
,iscountrysidenterprise
,financialgroupscope
,financialgroupposition
,industrialrestructuringtype
,transformationandupgradeid
,strategicemergingindustrytype
,creditinstitutioncode
,parentcompanyofficeadd
,officeaddupdatedate
,listingcorporation
,shareholderstructuredate
,hasiebusiness
,orgdetail
,orgstatus
,organiztype
,documenttype
,documentno
,financefiamtel
,financeothertel
,bankingtype
,societyinstitutioncode
,commercialregno
,clyxcustomerid
,onlylimit
,scopecalculate
,raterisklevel
,industrytypeproportion
,industrytypeproportion1
,industrytypeproportion2
,isfreshcust
,jtbbname
,mcompanyname
,mcompanycerttype
,mcompanycertid
,acceptbankid
,acceptbankname
,isdlfr
,outdate
,outmsg
,creditdebtlimit
,currencyfundlimit
,currencyfundused
,creditdebtused
,iseduhealth
,ishewpackard
,corporationgrowthstage
,laborintensiveentflag
,start_dt
,end_dt
,id_mark
from idl.crss_ent_info
where start_dt <= to_date('${batch_date}','yyyymmdd') and end_dt > to_date('${batch_date}','yyyymmdd')" \
        field="0x1b" record="0x0a"  \
        file="${iel_data_path}/crss_ent_info.f.${batch_date}.dat" \
        charset=zhs16gbk
        safe=yes