CREATE OR REPLACE PROCEDURE RRP_MDL.ETL_STATE_RERUN(I_P_DATE IN INTEGER,O_ERRCODE OUT VARCHAR2)
IS
  --支持重跑，清空跑批完成记录表当日记录
  V_P_DATE VARCHAR2(8);
BEGIN
  V_P_DATE := TO_CHAR(I_P_DATE);
  --清空
  DELETE FROM RRP_MDL.ETL_STATE WHERE ETL_DATE = V_P_DATE;
  COMMIT;
  O_ERRCODE := 0;
END ETL_STATE_RERUN;
/

