CREATE OR REPLACE PROCEDURE RRP_MDL.ETL_M_MRPT_ATMS_DEV_BASE_INFO (I_P_DATE IN INTEGER, --跑批日期
                                                           O_ERRCODE  OUT VARCHAR2 --错误代码
                                                 )
 /*******************************************************************
  **存储过程详细说明： 设备基础信息表
  **存储过程名称：    ETL_M_MRPT_ATMS_DEV_BASE_INFO
  **存储过程创建日期：20221226
  **存储过程创建人：  YANGJUAN
  **输入参数：        I_P_DATE
  **输出参数：        O_ERRCODE
  **返回值：          O_ERRCODE
  ** 修改日期    修改人     修改原因
  ********************************************************************/
 -- 定义变量 --
  AS
  I_STEP      INTEGER := 0; -- 处理步骤
  V_PROC_NAME VARCHAR2(50) := 'ETL_M_MRPT_ATMS_DEV_BASE_INFO'; -- 程序名称
  V_P_DATE    VARCHAR2(8); -- 跑批数据日期
  D_STARTTIME DATE; -- 处理开始时间
  D_ENDTIME   DATE;   -- 处理结束时间
  I_SQLCOUNT  INTEGER := 0; -- 更新或删除影响的记录数
  V_SQLMSG    VARCHAR2(300); -- SQL执行描述信息
  V_SYSTEM    VARCHAR2(30); -- 来源系统
  V_SQL       VARCHAR2(2000); -- 动态sql
  I_STEP_DESC VARCHAR2(200); --任务名称
  V_PART_NAME VARCHAR2(100);  --分区名称
  V_PART_COUNT INTEGER;        --分区是否存在
  V_TAB_NAME  VARCHAR2(100);  --表名称
  V_FREQ_FLAG   VARCHAR2(10);    --跑批频度标识

BEGIN

  O_ERRCODE := '0';
  -- 处理参数及月末等判断逻辑 --
  V_P_DATE := TO_CHAR(I_P_DATE); -- 获取跑批日期
  V_SYSTEM := '监管报送'; -- 默认写监管报送系统，有真实来源的按实际写
  V_PART_NAME := 'PARTITION_'||V_P_DATE; --分区名称
  V_TAB_NAME := 'M_MRPT_ATMS_DEV_BASE_INFO'; --表名称

  V_FREQ_FLAG := FUN_FREQ(V_P_DATE, V_PROC_NAME);
  IF V_FREQ_FLAG = '1' THEN

  -- 支持重跑 --
  I_STEP := 1;
  I_STEP_DESC := '-- 程序跑批开始 --';
  D_STARTTIME := SYSDATE;
  --DELETE FROM M_MRPT_ATMS_DEV_BASE_INFO T WHERE T.DATA_DT = V_P_DATE;--普通表的重跑处理
  /*SELECT COUNT(0)
    INTO V_PART_COUNT
    FROM USER_TAB_PARTITIONS T
   WHERE T.TABLE_NAME = V_TAB_NAME
     AND T.PARTITION_NAME = V_PART_NAME;

  IF V_PART_COUNT = 1 THEN
  V_SQL := 'ALTER TABLE '||V_TAB_NAME||' DROP PARTITION '||V_PART_NAME;--分区表的重跑处理
  EXECUTE IMMEDIATE V_SQL;
  --ETL_PARTITION_DROP(V_P_DATE,V_TAB_NAME,O_ERRCODE);--分区表的重跑处理
  END IF ;*/

 ETL_PARTITION_ADD(V_P_DATE,V_TAB_NAME,1,O_ERRCODE);--新增分区

  I_SQLCOUNT := SQL%ROWCOUNT;
  V_SQLMSG := '返回值：['||SQLCODE||'],执行信息：'||SQLERRM;
  O_ERRCODE := '0';
  D_ENDTIME := SYSDATE;

  COMMIT;
  ETL_YUSYS_LOG(V_P_DATE,V_SYSTEM,V_PROC_NAME,D_STARTTIME,D_ENDTIME,I_STEP,I_STEP_DESC,I_SQLCOUNT,O_ERRCODE,V_SQLMSG);

  -- 程序业务逻辑处理主体部分 --
  I_STEP := I_STEP + 1; -- 小于10步骤直接写数字，大于10步用I_STEP := I_STEP + 1;描述每一步骤的作用，如加工处理核心系统个人客户信息。
  I_STEP_DESC := '数据落地-设备基础信息表';
  D_STARTTIME := SYSDATE;
 INSERT /*+APPEND*/ INTO RRP_MDL.M_MRPT_ATMS_DEV_BASE_INFO NOLOGGING
     (
    DATA_DT
   ,NO
   ,IP
   ,ORG_NO
   ,AWAY_FLAG
   ,DEV_CATALOG
   ,DEV_VENDOR
   ,DEV_TYPE
   ,WORK_TYPE
   ,STATUS
   ,DEV_SERVICE
   ,TERMINAL_NO
   ,SERIAL
   ,ADDRESS
   ,BUY_DATE
   ,INSTALL_DATE
   ,START_DATE
   ,STOP_DATE
   ,OPEN_TIME
   ,CLOSE_TIME
   ,EXPIRE_DATE
   ,PATROL_PERIOD
   ,AREA_NO
   ,X
   ,Y
   ,CASHBOX_LIMIT
   ,OS
   ,ATMC_SOFT
   ,ANTI_VIRUS_SOFT
   ,SP
   ,VIRTUAL_TELLER_NO
   ,CARE_LEVEL
   ,LAST_PM_DATE
   ,EXPIRE_PM_DATE
   ,LOCATE_NO
   ,NOTE1
   ,NOTE2
   ,NOTE3
   ,NOTE4
   ,NOTE5
   ,CARRIER
   ,MONEY_ORG
   ,DEV_STATUS
   ,ENVIRONMENT
   ,ADDRESS_CODE
   ,CASH_TYPE
   ,SETUP_TYPE
   ,NET_TYPE
   ,OPERATE_STATUS
   ,REGISTRATION_STATUS
   ,COMM_PACKET
   ,ZIP_TYPE
   ,DEK_ENCODED
   ,ATMP_AREA
   ,SELFBANKTYPE
   ,ARM_TYPE
   ,PREF_NO
   ,COUNTRY_NO
   ,POSTCODE
   ,CONTACT
   ,ACPT_INS_ID_CD
   ,INVSTR_INS_ID_CD
   ,MAINTN_INS_ID_CD
   ,TERM_PUBLICIZE_CHNL
   ,SOCKET
   ,FRN_ACPT_TP
   ,SCAN_CODE
   ,MAGN_READ_IN
   ,NO_CARD
   ,CONT_IC_IN
   ,CONTLESS_IC_IN
   ,TERM_TRAN_FUN
   ,LAST_STATUE
   ,IS_EXPORT
   ,DEPLOY_AREA_NO
   ,DEPLOY_AREA_NAME
   ,TERMINAL_STATUS
   ,START_DT
   ,END_DT
   ,ID_MARK
      )
     SELECT /*+PARALLEL*/
    V_P_DATE
   ,NO
   ,IP
   ,ORG_NO
   ,AWAY_FLAG
   ,DEV_CATALOG
   ,DEV_VENDOR
   ,DEV_TYPE
   ,WORK_TYPE
   ,STATUS
   ,DEV_SERVICE
   ,TERMINAL_NO
   ,SERIAL
   ,ADDRESS
   ,BUY_DATE
   ,INSTALL_DATE
   ,START_DATE
   ,STOP_DATE
   ,OPEN_TIME
   ,CLOSE_TIME
   ,EXPIRE_DATE
   ,PATROL_PERIOD
   ,AREA_NO
   ,X
   ,Y
   ,CASHBOX_LIMIT
   ,OS
   ,ATMC_SOFT
   ,ANTI_VIRUS_SOFT
   ,SP
   ,VIRTUAL_TELLER_NO
   ,CARE_LEVEL
   ,LAST_PM_DATE
   ,EXPIRE_PM_DATE
   ,LOCATE_NO
   ,NOTE1
   ,NOTE2
   ,NOTE3
   ,NOTE4
   ,NOTE5
   ,CARRIER
   ,MONEY_ORG
   ,DEV_STATUS
   ,ENVIRONMENT
   ,ADDRESS_CODE
   ,CASH_TYPE
   ,SETUP_TYPE
   ,NET_TYPE
   ,OPERATE_STATUS
   ,REGISTRATION_STATUS
   ,COMM_PACKET
   ,ZIP_TYPE
   ,DEK_ENCODED
   ,ATMP_AREA
   ,SELFBANKTYPE
   ,ARM_TYPE
   ,PREF_NO
   ,COUNTRY_NO
   ,POSTCODE
   ,CONTACT
   ,ACPT_INS_ID_CD
   ,INVSTR_INS_ID_CD
   ,MAINTN_INS_ID_CD
   ,TERM_PUBLICIZE_CHNL
   ,SOCKET
   ,FRN_ACPT_TP
   ,SCAN_CODE
   ,MAGN_READ_IN
   ,NO_CARD
   ,CONT_IC_IN
   ,CONTLESS_IC_IN
   ,TERM_TRAN_FUN
   ,LAST_STATUE
   ,IS_EXPORT
   ,DEPLOY_AREA_NO
   ,DEPLOY_AREA_NAME
   ,TERMINAL_STATUS
   ,START_DT
   ,END_DT
   ,ID_MARK
    FROM RRP_MDL.O_IOL_ATMS_DEV_BASE_INFO   --设备基础信息表--视图
   WHERE START_DT <=TO_DATE(V_P_DATE,'YYYYMMDD')
     AND END_DT >=TO_DATE(V_P_DATE,'YYYYMMDD')

   ;
  -- 如需要分析表，请用如下代码 --
   -- DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>'写上数据库用户名',TABLENAME => '写上表名字',PARTNAME => 'P_'||V_P_DATE||'',DEGREE => 16,CASCATE => TRUE);
   ETL_YUSYS_LOG(V_P_DATE,V_SYSTEM,V_PROC_NAME,D_STARTTIME,D_ENDTIME,I_STEP,I_STEP_DESC,I_SQLCOUNT,O_ERRCODE,V_SQLMSG);

   INSERT INTO RRP_MDL.ETL_STATE(ETL_DATE, PROC_NAME,END_TIME)
   VALUES (V_P_DATE,V_PROC_NAME,TO_CHAR(SYSTIMESTAMP,'YYYYMMDD HH24:MI:SS'));
   COMMIT;

   -- 程序跑批结束记录 --
   I_STEP_DESC := '-- 程序跑批结束 --';
   O_ERRCODE  := '0';
   ETL_YUSYS_LOG(V_P_DATE,V_SYSTEM,V_PROC_NAME,D_STARTTIME,D_ENDTIME,I_STEP,I_STEP_DESC,I_SQLCOUNT,O_ERRCODE,'');
  
  END IF;
   -- 程序异常处理部分 --
   EXCEPTION
     WHEN OTHERS THEN
   V_SQLMSG := '返回值：['||SQLCODE||'],描述信息：'||SQLERRM;
   ROLLBACK;
     O_ERRCODE := '1';
     D_ENDTIME := SYSDATE;
  /* I_STEP := I_STEP + 1;
     I_STEP_DESC := '-- 程序跑批异常 --';*/
   ETL_YUSYS_LOG(V_P_DATE,V_SYSTEM,V_PROC_NAME,D_STARTTIME,D_ENDTIME,I_STEP,I_STEP_DESC,I_SQLCOUNT,O_ERRCODE,V_SQLMSG);


END ETL_M_MRPT_ATMS_DEV_BASE_INFO;
/

