CREATE OR REPLACE PROCEDURE RRP_MDL."ETL_INIT_O_IOL_ATMS_DEV_BASE_INFO" (I_P_DATE IN INTEGER, --跑批日期
                                                 O_ERRCODE  OUT VARCHAR2 --错误代码
                                                 )
 /*******************************************************************
  **存储过程详细说明： 设备基础信息表
  **存储过程名称：    ETL_INIT_O_IOL_ATMS_DEV_BASE_INFO
  **存储过程创建日期：20221130
  **存储过程创建人：  HULIJUAN
  **输入参数：        I_P_DATE
  **输出参数：        O_ERRCODE
  **返回值：           O_ERRCODE
  ** 修改日期    修改人     修改原因
  ********************************************************************/
 AS
  -- 定义变量 --

  V_STEP      INTEGER := '0'; -- 处理步骤
  V_PROC_NAME VARCHAR2(50) := 'ETL_INIT_O_IOL_ATMS_DEV_BASE_INFO'; -- 程序名称
  V_P_DATE  VARCHAR2(8); -- 跑批数据日期
  V_STARTTIME DATE; -- 处理开始时间
  V_ENDTIME DATE;   -- 处理结束时间
  V_SQLCOUNT  INTEGER := 0; -- 更新或删除影响的记录数
  V_SQLMSG    VARCHAR2(300); -- SQL执行描述信息
  V_SYSTEM    VARCHAR2(100); -- 来源系统
  V_LAST_DAT  VARCHAR2(8); -- 当月月末
  V_YESTADAY  VARCHAR2(8); -- 上日
  V_MONTH_START_DATE DATE;  --系统时间对应月初日期
  V_STEP_DESC VARCHAR2(200); --任务名称
  V_DATE DATE;
  V_TABLE_NAME VARCHAR2(100); --表名
BEGIN
V_TABLE_NAME := REPLACE(V_PROC_NAME,'ETL_INIT_','');
--清空表
EXECUTE IMMEDIATE 'TRUNCATE TABLE '|| V_TABLE_NAME;

  -- 处理参数及月末等判断逻辑 --
  V_P_DATE := TO_CHAR(I_P_DATE); -- 获取跑批日期
  O_ERRCODE := '0';
  V_SYSTEM := '监管报送'; -- 默认写监管报送系统，有真实来源的按实际写
  V_YESTADAY := TO_CHAR(TO_DATE(V_P_DATE,'YYYYMMDD')-1,'YYYYMMDD'); -- 上日
  V_LAST_DAT := TO_CHAR(LAST_DAY(TO_DATE(V_P_DATE,'YYYY-MM-DD')),'YYYYMMDD'); --当月月底
  V_MONTH_START_DATE:=TRUNC(TO_DATE(V_P_DATE,'YYYYMMDD'), 'MM');


  --将参数转化为日期格式，判读输入参数是否符合日期要求
  V_DATE    := TO_DATE(I_P_DATE,'YYYY-MM-DD');

  --清理当天数据
  -- EXECUTE IMMEDIATE ' TRUNCATE TABLE RRP_MDL.O_IOL_ATMS_DEV_BASE_INFO';

 INSERT /*+APPEND*/ INTO RRP_MDL.O_IOL_ATMS_DEV_BASE_INFO NOLOGGING
    (
    NO
   ,IP
   ,ORG_NO
   ,AWAY_FLAG
   ,DEV_CATALOG
   ,DEV_VENDOR
   ,DEV_TYPE
   ,WORK_TYPE
   ,STATUS
   ,DEV_SERVICE
   ,TERMINAL_NO
   ,SERIAL
   ,ADDRESS
   ,BUY_DATE
   ,INSTALL_DATE
   ,START_DATE
   ,STOP_DATE
   ,OPEN_TIME
   ,CLOSE_TIME
   ,EXPIRE_DATE
   ,PATROL_PERIOD
   ,AREA_NO
   ,X
   ,Y
   ,CASHBOX_LIMIT
   ,OS
   ,ATMC_SOFT
   ,ANTI_VIRUS_SOFT
   ,SP
   ,VIRTUAL_TELLER_NO
   ,CARE_LEVEL
   ,LAST_PM_DATE
   ,EXPIRE_PM_DATE
   ,LOCATE_NO
   ,NOTE1
   ,NOTE2
   ,NOTE3
   ,NOTE4
   ,NOTE5
   ,CARRIER
   ,MONEY_ORG
   ,DEV_STATUS
   ,ENVIRONMENT
   ,ADDRESS_CODE
   ,CASH_TYPE
   ,SETUP_TYPE
   ,NET_TYPE
   ,OPERATE_STATUS
   ,REGISTRATION_STATUS
   ,COMM_PACKET
   ,ZIP_TYPE
   ,DEK_ENCODED
   ,ATMP_AREA
   ,SELFBANKTYPE
   ,ARM_TYPE
   ,PREF_NO
   ,COUNTRY_NO
   ,POSTCODE
   ,CONTACT
   ,ACPT_INS_ID_CD
   ,INVSTR_INS_ID_CD
   ,MAINTN_INS_ID_CD
   ,TERM_PUBLICIZE_CHNL
   ,SOCKET
   ,FRN_ACPT_TP
   ,SCAN_CODE
   ,MAGN_READ_IN
   ,NO_CARD
   ,CONT_IC_IN
   ,CONTLESS_IC_IN
   ,TERM_TRAN_FUN
   ,LAST_STATUE
   ,IS_EXPORT
   ,DEPLOY_AREA_NO
   ,DEPLOY_AREA_NAME
   ,TERMINAL_STATUS
   ,START_DT
   ,END_DT
   ,ID_MARK
   ,ETL_TIMESTAMP

    )
     SELECT /*+PARALLEL*/
        NO
   ,IP
   ,ORG_NO
   ,AWAY_FLAG
   ,DEV_CATALOG
   ,DEV_VENDOR
   ,DEV_TYPE
   ,WORK_TYPE
   ,STATUS
   ,DEV_SERVICE
   ,TERMINAL_NO
   ,SERIAL
   ,ADDRESS
   ,BUY_DATE
   ,INSTALL_DATE
   ,START_DATE
   ,STOP_DATE
   ,OPEN_TIME
   ,CLOSE_TIME
   ,EXPIRE_DATE
   ,PATROL_PERIOD
   ,AREA_NO
   ,X
   ,Y
   ,CASHBOX_LIMIT
   ,OS
   ,ATMC_SOFT
   ,ANTI_VIRUS_SOFT
   ,SP
   ,VIRTUAL_TELLER_NO
   ,CARE_LEVEL
   ,LAST_PM_DATE
   ,EXPIRE_PM_DATE
   ,LOCATE_NO
   ,NOTE1
   ,NOTE2
   ,NOTE3
   ,NOTE4
   ,NOTE5
   ,CARRIER
   ,MONEY_ORG
   ,DEV_STATUS
   ,ENVIRONMENT
   ,ADDRESS_CODE
   ,CASH_TYPE
   ,SETUP_TYPE
   ,NET_TYPE
   ,OPERATE_STATUS
   ,REGISTRATION_STATUS
   ,COMM_PACKET
   ,ZIP_TYPE
   ,DEK_ENCODED
   ,ATMP_AREA
   ,SELFBANKTYPE
   ,ARM_TYPE
   ,PREF_NO
   ,COUNTRY_NO
   ,POSTCODE
   ,CONTACT
   ,ACPT_INS_ID_CD
   ,INVSTR_INS_ID_CD
   ,MAINTN_INS_ID_CD
   ,TERM_PUBLICIZE_CHNL
   ,SOCKET
   ,FRN_ACPT_TP
   ,SCAN_CODE
   ,MAGN_READ_IN
   ,NO_CARD
   ,CONT_IC_IN
   ,CONTLESS_IC_IN
   ,TERM_TRAN_FUN
   ,LAST_STATUE
   ,IS_EXPORT
   ,DEPLOY_AREA_NO
   ,DEPLOY_AREA_NAME
   ,TERMINAL_STATUS
   ,START_DT
   ,END_DT
   ,ID_MARK
   ,ETL_TIMESTAMP
    FROM IOL.V_ATMS_DEV_BASE_INFO   设备基础信息表--视图


   ;
  -- 如需要分析表，请用如下代码 --
   -- DBMS_STATS.GATHER_TABLE_STATS(OWNNAME=>'写上数据库用户名',TABLENAME => '写上表名字',PARTNAME => 'P_'||V_P_DATE||'',DEGREE => 16,CASCATE => TRUE);
   --ETL_DBMS_STATS(V_P_DATE, V_TAB_NAME, ‘, O_ERRCODE);

   INSERT INTO RRP_MDL.ETL_STATE(ETL_DATE, PROC_NAME,END_TIME)
   VALUES (V_P_DATE,V_PROC_NAME,TO_CHAR(SYSTIMESTAMP,'YYYYMMDD HH24:MI:SS'));
   COMMIT;
   ETL_YUSYS_LOG(V_P_DATE,V_SYSTEM,V_PROC_NAME,V_STARTTIME,V_ENDTIME,V_STEP,V_STEP_DESC,V_SQLCOUNT,O_ERRCODE,V_SQLMSG);

   -- 程序跑批结束记录 --
   V_STEP_DESC := '-- 程序跑批结束 --';
   ETL_YUSYS_LOG(V_P_DATE,V_SYSTEM,V_PROC_NAME,V_STARTTIME,V_ENDTIME,V_STEP,V_STEP_DESC,V_SQLCOUNT,O_ERRCODE,'');

   -- 程序异常处理部分 --
   EXCEPTION
     WHEN OTHERS THEN
   V_SQLMSG := '返回值：['||SQLCODE||'],描述信息：'||SQLERRM;
   ROLLBACK;
     O_ERRCODE := '1';
     V_ENDTIME := SYSDATE;

   ETL_YUSYS_LOG(V_P_DATE,V_SYSTEM,V_PROC_NAME,V_STARTTIME,V_ENDTIME,V_STEP,V_STEP_DESC,V_SQLCOUNT,O_ERRCODE,V_SQLMSG);


END ETL_INIT_O_IOL_ATMS_DEV_BASE_INFO;
/

