CREATE OR REPLACE PROCEDURE RRP_EAST.SP_EAST_CPGC(
  PI_PAR_DATE   IN VARCHAR2,
  PI_PROC_NAME  IN VARCHAR2
  )
 IS
  V_SQL                      VARCHAR2(1000);
  V_PRO_OUTPUT               VARCHAR2(2);
BEGIN
  V_SQL:='BEGIN '||PI_PROC_NAME||'(:V_PRO_DATE,:V_PRO_OUTPUT); END;';
  EXECUTE IMMEDIATE V_SQL USING IN PI_PAR_DATE, OUT V_PRO_OUTPUT;

END SP_EAST_CPGC;
/

