/*
Purpose:    整全模型层-快照表脚本，备份目标表当月数据（不含当天），用前一天数据与当天数据整合后插入到目标表中。此脚本由生成引擎自动生成。
Author:     Sunline
Usage:      python $ETL_HOME/script/main.py 20200930 iml_ecif2_iml_static_data_2
CreateDate: 20180515
Logs:
    zjj 2018-05-15 新建表本
*/

set timing on

alter session force parallel query parallel 8; 

-- 清除表
whenever sqlerror exit sql.sqlcode;
CREATE OR REPLACE VIEW IML.V_PTY_PARTY_CERT_INFO_H AS
SELECT PARTY_ID
  ,LP_ID
  ,SORC_SYS_CD
  ,CERT_TYPE_CD
  ,START_DT
  ,CERT_NUM
  ,CERT_ADDR
  ,ISSUE_CERT_ORG
  ,ISSUE_CERT_ORG_CTY_CD
  ,CERT_EFFECT_DT
  ,CERT_INVALID_DT
  ,LICEN_ISSUE_AUTHO_DIST_CD
  ,CRDT_CD_CERT_ID
  ,CERT_VALID_FLG
  ,CERT_STATUS_CD
  ,MAIN_CERT_NO_FLG
  ,NETW_VRFCTION_FLG
  ,NETW_VRFCTION_REST_CD
  ,END_DT
  ,ID_MARK
  ,SRC_TABLE_NAME
  ,JOB_CD
FROM IML.PTY_PARTY_CERT_INFO_H
UNION ALL
SELECT PARTY_ID
  ,LP_ID
  ,SORC_SYS_CD
  ,CERT_TYPE_CD
  ,START_DT
  ,CERT_NUM
  ,CERT_ADDR
  ,ISSUE_CERT_ORG
  ,ISSUE_CERT_ORG_CTY_CD
  ,CERT_EFFECT_DT
  ,CERT_INVALID_DT
  ,LICEN_ISSUE_AUTHO_DIST_CD
  ,CRDT_CD_CERT_ID
  ,CERT_VALID_FLG
  ,CERT_STATUS_CD
  ,MAIN_CERT_NO_FLG
  ,NETW_VRFCTION_FLG
  ,NETW_VRFCTION_REST_CD
  ,END_DT
  ,ID_MARK
  ,SRC_TABLE_NAME
  ,JOB_CD
FROM IML.PTY_PARTY_CERT_INFO_H_ECIF1_STATIC_DATA t1
where 1 = 1 
and not exists (select 1 from iml.pty_party_cert_info_h b 
                        where t1.party_id=b.party_id 
                          and t1.sorc_sys_cd=b.sorc_sys_cd 
                          and t1.cert_type_cd=b.cert_type_cd
                );
COMMENT ON TABLE IML.V_PTY_PARTY_CERT_INFO_H IS '当事人证件信息历史_视图';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.PARTY_ID IS '当事人编号';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.LP_ID IS '法人编号';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.SORC_SYS_CD IS '源系统代码';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.CERT_TYPE_CD IS '证件类型代码';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.START_DT IS '开始日期';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.CERT_NUM IS '证件号码';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.CERT_ADDR IS '证件地址';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.ISSUE_CERT_ORG IS '发证机关';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.ISSUE_CERT_ORG_CTY_CD IS '发证机关国家代码';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.CERT_EFFECT_DT IS '证件生效日期';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.CERT_INVALID_DT IS '证件失效日期';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.LICEN_ISSUE_AUTHO_DIST_CD IS '发证机关行政区划代码';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.CRDT_CD_CERT_ID IS '信用代码证编号';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.CERT_VALID_FLG IS '证件有效标志';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.CERT_STATUS_CD IS '证件状态代码';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.MAIN_CERT_NO_FLG IS '主证件号标志';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.NETW_VRFCTION_FLG IS '联网核查标志';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.NETW_VRFCTION_REST_CD IS '联网核查结果代码';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.END_DT IS '结束日期';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.ID_MARK IS '删除标识';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.SRC_TABLE_NAME IS '源表名称';
COMMENT ON COLUMN IML.V_PTY_PARTY_CERT_INFO_H.JOB_CD IS '任务代码';


grant select on iml.v_pty_party_cert_info_h to rdw,datacore;

commit;