/*
Purpose:    BASE_D_ACCT_CLASS_BUS(base_d_acct_class_bus_accum):账户类指标结果表(账户类基础指标结果表_累计)
Author:     Sunline/郑沛隆
Usage:      python $ETL_HOME/script/main.py yyyymmdd idl_mcyy_base_d_acct_class_bus_accum
Createdate: 20220509

Logs:
  郑沛隆 2022-05-09 新建脚本          
*/
 
set timing on
-- 0.1 alter parallel
alter session force parallel query parallel 4;
alter session force parallel dml parallel 4;
-- alter session force parallel ddl parallel 1;

-- 1.1 drop tmp tables and add partition
whenever sqlerror continue none;

alter table ${idl_schema}.base_d_acct_class_bus_accum add partition p_${batch_date} values (to_date('${batch_date}','yyyymmdd'));

drop table ${idl_schema}.tmp_base_d_acct_class_bus_accum purge;

-- 1.2 create tmp tables
whenever sqlerror exit sql.sqlcode;
create table ${idl_schema}.tmp_base_d_acct_class_bus_accum
compress ${option_switch} for query high
as
select
    *
from ${idl_schema}.base_d_acct_class_bus_accum
where 0=1;

-- 2.指标数据逻辑开始
-- 2.1 指标数据前置依赖
whenever sqlerror exit sql.sqlcode;
INSERT /*+ append */ INTO ${idl_schema}.TMP_base_d_acct_class_bus_accum
(
INDEX_NO
,ORG_NO
,SUP_ORG_NO
,INDEX_VALUE_D
,INDEX_VALUE_M
,INDEX_VALUE_Q
,INDEX_VALUE_Y
,ESPEC_DIMEN_CD1
,ESPEC_DIMEN_CD2
,ESPEC_DIMEN_CD3
,ESPEC_DIMEN_CD4
,ESPEC_DIMEN_CD5
,REMARK
,ETL_DT
,ETL_TIMESTAMP
)
WITH 
ST1 AS (SELECT * FROM ITL_EDW_CMM_DEP_CUST_ACCT_INFO WHERE ETL_DT=to_date('${batch_date}','yyyymmdd')),
ST2 AS (SELECT * FROM ITL_EDW_CMM_DEP_ACCT_INFO  WHERE ETL_DT=to_date('${batch_date}','yyyymmdd')),
ST3 AS (SELECT * FROM ITL_EDW_EVT_CARD_CHANGE_RGST_B WHERE ETL_DT=to_date('${batch_date}','yyyymmdd')),
ST4 AS (SELECT * FROM MCYY_ORGA_PARA),
--2.2 指标数据生成
--人民币对公基本存款账户累计户数
TMP_WD030111 AS (
SELECT 
'WD030111' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD = 'CNY' and ST2.ACCT_CLS_CD = '11001' AND ST2.ACCT_USAGE_CD NOT LIKE '2002%' and ST2.CORP_ACCT_FLG = '1'and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO ) AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--人民币对公一般存款账户累计户数
TMP_WD030112 AS (
SELECT 
'WD030112' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD = 'CNY' and ST2.ACCT_CLS_CD = '11002' AND ST2.ACCT_USAGE_CD NOT LIKE '2002%' and ST2.CORP_ACCT_FLG = '1'and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--人民币对公专用存款账户累计户数
TMP_WD030113 AS (
SELECT
'WD030113' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD = 'CNY' and ST2.ACCT_CLS_CD = '11004' AND ST2.ACCT_USAGE_CD NOT LIKE '2002%' and ST2.CORP_ACCT_FLG = '1'and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--人民币对公临时账户累计户数存款
TMP_WD030114 AS (
SELECT 
'WD030114' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD = 'CNY' and ST2.ACCT_CLS_CD = '11003' AND ST2.ACCT_USAGE_CD NOT LIKE '2002%'and ST2.CORP_ACCT_FLG = '1'and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--人民币对公定期存款账户累计户数 
TMP_WD030115 AS (
SELECT 
'WD030115' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD = 'CNY' and ST2.ACCT_CLS_CD = '11005' AND ST2.RC_FLG ='1' 
--AND ST2.MATER_ACCT_FLG = '1' 
AND ST2.CUST_ACCT_SUB_ACCT_NUM='1'
AND ST2.ACCT_USAGE_CD NOT LIKE '2002%'and ST2.CORP_ACCT_FLG = '1'and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--人民币对公保证金存款账户累计户数
TMP_WD030116 AS (
SELECT 
'WD030116' AS INDEX_NO
      ,ST1.ACCT_BELONG_ORG_ID AS ORG_NO
      ,ST4.SUPER_ORG_NO AS SUP_ORG_NO
      ,COUNT(DISTINCT ST1.cust_acct_id) AS INDEX_VALUE_D
      ,0 AS INDEX_VALUE_M
      ,0 AS INDEX_VALUE_Q
      ,0 AS INDEX_VALUE_Y
      ,'' AS ESPEC_DIMEN_CD1
      ,'' AS ESPEC_DIMEN_CD2
      ,'' AS ESPEC_DIMEN_CD3
      ,'' AS ESPEC_DIMEN_CD4
      ,'' AS ESPEC_DIMEN_CD5
      ,'' AS REMARK
,to_date('${batch_date}','yyyymmdd') AS ETL_DT
,to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
 FROM ST1
 INNER JOIN ST4
    ON ST1.ACCT_BELONG_ORG_ID = ST4.ORG_NO
 WHERE ST1.CURR_CD = 'CNY' AND ST1.std_prod_id = '904030300001' AND
       ST1.CORP_ACCT_FLG = '1' AND NOT EXISTS
 (SELECT 1
          FROM ST3
         WHERE ST3.NEW_CARD_NUM = ST1.CUST_ACCT_CARD_NO) AND
       ST1.OPEN_ACCT_DT <= to_date('${batch_date}', 'yyyymmdd') AND
       ST1.ACCT_STATUS_CD <> 'C'
 GROUP BY ST1.ACCT_BELONG_ORG_ID, ST4.SUPER_ORG_NO

),
--人民币个人结算Ⅰ类户累计户数
TMP_WD030209 AS (
SELECT 
'WD030209' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD = 'CNY' and ST2.ACCT_CLS_CD = '21001' AND ST2.STD_PROD_ID = '101010100001' AND ST2.ACCT_USAGE_CD NOT LIKE '2002%' AND  ST2.CORP_ACCT_FLG = '0' AND ST2.ACCT_TYPE_CD='1' and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--人民币个人结算Ⅱ类户累计户数
TMP_WD030210 AS (
SELECT 
'WD030210' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD = 'CNY' and ST2.ACCT_CLS_CD = '21001' AND  ST2.CORP_ACCT_FLG = '0' AND ST2.ACCT_TYPE_CD='2' and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--人民币个人结算Ⅲ类户累计户数
TMP_WD030211 AS (
SELECT 
'WD030211' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD = 'CNY' and ST2.ACCT_CLS_CD = '21001' AND  ST2.CORP_ACCT_FLG = '0' AND ST2.ACCT_TYPE_CD='3' and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--人民币个人定期存款账户累计户数
TMP_WD030212 AS (
SELECT 
'WD030212' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD = 'CNY'  AND  ST2.CORP_ACCT_FLG = '0' 
AND ST2.CUST_ACCT_SUB_ACCT_NUM='1'
--and ST2.STD_PROD_ID = '101020100002'
and (ST2.STD_PROD_ID = '101020100002'
       or ST2.STD_PROD_ID = '101020100009' or ST2.STD_PROD_ID='101020200001')
AND ST2.RC_FLG ='1' 
AND ST2.ACCT_USAGE_CD not LIKE '2002%'
--AND ST2.ACCT_TYPE_CD='9'
and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )
AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--人民币个人保证金存款账户累计户数
TMP_WD030215 AS (
SELECT 
'WD030215' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD = 'CNY' and ST2.ACCT_CLS_CD = '99001' AND  ST2.CORP_ACCT_FLG = '0' 
AND (ST2.STD_PROD_ID IN( '101010200001','101020500001') OR ST2.ACCT_USAGE_CD LIKE '2002%')
and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )
AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--外汇结算账户累计户数
TMP_WD030304 AS (
SELECT 
'WD030304' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD <> 'CNY' 
and ST2.ACCT_CLS_CD = '12001' 
AND ST2.STD_PROD_ID NOT IN ('103010200004','103020700004','101020600002') AND ST2.ACCT_USAGE_CD NOT LIKE '2002%'
and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )
AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
and st2.RC_FLG = '0'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--外汇定期母户累计户数
TMP_WD030305 AS (
SELECT 
'WD030305' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD <> 'CNY' 
and ST2.ACCT_CLS_CD = '12002' 
AND ST2.STD_PROD_ID NOT IN ('103010200004','103020700004','101020600002') AND ST2.ACCT_USAGE_CD NOT LIKE '2002%'
and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )
AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
and st2.RC_FLG = '1'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
--外汇保证金母户累计户数
TMP_WD030306 AS (
SELECT 
'WD030306' AS INDEX_NO,
ST2.BELONG_ORG_ID AS ORG_NO,
ST4.SUPER_ORG_NO AS SUP_ORG_NO,
COUNT(DISTINCT ST2.cust_acct_id) AS INDEX_VALUE_D,
0 AS INDEX_VALUE_M,
0 AS INDEX_VALUE_Q,
0 AS INDEX_VALUE_Y,
'' AS ESPEC_DIMEN_CD1,
'' AS ESPEC_DIMEN_CD2,
'' AS ESPEC_DIMEN_CD3,
'' AS ESPEC_DIMEN_CD4,
'' AS ESPEC_DIMEN_CD5,
'' AS REMARK,
to_date('${batch_date}','yyyymmdd') AS ETL_DT,
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM  ST2  INNER JOIN ST4 ON ST2.BELONG_ORG_ID=ST4.ORG_NO
WHERE ST2.CURR_CD <> 'CNY' and ST2.ACCT_CLS_CD = '99001' 
AND (ST2.STD_PROD_ID IN ('103010200004','103020700004','101020600002') OR ST2.ACCT_USAGE_CD  LIKE '2002%')
and NOT EXISTS (SELECT 1 FROM ST3 WHERE ST3.NEW_CARD_NUM=ST2.CUST_ACCT_CARD_NO )
AND ST2.OPEN_ACCT_DT<=to_date('${batch_date}', 'yyyymmdd')AND ST2.DEP_ACCT_STATUS_CD<>'C'
GROUP BY ST2.BELONG_ORG_ID,ST4.SUPER_ORG_NO
),
DB_REST AS (
SELECT * FROM TMP_WD030111
UNION ALL SELECT * FROM TMP_WD030112
UNION ALL SELECT * FROM TMP_WD030113
UNION ALL SELECT * FROM TMP_WD030114
UNION ALL SELECT * FROM TMP_WD030115
UNION ALL SELECT * FROM TMP_WD030116
UNION ALL SELECT * FROM TMP_WD030209
UNION ALL SELECT * FROM TMP_WD030210
UNION ALL SELECT * FROM TMP_WD030211
UNION ALL SELECT * FROM TMP_WD030212
UNION ALL SELECT * FROM TMP_WD030215
UNION ALL SELECT * FROM TMP_WD030304
UNION ALL SELECT * FROM TMP_WD030305
UNION ALL SELECT * FROM TMP_WD030306
)
SELECT 
*
FROM DB_REST;
COMMIT;


-- 3.2 exchage ex table and target table
alter table ${idl_schema}.base_d_acct_class_bus_accum exchange partition p_${batch_date} with table ${idl_schema}.tmp_base_d_acct_class_bus_accum;

-- 3.3 drop tmp table
drop TABLE ${idl_schema}.tmp_base_d_acct_class_bus_accum purge;

-- 4.1 gater table status
whenever sqlerror exit sql.sqlcode;
exec dbms_stats.gather_table_stats(ownname => '${idl_schema}',tabname => 'base_d_acct_class_bus_accum',partname => 'p_${batch_date}',ESTIMATE_PERCENT => 10,method_opt=>'for all columns size 1',no_invalidate=>false,granularity=>'partition',cascade => true,force=>true,degree => 8);



