/*
Purpose:    BASE_D_ACCT_CLASS_BUS(COMB_D_ACCT_CLASS_BUS):账户类指标结果表(账户类组合指标结果表)
Author:     Sunline/郑沛隆
Usage:      python $ETL_HOME/script/main.py yyyymmdd idl_mcyy_comb_d_acct_class_bus
Createdate: 20220510

Logs:
  郑沛隆 2022-05-10 新建脚本          
*/
 
set timing on
-- 0.1 alter parallel
alter session force parallel query parallel 4;
alter session force parallel dml parallel 4;
-- alter session force parallel ddl parallel 1;

-- 1.1 drop tmp tables and add partition
whenever sqlerror continue none;

alter table ${idl_schema}.comb_d_acct_class_bus add partition p_${batch_date} values (to_date('${batch_date}','yyyymmdd'));

drop table ${idl_schema}.tmp_comb_d_acct_class_bus purge;

-- 1.2 create tmp tables
whenever sqlerror exit sql.sqlcode;
create table ${idl_schema}.tmp_comb_d_acct_class_bus
compress ${option_switch} for query high
as
select
    *
from ${idl_schema}.comb_d_acct_class_bus
where 0=1;

-- 2.指标数据逻辑开始
-- 2.1 指标数据前置依赖

whenever sqlerror exit sql.sqlcode;
INSERT /*+ append */ INTO ${idl_schema}.TMP_comb_d_acct_class_bus
(
INDEX_NO
,ORG_NO
,SUP_ORG_NO
,INDEX_VALUE_D
,INDEX_VALUE_M
,INDEX_VALUE_Q
,INDEX_VALUE_Y
,ESPEC_DIMEN_CD1
,ESPEC_DIMEN_CD2
,ESPEC_DIMEN_CD3
,ESPEC_DIMEN_CD4
,ESPEC_DIMEN_CD5
,REMARK
,ETL_DT
,ETL_TIMESTAMP
)
WITH ST1 AS (
SELECT * FROM BASE_D_ACCT_CLASS_BUS_INCRS WHERE ETL_DT=to_date('${batch_date}','yyyymmdd')
),
ST2 AS (
SELECT * FROM BASE_D_ACCT_CLASS_BUS_ACCUM WHERE ETL_DT=to_date('${batch_date}','yyyymmdd')
),
--2.2 指标数据生成
--人民币对公结算账户开户数
TMP_WD030102 AS (
SELECT 
'WD030102' AS INDEX_NO , 
ST1.ORG_NO AS ORG_NO , 
ST1.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST1.INDEX_VALUE_D) AS INDEX_VALUE_D , 
SUM(ST1.INDEX_VALUE_M) AS INDEX_VALUE_M , 
SUM(ST1.INDEX_VALUE_Q) AS INDEX_VALUE_Q , 
SUM(ST1.INDEX_VALUE_Y) AS INDEX_VALUE_Y , 
ST1.ESPEC_DIMEN_CD1 AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP
FROM ST1
WHERE ST1.INDEX_NO IN ('WD030103','WD030104','WD030105','WD030106')
GROUP BY ST1.ORG_NO,ST1.SUP_ORG_NO,ST1.ESPEC_DIMEN_CD1
),
--人民币对公账户开户数(含保证金)
TMP_WD030117 AS (
SELECT 
'WD030117' AS INDEX_NO , 
ST1.ORG_NO AS ORG_NO , 
ST1.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST1.INDEX_VALUE_D) AS INDEX_VALUE_D , 
SUM(ST1.INDEX_VALUE_M) AS INDEX_VALUE_M , 
SUM(ST1.INDEX_VALUE_Q) AS INDEX_VALUE_Q , 
SUM(ST1.INDEX_VALUE_Y) AS INDEX_VALUE_Y , 
ST1.ESPEC_DIMEN_CD1 AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST1
WHERE ST1.INDEX_NO IN ('WD030103','WD030104','WD030105','WD030106','WD030107','WD030108')
GROUP BY ST1.ORG_NO,ST1.SUP_ORG_NO,ST1.ESPEC_DIMEN_CD1
),
--对公账户开户数(渠道)
TMP_WD030118 AS (
SELECT 
'WD030118' AS INDEX_NO , 
ST1.ORG_NO AS ORG_NO , 
ST1.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST1.INDEX_VALUE_D) AS INDEX_VALUE_D , 
SUM(ST1.INDEX_VALUE_M) AS INDEX_VALUE_M , 
SUM(ST1.INDEX_VALUE_Q) AS INDEX_VALUE_Q , 
SUM(ST1.INDEX_VALUE_Y) AS INDEX_VALUE_Y , 
ST1.ESPEC_DIMEN_CD1 AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST1
WHERE ST1.INDEX_NO IN ('WD030103','WD030104','WD030105','WD030106','WD030107','WD030108','WD030309')
GROUP BY ST1.ORG_NO,ST1.SUP_ORG_NO,ST1.ESPEC_DIMEN_CD1
),
--人民币个人结算账户开户数
TMP_WD030202 AS (
SELECT 
'WD030202' AS INDEX_NO , 
ST1.ORG_NO AS ORG_NO , 
ST1.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST1.INDEX_VALUE_D) AS INDEX_VALUE_D , 
SUM(ST1.INDEX_VALUE_M) AS INDEX_VALUE_M , 
SUM(ST1.INDEX_VALUE_Q) AS INDEX_VALUE_Q , 
SUM(ST1.INDEX_VALUE_Y) AS INDEX_VALUE_Y , 
ST1.ESPEC_DIMEN_CD1 AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST1
WHERE ST1.INDEX_NO IN ('WD030203','WD030204','WD030205')
GROUP BY ST1.ORG_NO,ST1.SUP_ORG_NO,ST1.ESPEC_DIMEN_CD1
),
--人民币个人账户开户数(含保证金)
TMP_WD030213 AS (
SELECT 
'WD030213' AS INDEX_NO , 
ST1.ORG_NO AS ORG_NO , 
ST1.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST1.INDEX_VALUE_D) AS INDEX_VALUE_D , 
SUM(ST1.INDEX_VALUE_M) AS INDEX_VALUE_M , 
SUM(ST1.INDEX_VALUE_Q) AS INDEX_VALUE_Q , 
SUM(ST1.INDEX_VALUE_Y) AS INDEX_VALUE_Y , 
ST1.ESPEC_DIMEN_CD1 AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST1
WHERE ST1.INDEX_NO IN ('WD030203','WD030204','WD030205','WD030206','WD030214')
GROUP BY ST1.ORG_NO,ST1.SUP_ORG_NO,ST1.ESPEC_DIMEN_CD1
),
--人民币个人账户开户数
TMP_WD030201 AS (
SELECT 
'WD030201' AS INDEX_NO , 
ST1.ORG_NO AS ORG_NO , 
ST1.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST1.INDEX_VALUE_D) AS INDEX_VALUE_D , 
SUM(ST1.INDEX_VALUE_M) AS INDEX_VALUE_M , 
SUM(ST1.INDEX_VALUE_Q) AS INDEX_VALUE_Q , 
SUM(ST1.INDEX_VALUE_Y) AS INDEX_VALUE_Y , 
ST1.ESPEC_DIMEN_CD1 AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST1
WHERE ST1.INDEX_NO IN ('WD030203','WD030204','WD030205','WD030206')
GROUP BY ST1.ORG_NO,ST1.SUP_ORG_NO,ST1.ESPEC_DIMEN_CD1
),
--个人账户开户数(渠道)
TMP_WD030216 AS (
SELECT 
'WD030216' AS INDEX_NO , 
ST1.ORG_NO AS ORG_NO , 
ST1.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST1.INDEX_VALUE_D) AS INDEX_VALUE_D , 
SUM(ST1.INDEX_VALUE_M) AS INDEX_VALUE_M , 
SUM(ST1.INDEX_VALUE_Q) AS INDEX_VALUE_Q , 
SUM(ST1.INDEX_VALUE_Y) AS INDEX_VALUE_Y , 
ST1.ESPEC_DIMEN_CD1 AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST1
WHERE ST1.INDEX_NO IN ('WD030203','WD030204','WD030205','WD030206','WD030214','WD030310')
GROUP BY ST1.ORG_NO,ST1.SUP_ORG_NO,ST1.ESPEC_DIMEN_CD1
),
--外汇账户开户数
TMP_WD030307 AS (
SELECT 
'WD030307' AS INDEX_NO , 
ST1.ORG_NO AS ORG_NO , 
ST1.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST1.INDEX_VALUE_D) AS INDEX_VALUE_D , 
SUM(ST1.INDEX_VALUE_M) AS INDEX_VALUE_M , 
SUM(ST1.INDEX_VALUE_Q) AS INDEX_VALUE_Q , 
SUM(ST1.INDEX_VALUE_Y) AS INDEX_VALUE_Y , 
ST1.ESPEC_DIMEN_CD1 AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST1
WHERE ST1.INDEX_NO IN ('WD030301','WD030302','WD030303')
GROUP BY ST1.ORG_NO,ST1.SUP_ORG_NO,ST1.ESPEC_DIMEN_CD1
),
--人民币对公账户累计户数(含保证金)
TMP_WD030109 AS (
SELECT 
'WD030109' AS INDEX_NO , 
ST2.ORG_NO AS ORG_NO , 
ST2.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST2.INDEX_VALUE_D) AS INDEX_VALUE_D , 
0 AS INDEX_VALUE_M , 
0 AS INDEX_VALUE_Q , 
0 AS INDEX_VALUE_Y , 
'' AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST2
WHERE ST2.INDEX_NO IN ('WD030111','WD030112','WD030113','WD030114','WD030115','WD030116')
GROUP BY ST2.ORG_NO,ST2.SUP_ORG_NO
),
--人民币对公结算账户累计户数
TMP_WD030110 AS (
SELECT 
'WD030110' AS INDEX_NO , 
ST2.ORG_NO AS ORG_NO , 
ST2.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST2.INDEX_VALUE_D) AS INDEX_VALUE_D , 
0 AS INDEX_VALUE_M , 
0 AS INDEX_VALUE_Q , 
0 AS INDEX_VALUE_Y , 
'' AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST2
WHERE ST2.INDEX_NO IN ('WD030111','WD030112','WD030113','WD030114')
GROUP BY ST2.ORG_NO,ST2.SUP_ORG_NO
),
--人民币个人账户累计户数(含保证金)
TMP_WD030207 AS (
SELECT 
'WD030207' AS INDEX_NO , 
ST2.ORG_NO AS ORG_NO , 
ST2.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST2.INDEX_VALUE_D) AS INDEX_VALUE_D , 
0 AS INDEX_VALUE_M , 
0 AS INDEX_VALUE_Q , 
0 AS INDEX_VALUE_Y , 
'' AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST2
WHERE ST2.INDEX_NO IN ('WD030209','WD030210','WD030211','WD030212','WD030215')
GROUP BY ST2.ORG_NO,ST2.SUP_ORG_NO
),
--人民币个人结算账户累计户数
TMP_WD030208 AS (
SELECT 
'WD030208' AS INDEX_NO , 
ST2.ORG_NO AS ORG_NO , 
ST2.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST2.INDEX_VALUE_D) AS INDEX_VALUE_D , 
0 AS INDEX_VALUE_M , 
0 AS INDEX_VALUE_Q , 
0 AS INDEX_VALUE_Y , 
'' AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST2
WHERE ST2.INDEX_NO IN ('WD030209','WD030210','WD030211')
GROUP BY ST2.ORG_NO,ST2.SUP_ORG_NO
),
--外汇账户累计户数
TMP_WD030308 AS (
SELECT 
'WD030308' AS INDEX_NO , 
ST2.ORG_NO AS ORG_NO , 
ST2.SUP_ORG_NO AS SUP_ORG_NO , 
SUM(ST2.INDEX_VALUE_D) AS INDEX_VALUE_D , 
0 AS INDEX_VALUE_M , 
0 AS INDEX_VALUE_Q , 
0 AS INDEX_VALUE_Y , 
'' AS ESPEC_DIMEN_CD1 , 
'' AS ESPEC_DIMEN_CD2 , 
'' AS ESPEC_DIMEN_CD3 , 
'' AS ESPEC_DIMEN_CD4 , 
'' AS ESPEC_DIMEN_CD5 , 
'' AS REMARK , 
to_date('${batch_date}','yyyymmdd') AS ETL_DT , 
to_timestamp('${batch_timestamp}','yyyy-mm-dd hh24:mi:ss.ff6') AS ETL_TIMESTAMP 
FROM ST2
WHERE ST2.INDEX_NO IN ('WD030304','WD030305','WD030306')
GROUP BY ST2.ORG_NO,ST2.SUP_ORG_NO
),
DB_REST AS (
SELECT * FROM TMP_WD030102
UNION ALL SELECT * FROM TMP_WD030202
UNION ALL SELECT * FROM TMP_WD030117
UNION ALL SELECT * FROM TMP_WD030307
UNION ALL SELECT * FROM TMP_WD030308
UNION ALL SELECT * FROM TMP_WD030213
UNION ALL SELECT * FROM TMP_WD030216
UNION ALL SELECT * FROM TMP_WD030118
UNION ALL SELECT * FROM TMP_WD030110
UNION ALL SELECT * FROM TMP_WD030109
UNION ALL SELECT * FROM TMP_WD030208
UNION ALL SELECT * FROM TMP_WD030207
UNION ALL SELECT * FROM TMP_WD030201
)
SELECT * FROM DB_REST;
COMMIT;


-- 3.2 exchage ex table and target table
alter table ${idl_schema}.comb_d_acct_class_bus exchange partition p_${batch_date} with table ${idl_schema}.tmp_comb_d_acct_class_bus;

-- 3.3 drop tmp table
drop TABLE ${idl_schema}.tmp_comb_d_acct_class_bus purge;

-- 4.1 gater table status
whenever sqlerror exit sql.sqlcode;
exec dbms_stats.gather_table_stats(ownname => '${idl_schema}',tabname => 'comb_d_acct_class_bus',partname => 'p_${batch_date}',ESTIMATE_PERCENT => 10,method_opt=>'for all columns size 1',no_invalidate=>false,granularity=>'partition',cascade => true,force=>true,degree => 8);
